!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
MODULE B2MOD_B2PLOT_DIFFV
!
  USE B2MOD_TYPES
  USE B2MOD_LAYER_DIFFV, ONLY : ntrack
  USE B2MOD_DIMENSIONS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!
  REAL(kind=r8), ALLOCATABLE, SAVE :: work(:, :, :, :), wrk(:), vxa(:, :&
& ), vya(:, :), vza(:, :), vxm(:, :), vym(:, :), vzm(:, :), vxi(:, :), &
& vyi(:, :), vzi(:, :), arrowx(:, :, :), arrowy(:, :, :), earrowx(:, :)&
& , earrowy(:, :), p1(:, :), p2(:, :), xx(:, :), yy(:, :), nh(:, :), &
& zeff(:, :), uutraj(:, :, :), vvtraj(:, :, :), targetx(:, :), targety(:&
& , :), targetr(:, :), targetz(:, :), wwrk(:), wrk_hlp(:), ewrk_hlp(:), &
& wwrk_hlp(:), twrk_hlp(:)
!
  REAL(kind=r8), SAVE :: pp1(2, def_nlim+2*def_nyd), pp2(2, def_nlim+2*&
& def_nyd)
!
  INTEGER, ALLOCATABLE, SAVE :: ind_hlp(:), indt_hlp(:)
!
  REAL(kind=r8), ALLOCATABLE, SAVE :: eirene_stack(:, :, :), &
& triangle_area(:), triangle_vol(:), wall_stack(:, :, :), wall_flux(:, :&
& ), wall_area(:), incident_energy(:, :), wall_heatflux(:), wall_temp(:)&
& , target_stack(:, :, :)
!
  INTEGER :: wklng
  PARAMETER (wklng=10)
!
  CHARACTER(len=16), ALLOCATABLE, SAVE :: textpl(:), textplel(:), &
& textplel2(:, :), textsp(:), textwk(:, :), textewk(:, :), textwwk(:, :)&
& , textbl(:), textni(:), textcomponents(:), text0123(:), textwl(:), &
& textcorner(:), texttrack(:), texttargsp(:)
!
  INTEGER :: npart
  PARAMETER (npart=100000)
! typeofplot=1 physical domain only, =2 computational domain only, =3 both
!
  REAL(kind=r8), SAVE :: arrowl, earrowl, arroww, sepwidth, lwidth, &
& wwidth, owidth, vwidth, ewidth, zwidth
  INTEGER, SAVE :: nidim, linlog, wlinlog, tlinlog, trglinlog
  INTEGER, SAVE :: ndim(3, wklng), nedim(2, wklng), nwdim(2, wklng), &
& typeofplot, iwrk, iewrk, iwwrk, itwrk, movie_skip, average
!ank 960511
  INTEGER, SAVE :: nlimi, nstsi, natmi, nmoli, nioni, nlim1
!ank
  INTEGER, SAVE :: mcol, scol, vcol, ocol, ecol, acol, zcol, &
& y_transform_l, dcol, wcol, tcol, hcol, gcol, bcol, xcol, lfsz, &
& expsymbol
!
  LOGICAL, SAVE :: writing_to_file, color_set, use_compile, &
& set_resignore_regions_to_zero, plotting_wall, map_to_midplane, &
& xparallel, plotting_sep, expline
!
  CHARACTER(len=256), SAVE :: graphlabel(wklng), eirene_label(wklng), &
& wall_label(wklng), target_label(wklng)
  CHARACTER(len=256), SAVE :: solpstop, moviename, expfile, wallfile
  CHARACTER(len=80), SAVE :: b2version
!
  INTEGER, SAVE :: nx, ny, ns, nsw, jxa, jxi, jsep, ixref, iyref, nxtr, &
& nxtl
!
  INTEGER, SAVE :: neo_ic

CONTAINS
!
!
  SUBROUTINE ALLOC_B2MOD_B2PLOT(nxd, nyd, nsd, ns_ext, wklngd, natmd, &
&   nmold, niond, nlim)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: nxd, nyd, nsd, ns_ext, wklngd, natmd, nmold, niond, nlim
    INTEGER :: nsw
    EXTERNAL GET_JSEP, GET_NXT, IPGETI, XERTST
    INTRINSIC MAX
    INTEGER :: max1
!
    nx = nxd
    ny = nyd
    ns = nsd
    IF (nsd + 3 .LT. (nsd+1)*(nsd+1) - 1) THEN
      IF ((nsd+1)*(nsd+1) - 1 .LT. ns_ext) THEN
        nsw = ns_ext
      ELSE
        nsw = (nsd+1)*(nsd+1) - 1
      END IF
    ELSE IF (nsd + 3 .LT. ns_ext) THEN
      nsw = ns_ext
    ELSE
      nsw = nsd + 3
    END IF
!
    CALL GET_JSEP(nx, ny, jxi, jxa, jsep)
    ixref = jxa
    iyref = jsep
    CALL IPGETI('set_transport_ixref', ixref)
    CALL XERTST(-1 .LE. ixref .AND. ixref .LE. nxd, &
&         'faulty argument set_transport_ixref')
    CALL IPGETI('set_transport_iyref', iyref)
    CALL XERTST(-1 .LE. iyref .AND. iyref .LE. nyd, &
&         'faulty argument set_transport_iyref')
    CALL GET_NXT(nx, nxtl, nxtr)
!
    ALLOCATE(work(-1:nxd, -1:nyd, 0:nsw, 1:wklngd))
    ALLOCATE(wrk(-1:nxd+nyd+1))
    ALLOCATE(wrk_hlp(1:nxd*nyd))
    ALLOCATE(ind_hlp(1:nxd*nyd))
    ALLOCATE(arrowx(-1:nxd, -1:nyd, 0:nsw))
    ALLOCATE(arrowy(-1:nxd, -1:nyd, 0:nsw))
    ALLOCATE(p1(2, nlim))
    ALLOCATE(p2(2, nlim))
    ALLOCATE(xx(-1:nx, 2))
    ALLOCATE(yy(-1:ny, 2))
    ALLOCATE(nh(-1:nxd, -1:nyd))
    ALLOCATE(zeff(-1:nxd, -1:nyd))
    ALLOCATE(uutraj(-1:nxd, -1:nyd, 0:nsd-1))
    ALLOCATE(vvtraj(-1:nxd, -1:nyd, 0:nsd-1))
    ALLOCATE(textpl(0:nsd-1))
    ALLOCATE(textplel(0:nsd))
    ALLOCATE(textplel2(0:nsd, 0:nsd))
    IF (1 .LT. natmd) THEN
      max1 = natmd
    ELSE
      max1 = 1
    END IF
    ALLOCATE(textsp(0:max1-1))
    ALLOCATE(textwl(0:nsd-1+natmd+nmold+niond))
    ALLOCATE(textwk(0:nsw, wklngd))
    ALLOCATE(textewk(0:MAX(1, natmd, nmold, niond)-1, wklngd))
    ALLOCATE(textwwk(0:nsd-1+natmd+nmold+niond, wklngd))
    ALLOCATE(textbl(0:0))
    ALLOCATE(textni(0:1))
    ALLOCATE(textcomponents(0:3))
    ALLOCATE(text0123(0:3))
    ALLOCATE(textcorner(0:3))
    ALLOCATE(texttrack(0:ntrack))
    ALLOCATE(texttargsp(ntrack))
!
    RETURN
  END SUBROUTINE ALLOC_B2MOD_B2PLOT

!
  SUBROUTINE ALLOC_B2MOD_B2PLOT_EIRENE(natmd, nmold, niond, ntrii, &
&   wklngd)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: natmd, nmold, niond, ntrii, wklngd
    INTRINSIC MAX
    INTEGER :: max1
    INTEGER :: max2
    INTEGER :: max3
    INTEGER :: max4
    INTEGER :: max5
    INTEGER :: max6
    INTEGER :: max7
    INTEGER :: max8
    INTEGER :: max9
!
    ALLOCATE(eirene_stack(ntrii, 0:MAX(1, natmd, nmold, niond)-1, wklngd&
&   ))
    ALLOCATE(triangle_area(ntrii))
    ALLOCATE(triangle_vol(ntrii))
    IF (1 .LT. natmd) THEN
      max1 = natmd
    ELSE
      max1 = 1
    END IF
    ALLOCATE(vxa(max1, ntrii))
    IF (1 .LT. natmd) THEN
      max2 = natmd
    ELSE
      max2 = 1
    END IF
    ALLOCATE(vya(max2, ntrii))
    IF (1 .LT. natmd) THEN
      max3 = natmd
    ELSE
      max3 = 1
    END IF
    ALLOCATE(vza(max3, ntrii))
    IF (1 .LT. nmold) THEN
      max4 = nmold
    ELSE
      max4 = 1
    END IF
    ALLOCATE(vxm(max4, ntrii))
    IF (1 .LT. nmold) THEN
      max5 = nmold
    ELSE
      max5 = 1
    END IF
    ALLOCATE(vym(max5, ntrii))
    IF (1 .LT. nmold) THEN
      max6 = nmold
    ELSE
      max6 = 1
    END IF
    ALLOCATE(vzm(max6, ntrii))
    IF (1 .LT. niond) THEN
      max7 = niond
    ELSE
      max7 = 1
    END IF
    ALLOCATE(vxi(max7, ntrii))
    IF (1 .LT. niond) THEN
      max8 = niond
    ELSE
      max8 = 1
    END IF
    ALLOCATE(vyi(max8, ntrii))
    IF (1 .LT. niond) THEN
      max9 = niond
    ELSE
      max9 = 1
    END IF
    ALLOCATE(vzi(max9, ntrii))
    ALLOCATE(earrowx(ntrii, 0:MAX(1, natmd, nmold, niond)-1))
    ALLOCATE(earrowy(ntrii, 0:MAX(1, natmd, nmold, niond)-1))
    ALLOCATE(ewrk_hlp(ntrii))
!
    RETURN
  END SUBROUTINE ALLOC_B2MOD_B2PLOT_EIRENE

!
  SUBROUTINE ALLOC_B2MOD_B2PLOT_WALL(nsd, natmd, nmold, niond, nwall, &
&   ndepth, wklngd)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: nsd, natmd, nmold, niond, nwall, ndepth, wklngd
!
    ALLOCATE(wwrk_hlp(1:nwall))
    ALLOCATE(twrk_hlp(1:nwall*ndepth))
    ALLOCATE(indt_hlp(1:nwall*ndepth))
    ALLOCATE(wall_stack(1:nwall, 0:nsd-1+natmd+nmold+niond, 1:wklngd))
    ALLOCATE(wall_flux(1:nwall, 0:nsd-1+natmd+nmold+niond))
    ALLOCATE(wall_area(1:nwall))
    ALLOCATE(incident_energy(1:nwall, 0:nsd-1+natmd+nmold+niond))
    ALLOCATE(wall_heatflux(1:nwall))
    ALLOCATE(wall_temp(1:nwall))
    ALLOCATE(targetx(1:nwall, 2))
    ALLOCATE(targety(1:ndepth, 2))
    ALLOCATE(targetr(1:nwall, 1:ndepth))
    ALLOCATE(targetz(1:nwall, 1:ndepth))
    ALLOCATE(wwrk(1:nwall+ndepth))
    ALLOCATE(target_stack(1:nwall, 1:ndepth, wklngd))
!
    RETURN
  END SUBROUTINE ALLOC_B2MOD_B2PLOT_WALL

!
  SUBROUTINE DEALLOC_B2MOD_B2PLOT()
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTRINSIC ALLOCATED
!
    IF (.NOT.ALLOCATED(work)) THEN
      RETURN
    ELSE
      DEALLOCATE(work)
      DEALLOCATE(wrk)
      DEALLOCATE(wrk_hlp)
      DEALLOCATE(ind_hlp)
      DEALLOCATE(arrowx)
      DEALLOCATE(arrowy)
      DEALLOCATE(p1)
      DEALLOCATE(p2)
      DEALLOCATE(xx)
      DEALLOCATE(yy)
      DEALLOCATE(nh)
      DEALLOCATE(zeff)
      DEALLOCATE(uutraj)
      DEALLOCATE(vvtraj)
      DEALLOCATE(textpl)
      DEALLOCATE(textplel)
      DEALLOCATE(textplel2)
      DEALLOCATE(textsp)
      DEALLOCATE(textwl)
      DEALLOCATE(textwk)
      DEALLOCATE(textewk)
      DEALLOCATE(textwwk)
      DEALLOCATE(textbl)
      DEALLOCATE(textni)
      DEALLOCATE(textcomponents)
      DEALLOCATE(text0123)
      DEALLOCATE(textcorner)
      DEALLOCATE(texttrack)
      DEALLOCATE(texttargsp)
!
      RETURN
    END IF
  END SUBROUTINE DEALLOC_B2MOD_B2PLOT

!
  SUBROUTINE DEALLOC_B2MOD_B2PLOT_EIRENE()
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
!
    DEALLOCATE(eirene_stack)
    DEALLOCATE(triangle_area)
    DEALLOCATE(triangle_vol)
    DEALLOCATE(vxa)
    DEALLOCATE(vya)
    DEALLOCATE(vza)
    DEALLOCATE(vxm)
    DEALLOCATE(vym)
    DEALLOCATE(vzm)
    DEALLOCATE(vxi)
    DEALLOCATE(vyi)
    DEALLOCATE(vzi)
    DEALLOCATE(earrowx)
    DEALLOCATE(earrowy)
    DEALLOCATE(ewrk_hlp)
!
    RETURN
  END SUBROUTINE DEALLOC_B2MOD_B2PLOT_EIRENE

!
  SUBROUTINE DEALLOC_B2MOD_B2PLOT_WALL()
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
!
    DEALLOCATE(wwrk_hlp)
    DEALLOCATE(twrk_hlp)
    DEALLOCATE(indt_hlp)
    DEALLOCATE(wall_stack)
    DEALLOCATE(wall_flux)
    DEALLOCATE(wall_area)
    DEALLOCATE(incident_energy)
    DEALLOCATE(wall_heatflux)
    DEALLOCATE(wall_temp)
    DEALLOCATE(targetx)
    DEALLOCATE(targety)
    DEALLOCATE(targetr)
    DEALLOCATE(targetz)
    DEALLOCATE(wwrk)
    DEALLOCATE(target_stack)
!
    RETURN
  END SUBROUTINE DEALLOC_B2MOD_B2PLOT_WALL

!
  SUBROUTINE READ_B2MOD_B2PLOT(nread)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: nread
    EXTERNAL XERTST
!
    CALL XERTST(0 .LT. nread, 'faulty input nread')
!
    RETURN
  END SUBROUTINE READ_B2MOD_B2PLOT

!
  SUBROUTINE WRITE_B2MOD_B2PLOT(nwrite)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: nwrite
    EXTERNAL XERTST
!
    CALL XERTST(0 .LT. nwrite, 'faulty input nwrite')
!
    RETURN
  END SUBROUTINE WRITE_B2MOD_B2PLOT

!
  FUNCTION IX_E2B(ixe)
    USE B2MOD_INDIRECT
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: ix_e2b
    INTEGER :: ixe
    INTEGER :: ic, i
!
    IF (ixe .EQ. -1 .OR. ixe .EQ. 0) THEN
      ix_e2b = -2
    ELSE
      i = 1
      ix_e2b = 0
      DO WHILE (i .LT. ixe)
        i = i + 1
        ix_e2b = ix_e2b + 1
        DO ic=1,nncut
          IF (ix_e2b .EQ. leftcut(ic)) i = i + 1
          IF (ix_e2b .EQ. rightcut(ic)) i = i + 1
        END DO
        IF (nncut .EQ. 2 .AND. ix_e2b .EQ. nxtr) i = i + 1
      END DO
    END IF
    RETURN
  END FUNCTION IX_E2B

!
  FUNCTION IX_B2E(ixb)
    USE B2MOD_INDIRECT
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    INTEGER :: ix_b2e
    INTEGER :: ixb
    INTEGER :: i
!
    IF (ixb .EQ. -2) THEN
      ix_b2e = -1
    ELSE IF (ixb .GT. nx) THEN
      ix_b2e = -1
    ELSE IF (ixb .EQ. -1 .OR. ixb .EQ. nx) THEN
      ix_b2e = -1
    ELSE IF (nncut .EQ. 2 .AND. (ixb .GE. nxtl .AND. ixb .LE. nxtr)) &
&   THEN
      ix_b2e = -1
    ELSE
      ix_b2e = ixb + 1
      DO i=1,nncut
        IF (ixb .GE. leftcut(i)) ix_b2e = ix_b2e + 1
        IF (ixb .GE. rightcut(i)) ix_b2e = ix_b2e + 1
      END DO
      IF (nncut .EQ. 2 .AND. ixb .GT. nxtr) ix_b2e = ix_b2e + 1
    END IF
    RETURN
  END FUNCTION IX_B2E

END MODULE B2MOD_B2PLOT_DIFFV

