!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2MXAC_NODIFF(ncv, ns, dv, diag)
  USE B2MOD_TYPES
  USE B2US_PLASMA_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2mxac
!
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, ns
  TYPE(B2DERIVATIVES), INTENT(IN) :: dv
!   ..output arguments (unspecified on entry)
  TYPE(B2DIAGNOSTIC), INTENT(INOUT) :: diag
!
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2MXAC computes the (maximum-)norms of the corrections.
!
!
!  3. description (see also routine b2cdca)
!
!     This routine computes maximum-norms of the corrections computed
!     towards the solution of the equations for continuity, parallel
!     momentum balance, electron heat balance, atom heat balance, and
!     charge balance.
!
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: is
  EXTERNAL XERTST, samax
!   ..procedures
  REAL(kind=r8) :: samax
  EXTERNAL B2XVFX_NODIFF
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2mxac')
!   ..test nCv, ns
  CALL XERTST(0 .LE. ncv, 'faulty argument nCv')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!
!
! ..compute norms of the corrections
!   ..compute acorpa, acorua
  DO is=0,ns-1
    diag%acorpa(is) = samax(ncv, dv%corpa(1, is), 1)
    diag%acorua(is) = samax(ncv, dv%corua(1, is), 1)
  END DO
!   ..compute acorut, acorte, acorti, acorpo
  diag%acorut = samax(ncv, dv%corut, 1)
  diag%acorte = samax(ncv, dv%corte, 1)
  diag%acorti = samax(ncv, dv%corti, 1)
  diag%acortn = samax(ncv, dv%cortn, 1)
  diag%acorpo = samax(ncv, dv%corpo, 1)
  diag%acorkt = samax(ncv, dv%corkt, 1)
!
! ..return
  CALL SUBEND()
  RETURN
END SUBROUTINE B2MXAC_NODIFF

