!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2stbm in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: *(srw.sch0) *(srw.she0) *(srw.shi0)
!                *(srw.smo0) *(srw.sna0)
!   with respect to varying inputs: *(srw.sch0) *(srw.she0) *(srw.shi0)
!                *(srw.smo0) *(srw.sna0) *(pl.na) *(pl.ua) *(pl.po)
!                *(pl.te) *(pl.ti)
!   Plus diff mem management of: dv.fch:in dv.fna:in dv.fhe:in
!                dv.fhi:in dv.kinrgy:in dv.ne:in dv.ni:in geo.cvhx:in
!                geo.cvqgam:in geo.cvvol:in geo.fcht:in geo.fcvol:in
!                geo.fcqgam:in st_ext.na:in st_ext.ua:in st_ext.ta:in
!                st_ext.sne:in st_ext.she:in st_ext.shi:in st_ext.sch:in
!                st_ext.sna:in st_ext.smo:in srw.sch0:in srw.she0:in
!                srw.shi0:in srw.sne0:in srw.smo0:in srw.sna0:in
!                srw.b2stbm_sch:in srw.b2stbm_she:in srw.b2stbm_shi:in
!                srw.b2stbm_sne:in srw.b2stbm_smo:in srw.b2stbm_sna:in
!                pl.na:in pl.ua:in pl.po:in pl.te:in pl.ti:in pl.tn:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2STBM_DV(ncv, nfc, nvx, ns, ismain, dtim, switch, geo, geod&
& , mpg, pl, pld, dv, dvd, co, rt, rtw, st_ext, st_extd, sr, srw, srwd, &
& main_call, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_INDIRECT
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPB_DIFFV
  USE B2MOD_EXTERNAL_DIFFV
  USE B2MOD_IMPGYRO_DIFFV
  USE B2MOD_NEUTRALS_NAMELIST_DIFFV
  USE B2MOD_NUMERICS_NAMELIST_DIFFV
!djm Jan2017
  USE B2MOD_BALANCE_DIFFV, ONLY : b2stbm_sna0to1, b2stbm_smo0to3, &
& b2stbm_she0to3, b2stbm_shi0to3, balance_netcdf
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_SUBSYS
!  Hint: nCv should be the size of dimension 1 of array cvbb
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2stbm
!
!
!djm Jan2017 Keep linearised sources for balance
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns, ismain
  LOGICAL :: main_call
  REAL(kind=r8) :: dtim
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2PLASMA_DIFFV), INTENT(IN) :: pld
  TYPE(B2STATEEXT), INTENT(INOUT) :: st_ext
  TYPE(B2STATEEXT_DIFFV), INTENT(INOUT) :: st_extd
!   ..input/output arguments 
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2DERIVATIVES_DIFFV), INTENT(INOUT) :: dvd
  TYPE(B2RATES), INTENT(INOUT) :: rt
  TYPE(B2RATESWORK), INTENT(INOUT) :: rtw
  TYPE(B2COEFF), INTENT(INOUT) :: co
  TYPE(B2SOURCE), INTENT(INOUT) :: sr
  TYPE(B2SOURCEWORK), INTENT(INOUT) :: srw
  TYPE(B2SOURCEWORK_DIFFV), INTENT(INOUT) :: srwd
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2STBM provides linearised expressions for the sources of
!     density, parallel momentum, and heat, due to miscellaneous
!     application specific processes.
!
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ia, is, is0, icv, ifc, ireg
  REAL(kind=r8) :: t0, vthe, ua_tmp, dua
  REAL(kind=r8), DIMENSION(nbdirsmax) :: t0d, vthed, ua_tmpd, duad
  REAL(kind=r8) :: n0_tmp, nr_tmp, nt_tmp, p0_tmp, pr_tmp, r0_tmp, &
& pe_tmp, re_tmp
  REAL(kind=r8) :: na_tot(ncv), na0(ncv, 0:ns-1), ua0(ncv, 0:ns-1), fna0&
& (nfc, 0:1, 0:ns-1), fhi0(nfc, 0:1), ti0(ncv), fhe0(nfc, 0:1), fch0(nfc&
& , 0:1)
  REAL(kind=r8) :: na0d(nbdirsmax, ncv, 0:ns-1), ua0d(nbdirsmax, ncv, 0:&
& ns-1)
  INTEGER, SAVE :: ncall=0
  EXTERNAL XERTST, SFILL_NODIFF, smin, smax, B2XVSG_NODIFF&
&     , B2XVFF_NODIFF, IPGETI, IPGETR
!   ..procedures
  REAL(kind=r8) :: smin, smax
  INTRINSIC ABS, MOD, SQRT
  INTRINSIC SIGN
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: abs3
  REAL(kind=r8) :: abs4
  REAL(kind=r8) :: abs5
  REAL(kind=r8) :: abs6
  REAL(kind=r8) :: abs7
  REAL(kind=r8) :: abs8
  REAL(kind=r8), DIMENSION(nbdirsmax) :: abs8d
  REAL(kind=r8) :: abs9
  REAL(kind=r8), DIMENSION(nbdirsmax) :: abs9d
  REAL(kind=r8) :: abs10
  REAL(kind=r8) :: abs11
  INTEGER :: arg1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(kind=r8) :: arg10
  REAL(kind=r8), DIMENSION(nCv) :: arg11
  REAL(r8) :: arg12
  REAL(r8), DIMENSION(nbdirsmax) :: arg12d
  INTEGER :: nd
  REAL(r8) :: temp
  REAL(kind=r8) :: temp0
  REAL(r8), DIMENSION(nCv) :: temp1
  REAL(kind=r8) :: temp2
  REAL(kind=r8) :: temp3
  INTEGER :: nbdirs
!
!-----------------------------------------------------------------------
!.documentation-internal
!
!     This version of b2stbm imports the sources computed from an
!     external code such as IMPGYRO.
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2stbm')
!   ..test nCv, nFc, ns, ismain
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
  CALL XERTST(0 .LE. ismain .AND. ismain .LT. ns, &
&       'faulty argument ismain')
!   ..extensive tests on first few calls
  IF (ncall .LT. 3) THEN
!    ..test sign of vol, hx, hy
    CALL B2XVSG_NODIFF(ncv, geo%cvvol, 1, 'vol', '.gt.')
    arg1 = nfc*2
    CALL B2XVSG_NODIFF(arg1, geo%fcvol, 1, 'vol', '.gt.')
    CALL B2XVSG_NODIFF(ncv, geo%cvhx, 1, 'hx', '.gt.')
    CALL B2XVSG_NODIFF(nfc, geo%fcht, 1, 'hy', '.gt.')
!    ..test range of cvQgam, fcQgam
    result1 = smin(ncv, geo%cvqgam(1, 1), 1)
    result2 = smax(ncv, geo%cvqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range cvQgam(,1)')
    result1 = smin(ncv, geo%cvqgam(1, 0), 1)
    result2 = smax(ncv, geo%cvqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range cvQgam(,0)')
    result1 = smin(nfc, geo%fcqgam(1, 1), 1)
    result2 = smax(nfc, geo%fcqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range fcQgam(,1)')
    result1 = smin(nfc, geo%fcqgam(1, 0), 1)
    result2 = smax(nfc, geo%fcqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range fcQgam(,0)')
!    ..test state
    CALL B2XVPS_NODIFF(ncv, nfc, ns, pl, dv)
!
!   ..test edge values of fluxes
  END IF
  DO nd=1,nbdirs
!
!   ..initialise sources to 0
    srwd%sna0(nd, :, :, :) = 0.D0
    srwd%smo0(nd, :, :, :) = 0.D0
    srwd%she0(nd, :, :) = 0.D0
    srwd%shi0(nd, :, :) = 0.D0
    srwd%sch0(nd, :, :) = 0.D0
  END DO
  srw%sna0 = 0.0_R8
  srw%smo0 = 0.0_R8
  srw%sne0 = 0.0_R8
  srw%she0 = 0.0_R8
  srw%shi0 = 0.0_R8
  srw%sch0 = 0.0_R8
  srw%b2stbm_sna = 0.0_R8
  srw%b2stbm_smo = 0.0_R8
  srw%b2stbm_sne = 0.0_R8
  srw%b2stbm_she = 0.0_R8
  srw%b2stbm_shi = 0.0_R8
  srw%b2stbm_sch = 0.0_R8
!
! ..obtain sources from IMPGYRO
  IF (switch%b2stbm_impgyro_mod .NE. 0) THEN
!
!xpb First provide plasma background (include neutral quantities)
!xpb Must convert fluxes to flux densities
    ti0 = 0.0_R8
    fhi0 = 0.0_R8
    na_tot = 0.0_R8
    DO nd=1,nbdirsmax
      na0d(nd, :, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      ua0d(nd, :, :) = 0.D0
    END DO
    DO is=0,ns-1
      IF (is_neutral(is)) THEN
        is0 = b2espcr(is)
      ELSE
        is0 = 0
      END IF
      IF (is0 .NE. 0) THEN
        DO icv=1,ncv
          n0_tmp = 0.0_R8
          nr_tmp = 0.0_R8
          nt_tmp = 0.0_R8
          p0_tmp = 0.0_R8
          pe_tmp = 0.0_R8
          pr_tmp = 0.0_R8
          r0_tmp = 0.0_R8
          re_tmp = 0.0_R8
          DO ia=1,nnatmi
            IF (latmscl(ia) .EQ. is0) THEN
              n0_tmp = n0_tmp + dab2(icv, ia, 1)
!WG_TODO        nr_tmp = nr_tmp + dab2(ixr+1,iyr+1,ia,1)
              nt_tmp = nt_tmp + dab2(icv, ia, 1)*tab2(icv, ia, 1)
              p0_tmp = p0_tmp + pfluxa(icv, ia, 1)
              pe_tmp = pe_tmp + pefluxa(icv, ia, 1)
!WG_TODO        pr_tmp = pr_tmp + pfluxa(ixr+1,iyr+1,ia,1)
              r0_tmp = r0_tmp + rfluxa(icv, ia, 1)
              re_tmp = re_tmp + refluxa(icv, ia, 1)
            END IF
          END DO
          IF (n0_tmp .GT. 0.0_R8 .AND. nr_tmp .GT. 0.0_R8) THEN
            ua_tmp = (p0_tmp/n0_tmp+pr_tmp/nr_tmp)/2.0_R8
          ELSE IF (n0_tmp .GT. 0.0_R8) THEN
            ua_tmp = p0_tmp/n0_tmp
          ELSE IF (nr_tmp .GT. 0.0_R8) THEN
            ua_tmp = pr_tmp/nr_tmp
          ELSE
            ua_tmp = 0.0_R8
          END IF
          na_tot(icv) = na_tot(icv) + n0_tmp
          na0(icv, is) = pl%na(icv, is) + n0_tmp
          arg10 = geo%cvbb(icv, 0)
          temp = SIGN(1.0_R8, arg10)
          temp0 = (ua_tmp*n0_tmp+temp*pl%ua(icv, is)*pl%na(icv, is))/na0&
&           (icv, is)
          DO nd=1,nbdirs
            na0d(nd, icv, is) = pld%na(nd, icv, is)
            ua0d(nd, icv, is) = (temp*(pl%na(icv, is)*pld%ua(nd, icv, is&
&             )+pl%ua(icv, is)*pld%na(nd, icv, is))-temp0*na0d(nd, icv, &
&             is))/na0(icv, is)
          END DO
          ti0(icv) = ti0(icv) + nt_tmp
          ua0(icv, is) = temp0
        END DO
        DO ifc=1,nfc
          fna0(ifc, 0, is) = dv%fna(ifc, 0, is)/geo%fcs(ifc)/geo%fcqgam(&
&           ifc, 0) + p0_tmp
          fna0(ifc, 1, is) = dv%fna(ifc, 1, is)/geo%fcs(ifc) + r0_tmp
          fhi0(ifc, 0) = fhi0(ifc, 0) + pe_tmp
          fhi0(ifc, 1) = fhi0(ifc, 1) + re_tmp
        END DO
      ELSE
        arg11(:) = geo%cvbb(:, 0)
        temp1 = SIGN(1.0_R8, arg11(:))
        DO nd=1,nbdirs
          na0d(nd, :, is) = pld%na(nd, :, is)
          ua0d(nd, :, is) = temp1*pld%ua(nd, :, is)
        END DO
        na0(:, is) = pl%na(:, is)
        ua0(:, is) = temp1*pl%ua(:, is)
        fna0(:, 0, is) = dv%fna(:, 0, is)/geo%fcs(:)/geo%fcqgam(ifc, 0)
        fna0(:, 1, is) = dv%fna(:, 1, is)/geo%fcs(:)
      END IF
    END DO
    DO is=1,nnmoli
      DO icv=1,ncv
        na_tot(icv) = na_tot(icv) + dmb2(icv, is, 1)
        ti0(icv) = ti0(icv) + dmb2(icv, is, 1)*tmb2(icv, is, 1)
      END DO
    END DO
    DO is=1,nnioni
      DO icv=1,ncv
        na_tot(icv) = na_tot(icv) + dib2(icv, is, 1)
        ti0(icv) = ti0(icv) + dib2(icv, is, 1)*tib2(icv, is, 1)
      END DO
    END DO
    DO icv=1,ncv
      ti0(icv) = (ti0(icv)+pl%ti(icv)*dv%ni(icv, 0))/(na_tot(icv)+dv%ni(&
&       icv, 0))
    END DO
    DO ifc=1,nfc
      fhi0(ifc, 0) = fhi0(ifc, 0) + dv%fhi(ifc, 0)/geo%fcs(ifc)/geo%&
&       fcqgam(ifc, 0)
      fhi0(ifc, 1) = fhi0(ifc, 1) + dv%fhi(ifc, 1)/geo%fcs(ifc)
      fhe0(ifc, 0) = dv%fhe(ifc, 0)/geo%fcs(ifc)/geo%fcqgam(ifc, 0)
      fhe0(ifc, 1) = dv%fhe(ifc, 1)/geo%fcs(ifc)
      fch0(ifc, 0) = dv%fch(ifc, 0)/geo%fcs(ifc)/geo%fcqgam(ifc, 0)
      fch0(ifc, 1) = dv%fch(ifc, 1)/geo%fcs(ifc)
    END DO
!
    IF (ncall .EQ. 0 .OR. (main_call .AND. MOD(ncall, switch%&
&       b2stbm_impgyro_mod) .EQ. 0)) THEN
!xpb The call below obtains the following quantities from IMPGYRO
!xpb Main W data: na_ext, ua_ext, ta_ext
!xpb Sources due to W: sne_ext, smo_ext, she_ext, shi_ext
!xpb Derived quantities: ne_ext, ne2_ext, ni_ext, fa_ext, fhi_ext, ue_ext
!        call read_b2mod_external(nx,ny,ns,ismain)
!xpb In the current arrangement, IMPGYRO provides: na_ext, ua_ext, ta_ext
!xpb It would be best to have instead as primary quantities:
!xpb na_ext, fa_ext, ta_ext, fhi_ext
!xpb And then derive: ua_ext
!
      st_ext%sna = 0.0_R8
      st_ext%sne = 0.0_R8
      st_ext%smo = 0.0_R8
      st_ext%she = 0.0_R8
      st_ext%shi = 0.0_R8
      st_ext%sch = 0.0_R8
      st_ext%na = 0.0_R8
      st_ext%ua = 0.0_R8
      st_ext%ta = 0.0_R8
!
    END IF
!
! ..linearise external sources
    DO icv=1,ncv
      ireg = mpg%cvreg(icv)
      IF (switch%b2stbm_linearisation .GT. 0.0_R8) THEN
!  ...electron particle source
        t0 = st_ext%sne(icv)
        IF (t0 .GE. 0.0_R8) THEN
          srw%sne0(icv, 0) = t0
        ELSE
          srw%sne0(icv, 1) = t0/dv%ne(icv)
        END IF
        IF (t0 .GE. 0.) THEN
          abs0 = t0
        ELSE
          abs0 = -t0
        END IF
        srw%sne0(icv, 0) = srw%sne0(icv, 0) + switch%&
&         b2stbm_linearisation*abs0
        IF (t0 .GE. 0.) THEN
          abs1 = t0
        ELSE
          abs1 = -t0
        END IF
        srw%sne0(icv, 1) = srw%sne0(icv, 1) - switch%&
&         b2stbm_linearisation*abs1/dv%ne(icv)
        DO is=0,ns-1
!  ...heavy particles sources
          t0 = st_ext%sna(icv, is)
          IF (t0 .GE. 0.0_R8) THEN
            DO nd=1,nbdirs
              srwd%sna0(nd, icv, 0, is) = 0.D0
            END DO
            srw%sna0(icv, 0, is) = t0
          ELSE
            temp0 = t0/pl%na(icv, is)
            DO nd=1,nbdirs
              srwd%sna0(nd, icv, 1, is) = -(temp0*pld%na(nd, icv, is)/pl&
&               %na(icv, is))
            END DO
            srw%sna0(icv, 1, is) = temp0
          END IF
          IF (t0 .GE. 0.) THEN
            abs2 = t0
          ELSE
            abs2 = -t0
          END IF
          srw%sna0(icv, 0, is) = srw%sna0(icv, 0, is) + switch%&
&           b2stbm_linearisation*abs2
          IF (t0 .GE. 0.) THEN
            abs3 = t0
          ELSE
            abs3 = -t0
          END IF
          temp0 = switch%b2stbm_linearisation*abs3/pl%na(icv, is)
          arg12 = pl%te(icv)/me
          temp = SQRT(arg12)
          arg10 = am(is)*mp/me
          result1 = SQRT(arg10)
          DO nd=1,nbdirs
            srwd%sna0(nd, icv, 1, is) = srwd%sna0(nd, icv, 1, is) + &
&             temp0*pld%na(nd, icv, is)/pl%na(icv, is)
!  ...parallel momentum sources
            arg12d(nd) = pld%te(nd, icv)/me
            IF (arg12 .EQ. 0.D0) THEN
              vthed(nd) = 0.D0
            ELSE
              vthed(nd) = arg12d(nd)/(2.0*temp)
            END IF
            vthed(nd) = vthed(nd)/result1
          END DO
          srw%sna0(icv, 1, is) = srw%sna0(icv, 1, is) - temp0
          vthe = temp
          vthe = vthe/result1
          arg10 = geo%cvbb(icv, 0)
          t0 = st_ext%smo(icv, is)*SIGN(1.0_R8, arg10)
          IF (t0 .GE. 0.) THEN
            abs4 = t0
          ELSE
            abs4 = -t0
          END IF
          temp = pl%ua(icv, is)/vthe
          DO nd=1,nbdirs
            srwd%smo0(nd, icv, 0, is) = srwd%smo0(nd, icv, 0, is) + &
&             switch%b2stbm_linearisation*abs4*(pld%ua(nd, icv, is)-temp&
&             *vthed(nd))/vthe
          END DO
          srw%smo0(icv, 0, is) = t0 + srw%smo0(icv, 0, is) + switch%&
&           b2stbm_linearisation*abs4*temp
          IF (t0 .GE. 0.) THEN
            abs5 = t0
          ELSE
            abs5 = -t0
          END IF
          temp0 = switch%b2stbm_linearisation*abs5/vthe
          DO nd=1,nbdirs
            srwd%smo0(nd, icv, 1, is) = srwd%smo0(nd, icv, 1, is) + &
&             temp0*vthed(nd)/vthe
          END DO
          srw%smo0(icv, 1, is) = srw%smo0(icv, 1, is) - temp0
        END DO
!  ...electron energy source
        t0 = st_ext%she(icv)
        IF (t0 .GE. 0.0_R8) THEN
          DO nd=1,nbdirs
            srwd%she0(nd, icv, 0) = 0.D0
          END DO
          srw%she0(icv, 0) = t0
        ELSE
          temp0 = t0/pl%te(icv)
          DO nd=1,nbdirs
            srwd%she0(nd, icv, 1) = -(temp0*pld%te(nd, icv)/pl%te(icv))
          END DO
          srw%she0(icv, 1) = temp0
        END IF
        IF (t0 .GE. 0.) THEN
          abs6 = t0
        ELSE
          abs6 = -t0
        END IF
        srw%she0(icv, 0) = srw%she0(icv, 0) + switch%&
&         b2stbm_linearisation*abs6
        IF (t0 .GE. 0.) THEN
          abs7 = t0
        ELSE
          abs7 = -t0
        END IF
        temp0 = switch%b2stbm_linearisation*abs7/pl%te(icv)
        DO nd=1,nbdirs
          srwd%she0(nd, icv, 1) = srwd%she0(nd, icv, 1) + temp0*pld%te(&
&           nd, icv)/pl%te(icv)
        END DO
        srw%she0(icv, 1) = srw%she0(icv, 1) - temp0
!  ...ion energy source
        t0 = st_ext%shi(icv)
        IF (switch%b2stbm_internal_energy_sources .EQ. 0) THEN
          DO nd=1,nbdirsmax
            t0d(nd) = 0.D0
          END DO
          DO is=0,ns-1
            IF (.NOT.(st_ext%smo(icv, is) .EQ. 0.0_R8 .AND. st_ext%sna(&
&               icv, is) .EQ. 0.0_R8)) THEN
              temp = st_ext%sna(icv, is)*dtim*dtco(is, ireg) + na0(icv, &
&               is)
              temp0 = (dtim*dtmo(is, ireg)*st_ext%smo(icv, is)/(am(is)*&
&               mp)+ua0(icv, is)*na0(icv, is))/temp
              DO nd=1,nbdirs
                ua_tmpd(nd) = (na0(icv, is)*ua0d(nd, icv, is)+(ua0(icv, &
&                 is)-temp0)*na0d(nd, icv, is))/temp
                duad(nd) = ua_tmpd(nd) - ua0d(nd, icv, is)
              END DO
              ua_tmp = temp0
              dua = ua_tmp - ua0(icv, is)
              temp0 = 0.5_R8*am(is)*mp
              temp2 = 0.5_R8*am(is)*mp
              temp3 = dua*dua/(dtim*dtei(ireg))
              temp = st_ext%sna(icv, is)*dtim*dtco(is, ireg) + na0(icv, &
&               is)
              DO nd=1,nbdirs
                t0d(nd) = t0d(nd) - (st_ext%smo(icv, is)-temp0*st_ext%&
&                 sna(icv, is)*2*ua0(icv, is))*ua0d(nd, icv, is) - temp2&
&                 *(temp3*na0d(nd, icv, is)+temp*2*dua*duad(nd)/(dtim*&
&                 dtei(ireg)))
              END DO
              t0 = t0 - st_ext%smo(icv, is)*ua0(icv, is) + temp0*(st_ext&
&               %sna(icv, is)*(ua0(icv, is)*ua0(icv, is))) - temp2*(temp&
&               *temp3)
            END IF
          END DO
        ELSE
          DO nd=1,nbdirsmax
            t0d(nd) = 0.D0
          END DO
        END IF
        IF (t0 .GE. 0.0_R8) THEN
          DO nd=1,nbdirs
            srwd%shi0(nd, icv, 0) = t0d(nd)
          END DO
          srw%shi0(icv, 0) = t0
        ELSE
          temp3 = t0/pl%ti(icv)
          DO nd=1,nbdirs
            srwd%shi0(nd, icv, 1) = (t0d(nd)-temp3*pld%ti(nd, icv))/pl%&
&             ti(icv)
          END DO
          srw%shi0(icv, 1) = temp3
        END IF
        IF (t0 .GE. 0.) THEN
          DO nd=1,nbdirs
            abs8d(nd) = t0d(nd)
          END DO
          abs8 = t0
        ELSE
          DO nd=1,nbdirs
            abs8d(nd) = -t0d(nd)
          END DO
          abs8 = -t0
        END IF
        DO nd=1,nbdirs
          srwd%shi0(nd, icv, 0) = srwd%shi0(nd, icv, 0) + switch%&
&           b2stbm_linearisation*abs8d(nd)
        END DO
        srw%shi0(icv, 0) = srw%shi0(icv, 0) + switch%&
&         b2stbm_linearisation*abs8
        IF (t0 .GE. 0.) THEN
          DO nd=1,nbdirs
            abs9d(nd) = t0d(nd)
          END DO
          abs9 = t0
        ELSE
          DO nd=1,nbdirs
            abs9d(nd) = -t0d(nd)
          END DO
          abs9 = -t0
        END IF
        temp3 = abs9/pl%ti(icv)
        DO nd=1,nbdirs
          srwd%shi0(nd, icv, 1) = srwd%shi0(nd, icv, 1) - switch%&
&           b2stbm_linearisation*(abs9d(nd)-temp3*pld%ti(nd, icv))/pl%ti&
&           (icv)
        END DO
        srw%shi0(icv, 1) = srw%shi0(icv, 1) - switch%&
&         b2stbm_linearisation*temp3
!  ...electric charge source
        t0 = st_ext%sch(icv)
        IF (t0 .GE. 0.0_R8) THEN
          DO nd=1,nbdirs
            srwd%sch0(nd, icv, 0) = 0.D0
          END DO
          srw%sch0(icv, 0) = t0
        ELSE
          temp3 = t0/pl%po(icv)
          DO nd=1,nbdirs
            srwd%sch0(nd, icv, 1) = -(temp3*pld%po(nd, icv)/pl%po(icv))
          END DO
          srw%sch0(icv, 1) = temp3
        END IF
        IF (t0 .GE. 0.) THEN
          abs10 = t0
        ELSE
          abs10 = -t0
        END IF
        srw%sch0(icv, 0) = srw%sch0(icv, 0) + switch%&
&         b2stbm_linearisation*abs10
        IF (t0 .GE. 0.) THEN
          abs11 = t0
        ELSE
          abs11 = -t0
        END IF
        temp3 = switch%b2stbm_linearisation*abs11/pl%po(icv)
        DO nd=1,nbdirs
          srwd%sch0(nd, icv, 1) = srwd%sch0(nd, icv, 1) + temp3*pld%po(&
&           nd, icv)/pl%po(icv)
        END DO
        srw%sch0(icv, 1) = srw%sch0(icv, 1) - temp3
      ELSE
!  ...raw sources: no linearisation
        srw%sne0(icv, 0) = st_ext%sne(icv)
        DO nd=1,nbdirs
          srwd%sna0(nd, icv, 0, 0:ns-1) = 0.D0
          srwd%smo0(nd, icv, 0, 0:ns-1) = 0.D0
          srwd%she0(nd, icv, 0) = 0.D0
          srwd%sch0(nd, icv, 0) = 0.D0
          srwd%shi0(nd, icv, 0) = 0.D0
        END DO
        srw%sna0(icv, 0, 0:ns-1) = st_ext%sna(icv, 0:ns-1)
        arg10 = geo%cvbb(icv, 0)
        srw%smo0(icv, 0, 0:ns-1) = st_ext%smo(icv, 0:ns-1)*SIGN(1.0_R8, &
&         arg10)
        srw%she0(icv, 0) = st_ext%she(icv)
        srw%sch0(icv, 0) = st_ext%sch(icv)
        srw%shi0(icv, 0) = st_ext%shi(icv)
        IF (switch%b2stbm_internal_energy_sources .EQ. 0) THEN
          DO is=0,ns-1
            IF (.NOT.(st_ext%smo(icv, is) .EQ. 0.0_R8 .AND. st_ext%sna(&
&               icv, is) .EQ. 0.0_R8)) THEN
              temp = st_ext%sna(icv, is)*dtim*dtco(is, ireg) + na0(icv, &
&               is)
              temp3 = (dtim*dtmo(is, ireg)*st_ext%smo(icv, is)/(am(is)*&
&               mp)+ua0(icv, is)*na0(icv, is))/temp
              DO nd=1,nbdirs
                ua_tmpd(nd) = (na0(icv, is)*ua0d(nd, icv, is)+(ua0(icv, &
&                 is)-temp3)*na0d(nd, icv, is))/temp
                duad(nd) = ua_tmpd(nd) - ua0d(nd, icv, is)
              END DO
              ua_tmp = temp3
              dua = ua_tmp - ua0(icv, is)
              temp3 = 0.5_R8*am(is)*mp
              temp2 = 0.5_R8*am(is)*mp
              temp0 = dua*dua/(dtim*dtei(ireg))
              temp = st_ext%sna(icv, is)*dtim*dtco(is, ireg) + na0(icv, &
&               is)
              DO nd=1,nbdirs
                srwd%shi0(nd, icv, 0) = srwd%shi0(nd, icv, 0) - (st_ext%&
&                 smo(icv, is)-temp3*st_ext%sna(icv, is)*2*ua0(icv, is))&
&                 *ua0d(nd, icv, is) - temp2*(temp0*na0d(nd, icv, is)+&
&                 temp*2*dua*duad(nd)/(dtim*dtei(ireg)))
              END DO
              srw%shi0(icv, 0) = srw%shi0(icv, 0) - st_ext%smo(icv, is)*&
&               ua0(icv, is) + temp3*(st_ext%sna(icv, is)*(ua0(icv, is)*&
&               ua0(icv, is))) - temp2*(temp*temp0)
            END IF
          END DO
        END IF
      END IF
    END DO
!
    srw%b2stbm_sna(:, :) = srw%sna0(:, 0, :) + srw%sna0(:, 1, :)*pl%na(:&
&     , :)
    srw%b2stbm_smo(:, :) = srw%smo0(:, 0, :) + srw%smo0(:, 1, :)*pl%ua(:&
&     , :)
    srw%b2stbm_sne(:) = srw%sne0(:, 0) + srw%sne0(:, 1)*dv%ne(:)
    srw%b2stbm_she(:) = srw%she0(:, 0) + srw%she0(:, 1)*pl%te(:)
    srw%b2stbm_shi(:) = srw%shi0(:, 0) + srw%shi0(:, 1)*pl%ti(:)
    srw%b2stbm_sch(:) = srw%sch0(:, 0) + srw%sch0(:, 1)*pl%po(:)
  END IF
!WG_TODO        b2stbm_sna0to1 = sna0
!WG_TODO        b2stbm_smo0to3 = smo0
!WG_TODO        b2stbm_she0to3 = she0
!WG_TODO        b2stbm_shi0to3 = shi0
!
! ..return
  IF (main_call .OR. ncall .EQ. 0) ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2STBM_DV

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2STBM_NODIFF(ncv, nfc, nvx, ns, ismain, dtim, switch, geo, &
& mpg, pl, dv, co, rt, rtw, st_ext, sr, srw, main_call)
  USE B2MOD_TYPES
  USE B2MOD_INDIRECT
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPB_DIFFV
  USE B2MOD_EXTERNAL_DIFFV
  USE B2MOD_IMPGYRO_DIFFV
  USE B2MOD_NEUTRALS_NAMELIST_DIFFV
  USE B2MOD_NUMERICS_NAMELIST_DIFFV
!djm Jan2017
  USE B2MOD_BALANCE_DIFFV, ONLY : b2stbm_sna0to1, b2stbm_smo0to3, &
& b2stbm_she0to3, b2stbm_shi0to3, balance_netcdf
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_SUBSYS
!  Hint: nCv should be the size of dimension 1 of array cvbb
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2stbm
!
!
!djm Jan2017 Keep linearised sources for balance
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns, ismain
  LOGICAL :: main_call
  REAL(kind=r8) :: dtim
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2STATEEXT), INTENT(INOUT) :: st_ext
!   ..input/output arguments 
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2RATES), INTENT(INOUT) :: rt
  TYPE(B2RATESWORK), INTENT(INOUT) :: rtw
  TYPE(B2COEFF), INTENT(INOUT) :: co
  TYPE(B2SOURCE), INTENT(INOUT) :: sr
  TYPE(B2SOURCEWORK), INTENT(INOUT) :: srw
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2STBM provides linearised expressions for the sources of
!     density, parallel momentum, and heat, due to miscellaneous
!     application specific processes.
!
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ia, is, is0, icv, ifc, ireg
  REAL(kind=r8) :: t0, vthe, ua_tmp, dua
  REAL(kind=r8) :: n0_tmp, nr_tmp, nt_tmp, p0_tmp, pr_tmp, r0_tmp, &
& pe_tmp, re_tmp
  REAL(kind=r8) :: na_tot(ncv), na0(ncv, 0:ns-1), ua0(ncv, 0:ns-1), fna0&
& (nfc, 0:1, 0:ns-1), fhi0(nfc, 0:1), ti0(ncv), fhe0(nfc, 0:1), fch0(nfc&
& , 0:1)
  INTEGER, SAVE :: ncall=0
  EXTERNAL XERTST, SFILL_NODIFF, smin, smax, B2XVSG_NODIFF&
&     , B2XVFF_NODIFF, IPGETI, IPGETR
!   ..procedures
  REAL(kind=r8) :: smin, smax
  INTRINSIC ABS, MOD, SQRT
  INTRINSIC SIGN
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: abs3
  REAL(kind=r8) :: abs4
  REAL(kind=r8) :: abs5
  REAL(kind=r8) :: abs6
  REAL(kind=r8) :: abs7
  REAL(kind=r8) :: abs8
  REAL(kind=r8) :: abs9
  REAL(kind=r8) :: abs10
  REAL(kind=r8) :: abs11
  INTEGER :: arg1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(kind=r8) :: arg10
  REAL(kind=r8), DIMENSION(nCv) :: arg11
  REAL(r8) :: arg12
!
!-----------------------------------------------------------------------
!.documentation-internal
!
!     This version of b2stbm imports the sources computed from an
!     external code such as IMPGYRO.
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2stbm')
!   ..test nCv, nFc, ns, ismain
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
  CALL XERTST(0 .LE. ismain .AND. ismain .LT. ns, &
&       'faulty argument ismain')
!   ..extensive tests on first few calls
  IF (ncall .LT. 3) THEN
!    ..test sign of vol, hx, hy
    CALL B2XVSG_NODIFF(ncv, geo%cvvol, 1, 'vol', '.gt.')
    arg1 = nfc*2
    CALL B2XVSG_NODIFF(arg1, geo%fcvol, 1, 'vol', '.gt.')
    CALL B2XVSG_NODIFF(ncv, geo%cvhx, 1, 'hx', '.gt.')
    CALL B2XVSG_NODIFF(nfc, geo%fcht, 1, 'hy', '.gt.')
!    ..test range of cvQgam, fcQgam
    result1 = smin(ncv, geo%cvqgam(1, 1), 1)
    result2 = smax(ncv, geo%cvqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range cvQgam(,1)')
    result1 = smin(ncv, geo%cvqgam(1, 0), 1)
    result2 = smax(ncv, geo%cvqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range cvQgam(,0)')
    result1 = smin(nfc, geo%fcqgam(1, 1), 1)
    result2 = smax(nfc, geo%fcqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range fcQgam(,1)')
    result1 = smin(nfc, geo%fcqgam(1, 0), 1)
    result2 = smax(nfc, geo%fcqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range fcQgam(,0)')
!    ..test state
    CALL B2XVPS_NODIFF(ncv, nfc, ns, pl, dv)
!
!   ..test edge values of fluxes
  END IF
!
!   ..initialise sources to 0
  srw%sna0 = 0.0_R8
  srw%smo0 = 0.0_R8
  srw%sne0 = 0.0_R8
  srw%she0 = 0.0_R8
  srw%shi0 = 0.0_R8
  srw%sch0 = 0.0_R8
  srw%b2stbm_sna = 0.0_R8
  srw%b2stbm_smo = 0.0_R8
  srw%b2stbm_sne = 0.0_R8
  srw%b2stbm_she = 0.0_R8
  srw%b2stbm_shi = 0.0_R8
  srw%b2stbm_sch = 0.0_R8
!
! ..obtain sources from IMPGYRO
  IF (switch%b2stbm_impgyro_mod .NE. 0) THEN
!
!xpb First provide plasma background (include neutral quantities)
!xpb Must convert fluxes to flux densities
    ti0 = 0.0_R8
    fhi0 = 0.0_R8
    na_tot = 0.0_R8
    DO is=0,ns-1
      IF (is_neutral(is)) THEN
        is0 = b2espcr(is)
      ELSE
        is0 = 0
      END IF
      IF (is0 .NE. 0) THEN
        DO icv=1,ncv
          n0_tmp = 0.0_R8
          nr_tmp = 0.0_R8
          nt_tmp = 0.0_R8
          p0_tmp = 0.0_R8
          pe_tmp = 0.0_R8
          pr_tmp = 0.0_R8
          r0_tmp = 0.0_R8
          re_tmp = 0.0_R8
          DO ia=1,nnatmi
            IF (latmscl(ia) .EQ. is0) THEN
              n0_tmp = n0_tmp + dab2(icv, ia, 1)
!WG_TODO        nr_tmp = nr_tmp + dab2(ixr+1,iyr+1,ia,1)
              nt_tmp = nt_tmp + dab2(icv, ia, 1)*tab2(icv, ia, 1)
              p0_tmp = p0_tmp + pfluxa(icv, ia, 1)
              pe_tmp = pe_tmp + pefluxa(icv, ia, 1)
!WG_TODO        pr_tmp = pr_tmp + pfluxa(ixr+1,iyr+1,ia,1)
              r0_tmp = r0_tmp + rfluxa(icv, ia, 1)
              re_tmp = re_tmp + refluxa(icv, ia, 1)
            END IF
          END DO
          IF (n0_tmp .GT. 0.0_R8 .AND. nr_tmp .GT. 0.0_R8) THEN
            ua_tmp = (p0_tmp/n0_tmp+pr_tmp/nr_tmp)/2.0_R8
          ELSE IF (n0_tmp .GT. 0.0_R8) THEN
            ua_tmp = p0_tmp/n0_tmp
          ELSE IF (nr_tmp .GT. 0.0_R8) THEN
            ua_tmp = pr_tmp/nr_tmp
          ELSE
            ua_tmp = 0.0_R8
          END IF
          na_tot(icv) = na_tot(icv) + n0_tmp
          na0(icv, is) = pl%na(icv, is) + n0_tmp
          ti0(icv) = ti0(icv) + nt_tmp
          arg10 = geo%cvbb(icv, 0)
          ua0(icv, is) = (pl%ua(icv, is)*pl%na(icv, is)*SIGN(1.0_R8, &
&           arg10)+ua_tmp*n0_tmp)/na0(icv, is)
        END DO
        DO ifc=1,nfc
          fna0(ifc, 0, is) = dv%fna(ifc, 0, is)/geo%fcs(ifc)/geo%fcqgam(&
&           ifc, 0) + p0_tmp
          fna0(ifc, 1, is) = dv%fna(ifc, 1, is)/geo%fcs(ifc) + r0_tmp
          fhi0(ifc, 0) = fhi0(ifc, 0) + pe_tmp
          fhi0(ifc, 1) = fhi0(ifc, 1) + re_tmp
        END DO
      ELSE
        na0(:, is) = pl%na(:, is)
        arg11(:) = geo%cvbb(:, 0)
        ua0(:, is) = pl%ua(:, is)*SIGN(1.0_R8, arg11(:))
        fna0(:, 0, is) = dv%fna(:, 0, is)/geo%fcs(:)/geo%fcqgam(ifc, 0)
        fna0(:, 1, is) = dv%fna(:, 1, is)/geo%fcs(:)
      END IF
    END DO
    DO is=1,nnmoli
      DO icv=1,ncv
        na_tot(icv) = na_tot(icv) + dmb2(icv, is, 1)
        ti0(icv) = ti0(icv) + dmb2(icv, is, 1)*tmb2(icv, is, 1)
      END DO
    END DO
    DO is=1,nnioni
      DO icv=1,ncv
        na_tot(icv) = na_tot(icv) + dib2(icv, is, 1)
        ti0(icv) = ti0(icv) + dib2(icv, is, 1)*tib2(icv, is, 1)
      END DO
    END DO
    DO icv=1,ncv
      ti0(icv) = (ti0(icv)+pl%ti(icv)*dv%ni(icv, 0))/(na_tot(icv)+dv%ni(&
&       icv, 0))
    END DO
    DO ifc=1,nfc
      fhi0(ifc, 0) = fhi0(ifc, 0) + dv%fhi(ifc, 0)/geo%fcs(ifc)/geo%&
&       fcqgam(ifc, 0)
      fhi0(ifc, 1) = fhi0(ifc, 1) + dv%fhi(ifc, 1)/geo%fcs(ifc)
      fhe0(ifc, 0) = dv%fhe(ifc, 0)/geo%fcs(ifc)/geo%fcqgam(ifc, 0)
      fhe0(ifc, 1) = dv%fhe(ifc, 1)/geo%fcs(ifc)
      fch0(ifc, 0) = dv%fch(ifc, 0)/geo%fcs(ifc)/geo%fcqgam(ifc, 0)
      fch0(ifc, 1) = dv%fch(ifc, 1)/geo%fcs(ifc)
    END DO
!
    IF (ncall .EQ. 0 .OR. (main_call .AND. MOD(ncall, switch%&
&       b2stbm_impgyro_mod) .EQ. 0)) THEN
!xpb The call below obtains the following quantities from IMPGYRO
!xpb Main W data: na_ext, ua_ext, ta_ext
!xpb Sources due to W: sne_ext, smo_ext, she_ext, shi_ext
!xpb Derived quantities: ne_ext, ne2_ext, ni_ext, fa_ext, fhi_ext, ue_ext
!        call read_b2mod_external(nx,ny,ns,ismain)
!xpb In the current arrangement, IMPGYRO provides: na_ext, ua_ext, ta_ext
!xpb It would be best to have instead as primary quantities:
!xpb na_ext, fa_ext, ta_ext, fhi_ext
!xpb And then derive: ua_ext
!
      st_ext%sna = 0.0_R8
      st_ext%sne = 0.0_R8
      st_ext%smo = 0.0_R8
      st_ext%she = 0.0_R8
      st_ext%shi = 0.0_R8
      st_ext%sch = 0.0_R8
      st_ext%na = 0.0_R8
      st_ext%ua = 0.0_R8
      st_ext%ta = 0.0_R8
!
    END IF
!
! ..linearise external sources
    DO icv=1,ncv
      ireg = mpg%cvreg(icv)
      IF (switch%b2stbm_linearisation .GT. 0.0_R8) THEN
!  ...electron particle source
        t0 = st_ext%sne(icv)
        IF (t0 .GE. 0.0_R8) THEN
          srw%sne0(icv, 0) = t0
        ELSE
          srw%sne0(icv, 1) = t0/dv%ne(icv)
        END IF
        IF (t0 .GE. 0.) THEN
          abs0 = t0
        ELSE
          abs0 = -t0
        END IF
        srw%sne0(icv, 0) = srw%sne0(icv, 0) + switch%&
&         b2stbm_linearisation*abs0
        IF (t0 .GE. 0.) THEN
          abs1 = t0
        ELSE
          abs1 = -t0
        END IF
        srw%sne0(icv, 1) = srw%sne0(icv, 1) - switch%&
&         b2stbm_linearisation*abs1/dv%ne(icv)
        DO is=0,ns-1
!  ...heavy particles sources
          t0 = st_ext%sna(icv, is)
          IF (t0 .GE. 0.0_R8) THEN
            srw%sna0(icv, 0, is) = t0
          ELSE
            srw%sna0(icv, 1, is) = t0/pl%na(icv, is)
          END IF
          IF (t0 .GE. 0.) THEN
            abs2 = t0
          ELSE
            abs2 = -t0
          END IF
          srw%sna0(icv, 0, is) = srw%sna0(icv, 0, is) + switch%&
&           b2stbm_linearisation*abs2
          IF (t0 .GE. 0.) THEN
            abs3 = t0
          ELSE
            abs3 = -t0
          END IF
          srw%sna0(icv, 1, is) = srw%sna0(icv, 1, is) - switch%&
&           b2stbm_linearisation*abs3/pl%na(icv, is)
!  ...parallel momentum sources
          arg12 = pl%te(icv)/me
          vthe = SQRT(arg12)
          arg10 = am(is)*mp/me
          result1 = SQRT(arg10)
          vthe = vthe/result1
          arg10 = geo%cvbb(icv, 0)
          t0 = st_ext%smo(icv, is)*SIGN(1.0_R8, arg10)
          IF (t0 .GE. 0.) THEN
            abs4 = t0
          ELSE
            abs4 = -t0
          END IF
          srw%smo0(icv, 0, is) = srw%smo0(icv, 0, is) + t0 + switch%&
&           b2stbm_linearisation*abs4*pl%ua(icv, is)/vthe
          IF (t0 .GE. 0.) THEN
            abs5 = t0
          ELSE
            abs5 = -t0
          END IF
          srw%smo0(icv, 1, is) = srw%smo0(icv, 1, is) - switch%&
&           b2stbm_linearisation*abs5/vthe
        END DO
!  ...electron energy source
        t0 = st_ext%she(icv)
        IF (t0 .GE. 0.0_R8) THEN
          srw%she0(icv, 0) = t0
        ELSE
          srw%she0(icv, 1) = t0/pl%te(icv)
        END IF
        IF (t0 .GE. 0.) THEN
          abs6 = t0
        ELSE
          abs6 = -t0
        END IF
        srw%she0(icv, 0) = srw%she0(icv, 0) + switch%&
&         b2stbm_linearisation*abs6
        IF (t0 .GE. 0.) THEN
          abs7 = t0
        ELSE
          abs7 = -t0
        END IF
        srw%she0(icv, 1) = srw%she0(icv, 1) - switch%&
&         b2stbm_linearisation*abs7/pl%te(icv)
!  ...ion energy source
        t0 = st_ext%shi(icv)
        IF (switch%b2stbm_internal_energy_sources .EQ. 0) THEN
          DO is=0,ns-1
            IF (.NOT.(st_ext%smo(icv, is) .EQ. 0.0_R8 .AND. st_ext%sna(&
&               icv, is) .EQ. 0.0_R8)) THEN
              ua_tmp = (ua0(icv, is)*na0(icv, is)+st_ext%smo(icv, is)*&
&               dtim*dtmo(is, ireg)/(am(is)*mp))/(na0(icv, is)+st_ext%&
&               sna(icv, is)*dtim*dtco(is, ireg))
              dua = ua_tmp - ua0(icv, is)
              t0 = t0 - ua0(icv, is)*st_ext%smo(icv, is) + 0.5_R8*(am(is&
&               )*mp)*ua0(icv, is)**2*st_ext%sna(icv, is) - (na0(icv, is&
&               )+st_ext%sna(icv, is)*dtim*dtco(is, ireg))/(dtim*dtei(&
&               ireg))*0.5_R8*(am(is)*mp)*dua**2
            END IF
          END DO
        END IF
        IF (t0 .GE. 0.0_R8) THEN
          srw%shi0(icv, 0) = t0
        ELSE
          srw%shi0(icv, 1) = t0/pl%ti(icv)
        END IF
        IF (t0 .GE. 0.) THEN
          abs8 = t0
        ELSE
          abs8 = -t0
        END IF
        srw%shi0(icv, 0) = srw%shi0(icv, 0) + switch%&
&         b2stbm_linearisation*abs8
        IF (t0 .GE. 0.) THEN
          abs9 = t0
        ELSE
          abs9 = -t0
        END IF
        srw%shi0(icv, 1) = srw%shi0(icv, 1) - switch%&
&         b2stbm_linearisation*abs9/pl%ti(icv)
!  ...electric charge source
        t0 = st_ext%sch(icv)
        IF (t0 .GE. 0.0_R8) THEN
          srw%sch0(icv, 0) = t0
        ELSE
          srw%sch0(icv, 1) = t0/pl%po(icv)
        END IF
        IF (t0 .GE. 0.) THEN
          abs10 = t0
        ELSE
          abs10 = -t0
        END IF
        srw%sch0(icv, 0) = srw%sch0(icv, 0) + switch%&
&         b2stbm_linearisation*abs10
        IF (t0 .GE. 0.) THEN
          abs11 = t0
        ELSE
          abs11 = -t0
        END IF
        srw%sch0(icv, 1) = srw%sch0(icv, 1) - switch%&
&         b2stbm_linearisation*abs11/pl%po(icv)
      ELSE
!  ...raw sources: no linearisation
        srw%sne0(icv, 0) = st_ext%sne(icv)
        srw%sna0(icv, 0, 0:ns-1) = st_ext%sna(icv, 0:ns-1)
        arg10 = geo%cvbb(icv, 0)
        srw%smo0(icv, 0, 0:ns-1) = st_ext%smo(icv, 0:ns-1)*SIGN(1.0_R8, &
&         arg10)
        srw%she0(icv, 0) = st_ext%she(icv)
        srw%sch0(icv, 0) = st_ext%sch(icv)
        srw%shi0(icv, 0) = st_ext%shi(icv)
        IF (switch%b2stbm_internal_energy_sources .EQ. 0) THEN
          DO is=0,ns-1
            IF (.NOT.(st_ext%smo(icv, is) .EQ. 0.0_R8 .AND. st_ext%sna(&
&               icv, is) .EQ. 0.0_R8)) THEN
              ua_tmp = (ua0(icv, is)*na0(icv, is)+st_ext%smo(icv, is)*&
&               dtim*dtmo(is, ireg)/(am(is)*mp))/(na0(icv, is)+st_ext%&
&               sna(icv, is)*dtim*dtco(is, ireg))
              dua = ua_tmp - ua0(icv, is)
              srw%shi0(icv, 0) = srw%shi0(icv, 0) - ua0(icv, is)*st_ext%&
&               smo(icv, is) + 0.5_R8*(am(is)*mp)*ua0(icv, is)**2*st_ext&
&               %sna(icv, is) - (na0(icv, is)+st_ext%sna(icv, is)*dtim*&
&               dtco(is, ireg))/(dtim*dtei(ireg))*0.5_R8*(am(is)*mp)*dua&
&               **2
            END IF
          END DO
        END IF
      END IF
    END DO
!
    srw%b2stbm_sna(:, :) = srw%sna0(:, 0, :) + srw%sna0(:, 1, :)*pl%na(:&
&     , :)
    srw%b2stbm_smo(:, :) = srw%smo0(:, 0, :) + srw%smo0(:, 1, :)*pl%ua(:&
&     , :)
    srw%b2stbm_sne(:) = srw%sne0(:, 0) + srw%sne0(:, 1)*dv%ne(:)
    srw%b2stbm_she(:) = srw%she0(:, 0) + srw%she0(:, 1)*pl%te(:)
    srw%b2stbm_shi(:) = srw%shi0(:, 0) + srw%shi0(:, 1)*pl%ti(:)
    srw%b2stbm_sch(:) = srw%sch0(:, 0) + srw%sch0(:, 1)*pl%po(:)
  END IF
!WG_TODO        b2stbm_sna0to1 = sna0
!WG_TODO        b2stbm_smo0to3 = smo0
!WG_TODO        b2stbm_she0to3 = she0
!WG_TODO        b2stbm_shi0to3 = shi0
!
! ..return
  IF (main_call .OR. ncall .EQ. 0) ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2STBM_NODIFF

