!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2tinnt in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: fchin
!   with respect to varying inputs: ti na fna *(rt.rza) csigin
!                po
!   Plus diff mem management of: mpg.intcellp:in mpg.intcellr:in
!                geo.fcbb:in geo.fcs:in geo.fchc:in geo.fcht:in
!                geo.fcvol:in geo.fcqgam:in geo.fcqalf:in geo.fcqbet:in
!                geo.vxvol:in rt.rza:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 08.03.99 16.06.09
SUBROUTINE B2TINNT_DV(ncv, nfc, nvx, ns, switch, geo, geod, mpg, mpgd, &
& rt, rtd, facdrift, fac_exb, ismain, ismain0, te, po, pod, ti, tid, na&
& , nad, fna, fnad, csigin, csigind, fchin, fchind, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMFS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_NEUTRALS_NAMELIST_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
!  Hint: nFc should be the size of dimension 1 of array fcqalf
!  Hint: nFc should be the size of dimension 1 of array fchc
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2tinnt
!
!   ..set internal parameters on first call
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns, ismain, ismain0
  REAL(kind=r8) :: facdrift(nfc), fac_exb(nfc), te(ncv), po(ncv), ti(ncv&
& ), na(ncv, 0:ns-1), fna(nfc, 0:1, 0:ns-1), csigin(nfc, 0:1, 0:ns-1, 0:&
& ns-1)
  REAL(kind=r8) :: pod(nbdirsmax, ncv), tid(nbdirsmax, ncv), nad(&
& nbdirsmax, ncv, 0:ns-1), fnad(nbdirsmax, nfc, 0:1, 0:ns-1), csigind(&
& nbdirsmax, nfc, 0:1, 0:ns-1, 0:ns-1)
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  TYPE(B2RATES), INTENT(IN) :: rt
  TYPE(B2RATES_DIFFV), INTENT(IN) :: rtd
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fchin(nfc, 0:1)
  REAL(kind=r8) :: fchind(nbdirsmax, nfc, 0:1)
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TINNT computes the ion-neutral current
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: is, is0
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8), PARAMETER :: eps=1.0e-60_R8
!srv 08.07.09
!WG_TODO work(-1:nx,-1:ny,0:1,0:ns-1),
  REAL(kind=r8) :: fnac(ncv, 0:1, 0:ns-1), vntrc(ncv, 0:1), vntrf(nfc, 0&
& :1), tif(nfc), naf(nfc, 0:ns-1), dpo(nfc, 0:1), fnan(nfc, 0:1, 0:ns-1)&
& , wrk(ncv), wrk0(nfc, 0:1, 0:ns-1), wrk1(nfc, 0:1), wrk2(nfc), wrkvx(&
& nvx), wrk3(nfc, 0:1), wrkv(ncv)
  REAL(kind=r8) :: fnacd(nbdirsmax, ncv, 0:1, 0:ns-1), vntrcd(nbdirsmax&
& , ncv, 0:1), vntrfd(nbdirsmax, nfc, 0:1), tifd(nbdirsmax, nfc), nafd(&
& nbdirsmax, nfc, 0:ns-1), dpod(nbdirsmax, nfc, 0:1), fnand(nbdirsmax, &
& nfc, 0:1, 0:ns-1), wrkd(nbdirsmax, ncv), wrk0d(nbdirsmax, nfc, 0:1, 0:&
& ns-1), wrk1d(nbdirsmax, nfc, 0:1), wrk2d(nbdirsmax, nfc), wrkvxd(&
& nbdirsmax, nvx), wrkvd(nbdirsmax, ncv)
!srv 20.10.17
  REAL(kind=r8) :: facdriftm, fac_exbm
  INTRINSIC MAXVAL
  EXTERNAL XERRAB
  INTRINSIC LOG
  INTRINSIC NINT
  INTEGER :: nd
  REAL(kind=r8), DIMENSION(nFc) :: temp
  REAL(kind=r8), DIMENSION(ncv) :: temp0
  REAL(kind=r8), DIMENSION(nFc) :: temp1
  REAL(kind=r8), DIMENSION(nfc) :: temp2
  REAL(kind=r8), DIMENSION(nfc) :: temp3
  INTEGER :: nbdirs
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!      integer, save :: mode = 1
!      integer, save :: iout = 0
!      integer, save :: fchin_in_core = 0                                  !srv 16.11.17
!   ..procedures
!   ..initialisation
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tinnt')
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgeti ('b2tinnt_iout', iout)
!        call ipgeti ('b2tral_mode', mode)
!        call ipgeti ('b2tinnt_fchin_in_core', fchin_in_core)              !srv 16.11.17
!   ..test nCv, nFc
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
!srv 09.07.99
  fchin = 0.0e0_R8
!srv 20.10.17
  facdriftm = MAXVAL(facdrift)
  fac_exbm = MAXVAL(fac_exb)
!
  IF (switch%pot_eq .EQ. 1 .AND. (facdriftm .GT. 0.0_R8 .OR. fac_exbm &
&     .GT. 0.0_R8) .AND. switch%no_current .EQ. 0 .AND. switch%&
&     fch_ion_neutral .NE. 0.0e0_R8) THEN
!srv 26.07.06 01.07.99
    IF (switch%use_eirene .NE. 0) THEN
      CALL XERRAB('b2tinnt not yet available for WG + EIRENE')
      DO nd=1,nbdirsmax
        fchind(nd, :, :) = 0.D0
      END DO
    ELSE
!   ..extensive tests on first few calls
      IF (ncall .LT. 3) THEN
!    ..test sign of te
        CALL B2XVSG_NODIFF(ncv, te, 1, 'te', '.gt.')
!    ..test sign of csigin
        DO is=0,ns-1
          DO is0=0,ns-1
            wrk3(:, 0) = csigin(:, 0, is, is0)*geo%fcqalf(:, 0)
            wrk3(:, 1) = csigin(:, 1, is, is0)*geo%fcqalf(:, 1)
            CALL B2XVSG_NODIFF(nfc, wrk3(:, 0), 1, 'csigin0', '.ge.')
            CALL B2XVSG_NODIFF(nfc, wrk3(:, 1), 1, 'csigin1', '.ge.')
          END DO
        END DO
      END IF
      IF (switch%b2tinnt_style .EQ. 0) THEN
!   ..interpolate ti to cell faces
        DO nd=1,nbdirsmax
          tifd(nd, :) = 0.D0
        END DO
        CALL INTFACE_DV(ncv, nfc, mpg%fccv, geo%fcvol, ti, tid, tif, &
&                 tifd, nbdirs)
!   ..pre-computation of differences
        DO nd=1,nbdirsmax
          dpod(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          wrkvxd(nd, :) = 0.D0
        END DO
        CALL DIFF_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, po, pod, &
&              wrkvx, wrkvxd, dpo, dpod, nbdirs)
        DO nd=1,nbdirsmax
          wrk0d(nd, :, :, :) = 0.D0
        END DO
        DO is=0,ns-1
!srv 12.05.18
          DO nd=1,nbdirs
            wrkd(nd, :) = nad(nd, :, is)/na(:, is)
          END DO
          wrk = LOG(na(:, is))
          CALL DIFF_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, wrk, wrkd&
&                , wrkvx, wrkvxd, wrk0(:, :, is), wrk0d(:, :, :, is), &
&                nbdirs)
        END DO
        DO nd=1,nbdirsmax
          wrk1d(nd, :, :) = 0.D0
        END DO
        CALL DIFF_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, ti, tid, &
&              wrkvx, wrkvxd, wrk1, wrk1d, nbdirs)
        DO nd=1,nbdirsmax
          fchind(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          vntrfd(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          fnand(nd, :, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          nafd(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          wrk2d(nd, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          vntrcd(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          fnacd(nd, :, :, :) = 0.D0
        END DO
      ELSE
        DO nd=1,nbdirsmax
          nafd(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          wrk0d(nd, :, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          wrkvxd(nd, :) = 0.D0
        END DO
        DO is=0,ns-1
!   ..interpolate na to cell faces
          CALL INTFACE_DV(ncv, nfc, mpg%fccv, geo%fcvol, na(:, is), nad(&
&                   :, :, is), naf(:, is), nafd(:, :, is), nbdirs)
!   ..pre-computation of differences
          DO nd=1,nbdirs
            wrkvd(nd, :) = ti(:)*nad(nd, :, is) + na(:, is)*tid(nd, :)
          END DO
          wrkv(:) = na(:, is)*ti(:)
          CALL DIFF_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, wrkv, &
&                wrkvd, wrkvx, wrkvxd, wrk0(:, :, is), wrk0d(:, :, :, is&
&                ), nbdirs)
        END DO
        DO nd=1,nbdirsmax
          dpod(nd, :, :) = 0.D0
        END DO
        CALL DIFF_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, po, pod, &
&              wrkvx, wrkvxd, dpo, dpod, nbdirs)
        DO nd=1,nbdirsmax
          fchind(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          vntrfd(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          fnand(nd, :, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          tifd(nd, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          wrk1d(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          wrk2d(nd, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          vntrcd(nd, :, :) = 0.D0
        END DO
        DO nd=1,nbdirsmax
          fnacd(nd, :, :, :) = 0.D0
        END DO
      END IF
!   ..calculate the contribution of ion-neutral current
      DO is0=0,ns-1
        IF (is_neutral(is0) .AND. NINT(zn(is0)) .EQ. 1) THEN
!srv 20.10.17
!      ..get fluxes divided by area
          temp = geo%fcs*geo%fcqalf(:, 0) + eps
          DO nd=1,nbdirs
            fnand(nd, :, 0, is0) = fnad(nd, :, 0, is0)/temp
          END DO
          fnan(:, 0, is0) = fna(:, 0, is0)/temp
          temp = geo%fcs*geo%fcqalf(:, 1) + eps
!       ..get fluxes in the cell centre
          CALL INTCELL_DV(nfc, ncv, mpg, mpg%intcellp, fnan(:, 0, is0), &
&                   fnand(:, :, 0, is0), fnac(:, 0, is0), fnacd(:, :, 0&
&                   , is0), nbdirs)
!      ..get velocities in the cell centre
          temp0 = fnac(:, 0, is0)/na(:, is0)
          DO nd=1,nbdirs
            fnand(nd, :, 1, is0) = fnad(nd, :, 1, is0)/temp
            vntrcd(nd, :, 0) = (fnacd(nd, :, 0, is0)-temp0*nad(nd, :, &
&             is0))/na(:, is0)
          END DO
          fnan(:, 1, is0) = fna(:, 1, is0)/temp
          CALL INTCELL_DV(nfc, ncv, mpg, mpg%intcellr, fnan(:, 1, is0), &
&                   fnand(:, :, 1, is0), fnac(:, 1, is0), fnacd(:, :, 1&
&                   , is0), nbdirs)
          vntrc(:, 0) = temp0
          temp0 = fnac(:, 1, is0)/na(:, is0)
          DO nd=1,nbdirs
            vntrcd(nd, :, 1) = (fnacd(nd, :, 1, is0)-temp0*nad(nd, :, &
&             is0))/na(:, is0)
          END DO
          vntrc(:, 1) = temp0
!      ..interpolate velocities in the cell face
          CALL INTFACE_DV(ncv, nfc, mpg%fccv, geo%fcvol, vntrc(:, 0), &
&                   vntrcd(:, :, 0), vntrf(:, 0), vntrfd(:, :, 0), &
&                   nbdirs)
          CALL INTFACE_DV(ncv, nfc, mpg%fccv, geo%fcvol, vntrc(:, 1), &
&                   vntrcd(:, :, 1), vntrf(:, 1), vntrfd(:, :, 1), &
&                   nbdirs)
!      ..components of ion-neutral current
          DO is=0,ns-1
            IF (.NOT.is_neutral(is) .AND. NINT(zn(is)) .EQ. 1) THEN
!srv 20.10.17
              DO nd=1,nbdirs
                wrkd(nd, :) = qe*rtd%rza(nd, :, is)
              END DO
              wrk = qe*rt%rza(:, is)
              CALL INTFACE_DV(ncv, nfc, mpg%fccv, geo%fcvol, wrk, wrkd, &
&                       wrk2, wrk2d, nbdirs)
              IF (switch%b2tinnt_style .EQ. 0) THEN
                temp1 = geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(:, 2))
                temp2 = (wrk1(:, 0)+tif*wrk0(:, 0, is))/wrk2
                temp3 = geo%fcbb(:, 2)*geo%fcbb(:, 2)*(-dpo(:, 0)-temp2)&
&                 /(geo%fcbb(:, 3)*geo%fcbb(:, 3)) + geo%fcbb(:, 2)*&
&                 vntrf(:, 1)*temp1
                DO nd=1,nbdirs
                  fchind(nd, :, 0) = fchind(nd, :, 0) + temp3*csigind(nd&
&                   , :, 0, is, is0) + csigin(:, 0, is, is0)*(geo%fcbb(:&
&                   , 2)**2*(-dpod(nd, :, 0)-(wrk1d(nd, :, 0)+wrk0(:, 0&
&                   , is)*tifd(nd, :)+tif*wrk0d(nd, :, 0, is)-temp2*&
&                   wrk2d(nd, :))/wrk2)/geo%fcbb(:, 3)**2+temp1*geo%fcbb&
&                   (:, 2)*vntrfd(nd, :, 1))
                END DO
                fchin(:, 0) = fchin(:, 0) + csigin(:, 0, is, is0)*temp3
                temp1 = geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(:, 2))
                temp3 = (wrk1(:, 1)+tif*wrk0(:, 1, is))/wrk2
                temp2 = -dpo(:, 1) - temp3 - geo%fcbb(:, 2)*vntrf(:, 0)*&
&                 temp1
                DO nd=1,nbdirs
                  fchind(nd, :, 1) = fchind(nd, :, 1) + temp2*csigind(nd&
&                   , :, 1, is, is0) + csigin(:, 1, is, is0)*(-dpod(nd, &
&                   :, 1)-(wrk1d(nd, :, 1)+wrk0(:, 1, is)*tifd(nd, :)+&
&                   tif*wrk0d(nd, :, 1, is)-temp3*wrk2d(nd, :))/wrk2-&
&                   temp1*geo%fcbb(:, 2)*vntrfd(nd, :, 0))
                END DO
                fchin(:, 1) = fchin(:, 1) + csigin(:, 1, is, is0)*temp2
              ELSE
                temp1 = geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(:, 2))
                temp3 = wrk0(:, 0, is)/(naf(:, is)*wrk2)
                temp2 = geo%fcbb(:, 2)*geo%fcbb(:, 2)*(-dpo(:, 0)-temp3)&
&                 /(geo%fcbb(:, 3)*geo%fcbb(:, 3)) + geo%fcbb(:, 2)*&
&                 vntrf(:, 1)*temp1
                DO nd=1,nbdirs
                  fchind(nd, :, 0) = fchind(nd, :, 0) + temp2*csigind(nd&
&                   , :, 0, is, is0) + csigin(:, 0, is, is0)*(geo%fcbb(:&
&                   , 2)**2*(-dpod(nd, :, 0)-(wrk0d(nd, :, 0, is)-temp3*&
&                   (wrk2*nafd(nd, :, is)+naf(:, is)*wrk2d(nd, :)))/(naf&
&                   (:, is)*wrk2))/geo%fcbb(:, 3)**2+temp1*geo%fcbb(:, 2&
&                   )*vntrfd(nd, :, 1))
                END DO
                fchin(:, 0) = fchin(:, 0) + csigin(:, 0, is, is0)*temp2
                temp1 = geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(:, 2))
                temp3 = wrk0(:, 1, is)/(naf(:, is)*wrk2)
                temp2 = -dpo(:, 1) - temp3 - geo%fcbb(:, 2)*vntrf(:, 0)*&
&                 temp1
                DO nd=1,nbdirs
                  fchind(nd, :, 1) = fchind(nd, :, 1) + temp2*csigind(nd&
&                   , :, 1, is, is0) + csigin(:, 1, is, is0)*(-dpod(nd, &
&                   :, 1)-(wrk0d(nd, :, 1, is)-temp3*(wrk2*nafd(nd, :, &
&                   is)+naf(:, is)*wrk2d(nd, :)))/(naf(:, is)*wrk2)-&
&                   temp1*geo%fcbb(:, 2)*vntrfd(nd, :, 0))
                END DO
                fchin(:, 1) = fchin(:, 1) + csigin(:, 1, is, is0)*temp2
              END IF
            END IF
          END DO
        END IF
      END DO
    END IF
  ELSE
    DO nd=1,nbdirsmax
      fchind(nd, :, :) = 0.D0
    END DO
  END IF
!srv 08.07.09 }
!
!
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TINNT_DV

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 08.03.99 16.06.09
SUBROUTINE B2TINNT_NODIFF(ncv, nfc, nvx, ns, switch, geo, mpg, rt, &
& facdrift, fac_exb, ismain, ismain0, te, po, ti, na, fna, csigin, fchin&
&)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMFS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_NEUTRALS_NAMELIST_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2tinnt
!
!   ..set internal parameters on first call
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns, ismain, ismain0
  REAL(kind=r8) :: facdrift(nfc), fac_exb(nfc), te(ncv), po(ncv), ti(ncv&
& ), na(ncv, 0:ns-1), fna(nfc, 0:1, 0:ns-1), csigin(nfc, 0:1, 0:ns-1, 0:&
& ns-1)
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2RATES), INTENT(IN) :: rt
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fchin(nfc, 0:1)
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TINNT computes the ion-neutral current
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: is, is0
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8), PARAMETER :: eps=1.0e-60_R8
!srv 08.07.09
!WG_TODO work(-1:nx,-1:ny,0:1,0:ns-1),
  REAL(kind=r8) :: fnac(ncv, 0:1, 0:ns-1), vntrc(ncv, 0:1), vntrf(nfc, 0&
& :1), tif(nfc), naf(nfc, 0:ns-1), dpo(nfc, 0:1), fnan(nfc, 0:1, 0:ns-1)&
& , wrk(ncv), wrk0(nfc, 0:1, 0:ns-1), wrk1(nfc, 0:1), wrk2(nfc), wrkvx(&
& nvx), wrk3(nfc, 0:1), wrkv(ncv)
!srv 20.10.17
  REAL(kind=r8) :: facdriftm, fac_exbm
  INTRINSIC MAXVAL
  EXTERNAL XERRAB
  INTRINSIC LOG
  INTRINSIC NINT
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!      integer, save :: mode = 1
!      integer, save :: iout = 0
!      integer, save :: fchin_in_core = 0                                  !srv 16.11.17
!   ..procedures
!   ..initialisation
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tinnt')
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgeti ('b2tinnt_iout', iout)
!        call ipgeti ('b2tral_mode', mode)
!        call ipgeti ('b2tinnt_fchin_in_core', fchin_in_core)              !srv 16.11.17
!   ..test nCv, nFc
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
!srv 09.07.99
  fchin = 0.0e0_R8
!srv 20.10.17
  facdriftm = MAXVAL(facdrift)
  fac_exbm = MAXVAL(fac_exb)
!
  IF (switch%pot_eq .EQ. 1 .AND. (facdriftm .GT. 0.0_R8 .OR. fac_exbm &
&     .GT. 0.0_R8) .AND. switch%no_current .EQ. 0 .AND. switch%&
&     fch_ion_neutral .NE. 0.0e0_R8) THEN
!srv 26.07.06 01.07.99
    IF (switch%use_eirene .NE. 0) THEN
      CALL XERRAB('b2tinnt not yet available for WG + EIRENE')
    ELSE
!   ..extensive tests on first few calls
      IF (ncall .LT. 3) THEN
!    ..test sign of te
        CALL B2XVSG_NODIFF(ncv, te, 1, 'te', '.gt.')
!    ..test sign of csigin
        DO is=0,ns-1
          DO is0=0,ns-1
            wrk3(:, 0) = csigin(:, 0, is, is0)*geo%fcqalf(:, 0)
            wrk3(:, 1) = csigin(:, 1, is, is0)*geo%fcqalf(:, 1)
            CALL B2XVSG_NODIFF(nfc, wrk3(:, 0), 1, 'csigin0', '.ge.')
            CALL B2XVSG_NODIFF(nfc, wrk3(:, 1), 1, 'csigin1', '.ge.')
          END DO
        END DO
      END IF
      IF (switch%b2tinnt_style .EQ. 0) THEN
!   ..interpolate ti to cell faces
        CALL INTFACE(ncv, nfc, mpg%fccv, geo%fcvol, ti, tif)
!   ..pre-computation of differences
        CALL DIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, po, wrkvx, dpo)
        DO is=0,ns-1
!srv 12.05.18
          wrk = LOG(na(:, is))
          CALL DIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, wrk, wrkvx, wrk0(&
&                    :, :, is))
        END DO
        CALL DIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, ti, wrkvx, wrk1)
      ELSE
        DO is=0,ns-1
!   ..interpolate na to cell faces
          CALL INTFACE(ncv, nfc, mpg%fccv, geo%fcvol, na(:, is), naf(:, &
&                is))
!   ..pre-computation of differences
          wrkv(:) = na(:, is)*ti(:)
          CALL DIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, wrkv, wrkvx, wrk0&
&                    (:, :, is))
        END DO
        CALL DIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, po, wrkvx, dpo)
      END IF
!   ..calculate the contribution of ion-neutral current
      DO is0=0,ns-1
        IF (is_neutral(is0) .AND. NINT(zn(is0)) .EQ. 1) THEN
!srv 20.10.17
!      ..get fluxes divided by area
          fnan(:, 0, is0) = fna(:, 0, is0)/(geo%fcs*geo%fcqalf(:, 0)+eps&
&           )
          fnan(:, 1, is0) = fna(:, 1, is0)/(geo%fcs*geo%fcqalf(:, 1)+eps&
&           )
!       ..get fluxes in the cell centre
          CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellp, fnan(:, 0, &
&                       is0), fnac(:, 0, is0))
          CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellr, fnan(:, 1, &
&                       is0), fnac(:, 1, is0))
!      ..get velocities in the cell centre
          vntrc(:, 0) = fnac(:, 0, is0)/na(:, is0)
          vntrc(:, 1) = fnac(:, 1, is0)/na(:, is0)
!      ..interpolate velocities in the cell face
          CALL INTFACE(ncv, nfc, mpg%fccv, geo%fcvol, vntrc(:, 0), vntrf&
&                (:, 0))
          CALL INTFACE(ncv, nfc, mpg%fccv, geo%fcvol, vntrc(:, 1), vntrf&
&                (:, 1))
!      ..components of ion-neutral current
          DO is=0,ns-1
            IF (.NOT.is_neutral(is) .AND. NINT(zn(is)) .EQ. 1) THEN
!srv 20.10.17
              wrk = qe*rt%rza(:, is)
              CALL INTFACE(ncv, nfc, mpg%fccv, geo%fcvol, wrk, wrk2)
              IF (switch%b2tinnt_style .EQ. 0) THEN
                fchin(:, 0) = fchin(:, 0) + csigin(:, 0, is, is0)*((-dpo&
&                 (:, 0)-(wrk1(:, 0)+tif*wrk0(:, 0, is))/wrk2)*(geo%fcbb&
&                 (:, 2)/geo%fcbb(:, 3))**2+geo%fcbb(:, 2)*vntrf(:, 1)*&
&                 geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(:, 2)))
                fchin(:, 1) = fchin(:, 1) + csigin(:, 1, is, is0)*(-dpo(&
&                 :, 1)-(wrk1(:, 1)+tif*wrk0(:, 1, is))/wrk2-geo%fcbb(:&
&                 , 2)*vntrf(:, 0)*geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%&
&                 fchc(:, 2)))
              ELSE
                fchin(:, 0) = fchin(:, 0) + csigin(:, 0, is, is0)*((-dpo&
&                 (:, 0)-wrk0(:, 0, is)/(naf(:, is)*wrk2))*(geo%fcbb(:, &
&                 2)/geo%fcbb(:, 3))**2+geo%fcbb(:, 2)*vntrf(:, 1)*geo%&
&                 fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(:, 2)))
                fchin(:, 1) = fchin(:, 1) + csigin(:, 1, is, is0)*(-dpo(&
&                 :, 1)-wrk0(:, 1, is)/(naf(:, is)*wrk2)-geo%fcbb(:, 2)*&
&                 vntrf(:, 0)*geo%fcqgam(:, 0)*(geo%fchc(:, 1)+geo%fchc(&
&                 :, 2)))
              END IF
            END IF
          END DO
        END IF
      END DO
    END IF
  END IF
!srv 08.07.09 }
!
!
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TINNT_NODIFF

