!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHI_NODIFF(ncv, nfc, mp, cflmi, switch, geo, mpg, ni, nirm&
& , ni_ext, ti, tn, chvimx)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: mp, cflmi, ni(ncv, 0:1), nirm(ncv), ni_ext(ncv, 0:1)&
& , ti(ncv), tn(ncv), chvimx(nfc)
!     ------------------------------------------------------------------
!     B2TLHI computes the all atom heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: icv, ifc
  REAL(kind=r8) :: t0, t1
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVFX_NODIFF
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: arg1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(kind=r8) :: result3
  REAL(kind=r8) :: arg2
  REAL(kind=r8) :: result4
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlhi')
!   ..test mp, cflmi
  CALL XERTST(0.0_R8 .LT. mp, 'faulty argument mp')
  CALL XERTST(0.0_R8 .LE. cflmi, 'faulty argument cflmi')
!
!   ..compute flux limit velocity
  IF (switch%b2tqca_model .EQ. 1) THEN
! SOLPS5.0 treatments
    DO ifc=1,nfc
      IF (ti(mpg%fccv(ifc, 1)) .LT. ti(mpg%fccv(ifc, 2))) THEN
        t0 = ti(mpg%fccv(ifc, 2))
      ELSE
        t0 = ti(mpg%fccv(ifc, 1))
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        abs0 = geo%fcpbs(ifc)
      ELSE
        abs0 = -geo%fcpbs(ifc)
      END IF
!srv 11.01.13
      arg1 = t0/mp
      result1 = SQRT(arg1)
      chvimx(ifc) = cflmi*abs0*result1*(nirm(mpg%fccv(ifc, 1))+nirm(mpg%&
&       fccv(ifc, 2)))/(ni(mpg%fccv(ifc, 1), 0)+ni_ext(mpg%fccv(ifc, 1)&
&       , 0)+ni(mpg%fccv(ifc, 2), 0)+ni_ext(mpg%fccv(ifc, 2), 0))
    END DO
  ELSE IF (switch%b2tqca_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      t0 = ti(mpg%fccv(ifc, 2))
      t1 = ti(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        abs1 = geo%fcqalf(ifc, 0)
      ELSE
        abs1 = -geo%fcqalf(ifc, 0)
      END IF
      IF (t0 .LT. t1) THEN
        max1 = t1
      ELSE
        max1 = t0
      END IF
!wdk 10.03.16 Divide by ni*ti at cell faces, so chvimx contains the same information
!           as case b2tqca_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhi), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      result1 = PIT(mpg%fccv(ifc, 2))
      arg1 = t0/mp
      result2 = SQRT(arg1)
      result3 = PIT(mpg%fccv(ifc, 1))
      arg2 = t1/mp
      result4 = SQRT(arg2)
      chvimx(ifc) = cflmi*geo%fcs(ifc)*abs1*(nirm(mpg%fccv(ifc, 2))*&
&       result1*result2*t0+nirm(mpg%fccv(ifc, 1))*result3*result4*t1)/((&
&       ni(mpg%fccv(ifc, 1), 0)+ni_ext(mpg%fccv(ifc, 1), 0)+ni(mpg%fccv(&
&       ifc, 2), 0)+ni_ext(mpg%fccv(ifc, 2), 0))*max1)
    END DO
  END IF
  CALL SUBEND()
  RETURN

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHI_NODIFF

!  Differentiation of b2tlhi in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: chvimx
!   with respect to varying inputs: ti ni nirm chvimx
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHI_DV(ncv, nfc, mp, cflmi, switch, geo, mpg, ni, nid, &
& nirm, nirmd, ni_ext, ti, tid, tn, chvimx, chvimxd, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: mp, cflmi, ni(ncv, 0:1), nirm(ncv), ni_ext(ncv, 0:1)&
& , ti(ncv), tn(ncv), chvimx(nfc)
  REAL(kind=r8) :: nid(nbdirsmax, ncv, 0:1), nirmd(nbdirsmax, ncv), tid(&
& nbdirsmax, ncv), chvimxd(nbdirsmax, nfc)
!     ------------------------------------------------------------------
!     B2TLHI computes the all atom heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: icv, ifc
  REAL(kind=r8) :: t0, t1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: t0d, t1d
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVFX_NODIFF
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: max1d
  REAL(kind=r8) :: arg1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg1d
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8) :: result2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result2d
  REAL(kind=r8) :: result3
  REAL(kind=r8) :: arg2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg2d
  REAL(kind=r8) :: result4
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result4d
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8) :: temp0
  REAL(kind=r8) :: temp1
  INTEGER :: nbdirs
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlhi')
!   ..test mp, cflmi
  CALL XERTST(0.0_R8 .LT. mp, 'faulty argument mp')
  CALL XERTST(0.0_R8 .LE. cflmi, 'faulty argument cflmi')
!
!   ..compute flux limit velocity
  IF (switch%b2tqca_model .EQ. 1) THEN
! SOLPS5.0 treatments
    DO ifc=1,nfc
      IF (ti(mpg%fccv(ifc, 1)) .LT. ti(mpg%fccv(ifc, 2))) THEN
        DO nd=1,nbdirs
          t0d(nd) = tid(nd, mpg%fccv(ifc, 2))
        END DO
        t0 = ti(mpg%fccv(ifc, 2))
      ELSE
        DO nd=1,nbdirs
          t0d(nd) = tid(nd, mpg%fccv(ifc, 1))
        END DO
        t0 = ti(mpg%fccv(ifc, 1))
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        abs0 = geo%fcpbs(ifc)
      ELSE
        abs0 = -geo%fcpbs(ifc)
      END IF
      arg1 = t0/mp
      temp = SQRT(arg1)
      DO nd=1,nbdirs
!srv 11.01.13
        arg1d(nd) = t0d(nd)/mp
        IF (arg1 .EQ. 0.D0) THEN
          result1d(nd) = 0.D0
        ELSE
          result1d(nd) = arg1d(nd)/(2.0*temp)
        END IF
      END DO
      result1 = temp
      temp = ni_ext(mpg%fccv(ifc, 1), 0) + ni_ext(mpg%fccv(ifc, 2), 0) +&
&       ni(mpg%fccv(ifc, 1), 0) + ni(mpg%fccv(ifc, 2), 0)
      temp0 = nirm(mpg%fccv(ifc, 1)) + nirm(mpg%fccv(ifc, 2))
      temp1 = result1*temp0/temp
      DO nd=1,nbdirs
        chvimxd(nd, ifc) = cflmi*abs0*(temp0*result1d(nd)+result1*(nirmd&
&         (nd, mpg%fccv(ifc, 1))+nirmd(nd, mpg%fccv(ifc, 2)))-temp1*(nid&
&         (nd, mpg%fccv(ifc, 1), 0)+nid(nd, mpg%fccv(ifc, 2), 0)))/temp
      END DO
      chvimx(ifc) = cflmi*abs0*temp1
    END DO
  ELSE IF (switch%b2tqca_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      DO nd=1,nbdirs
        t0d(nd) = tid(nd, mpg%fccv(ifc, 2))
        t1d(nd) = tid(nd, mpg%fccv(ifc, 1))
      END DO
      t0 = ti(mpg%fccv(ifc, 2))
      t1 = ti(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        abs1 = geo%fcqalf(ifc, 0)
      ELSE
        abs1 = -geo%fcqalf(ifc, 0)
      END IF
      IF (t0 .LT. t1) THEN
        DO nd=1,nbdirs
          max1d(nd) = t1d(nd)
        END DO
        max1 = t1
      ELSE
        DO nd=1,nbdirs
          max1d(nd) = t0d(nd)
        END DO
        max1 = t0
      END IF
!wdk 10.03.16 Divide by ni*ti at cell faces, so chvimx contains the same information
!           as case b2tqca_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhi), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      result1 = PIT(mpg%fccv(ifc, 2))
      arg1 = t0/mp
      temp1 = SQRT(arg1)
      DO nd=1,nbdirs
        arg1d(nd) = t0d(nd)/mp
        IF (arg1 .EQ. 0.D0) THEN
          result2d(nd) = 0.D0
        ELSE
          result2d(nd) = arg1d(nd)/(2.0*temp1)
        END IF
        arg2d(nd) = t1d(nd)/mp
      END DO
      result2 = temp1
      result3 = PIT(mpg%fccv(ifc, 1))
      arg2 = t1/mp
      temp1 = SQRT(arg2)
      DO nd=1,nbdirs
        IF (arg2 .EQ. 0.D0) THEN
          result4d(nd) = 0.D0
        ELSE
          result4d(nd) = arg2d(nd)/(2.0*temp1)
        END IF
      END DO
      result4 = temp1
      temp1 = geo%fcs(ifc)*cflmi*abs1
      temp0 = ni_ext(mpg%fccv(ifc, 1), 0) + ni_ext(mpg%fccv(ifc, 2), 0) &
&       + ni(mpg%fccv(ifc, 1), 0) + ni(mpg%fccv(ifc, 2), 0)
      temp = (result1*nirm(mpg%fccv(ifc, 2))*result2*t0+result3*nirm(mpg&
&       %fccv(ifc, 1))*result4*t1)/(temp0*max1)
      DO nd=1,nbdirs
        chvimxd(nd, ifc) = temp1*(result1*(result2*t0*nirmd(nd, mpg%fccv&
&         (ifc, 2))+nirm(mpg%fccv(ifc, 2))*(t0*result2d(nd)+result2*t0d(&
&         nd)))+result3*(result4*t1*nirmd(nd, mpg%fccv(ifc, 1))+nirm(mpg&
&         %fccv(ifc, 1))*(t1*result4d(nd)+result4*t1d(nd)))-temp*(max1*(&
&         nid(nd, mpg%fccv(ifc, 1), 0)+nid(nd, mpg%fccv(ifc, 2), 0))+&
&         temp0*max1d(nd)))/(temp0*max1)
      END DO
      chvimx(ifc) = temp1*temp
    END DO
  END IF
  CALL SUBEND()
  RETURN

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHI_DV

