!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2usr_cost_function in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: *b2voloncf *b2data *b2dataoncf
!                j
!   with respect to varying inputs: *b2voloncf *b2data *b2dataoncf
!                sigma shift *par_opt_phys mean *(st.pl.na) *(st.pl.te)
!                *(st.pl.ti) *(st.dv.fht) *(st.dv.ne)
!   Plus diff mem management of: b2voloncf:in b2data:in b2dataoncf:in
!                par_opt_phys:in mpg.cffcor:in mpg.intcellr:in
!                geo.cvx:in geo.cvy:in geo.cvvol:in geo.fcs:in
!                geo.fchc:in geo.fcht:in geo.fcqgam:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in st_ext.am:in st_ext.na:in
!                st_ext.ta:in st.pl.na:in st.pl.te:in st.pl.ti:in
!                st.dv.fht:in st.dv.ne:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2USR_COST_FUNCTION_DV(ncv, nfc, nvx, ns, geo, geod, mpg, &
& mpgd, st, std, st_ext, st_extd, boris, j, jd, nbdirs)
  USE B2MOD_TYPES
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2US_GEO_DIFFV
  USE B2MOD_PAR_OPT_DIFFV
  USE B2MOD_CONSTANTS
  USE B2MOD_USER_NAMELIST_DIFFV, ONLY : omp, nomp, icsepomp
  USE B2MOD_B2CMPA_DIFFV, ONLY : am
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : vold, voldd, cfnorm, cfnormd, nncf, b2rr, &
& b2voloncf, b2voloncfd, b2data, b2datad, b2dataoncf, b2dataoncfd
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(B2STATE), INTENT(IN) :: st
  TYPE(B2STATE_DIFFV), INTENT(IN) :: std
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  TYPE(B2STATEEXT_DIFFV), INTENT(IN) :: st_extd
  REAL(kind=r8) :: boris, j(nncf)
  REAL(kind=r8) :: jd(nbdirsmax, nncf)
  INTEGER :: ncv, nfc, nvx, ns
  INTEGER :: icf, ic1, ic2, icv, n1, n2, ifc, is, iicf
  LOGICAL, SAVE :: first_call=.true.
  LOGICAL :: inrange
  REAL(kind=r8) :: qq, prior, lll, lll_cum, curr_shift
  REAL(kind=r8), DIMENSION(nbdirsmax) :: qqd, priord, llld, lll_cumd, &
& curr_shiftd
  REAL(kind=r8) :: gradr(ncv), funv(nvx), pz(ncv), rz(ncv), cs(ncv)
  REAL(kind=r8) :: gradrd(nbdirsmax, ncv), funvd(nbdirsmax, nvx), pzd(&
& nbdirsmax, ncv), rzd(nbdirsmax, ncv), csd(nbdirsmax, ncv)
  INTEGER :: isigma, imean
  EXTERNAL CALC_DIST_NODIFF
  INTRINSIC SUM
  INTRINSIC SQRT
  EXTERNAL XERRAB
  REAL(kind=r8) :: max1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: max1d
  INTEGER :: arg1
  REAL(kind=r8), DIMENSION(ncv) :: arg10
  REAL(kind=r8), DIMENSION(nbdirsmax, ncv) :: arg10d
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(r8) :: temp0
  REAL(kind=r8), DIMENSION(ncv) :: temp1
  INTEGER :: nbdirs
!
  CALL SUBINI('b2usr_cost_function')
!
  IF (first_call .AND. ncf .GT. 0) THEN
    CALL XERTST(ncf .EQ. mpg%ncf, 'ncf=/mpg%nCf')
    CALL XERTST(mpg%isclassicalgrid .EQ. 1, ' Cost function CVs and '//&
&         'FCs ordering  and interpolation in case of unstructured grid'&
&         //' needs to be revised')
    DO icf=1,ncf
      IF (cfread(icf)) THEN
! WARNING! For now we assume that the data read from the cost function is only radially dependent
        WRITE(*, *) 'WARNING, b2usr_cost_function assumes data '//&
&       'read for CF is only radially dependent'
        ic1 = mpg%cfregp(icf, 1)
        ic2 = ic1 + mpg%cfregp(icf, 2) - 1
        n1 = mpg%cfregp(icf, 2)
        n2 = ncfdata(icf)
!csc icsep-1 because non-internal cells have been excluded!
        arg1 = icsepomp - 1
        CALL CALC_DIST_NODIFF(mpg, geo, mpg%cfreg(ic1:ic2), n1, arg1, &
&                       b2rr(icf, 1:n1))
      END IF
      IF (maptoomp(icf)) THEN
! FIXME to be considerably improved!
!for now assume radial data rigidly moved at the OMP (like in ST code)
! simply use as b2rr the OMP radial coordinates.
        CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&             'Mapping to OMP need revision for extended grids')
! check on, and then use, only internal Cvs in OMP list
        CALL XERTST(n1 .EQ. nomp - 2, &
&             'number of Cv in CF does not equal Cvs in OMP')
        arg1 = icsepomp - 1
        CALL CALC_DIST_NODIFF(mpg, geo, omp(2:nomp-1), n1, arg1, b2rr(&
&                       icf, 1:n1))
      END IF
    END DO
    first_call = .false.
  END IF
! cf normalization depends on shift now, as some points may eventualy be left out of the B2 domain
  cfnorm = 0.0_R8
  vold = 0.0_R8
  DO nd=1,nbdirsmax
    cfnormd(nd, :) = 0.D0
  END DO
  DO nd=1,nbdirsmax
    voldd(nd, :) = 0.D0
  END DO
  DO icf=1,ncf
    IF (cfread(icf)) THEN
      ic1 = mpg%cfregp(icf, 1)
      ic2 = ic1 + mpg%cfregp(icf, 2) - 1
      n1 = mpg%cfregp(icf, 2)
      n2 = ncfdata(icf)
      curr_shift = 0.0_R8
!shift is in mm!
      IF (cf_to_shift(icf) .GT. 0) THEN
        DO nd=1,nbdirs
          curr_shiftd(nd) = shiftd(nd, cf_to_shift(icf))/1.0e3_R8
        END DO
        curr_shift = shift(cf_to_shift(icf))/1.0e3_R8
      ELSE
        DO nd=1,nbdirsmax
          curr_shiftd(nd) = 0.D0
        END DO
      END IF
      DO nd=1,nbdirs
        b2datad(nd, 1:n1) = 0.D0
      END DO
      b2data(1:n1) = geo%cvvol(mpg%cfreg(ic1:ic2))
      CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                b2data(1:n1), b2datad(:, 1:n1), b2voloncf(icf, 1:n2), &
&                b2voloncfd(:, icf, 1:n2), curr_shift, curr_shiftd, &
&                nbdirs)
      DO nd=1,nbdirs
        voldd(nd, icf) = SUM(b2voloncfd(nd, icf, 1:n2))
      END DO
      vold(icf) = SUM(b2voloncf(icf, 1:n2))
      DO icv=1,n2
        DO nd=1,nbdirs
          cfnormd(nd, icf) = cfnormd(nd, icf) + cfdata(icf, 2, icv)*&
&           b2voloncfd(nd, icf, icv)
        END DO
        cfnorm(icf) = cfnorm(icf) + b2voloncf(icf, icv)*cfdata(icf, 2, &
&         icv)
      END DO
    END IF
  END DO
!
  j = 0.0_R8
  IF (ncf .GT. 0) THEN
    DO nd=1,nbdirsmax
      jd(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      funvd(nd, :) = 0.D0
    END DO
    DO icf=1,ncf
      ic1 = mpg%cfregp(icf, 1)
      ic2 = ic1 + mpg%cfregp(icf, 2) - 1
      n1 = mpg%cfregp(icf, 2)
      n2 = ncfdata(icf)
      curr_shift = 0.0_R8
!shift is in mm!
      IF (cf_to_shift(icf) .GT. 0) THEN
        DO nd=1,nbdirs
          curr_shiftd(nd) = shiftd(nd, cf_to_shift(icf))/1.0e3_R8
        END DO
        curr_shift = shift(cf_to_shift(icf))/1.0e3_R8
      ELSE
        DO nd=1,nbdirsmax
          curr_shiftd(nd) = 0.D0
        END DO
      END IF
      SELECT CASE  (cftype(icf)) 
      CASE (0) 

      CASE (1) 
!sum of other cost function. It is skipped at this stage because it MUST be J(1) for optimization
!electron density on desired CVs
        DO nd=1,nbdirs
          b2datad(nd, 1:n1) = std%dv%ne(nd, mpg%cfreg(ic1:ic2))/&
&           1.0e19_R8
        END DO
        b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE (2) 
!electron temperature on desired CVs
        DO nd=1,nbdirs
          b2datad(nd, 1:n1) = std%pl%te(nd, mpg%cfreg(ic1:ic2))/ev
        END DO
        b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE (3) 
!ion temperature on desired CVs
        DO nd=1,nbdirs
          b2datad(nd, 1:n1) = std%pl%ti(nd, mpg%cfreg(ic1:ic2))/ev
        END DO
        b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE (4) 
!max electron temperature on desired CVs
        DO icv=ic1,ic2
          IF (j(icf) .LT. st%pl%te(mpg%cfreg(icv))) THEN
            DO nd=1,nbdirs
              jd(nd, icf) = std%pl%te(nd, mpg%cfreg(icv))
            END DO
            j(icf) = st%pl%te(mpg%cfreg(icv))
          ELSE
            j(icf) = j(icf)
          END IF
        END DO
        DO nd=1,nbdirs
          jd(nd, icf) = jd(nd, icf)/ev
        END DO
        j(icf) = j(icf)/ev
      CASE (5) 
!max heat flux density on desired FCs
        DO ifc=ic1,ic2
          DO nd=1,nbdirs
            qqd(nd) = mpg%cffcor(ifc)*std%dv%fht(nd, mpg%cfreg(ifc), 0)/&
&             geo%fcs(mpg%cfreg(ifc))
          END DO
          qq = st%dv%fht(mpg%cfreg(ifc), 0)*mpg%cffcor(ifc)/geo%fcs(mpg%&
&           cfreg(ifc))
          IF (j(icf) .LT. qq) THEN
            DO nd=1,nbdirs
              max1d(nd) = qqd(nd)
            END DO
            max1 = qq
          ELSE
            DO nd=1,nbdirs
              max1d(nd) = jd(nd, icf)
            END DO
            max1 = j(icf)
          END IF
          DO nd=1,nbdirs
            jd(nd, icf) = cfweight(icf)*max1d(nd)
          END DO
          j(icf) = max1*cfweight(icf)
        END DO
      CASE (6) 
!loglikelihood + log prior for Bayesian MAP estimate
        CALL CALC_LOG_PRIOR_DV(prior, priord, inrange, nbdirs)
        WRITE(*, *) 'MAP log prior value:', prior
        lll_cum = 0.0_R8
        isigma = 1
        imean = 1
        DO nd=1,nbdirsmax
          lll_cumd(nd) = 0.D0
        END DO
        DO iicf=cfstart(1),cfend(1)
          n1 = mpg%cfregp(iicf, 2)
          n2 = ncfdata(iicf)
          ic1 = mpg%cfregp(iicf, 1)
          ic2 = ic1 + n1 - 1
          curr_shift = 0.0_R8
!shift is in mm!
          IF (cf_to_shift(iicf) .GT. 0) THEN
            DO nd=1,nbdirs
              curr_shiftd(nd) = shiftd(nd, cf_to_shift(iicf))/1.0e3_R8
            END DO
            curr_shift = shift(cf_to_shift(iicf))/1.0e3_R8
          ELSE
            DO nd=1,nbdirsmax
              curr_shiftd(nd) = 0.D0
            END DO
          END IF
          SELECT CASE  (cftype(iicf)) 
          CASE (1) 
!electron density
            DO nd=1,nbdirs
              b2datad(nd, 1:n1) = std%dv%ne(nd, mpg%cfreg(ic1:ic2))/&
&               1.0e19_R8
            END DO
            b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
          CASE (2) 
!electron temperature
            DO nd=1,nbdirs
              b2datad(nd, 1:n1) = std%pl%te(nd, mpg%cfreg(ic1:ic2))/ev
            END DO
            b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
          CASE (3) 
!ion temperature
            DO nd=1,nbdirs
              b2datad(nd, 1:n1) = std%pl%ti(nd, mpg%cfreg(ic1:ic2))/ev
            END DO
            b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
          CASE (7) 
!electron density radial gradient
            CALL GRADC_R_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, st%&
&                     dv%ne, std%dv%ne, funv, funvd, gradr, gradrd, &
&                     nbdirs)
            DO nd=1,nbdirs
              b2datad(nd, 1:n1) = gradrd(nd, mpg%cfreg(ic1:ic2))/&
&               1.0e19_R8
            END DO
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
          CASE (8) 
!electron temperature radial gradient
            CALL GRADC_R_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, st%&
&                     pl%te, std%pl%te, funv, funvd, gradr, gradrd, &
&                     nbdirs)
            DO nd=1,nbdirs
              b2datad(nd, 1:n1) = gradrd(nd, mpg%cfreg(ic1:ic2))/ev
            END DO
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
          CASE (9) 
!ion temperature radial gradient
            CALL GRADC_R_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, st%&
&                     pl%ti, std%pl%ti, funv, funvd, gradr, gradrd, &
&                     nbdirs)
            DO nd=1,nbdirs
              b2datad(nd, 1:n1) = gradrd(nd, mpg%cfreg(ic1:ic2))/ev
            END DO
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
          CASE (10) 
!ion saturation current (kA/m**2)
            CALL B2XPRZ_DV(ncv, ns, mp, am, st%pl%na, std%pl%na, rz, rzd&
&                    , st_ext, nbdirs)
            CALL B2XPPZ_DV(ncv, ns, st%dv%ne, std%dv%ne, st%pl%na, std%&
&                    pl%na, st%pl%te, std%pl%te, st%pl%ti, std%pl%ti, pz&
&                    , pzd, st_ext, nbdirs)
            arg10(:) = pz/rz
            temp1 = SQRT(arg10(:))
            DO nd=1,nbdirs
              arg10d(nd, :) = (pzd(nd, :)-pz*rzd(nd, :)/rz)/rz
              WHERE (arg10(:) .EQ. 0.D0) 
                csd(nd, :) = 0.D0
              ELSEWHERE
                csd(nd, :) = arg10d(nd, :)/(2.0*temp1)
              END WHERE
            END DO
            cs = temp1
            DO icv=1,n1
              temp = cs(mpg%cfreg(ic1+icv-1))/1.0e3_R8
              temp0 = st%dv%ne(mpg%cfreg(ic1+icv-1))
              DO nd=1,nbdirs
                b2datad(nd, icv) = ev*(temp*std%dv%ne(nd, mpg%cfreg(ic1+&
&                 icv-1))+temp0*csd(nd, mpg%cfreg(ic1+icv-1))/1.0e3_R8)
              END DO
              b2data(icv) = ev*(temp0*temp)
            END DO
          CASE DEFAULT
            WRITE(*, *) cftype(iicf)
            CALL XERRAB('cftype for sum out of bounds for cftype=6')
          END SELECT
          CALL INTERP1D_DV(n1, n2, b2rr(iicf, 1:n1), cfdata(iicf, 1, 1:&
&                    n2), b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:&
&                    n2), b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd&
&                    , nbdirs)
          CALL CALC_LOGLIKELIHOOD_DV(n2, b2dataoncf(1:n2), b2dataoncfd(:&
&                              , 1:n2), cfdata(iicf, 2, 1:n2), cfdata(&
&                              iicf, 3, 1:n2), lll, llld, isigma, imean&
&                              , nbdirs)
          DO nd=1,nbdirs
            lll_cumd(nd) = lll_cumd(nd) + llld(nd)
          END DO
          lll_cum = lll_cum + lll
          isigma = isigma + 1
          imean = imean + 1
        END DO
        IF (inrange) THEN
          DO nd=1,nbdirs
            jd(nd, icf) = -(cfweight(icf)*(priord(nd)+lll_cumd(nd)))
          END DO
          j(icf) = -((prior+lll_cum)*cfweight(icf))
        ELSE
          DO nd=1,nbdirs
            jd(nd, icf) = 0.D0
          END DO
          j(icf) = inf_opt
        END IF
      CASE (7) 
!electron density radial gradient
        CALL GRADC_R_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, st%dv%ne&
&                 , std%dv%ne, funv, funvd, gradr, gradrd, nbdirs)
        DO nd=1,nbdirs
          b2datad(nd, 1:n1) = gradrd(nd, mpg%cfreg(ic1:ic2))/1.0e19_R8
        END DO
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE (8) 
!electron temperature radial gradient
        CALL GRADC_R_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, st%pl%te&
&                 , std%pl%te, funv, funvd, gradr, gradrd, nbdirs)
        DO nd=1,nbdirs
          b2datad(nd, 1:n1) = gradrd(nd, mpg%cfreg(ic1:ic2))/ev
        END DO
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE (9) 
!ion temperature radial gradient
        CALL GRADC_R_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, st%pl%ti&
&                 , std%pl%ti, funv, funvd, gradr, gradrd, nbdirs)
        DO nd=1,nbdirs
          b2datad(nd, 1:n1) = gradrd(nd, mpg%cfreg(ic1:ic2))/ev
        END DO
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE (10) 
!ion saturation current (kA/m**2)
        CALL B2XPRZ_DV(ncv, ns, mp, am, st%pl%na, std%pl%na, rz, rzd, &
&                st_ext, nbdirs)
        CALL B2XPPZ_DV(ncv, ns, st%dv%ne, std%dv%ne, st%pl%na, std%pl%na&
&                , st%pl%te, std%pl%te, st%pl%ti, std%pl%ti, pz, pzd, &
&                st_ext, nbdirs)
        arg10(:) = pz/rz
        temp1 = SQRT(arg10(:))
        DO nd=1,nbdirs
! Calculate saturation current as ne*cs*eV
          arg10d(nd, :) = (pzd(nd, :)-pz*rzd(nd, :)/rz)/rz
          WHERE (arg10(:) .EQ. 0.D0) 
            csd(nd, :) = 0.D0
          ELSEWHERE
            csd(nd, :) = arg10d(nd, :)/(2.0*temp1)
          END WHERE
        END DO
        cs = temp1
        DO icv=1,n1
          temp = cs(mpg%cfreg(ic1+icv-1))/1.0e3_R8
          temp0 = st%dv%ne(mpg%cfreg(ic1+icv-1))
          DO nd=1,nbdirs
            b2datad(nd, icv) = ev*(temp*std%dv%ne(nd, mpg%cfreg(ic1+icv-&
&             1))+temp0*csd(nd, mpg%cfreg(ic1+icv-1))/1.0e3_R8)
          END DO
          b2data(icv) = ev*(temp0*temp)
        END DO
        CALL INTERP1D_DV(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&                  b2data(1:n1), b2datad(:, 1:n1), b2dataoncf(1:n2), &
&                  b2dataoncfd(:, 1:n2), curr_shift, curr_shiftd, nbdirs&
&                 )
        DO icv=1,n2
          temp = (b2dataoncf(icv)-cfdata(icf, 2, icv))*(b2dataoncf(icv)-&
&           cfdata(icf, 2, icv))
          DO nd=1,nbdirs
            jd(nd, icf) = jd(nd, icf) + temp*b2voloncfd(nd, icf, icv) + &
&             b2voloncf(icf, icv)*2*(b2dataoncf(icv)-cfdata(icf, 2, icv)&
&             )*b2dataoncfd(nd, icv)
          END DO
          j(icf) = j(icf) + b2voloncf(icf, icv)*temp
        END DO
        temp0 = 2.0_R8*(cfnorm(icf)*cfnorm(icf))
        temp = j(icf)*vold(icf)/temp0
        DO nd=1,nbdirs
          jd(nd, icf) = cfweight(icf)*(vold(icf)*jd(nd, icf)+j(icf)*&
&           voldd(nd, icf)-temp*2.0_R8*2*cfnorm(icf)*cfnormd(nd, icf))/&
&           temp0
        END DO
        j(icf) = cfweight(icf)*temp
      CASE DEFAULT
        WRITE(*, *) cftype(icf)
        CALL XERRAB('cftype out of bounds')
      END SELECT
    END DO
! now sum of cost functions for cftype=0
    IF (cftype(1) .EQ. 0) THEN
      DO icf=cfstart(1),cfend(1)
        DO nd=1,nbdirs
          jd(nd, 1) = jd(nd, 1) + jd(nd, icf)
        END DO
        j(1) = j(1) + j(icf)
      END DO
    END IF
  ELSE
    DO nd=1,nbdirsmax
      jd(nd, :) = 0.D0
    END DO
  END IF
  CALL SUBEND()
  RETURN
END SUBROUTINE B2USR_COST_FUNCTION_DV
!

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2USR_COST_FUNCTION_NODIFF(ncv, nfc, nvx, ns, geo, mpg, st, &
& st_ext, boris, j)
  USE B2MOD_TYPES
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2US_GEO_DIFFV
  USE B2MOD_PAR_OPT_DIFFV
  USE B2MOD_CONSTANTS
  USE B2MOD_USER_NAMELIST_DIFFV, ONLY : omp, nomp, icsepomp
  USE B2MOD_B2CMPA_DIFFV, ONLY : am
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : vold, cfnorm, nncf, b2rr, b2voloncf, b2data&
& , b2dataoncf
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(B2STATE), INTENT(IN) :: st
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  REAL(kind=r8) :: boris, j(nncf)
  INTEGER :: ncv, nfc, nvx, ns
  INTEGER :: icf, ic1, ic2, icv, n1, n2, ifc, is, iicf
  LOGICAL, SAVE :: first_call=.true.
  LOGICAL :: inrange
  REAL(kind=r8) :: qq, prior, lll, lll_cum, curr_shift
  REAL(kind=r8) :: gradr(ncv), funv(nvx), pz(ncv), rz(ncv), cs(ncv)
  INTEGER :: isigma, imean
  EXTERNAL CALC_DIST_NODIFF
  INTRINSIC SUM
  INTRINSIC SQRT
  EXTERNAL XERRAB
  REAL(kind=r8) :: max1
  INTEGER :: arg1
  REAL(kind=r8), DIMENSION(ncv) :: arg10
!
  CALL SUBINI('b2usr_cost_function')
!
  IF (first_call .AND. ncf .GT. 0) THEN
    CALL XERTST(ncf .EQ. mpg%ncf, 'ncf=/mpg%nCf')
    CALL XERTST(mpg%isclassicalgrid .EQ. 1, ' Cost function CVs and '//&
&         'FCs ordering  and interpolation in case of unstructured grid'&
&         //' needs to be revised')
    DO icf=1,ncf
      IF (cfread(icf)) THEN
! WARNING! For now we assume that the data read from the cost function is only radially dependent
        WRITE(*, *) 'WARNING, b2usr_cost_function assumes data '//&
&       'read for CF is only radially dependent'
        ic1 = mpg%cfregp(icf, 1)
        ic2 = ic1 + mpg%cfregp(icf, 2) - 1
        n1 = mpg%cfregp(icf, 2)
        n2 = ncfdata(icf)
!csc icsep-1 because non-internal cells have been excluded!
        arg1 = icsepomp - 1
        CALL CALC_DIST_NODIFF(mpg, geo, mpg%cfreg(ic1:ic2), n1, arg1, &
&                       b2rr(icf, 1:n1))
      END IF
      IF (maptoomp(icf)) THEN
! FIXME to be considerably improved!
!for now assume radial data rigidly moved at the OMP (like in ST code)
! simply use as b2rr the OMP radial coordinates.
        CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&             'Mapping to OMP need revision for extended grids')
! check on, and then use, only internal Cvs in OMP list
        CALL XERTST(n1 .EQ. nomp - 2, &
&             'number of Cv in CF does not equal Cvs in OMP')
        arg1 = icsepomp - 1
        CALL CALC_DIST_NODIFF(mpg, geo, omp(2:nomp-1), n1, arg1, b2rr(&
&                       icf, 1:n1))
      END IF
    END DO
    first_call = .false.
  END IF
! cf normalization depends on shift now, as some points may eventualy be left out of the B2 domain
  cfnorm = 0.0_R8
  vold = 0.0_R8
  DO icf=1,ncf
    IF (cfread(icf)) THEN
      ic1 = mpg%cfregp(icf, 1)
      ic2 = ic1 + mpg%cfregp(icf, 2) - 1
      n1 = mpg%cfregp(icf, 2)
      n2 = ncfdata(icf)
      curr_shift = 0.0_R8
!shift is in mm!
      IF (cf_to_shift(icf) .GT. 0) curr_shift = shift(cf_to_shift(icf))/&
&         1.0e3_R8
      b2data(1:n1) = geo%cvvol(mpg%cfreg(ic1:ic2))
      CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&             b2data(1:n1), b2voloncf(icf, 1:n2), curr_shift)
      vold(icf) = SUM(b2voloncf(icf, 1:n2))
      DO icv=1,n2
        cfnorm(icf) = cfnorm(icf) + b2voloncf(icf, icv)*cfdata(icf, 2, &
&         icv)
      END DO
    END IF
  END DO
!
  j = 0.0_R8
  IF (ncf .GT. 0) THEN
    DO icf=1,ncf
      ic1 = mpg%cfregp(icf, 1)
      ic2 = ic1 + mpg%cfregp(icf, 2) - 1
      n1 = mpg%cfregp(icf, 2)
      n2 = ncfdata(icf)
      curr_shift = 0.0_R8
!shift is in mm!
      IF (cf_to_shift(icf) .GT. 0) curr_shift = shift(cf_to_shift(icf))/&
&         1.0e3_R8
      SELECT CASE  (cftype(icf)) 
      CASE (0) 

      CASE (1) 
!sum of other cost function. It is skipped at this stage because it MUST be J(1) for optimization
!electron density on desired CVs
        b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (2) 
!electron temperature on desired CVs
        b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (3) 
!ion temperature on desired CVs
        b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (4) 
!max electron temperature on desired CVs
        DO icv=ic1,ic2
          IF (j(icf) .LT. st%pl%te(mpg%cfreg(icv))) THEN
            j(icf) = st%pl%te(mpg%cfreg(icv))
          ELSE
            j(icf) = j(icf)
          END IF
        END DO
        j(icf) = j(icf)/ev
      CASE (5) 
!max heat flux density on desired FCs
        DO ifc=ic1,ic2
          qq = st%dv%fht(mpg%cfreg(ifc), 0)*mpg%cffcor(ifc)/geo%fcs(mpg%&
&           cfreg(ifc))
          IF (j(icf) .LT. qq) THEN
            max1 = qq
          ELSE
            max1 = j(icf)
          END IF
          j(icf) = max1*cfweight(icf)
        END DO
      CASE (6) 
!loglikelihood + log prior for Bayesian MAP estimate
        CALL CALC_LOG_PRIOR_NODIFF(prior, inrange)
        WRITE(*, *) 'MAP log prior value:', prior
        lll_cum = 0.0_R8
        isigma = 1
        imean = 1
        DO iicf=cfstart(1),cfend(1)
          n1 = mpg%cfregp(iicf, 2)
          n2 = ncfdata(iicf)
          ic1 = mpg%cfregp(iicf, 1)
          ic2 = ic1 + n1 - 1
          curr_shift = 0.0_R8
!shift is in mm!
          IF (cf_to_shift(iicf) .GT. 0) curr_shift = shift(cf_to_shift(&
&             iicf))/1.0e3_R8
          SELECT CASE  (cftype(iicf)) 
          CASE (1) 
!electron density
            b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
          CASE (2) 
!electron temperature
            b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
          CASE (3) 
!ion temperature
            b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
          CASE (7) 
!electron density radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%dv%ne, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
          CASE (8) 
!electron temperature radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%te, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
          CASE (9) 
!ion temperature radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%ti, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
          CASE (10) 
!ion saturation current (kA/m**2)
            CALL B2XPRZ_NODIFF(ncv, ns, mp, am, st%pl%na, rz, st_ext)
            CALL B2XPPZ_NODIFF(ncv, ns, st%dv%ne, st%pl%na, st%pl%te, st&
&                        %pl%ti, pz, st_ext)
            arg10(:) = pz/rz
            cs = SQRT(arg10(:))
            DO icv=1,n1
              b2data(icv) = st%dv%ne(mpg%cfreg(ic1+icv-1))*cs(mpg%cfreg(&
&               ic1+icv-1))*ev/1.0e3_R8
            END DO
          CASE DEFAULT
            WRITE(*, *) cftype(iicf)
            CALL XERRAB('cftype for sum out of bounds for cftype=6')
          END SELECT
          CALL INTERP1D(n1, n2, b2rr(iicf, 1:n1), cfdata(iicf, 1, 1:n2)&
&                 , b2data(1:n1), b2dataoncf(1:n2), curr_shift)
          CALL CALC_LOGLIKELIHOOD_NODIFF(n2, b2dataoncf(1:n2), cfdata(&
&                                  iicf, 2, 1:n2), cfdata(iicf, 3, 1:n2)&
&                                  , lll, isigma, imean)
          lll_cum = lll_cum + lll
          isigma = isigma + 1
          imean = imean + 1
        END DO
        IF (inrange) THEN
          j(icf) = -((prior+lll_cum)*cfweight(icf))
        ELSE
          j(icf) = inf_opt
        END IF
      CASE (7) 
!electron density radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%dv%ne, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (8) 
!electron temperature radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%te, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (9) 
!ion temperature radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%ti, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (10) 
!ion saturation current (kA/m**2)
        CALL B2XPRZ_NODIFF(ncv, ns, mp, am, st%pl%na, rz, st_ext)
        CALL B2XPPZ_NODIFF(ncv, ns, st%dv%ne, st%pl%na, st%pl%te, st%pl%&
&                    ti, pz, st_ext)
! Calculate saturation current as ne*cs*eV
        arg10(:) = pz/rz
        cs = SQRT(arg10(:))
        DO icv=1,n1
          b2data(icv) = st%dv%ne(mpg%cfreg(ic1+icv-1))*cs(mpg%cfreg(ic1+&
&           icv-1))*ev/1.0e3_R8
        END DO
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2), curr_shift)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE DEFAULT
        WRITE(*, *) cftype(icf)
        CALL XERRAB('cftype out of bounds')
      END SELECT
    END DO
! now sum of cost functions for cftype=0
    IF (cftype(1) .EQ. 0) THEN
      DO icf=cfstart(1),cfend(1)
        j(1) = j(1) + j(icf)
      END DO
    END IF
  END IF
  CALL SUBEND()
  RETURN
END SUBROUTINE B2USR_COST_FUNCTION_NODIFF
!

