!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of calc_loglikelihood in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: lll
!   with respect to varying inputs: sigma ff
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE CALC_LOGLIKELIHOOD_DV(nn, ff, ffd, yy, ss, lll, llld, isigma&
& , nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_PAR_OPT_DIFFV, ONLY : sigma, sigmad, scale_sigma
  USE B2MOD_CONSTANTS
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: nn, isigma
!SOLPS results
  REAL(kind=r8), INTENT(IN) :: ff(nn)
  REAL(kind=r8), INTENT(IN) :: ffd(nbdirsmax, nn)
!Data
  REAL(kind=r8), INTENT(IN) :: yy(nn)
!Standard deviation
  REAL(kind=r8), INTENT(IN) :: ss(nn)
!loglikelihood
  REAL(kind=r8), INTENT(INOUT) :: lll
  REAL(kind=r8), DIMENSION(nbdirsmax), INTENT(INOUT) :: llld
  INTEGER :: ii
  REAL(kind=r8) :: zz(nn), rr(nn), invc_z(nn)
  REAL(kind=r8) :: zzd(nbdirsmax, nn), rrd(nbdirsmax, nn), invc_zd(&
& nbdirsmax, nn)
  INTRINSIC SQRT, LOG
  INTRINSIC SUM
  REAL(r8) :: arg1
  REAL(r8), DIMENSION(nn) :: arg2
  REAL(r8), DIMENSION(nbdirsmax, nn) :: arg2d
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8), DIMENSION(nn) :: temp0
  INTEGER :: nbdirs
! sc  Routine based on R. De Wolf et al 2021 Nucl. Fusion 61 046048
  CALL SUBINI('calc_loglikelihood')
! sc  TO BE DONE: proper covariance matrix should be built here
!     for the moment no correlation => only diagonal elements
  IF (scale_sigma(isigma)) THEN
! diagonal elements
    DO nd=1,nbdirs
      rrd(nd, :) = 2*(ss+yy*sigma(isigma))*yy*sigmad(nd, isigma)
    END DO
    rr = (yy*sigma(isigma)+ss)**2
  ELSE
    DO nd=1,nbdirs
      rrd(nd, :) = 2*(ss+sigma(isigma))*sigmad(nd, isigma)
    END DO
    rr = (sigma(isigma)+ss)**2
  END IF
! FIXME in principle also -mu
  DO nd=1,nbdirs
    zzd(nd, :) = ffd(nd, :)
  END DO
  zz = ff - yy
  DO nd=1,nbdirsmax
    invc_zd(nd, :) = 0.D0
  END DO
!     solution of quadratic problem for DIAGONAL matrix
! FIXME in principle invC_z = Cov\zz = SIGMA^-1*zz
  DO ii=1,nn
    temp = zz(ii)*zz(ii)/rr(ii)
    DO nd=1,nbdirs
      invc_zd(nd, ii) = (2*zz(ii)*zzd(nd, ii)-temp*rrd(nd, ii))/rr(ii)
    END DO
    invc_z(ii) = temp
  END DO
!     rest = Z'*invCov_z
!     Calculate log-likelihood
! FIXME, should go away when real cholezky factorization is there
  temp0 = SQRT(rr)
  DO nd=1,nbdirs
    WHERE (rr .EQ. 0.D0) 
      rrd(nd, :) = 0.D0
    ELSEWHERE
      rrd(nd, :) = rrd(nd, :)/(2.0*temp0)
    END WHERE
  END DO
  rr = temp0
  arg1 = 2.0_R8*pi
  DO nd=1,nbdirs
    arg2d(nd, :) = 2.0_R8*rrd(nd, :)/rr
    llld(nd) = -(0.5_R8*(SUM(arg2d(nd, :))+SUM(invc_zd(nd, :))))
  END DO
  arg2(:) = 2.0_R8*LOG(rr)
  lll = -(0.5_R8*(nn*LOG(arg1)+SUM(arg2(:))+SUM(invc_z)))
  CALL SUBEND()
  RETURN
END SUBROUTINE CALC_LOGLIKELIHOOD_DV

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE CALC_LOGLIKELIHOOD_NODIFF(nn, ff, yy, ss, lll, isigma)
  USE B2MOD_TYPES
  USE B2MOD_PAR_OPT_DIFFV, ONLY : sigma, scale_sigma
  USE B2MOD_CONSTANTS
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: nn, isigma
!SOLPS results
  REAL(kind=r8), INTENT(IN) :: ff(nn)
!Data
  REAL(kind=r8), INTENT(IN) :: yy(nn)
!Standard deviation
  REAL(kind=r8), INTENT(IN) :: ss(nn)
!loglikelihood
  REAL(kind=r8), INTENT(INOUT) :: lll
  INTEGER :: ii
  REAL(kind=r8) :: zz(nn), rr(nn), invc_z(nn)
  INTRINSIC SQRT, LOG
  INTRINSIC SUM
  REAL(r8) :: arg1
  REAL(r8), DIMENSION(nn) :: arg2
! sc  Routine based on R. De Wolf et al 2021 Nucl. Fusion 61 046048
  CALL SUBINI('calc_loglikelihood')
! sc  TO BE DONE: proper covariance matrix should be built here
!     for the moment no correlation => only diagonal elements
  IF (scale_sigma(isigma)) THEN
! diagonal elements
    rr = (yy*sigma(isigma)+ss)**2
  ELSE
    rr = (sigma(isigma)+ss)**2
  END IF
! FIXME in principle also -mu
  zz = ff - yy
!     solution of quadratic problem for DIAGONAL matrix
! FIXME in principle invC_z = Cov\zz = SIGMA^-1*zz
  DO ii=1,nn
    invc_z(ii) = zz(ii)**2/rr(ii)
  END DO
!     rest = Z'*invCov_z
!     Calculate log-likelihood
! FIXME, should go away when real cholezky factorization is there
  rr = SQRT(rr)
  arg1 = 2.0_R8*pi
  arg2(:) = 2.0_R8*LOG(rr)
  lll = -(0.5_R8*(nn*LOG(arg1)+SUM(arg2(:))+SUM(invc_z)))
  CALL SUBEND()
  RETURN
END SUBROUTINE CALC_LOGLIKELIHOOD_NODIFF

