!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
!
FUNCTION CHORD_VALUE_NODIFF(nx, ny, tt, xp, yp, zp, dxp, dyp, dzp, &
& vector) RESULT (chord_value)
!
  USE B2MOD_TYPES
  USE B2MOD_GEO_DIFFV
  USE B2MOD_CONSTANTS
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  REAL(kind=r8) :: chord_value
  INTEGER :: nx, ny
  REAL(kind=r8) :: tt(-1:nx, -1:ny)
  REAL(kind=r8) :: xp, yp, zp, dxp, dyp, dzp
  LOGICAL :: vector
!
  REAL(kind=r8) :: x, y, z, dl, dx, dy, dz, dbr, dbz, dbphi, dbx, dby, &
& dbs, dotprod, phi, rt, zt
  INTEGER :: ix, iy
  LOGICAL :: found
!
  REAL(kind=r8) :: rshift, zshift, r0, z0, a0, b0, tt0
  COMMON /chord_shift/ rshift, zshift, r0, z0, a0, b0, tt0
  INTRINSIC SQRT, SIN, COS, ABS, ATAN2
  EXTERNAL CHORD_FIND, XERTST
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: arg1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
!
  CALL SUBINI('chord_value')
  x = xp
  y = yp
  z = zp
  dx = dxp
  dy = dyp
  dz = dzp
!
  chord_value = 0.0_R8
!
  CALL CHORD_FIND(nx, ny, crx, cry, x, y, z, found, ix, iy)
!
  IF (.NOT.found) THEN
    IF (.NOT.vector .AND. a0 .GT. 0.0_R8 .AND. b0 .GT. 0.0_R8) THEN
      zt = z + zshift
      arg1 = x**2 + y**2
      result1 = SQRT(arg1)
      rt = result1 + rshift
      IF (((rt-r0)/a0)**2 + ((zt-z0)/b0)**2 .LE. 1.0_R8) chord_value = &
&         tt0
    END IF
    CALL SUBEND()
    RETURN
  ELSE
!
    IF (vector) THEN
! in r,z,phi
      dbr = (crx(ix, iy, 1)+crx(ix, iy, 3)-(crx(ix, iy, 2)+crx(ix, iy, 0&
&       )))/2.0_R8
      dbz = (cry(ix, iy, 1)+cry(ix, iy, 3)-(cry(ix, iy, 2)+cry(ix, iy, 0&
&       )))/2.0_R8
      arg1 = dbr**2 + dbz**2
      dbs = SQRT(arg1)
      result1 = PIT(ix, iy)
      dbr = dbr/dbs*result1
      result1 = PIT(ix, iy)
      dbz = dbz/dbs*result1
      result1 = PIT(ix, iy)
      arg1 = 1.0 - result1**2
      result2 = SQRT(arg1)
      dbphi = 1.0*result2
! in x,y,z
      phi = ATAN2(y, x)
      dbz = dbz
      arg1 = phi + pi/2.0_R8
      dbx = dbr*COS(phi) + dbphi*COS(arg1)
      arg1 = phi + pi/2.0_R8
      dby = dbr*SIN(phi) + dbphi*SIN(arg1)
! assert
      dotprod = dbx*dbx + dby*dby + dbz*dbz
      IF (dotprod - 1.0 .GE. 0.) THEN
        abs0 = dotprod - 1.0
      ELSE
        abs0 = -(dotprod-1.0)
      END IF
      IF (abs0 .GT. 1e-10_R8) WRITE(*, *) &
&                             'Assertion failed, norm of unit vector = '&
&                             , dotprod
! end-assertion
      arg1 = dx**2 + dy**2 + dz**2
      dl = SQRT(arg1)
      CALL XERTST(dl .NE. 0., 'dl in chord.F == 0')
      dx = dx/dl
      dy = dy/dl
      dz = dz/dl
      dotprod = dbx*dx + dby*dy + dbz*dz
!       write(*,*) 'ix,iy = ',ix,iy
!       write(*,*) 'dl = ',dx,dy,dz
!       write(*,*) 'bl = ',dbr,dbz,dbphi
!       write(*,*) 'phi = ',phi
!       write(*,*) 'bl = ',dbx,dby,dbz
!       write(*,*) 'dl.bl = ',dotprod
      chord_value = tt(ix, iy)*dotprod
    ELSE
      chord_value = tt(ix, iy)
    END IF
    CALL SUBEND()
    RETURN
  END IF
END FUNCTION CHORD_VALUE_NODIFF

