!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE COPY_BACKGROUND_NODIFF(ncv, nfc, ns, switch, mpg, gm, pl, dv&
& , kin_frac_hyb, fnn_inc)
  USE B2MOD_TYPES
  USE B2MOD_PLASMA_DIFFV
  USE B2MOD_INDIRECT
  USE B2MOD_SWITCHES_DIFFV
  USE B2MOD_GEO_DIFFV
  USE B2MOD_CONSTANTS
  USE B2MOD_EIRENE_GLOBALS
  USE B2MOD_B2CMPA_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_DIAG_DIFFV, ONLY : fluids_list
  USE B2MOD_SUBSYS
  USE B2MOD_BRAEIR_DIFFV
  USE B2MOD_NEUTRALS_NAMELIST_DIFFV, ONLY : crcstra, rcfe, rcfi, mol
  USE B2MOD_RECYCLE_DIFFV, ONLY : fna_mol
!  Hint: nCv should be the size of dimension 1 of array arg1
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!  version : 28.12.96 21:39
!
!  Common dimensions
!
!  version : 01.12.98 21:42
!
!
!
! parameters that are common to Eirene and B2
!
!
! NOTE: DEF_NXD should not include the additional cells to handle the cuts
!*** Max. number of groups of Eirene surfaces for which the data can
!*** be transferred from B2 (DG specification "Surface special")
!
! new! [2002.04.22]
! new! [2002.06.14]
!
!
! parameters that are unique to B2
!
!
!
!
! parameters that are unique to Eirene
!
!
!
!
! parameters needed by uinp
!
!
!
!
!     COUPLING-DEFINITION COMMON (KOPPLDIM)
!
!
!  -- PRINCIPAL DIMENSIONS -- SHOULD MATCH EIRENE DECLARATIONS!!!
  INTEGER :: nxdd, nydd, nstra, nfl
  PARAMETER (nxdd=200+4*5, nydd=100, nstra=(5*4/2+2)*6+1, nfl=42)
  INTEGER :: natm, nmol, nion, npls, nspz
  PARAMETER (natm=6, nmol=3, nion=3, npls=42-6+(6+3)*(6+3), nspz=6+3+3+(&
&   42-6)+(6+3)*(6+3))
  INTEGER :: nlim, nsts, nsrfs, nsgmx
  PARAMETER (nlim=300, nsts=50, nsrfs=4)
  PARAMETER (nsgmx=300+max(2, 4)*100)
!
  INTEGER :: n1st, n2nd, n3rd
  PARAMETER (n1st=100+1, n2nd=200+1+4+(4/2-1)*(1+0), n3rd=1)
  INTEGER :: n1f, n2f, n3f
  PARAMETER (n1f=1-1/n1st, n2f=1-1/n2nd, n3f=1-1/n3rd)
  INTEGER :: ngitt, ngittp
  PARAMETER (ngitt=n1st*n2nd*n3f+n1st*n3rd*n2f+n2nd*n3rd*n1f, ngittp=&
&   ngitt+1)
  INTEGER :: ndx, ndy
  PARAMETER (ndx=nxdd, ndy=nydd)
  INTEGER :: ndxp, ndyp, nlimps
  PARAMETER (ndxp=nxdd+1, ndyp=nydd+1, nlimps=nlim+nsts)
  INTEGER :: ngtsft, nlmpgs
  PARAMETER (ngtsft=1*ngitt)
  PARAMETER (nlmpgs=nlim+(ngtsft+1)*nsts)
!
  INTEGER :: ncv, nfc, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(GEOMETRY), INTENT(IN) :: gm
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2DERIVATIVES), INTENT(IN) :: dv
!
!srv 16.09.02
  CHARACTER :: chns*3
  CHARACTER(len=2) :: ccall
!srv 21.06.08
  INTEGER, SAVE :: icall=0
  INTEGER :: is, ncall
  EXTERNAL IPGETR, IPGETI, XERRAB
  REAL(kind=r8) :: te_min_val, te_max_val, ti_min_val, ti_max_val, &
& na_min_val, na_max_val, ua_min_val, ua_max_val, ne_min_val, ne_max_val
  REAL(kind=r8) :: kintmp(nfc, 0:ns-1)
  REAL(kind=r8) :: vaecrbc(ncv, 0:1, 0:ns-1), wadiac(ncv, 0:1, 0:ns-1), &
& vadiac(ncv, 0:1, 0:ns-1)
  REAL(kind=r8) :: naf(nfc, 0:ns-1), fna_tmp(nfc, 0:ns-1), uuc(ncv, 0:ns&
& -1), vvc(ncv, 0:ns-1), nafsqalf(nfc, 0:1, 0:ns-1)
  INTEGER :: ic, ifc, ian, ien, ntrgdat, ifl, i, istra, ic2, iv1, iv2, &
& icp
  REAL(kind=r8) :: evi, ebx, eby, ebn, uu, vv, ww, pvxs, pvys, puxs, &
& puys
  REAL(kind=r8) :: wght(nfc, 2)
  REAL(kind=r8), INTENT(IN) :: kin_frac_hyb(mpg%nfc), fnn_inc(mpg%nfc, 0&
& :ns-1)
  REAL(kind=r8) :: fnn_inc_b(nfc, ns), fnn_mol_b(nfc, ns)
  INTRINSIC MINVAL
  INTRINSIC MAXVAL
  INTRINSIC MIN
  INTRINSIC MAX
  INTRINSIC SQRT
  INTRINSIC SIGN
  INTRINSIC COUNT
  INTRINSIC ALLOCATED
  REAL(r8) :: x1
  REAL(r8) :: x2
  REAL(r8) :: x3
  REAL(r8) :: x4
  REAL(r8) :: x5
  REAL(r8) :: x6
  REAL(r8) :: x7
  REAL(kind=r8) :: x8
  REAL(kind=r8) :: x9
  REAL(kind=r8) :: x10
  REAL(kind=r8) :: x11
  REAL(kind=r8) :: x12
  REAL(kind=r8) :: x13
  REAL(kind=r8) :: x14
  REAL(kind=r8) :: x15
  REAL(kind=r8) :: x16
  REAL(kind=r8) :: x17
  REAL(r8) :: max1
  REAL(r8), DIMENSION(nCv) :: arg1
  REAL(r8) :: result1
  REAL(r8), DIMENSION(nCv) :: arg10
  REAL(r8), DIMENSION(nCv) :: arg11
  REAL(r8), DIMENSION(nCv) :: arg12
  CHARACTER(len=11) :: arg13
  CHARACTER(len=10) :: arg14
  CHARACTER(len=15) :: arg15
  CHARACTER(len=14) :: arg16
  CHARACTER(len=13) :: arg17
  CHARACTER(len=12) :: arg18
  CHARACTER(len=7) :: arg19
  INTEGER :: arg110
  REAL(kind=r8) :: arg111
  CHARACTER(len=8) :: arg112
  REAL(kind=r8) :: result10
  DATA ncall /0/
!
  CALL SUBINI('copy_background')
!
! Initialization
  fnn_inc_b = 0.0_R8
  fnn_mol_b = 0.0_R8
!
  evi = 1.0_R8/ev
  IF (switch%eirene_print_minmax .NE. 0) THEN
    arg1(:) = pl%te(:)
    result1 = MINVAL(arg1(:))
    te_min_val = result1*evi
    arg10(:) = pl%te(:)
    result1 = MAXVAL(arg10(:))
    te_max_val = result1*evi
    arg11(:) = pl%ti(:)
    result1 = MINVAL(arg11(:))
    ti_min_val = result1*evi
    arg12(:) = pl%ti(:)
    result1 = MAXVAL(arg12(:))
    ti_max_val = result1*evi
    na_min_val = MINVAL(pl%na(:, 0:ns-1))
    na_max_val = MAXVAL(pl%na(:, 0:ns-1))
    ne_min_val = MINVAL(dv%ne(:))
    ne_max_val = MAXVAL(dv%ne(:))
    ua_min_val = MINVAL(pl%ua(:, 0:ns-1))
    ua_max_val = MAXVAL(pl%ua(:, 0:ns-1))
    WRITE(*, '(a,1p,10(1x,g12.3))') 'minmax: te, ti, na, ua, ne', &
&   te_min_val, te_max_val, ti_min_val, ti_max_val, na_min_val, &
&   na_max_val, ua_min_val, ua_max_val, ne_min_val, ne_max_val
  END IF
!
! get drift velocities in cell centers
  DO is=0,ns-1
    CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellp, dv%vaecrb(:, 0, is)&
&                 , vaecrbc(:, 0, is))
    CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellp, dv%wadia(:, 0, is)&
&                 , wadiac(:, 0, is))
    CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellp, dv%vadia(:, 0, is)&
&                 , vadiac(:, 0, is))
    CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellr, dv%vaecrb(:, 1, is)&
&                 , vaecrbc(:, 1, is))
    CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellr, dv%wadia(:, 1, is)&
&                 , wadiac(:, 1, is))
    CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellr, dv%vadia(:, 1, is)&
&                 , vadiac(:, 1, is))
  END DO
!
  IF (switch%copy_background_iout .NE. 0) THEN
!srv 18.06.08 {
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      WRITE(ccall, '(a1,i1)') '_', icall
      arg13(:) = 'copy_fna_th'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%fna(1, 0, is), arg13(:))
      arg14(:) = 'copy_fna_r'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%fna(1, 1, is), arg14(:))
      arg15(:) = 'copy_fna_eir_th'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%fna_eir(1, 0, is), arg15(:))
      arg16(:) = 'copy_fna_eir_r'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%fna_eir(1, 1, is), arg16(:))
      arg17(:) = 'copy_vecrb_th'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%vaecrb(1, 0, is), arg17(:))
      arg18(:) = 'copy_vecrb_r'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%vaecrb(1, 1, is), arg18(:))
      arg17(:) = 'copy_wadia_th'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%wadia(1, 0, is), arg17(:))
      arg18(:) = 'copy_wadia_r'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%wadia(1, 1, is), arg18(:))
      arg17(:) = 'copy_vadia_th'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%vadia(1, 0, is), arg17(:))
      arg18(:) = 'copy_vadia_r'//chns
      CALL MY_OUT_US(70, nfc, 1, dv%vadia(1, 1, is), arg18(:))
      arg16(:) = 'copy_vecrbc_th'//chns
      CALL MY_OUT_US(70, ncv, 0, vaecrbc(1, 0, is), arg16(:))
      arg17(:) = 'copy_vecrbc_r'//chns
      CALL MY_OUT_US(70, ncv, 0, vaecrbc(1, 1, is), arg17(:))
      arg16(:) = 'copy_wadiac_th'//chns
      CALL MY_OUT_US(70, ncv, 0, wadiac(1, 0, is), arg16(:))
      arg17(:) = 'copy_wadiac_r'//chns
      CALL MY_OUT_US(70, ncv, 0, wadiac(1, 1, is), arg17(:))
      arg16(:) = 'copy_vadiac_th'//chns
      CALL MY_OUT_US(70, ncv, 0, vadiac(1, 0, is), arg16(:))
      arg17(:) = 'copy_vadiac_r'//chns
      CALL MY_OUT_US(70, ncv, 0, vadiac(1, 1, is), arg17(:))
      arg19(:) = 'copy_ua'//chns//ccall
      CALL MY_OUT_US(70, ncv, 0, pl%ua(1, is), arg19(:))
      arg19(:) = 'copy_na'//chns
      CALL MY_OUT_US(70, ncv, 0, pl%na(1, is), arg19(:))
    END DO
    CALL MY_OUT_US(70, nfc, 1, dv%fne_eir(1, 0), &
&                   'copy_fne_eir_th')
    CALL MY_OUT_US(70, nfc, 1, dv%fne_eir(1, 1), 'copy_fne_eir_r'&
&                  )
    CALL MY_OUT_US(70, nfc, 1, dv%fhe_eir(1, 0), &
&                   'copy_fhe_eir_th')
    CALL MY_OUT_US(70, nfc, 1, dv%fhe_eir(1, 1), 'copy_fhe_eir_r'&
&                  )
    CALL MY_OUT_US(70, nfc, 1, dv%fhi_eir(1, 0), &
&                   'copy_fhi_eir_th')
    CALL MY_OUT_US(70, nfc, 1, dv%fhi_eir(1, 1), 'copy_fhi_eir_r'&
&                  )
    CALL MY_OUT_US(70, ncv, 0, dv%ne, 'copy_ne')
    CALL MY_OUT_US(70, ncv, 0, pl%te, 'copy_te')
    CALL MY_OUT_US(70, ncv, 0, pl%ti, 'copy_ti')
    CALL MY_OUT_US(70, ncv, 0, pl%po, 'copy_po')
    CALL MY_OUT_US(70, ncv, 0, gm%cvbb(1, 0), 'copy_bb_0')
    CALL MY_OUT_US(70, ncv, 0, gm%cvbb(1, 1), 'copy_bb_1')
    CALL MY_OUT_US(70, ncv, 0, gm%cvbb(1, 2), 'copy_bb_2')
    CALL MY_OUT_US(70, ncv, 0, gm%cvbb(1, 3), 'copy_bb_3')
  END IF
!
! cell centred
  DO ic=1,ncv
    IF (dv%ne(ic) .GT. switch%eir_ne_max) THEN
      x1 = switch%eir_ne_max
    ELSE
      x1 = dv%ne(ic)
    END IF
    IF (x1 .LT. switch%eir_ne_min) THEN
      neb(ic) = switch%eir_ne_min
    ELSE
      neb(ic) = x1
    END IF
    IF (pl%te(ic)*evi .GT. switch%eir_te_max) THEN
      x2 = switch%eir_te_max
    ELSE
      x2 = pl%te(ic)*evi
    END IF
    IF (x2 .LT. switch%eir_te_min) THEN
      teb(ic) = switch%eir_te_min
    ELSE
      teb(ic) = x2
    END IF
    IF (pl%ti(ic)*evi .GT. switch%eir_ti_max) THEN
      x3 = switch%eir_ti_max
    ELSE
      x3 = pl%ti(ic)*evi
    END IF
    IF (x3 .LT. switch%eir_ti_min) THEN
      tib(ic) = switch%eir_ti_min
    ELSE
      tib(ic) = x3
    END IF
    IF (pl%tn(ic)*evi .GT. switch%eir_ti_max) THEN
      x4 = switch%eir_ti_max
    ELSE
      x4 = pl%tn(ic)*evi
    END IF
    IF (x4 .LT. switch%eir_ti_min) THEN
      tnb(ic) = switch%eir_ti_min
    ELSE
      tnb(ic) = x4
    END IF
    pob(ic) = pl%po(ic)
    IF (dv%ne(ic) .GT. switch%eir_na_max) THEN
      x5 = switch%eir_na_max
    ELSE
      x5 = dv%ne(ic)
    END IF
    IF (x5 .LT. switch%eir_na_min) THEN
      max1 = switch%eir_na_min
    ELSE
      max1 = x5
    END IF
    prb(ic) = teb(ic)*max1
    rrb(ic) = gm%cvbb(ic, 0)/gm%cvbb(ic, 3)
    volb(ic) = gm%cvvol(ic)
    bbxb(ic) = gm%cvbb(ic, 3)*gm%cveb(ic, 0)
    bbyb(ic) = gm%cvbb(ic, 3)*gm%cveb(ic, 1)
    bbzb(ic) = gm%cvbb(ic, 3)*gm%cveb(ic, 2)
    bfeldb(ic) = gm%cvbb(ic, 3)
  END DO
!
! faces
!      call intface(nCv,nFc,mpg%fcCv,gm%fcVol,dv%kinrgy,kintmp)
  arg110 = ns - 1
  CALL INTFACE1(ncv, nfc, arg110, mpg%fccv, gm%fchc, dv%kinrgy, kintmp)
  DO ifc=1,nfc
    feib(ifc) = dv%fhi(ifc, 0) + dv%fhi(ifc, 1)
    feeb(ifc) = dv%fhe(ifc, 0) + dv%fhe(ifc, 1)
    DO is=0,ns-1
      feib(ifc) = feib(ifc) + kintmp(ifc, is)*(1.0_R8-switch%boris)*(dv%&
&       fna(ifc, 0, is)+dv%fna(ifc, 1, is))
    END DO
  END DO
! by ns
!
!   ..interpolate density to cell faces
!pb      call intface1(nCv,nFc,ns-1,mpg%fcCv,gm%fcVol,pl%na,naf)
  wght = 1.0_R8
  arg110 = ns - 1
  CALL INTFACE1(ncv, nfc, arg110, mpg%fccv, wght, pl%na, naf)
!
  IF (switch%eirene_uub_style .EQ. 1) THEN
    DO is=0,ns-1
      nafsqalf(1:nfc, 0, is) = gm%fcs(1:nfc)*gm%fcqalf(1:nfc, 0)*naf(1:&
&       nfc, is) + 1.e-30_R8
    END DO
    IF (switch%eirene_background .EQ. 0) THEN
      fna_tmp(1:nfc, 0:ns-1) = dv%fna(1:nfc, 0, 0:ns-1)/nafsqalf(1:nfc, &
&       0, 0:ns-1)
    ELSE
      fna_tmp(1:nfc, 0:ns-1) = dv%fna_eir(1:nfc, 0, 0:ns-1)/nafsqalf(1:&
&       nfc, 0, 0:ns-1)
    END IF
    arg110 = ns - 1
    CALL INTCELL1_NODIFF(nfc, ncv, arg110, mpg, mpg%intcellp, fna_tmp, &
&                  uuc)
  END IF
!
  DO is=0,ns-1
    nafsqalf(1:nfc, 1, is) = gm%fcs(1:nfc)*gm%fcqalf(1:nfc, 1)*naf(1:nfc&
&     , is) + 1.e-30_R8
    IF (switch%eirene_background .EQ. 0) THEN
      fna_tmp(1:nfc, is) = dv%fna(1:nfc, 1, is)/nafsqalf(1:nfc, 1, is)
! loop over all guard cells
      DO ic=mpg%nci+1,ncv
        ifc = mpg%cvfc(mpg%cvfcp(ic, 1))
! index of plasma cell
        icp = mpg%fccv(ifc, 1) + mpg%fccv(ifc, 2) - ic
        fna_tmp(ifc, is) = dv%fna(ifc, 1, is)/(gm%fcs(ifc)*gm%fcqalf(ifc&
&         , 1)*pl%na(ic, is)+1.e-30_R8)
      END DO
    ELSE
      fna_tmp(1:nfc, is) = dv%fna_eir(1:nfc, 1, is)/nafsqalf(1:nfc, 1, &
&       is)
    END IF
  END DO
  arg110 = ns - 1
  CALL INTCELL1_NODIFF(nfc, ncv, arg110, mpg, mpg%intcellr, fna_tmp, vvc&
&               )
!
! for neutrals (needed on Eirene side in case of spatially hybrid neutrals),
! always use fna instead of fna_eir, regardless of eirene_background switch
  IF (switch%spatial_hybrid .NE. 0) THEN
    DO is=0,ns-1
      IF (is_neutral(is)) THEN
        fna_tmp(1:nfc, is) = dv%fna(1:nfc, 1, is)/nafsqalf(1:nfc, 1, is)
        CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellr, fna_tmp(1:nfc, &
&                     is), vvc(1:nfc, is))
      END IF
    END DO
  END IF
!
  nflai = 0
  DO is=0,ns-1
!!        if(.not.is_neutral(is)) then
!!          nflai=nflai+1
    IF (fluids_list(is) .NE. 0) THEN
      nflai = fluids_list(is)
      CALL XERTST(nflai .LE. nfl, 'eirene_mc: increase size of nfl')
      amb(nflai) = am(is)
      znb(nflai) = zn(is)
      IF (zamin(is) .EQ. zamax(is)) THEN
        zab(nflai) = zamin(is)
      ELSE
        CALL XERRAB('eirene_mc: do not use bundled '//&
&             'species for Eirene')
      END IF
! cell centred
      DO ic=1,ncv
        IF (pl%na(ic, is) .GT. switch%eir_na_max) THEN
          x6 = switch%eir_na_max
        ELSE
          x6 = pl%na(ic, is)
        END IF
        IF (x6 .LT. switch%eir_na_min) THEN
          dnib(ic, nflai) = switch%eir_na_min
        ELSE
          dnib(ic, nflai) = x6
        END IF
        IF (pl%ua(ic, is) .GT. switch%eir_ua_max) THEN
          x7 = switch%eir_ua_max
        ELSE
          x7 = pl%ua(ic, is)
        END IF
        IF (x7 .LT. switch%eir_ua_min) THEN
          upb(ic, nflai) = switch%eir_ua_min
        ELSE
          upb(ic, nflai) = x7
        END IF
        IF (wadiac(ic, 0, is) + vaecrbc(ic, 0, is) .GT. switch%&
&           eir_ua_max) THEN
          x8 = switch%eir_ua_max
        ELSE
          x8 = wadiac(ic, 0, is) + vaecrbc(ic, 0, is)
        END IF
        IF (x8 .LT. switch%eir_ua_min) THEN
          uudiab(ic, nflai) = switch%eir_ua_min
        ELSE
          uudiab(ic, nflai) = x8
        END IF
        IF (wadiac(ic, 1, is) + vaecrbc(ic, 1, is) .GT. switch%&
&           eir_ua_max) THEN
          x9 = switch%eir_ua_max
        ELSE
          x9 = wadiac(ic, 1, is) + vaecrbc(ic, 1, is)
        END IF
        IF (x9 .LT. switch%eir_ua_min) THEN
          vvdiab(ic, nflai) = switch%eir_ua_min
        ELSE
          vvdiab(ic, nflai) = x9
        END IF
        IF (.NOT.is_neutral(is)) THEN
          prb(ic) = prb(ic) + tib(ic)*dnib(ic, nflai)
        ELSE
          prb(ic) = prb(ic) + tnb(ic)*dnib(ic, nflai)
        END IF
!     Velocities uub, vvb, wwb
!     * cell-centered
!     * internal cell values used for plasma background properties in infcop
!     * guard cell values used for source sampling in infcop
        IF (switch%eirene_uub_style .EQ. 0) THEN
          IF (switch%eirene_background .EQ. 0 .OR. ic .GT. mpg%nci) THEN
            x16 = upb(ic, nflai)*gm%cvbb(ic, 0)/gm%cvbb(ic, 3) + switch%&
&             xwdia*vadiac(ic, 0, is) + switch%xvecrb*vaecrbc(ic, 0, is)
            IF (x16 .GT. switch%eir_ua_max) THEN
              x10 = switch%eir_ua_max
            ELSE
              x10 = x16
            END IF
            IF (x10 .LT. switch%eir_ua_min) THEN
              uub(ic, nflai) = switch%eir_ua_min
            ELSE
              uub(ic, nflai) = x10
            END IF
          ELSE
            x17 = upb(ic, nflai)*gm%cvbb(ic, 0)/gm%cvbb(ic, 3) + switch%&
&             xwdia*wadiac(ic, 0, is) + switch%xvecrb*vaecrbc(ic, 0, is)
            IF (x17 .GT. switch%eir_ua_max) THEN
              x11 = switch%eir_ua_max
            ELSE
              x11 = x17
            END IF
            IF (x11 .LT. switch%eir_ua_min) THEN
              uub(ic, nflai) = switch%eir_ua_min
            ELSE
              uub(ic, nflai) = x11
            END IF
          END IF
        ELSE IF (switch%eirene_uub_style .EQ. 1) THEN
          IF (uuc(ic, is) .GT. switch%eir_ua_max) THEN
            x12 = switch%eir_ua_max
          ELSE
            x12 = uuc(ic, is)
          END IF
          IF (x12 .LT. switch%eir_ua_min) THEN
            uub(ic, nflai) = switch%eir_ua_min
          ELSE
            uub(ic, nflai) = x12
          END IF
        END IF
        IF (vvc(ic, is) .GT. switch%eir_ua_max) THEN
          x13 = switch%eir_ua_max
        ELSE
          x13 = vvc(ic, is)
        END IF
        IF (x13 .LT. switch%eir_ua_min) THEN
          vvb(ic, nflai) = switch%eir_ua_min
        ELSE
          vvb(ic, nflai) = x13
        END IF
!wdk  wwb directly computed from cell-centered velocities.
!     Compatible with SOLPS4.3, and consistent with sign convention ua,
!     but may not be fully consistent with respect to drifts.
!     In particular: convective anomalous contribution (if present) is missing
!                    (diffusive anomalous contribution zero due to toroidal symm.)
        IF (switch%eirene_background .EQ. 0 .OR. ic .GT. mpg%nci) THEN
          IF (upb(ic, nflai)*gm%cvbb(ic, 2)/gm%cvbb(ic, 3) - (switch%&
&             xwdia*vadiac(ic, 0, is)+switch%xvecrb*vaecrbc(ic, 0, is))*&
&             gm%cvbb(ic, 0)/gm%cvbb(ic, 2) .GT. switch%eir_ua_max) THEN
            x14 = switch%eir_ua_max
          ELSE
            x14 = upb(ic, nflai)*gm%cvbb(ic, 2)/gm%cvbb(ic, 3) - (switch&
&             %xwdia*vadiac(ic, 0, is)+switch%xvecrb*vaecrbc(ic, 0, is))&
&             *gm%cvbb(ic, 0)/gm%cvbb(ic, 2)
          END IF
          IF (x14 .LT. switch%eir_ua_min) THEN
            wwb(ic, nflai) = switch%eir_ua_min
          ELSE
            wwb(ic, nflai) = x14
          END IF
        ELSE
          IF (upb(ic, nflai)*gm%cvbb(ic, 2)/gm%cvbb(ic, 3) - (switch%&
&             xwdia*wadiac(ic, 0, is)+switch%xvecrb*vaecrbc(ic, 0, is))*&
&             gm%cvbb(ic, 0)/gm%cvbb(ic, 2) .GT. switch%eir_ua_max) THEN
            x15 = switch%eir_ua_max
          ELSE
            x15 = upb(ic, nflai)*gm%cvbb(ic, 2)/gm%cvbb(ic, 3) - (switch&
&             %xwdia*wadiac(ic, 0, is)+switch%xvecrb*vaecrbc(ic, 0, is))&
&             *gm%cvbb(ic, 0)/gm%cvbb(ic, 2)
          END IF
          IF (x15 .LT. switch%eir_ua_min) THEN
            wwb(ic, nflai) = switch%eir_ua_min
          ELSE
            wwb(ic, nflai) = x15
          END IF
        END IF
!
        ebx = gm%cveb(ic, 0)
        eby = gm%cveb(ic, 1)
        arg111 = ebx*ebx + eby*eby
        ebn = SQRT(arg111)
        IF (ebn .GT. 0) THEN
          ebx = ebx/ebn
          eby = eby/ebn
        END IF
        pux(ic) = ebx
        puy(ic) = eby
        pvx(ic) = -eby
        pvy(ic) = ebx
        vxb(ic, nflai) = uub(ic, nflai)*pux(ic) + vvb(ic, nflai)*pvx(ic)
        vyb(ic, nflai) = uub(ic, nflai)*puy(ic) + vvb(ic, nflai)*pvy(ic)
        arg111 = gm%cveb(ic, 2)
        vzb(ic, nflai) = wwb(ic, nflai)*SIGN(1.0_R8, arg111)
      END DO
!
! cell faces
      DO ifc=1,nfc
        fnib(ifc, nflai) = dv%fna(ifc, 0, is) + dv%fna(ifc, 1, is)
        IF (is_neutral(is)) THEN
          fnn_inc_b(ifc, nflai) = fnn_inc(ifc, is)
          fnn_mol_b(ifc, nflai) = fna_mol(ifc, is)
        END IF
      END DO
    END IF
  END DO
!
!!        endif
!
!pb  05.03.18
  nflai = COUNT(fluids_list .GT. 0, 1)
!
  IF (switch%eirene_extrap .NE. 0) THEN
! do nothing
    IF (switch%eirene_extrap .EQ. 1) THEN
! we derive the guard cell value from its neighbouring interior cell
      DO ic=mpg%nci+1,mpg%ncv
        ifc = mpg%cvfc(mpg%cvfcp(ic, 1))
        IF (mpg%fccv(ifc, 1) .GT. mpg%fccv(ifc, 2)) THEN
          ic2 = mpg%fccv(ifc, 2)
        ELSE
          ic2 = mpg%fccv(ifc, 1)
        END IF
        teb(ic) = teb(ic2)
        tib(ic) = tib(ic2)
        tnb(ic) = tnb(ic2)
        pob(ic) = pob(ic2)
        dnib(ic, :) = dnib(ic2, :)
      END DO
    ELSE
      WRITE(*, *) switch%eirene_extrap, &
&     ' not available as an eirene_extrap option'
    END IF
  END IF
!
  IF (switch%eirene_print_minmax .NE. 0) THEN
    te_min_val = MINVAL(teb(:))
    te_max_val = MAXVAL(teb(:))
    ti_min_val = MINVAL(tib(:))
    ti_max_val = MAXVAL(tib(:))
    na_min_val = MINVAL(dnib(:, 1:nflai))
    na_max_val = MAXVAL(dnib(:, 1:nflai))
    ua_min_val = MINVAL(uub(:, 1:nflai))
    ua_max_val = MAXVAL(uub(:, 1:nflai))
    WRITE(*, '(a,1p,8(1x,g12.3))') 'minmax:teb,tib,nab,uub ', te_min_val&
&   , te_max_val, ti_min_val, ti_max_val, na_min_val, na_max_val, &
&   ua_min_val, ua_max_val
  END IF
!
  IF (switch%copy_background_iout .NE. 0) THEN
    nflai = 0
    DO is=0,ns-1
      IF (.NOT.is_neutral(is)) THEN
        nflai = nflai + 1
        WRITE(chns, '(i3.3)') is
        WRITE(ccall, '(a1,i1)') '_', icall
        arg112(:) = 'copy_uub'//chns//ccall
        CALL MY_OUT_US(70, ncv, 0, uub(1, nflai), arg112(:))
        arg112(:) = 'copy_vvb'//chns//ccall
        CALL MY_OUT_US(70, ncv, 0, vvb(1, nflai), arg112(:))
        arg112(:) = 'copy_wwb'//chns//ccall
        CALL MY_OUT_US(70, ncv, 0, wwb(1, nflai), arg112(:))
        arg112(:) = 'copy_upb'//chns//ccall
        CALL MY_OUT_US(70, ncv, 0, upb(1, nflai), arg112(:))
      END IF
    END DO
    CALL MY_OUT_US(70, ncv, 0, teb, 'copy_teb')
    CALL MY_OUT_US(70, ncv, 0, tib, 'copy_tib')
    CALL MY_OUT_US(70, ncv, 0, tnb, 'copy_tnb')
    CALL MY_OUT_US(70, ncv, 0, pob, 'copy_pob')
    icall = icall + 1
  END IF
!
!  .. define target data
!
  IF (.NOT.ALLOCATED(trgt)) THEN
    ALLOCATE(trgt(mpg%nrc))
  END IF
  DO istra=1,mpg%nrc
    ian = mpg%rcfcp(istra, 1)
    ien = ian + mpg%rcfcp(istra, 2) - 1
    ntrgdat = ien - ian + 1
    IF (ien - ian + 1 .LE. 0) THEN
      trgt(istra)%ntrgdat = 0
    ELSE
!
      CALL ALLOC_TARGET_DATA(istra, ntrgdat, nflai)
!
      DO i=1,ntrgdat
        ifc = mpg%rcfc(ian+i-1)
        trgt(istra)%faces(i) = ifc
        trgt(istra)%fcori(i) = mpg%rcfcor(ian+i-1)
        iv1 = mpg%fcvx(ifc, 1)
        iv2 = mpg%fcvx(ifc, 2)
! index of guard cell
        ic = mpg%rccv(ian+i-1, 1)
        arg111 = (gm%vxx(iv1)-gm%vxx(iv2))**2 + (gm%vxy(iv1)-gm%vxy(iv2)&
&         )**2
        result10 = SQRT(arg111)
        trgt(istra)%flength(i) = result10*100._R8
        trgt(istra)%tet(i) = teb(ic)
        trgt(istra)%tit(i) = tib(ic)
        trgt(istra)%tnt(i) = tnb(ic)
        trgt(istra)%fe(i) = rcfe(istra)
        trgt(istra)%fsh(i) = delta_sheathb(ifc)
        DO ifl=1,nflai
          trgt(istra)%dnit(i, ifl) = dnib(ic, ifl)
          IF (zab(ifl) .NE. 0) THEN
!! ion species
            trgt(istra)%flux(i, ifl) = fnib(ifc, ifl)*mpg%rcfcor(ian+i-1&
&             )*kin_frac_hyb(ifc)
          ELSE IF (mol(istra) .EQ. 0) THEN
!! neutral atom species
            trgt(istra)%flux(i, ifl) = fnn_inc_b(ifc, ifl)*mpg%rcfcor(&
&             ian+i-1)*kin_frac_hyb(ifc)
          ELSE
!! neutral molecule species
            trgt(istra)%flux(i, ifl) = 2.0_R8*fnn_mol_b(ifc, ifl)
          END IF
          IF (trgt(istra)%flux(i, ifl) .LT. 0.0_R8) THEN
            WRITE(*, *) 'negative flux !! istra, i, ifl = ', istra, i, &
&           ifl
            trgt(istra)%flux(i, ifl) = 0.0_R8
            fnib(ifc, ifl) = 0.0_R8
          END IF
          trgt(istra)%fi(i, ifl) = rcfi(istra)
!
          ebx = gm%fceb(ifc, 0)
          eby = gm%fceb(ifc, 1)
          arg111 = ebx*ebx + eby*eby
          ebn = SQRT(arg111)
          IF (ebn .GT. 0) THEN
            ebx = ebx/ebn
            eby = eby/ebn
          END IF
          puxs = ebx
          puys = eby
          pvxs = -eby
          pvys = ebx
          uu = uub(ic, ifl)
          vv = vvb(ic, ifl)
          ww = wwb(ic, ifl)
          trgt(istra)%vxt(i, ifl) = puxs*uu + pvxs*vv
          trgt(istra)%vyt(i, ifl) = puys*uu + pvys*vv
          trgt(istra)%vzt(i, ifl) = ww
          trgt(istra)%fel(i, ifl) = 0.0_R8
          trgt(istra)%vpart(i, ifl) = 0.0_R8
          trgt(istra)%mach(i, ifl) = 1.0_R8
          trgt(istra)%usr(i, ifl) = 0.0_R8
        END DO
      END DO
    END IF
  END DO
!
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE COPY_BACKGROUND_NODIFF

!
SUBROUTINE WRITE_F31_NODIFF(mpg)
  USE B2MOD_TYPES
  USE B2MOD_EIRENE_GLOBALS
  USE B2MOD_B2CMPA_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_BRAEIR_DIFFV
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!  version : 28.12.96 21:39
!
!  Common dimensions
!
!  version : 01.12.98 21:42
!
!
!     COUPLING-DEFINITION COMMON (KOPPLDIM)
!
!
!  -- PRINCIPAL DIMENSIONS -- SHOULD MATCH EIRENE DECLARATIONS!!!
  INTEGER :: nxdd, nydd, nstra, nfl
  PARAMETER (nxdd=200+4*5, nydd=100, nstra=(5*4/2+2)*6+1, nfl=42)
  INTEGER :: natm, nmol, nion, npls, nspz
  PARAMETER (natm=6, nmol=3, nion=3, npls=42-6+(6+3)*(6+3), nspz=6+3+3+(&
&   42-6)+(6+3)*(6+3))
  INTEGER :: nlim, nsts, nsrfs, nsgmx
  PARAMETER (nlim=300, nsts=50, nsrfs=4)
  PARAMETER (nsgmx=300+max(2, 4)*100)
!
  INTEGER :: n1st, n2nd, n3rd
  PARAMETER (n1st=100+1, n2nd=200+1+4+(4/2-1)*(1+0), n3rd=1)
  INTEGER :: n1f, n2f, n3f
  PARAMETER (n1f=1-1/n1st, n2f=1-1/n2nd, n3f=1-1/n3rd)
  INTEGER :: ngitt, ngittp
  PARAMETER (ngitt=n1st*n2nd*n3f+n1st*n3rd*n2f+n2nd*n3rd*n1f, ngittp=&
&   ngitt+1)
  INTEGER :: ndx, ndy
  PARAMETER (ndx=nxdd, ndy=nydd)
  INTEGER :: ndxp, ndyp, nlimps
  PARAMETER (ndxp=nxdd+1, ndyp=nydd+1, nlimps=nlim+nsts)
  INTEGER :: ngtsft, nlmpgs
  PARAMETER (ngtsft=1*ngitt)
  PARAMETER (nlmpgs=nlim+(ngtsft+1)*nsts)
!
  TYPE(MAPPING), INTENT(IN) :: mpg
  INTEGER :: i, ic, ifl, ntrgdat, istra
  INTRINSIC COUNT
!
!  .. use approach to generalized user interface
!
!  .. plasma data
  REWIND(31) 
  WRITE(31, '(a)') '* EIRENE PLASMA FILE '
  WRITE(31, '(a)') '*'
  WRITE(31, '(a)') '*** MISC PLASMA DATA'
  WRITE(31, '(a)') '*'
  WRITE(31, '(a1,a6,15a15)') '*', 'Index', 'Te', 'ne', 'Bx', 'By', 'Bz'&
& , 'Ex', 'Ey', 'Ez', 'pot', 'psi', 'f', 'Pux', 'Puy', 'Pvx', 'Pvy'
  WRITE(31, '(a1,a6,15a15)') '*', ' ', '(eV)', '(1/m^3)', 'Tesla', &
& 'Tesla', 'Tesla', '(V/m)', '(V/m)', '(V/m)', 'V', '??', '??', ' ', ' '&
& , ' ', ' '
!
  WRITE(31, '(3i6)') mpg%ncv, mpg%nci, mpg%nfc
!
  DO ic=1,mpg%nci
    WRITE(31, '(i7,15es15.7)') ic, teb(ic), neb(ic), bbxb(ic), bbyb(ic)&
&   , bbzb(ic), 0.0_R8, 0.0_R8, 0.0_R8, pob(ic), 0.0_R8, 0.0_R8, pux(ic)&
&   , puy(ic), pvx(ic), pvy(ic)
  END DO
!
  DO ifl=1,nflai
!
    WRITE(31, '(a)') '*'
    WRITE(31, '(a,i0,a)') '*** ION #', ifl, ' PLASMA DATA'
    WRITE(31, '(a)') '*'
    WRITE(31, '(a1,a6,5a15)') '*', 'Index', 'Ti', 'ni', 'Vx', 'Vy', 'Vz'
    WRITE(31, '(a1,a6,5a15)') '*', ' ', '(eV)', '(1/m^3)', 'm/s', 'm/s'&
&   , 'm/s'
!
    WRITE(31, '(3es15.7)') amb(ifl), znb(ifl), zab(ifl)
!
    WRITE(31, '(i6)') mpg%nci
!
    DO ic=1,mpg%nci
      WRITE(31, '(i7,5es15.7)') ic, tib(ic), dnib(ic, ifl), vxb(ic, ifl)&
&     , vyb(ic, ifl), vzb(ic, ifl)
    END DO
  END DO
!
!
!  .. target data
  WRITE(31, '(a)') '*'
  WRITE(31, '(a)') '*** TARGET DATA'
  WRITE(31, '(a)') '*'
!      write (31,'(i6)') mpg%nRc
  WRITE(31, '(i6)') COUNT(trgt(1:mpg%nrc)%ntrgdat .GT. 0)
!
  DO istra=1,mpg%nrc
    ntrgdat = trgt(istra)%ntrgdat
    IF (ntrgdat .NE. 0) THEN
      WRITE(31, '(a)') '*'
      WRITE(31, '(a,i0)') '*** MISC TARGET DATA #', istra
      WRITE(31, '(a)') '*'
      WRITE(31, '(a1,2a6,6a15)') '*', 'Index', 'face', 'ori', 'Te', 'fe'&
&     , 'fsh', 'length'
      WRITE(31, '(a1,2a6,6a15)') '*', ' ', ' ', ' ', '(eV)', ' ', ' ', &
&     ' '
      WRITE(31, '(i6)') ntrgdat
!
      DO i=1,ntrgdat
        WRITE(31, '(i7,i6,6es15.7)') i, trgt(istra)%faces(i), trgt(istra&
&       )%fcori(i), trgt(istra)%tet(i), trgt(istra)%fe(i), trgt(istra)%&
&       fsh(i), trgt(istra)%flength(i)
      END DO
!
      DO ifl=1,nflai
!
        WRITE(31, '(a)') '*'
        WRITE(31, '(a,i0,a,i0)') '*** ION #', ifl, ' TARGET DATA #', &
&       istra
        WRITE(31, '(a)') '*'
!
        WRITE(31, '(a1,a6,11a15)') '*', 'Index', 'Flux', 'Ti', 'ni', &
&       'Vx', 'Vy', 'Vz', 'fi', 'fel', 'vpart', 'mach', 'usr'
        WRITE(31, '(a1,a6,11a15)') '*', ' ', ' ', '(eV)', '(1/m^3)', &
&       'm/s', 'm/s', 'm/s', ' ', ' ', ' ', ' '
!
        WRITE(31, '(3es15.7)') amb(ifl), znb(ifl), zab(ifl)
        WRITE(31, '(i6)') ntrgdat
!
        DO i=1,ntrgdat
          WRITE(31, '(i7,11es15.7)') i, trgt(istra)%flux(i, ifl), trgt(&
&         istra)%tit(i), trgt(istra)%dnit(i, ifl), trgt(istra)%vxt(i, &
&         ifl), trgt(istra)%vyt(i, ifl), trgt(istra)%vzt(i, ifl), trgt(&
&         istra)%fi(i, ifl), trgt(istra)%fel(i, ifl), trgt(istra)%vpart(&
&         i, ifl), trgt(istra)%mach(i, ifl), trgt(istra)%usr(i, ifl)
        END DO
      END DO
    END IF
  END DO
! ifl
! istra
  FLUSH(31) 
  RETURN
END SUBROUTINE WRITE_F31_NODIFF

