!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of extend in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: field
!   with respect to varying inputs: field
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE EXTEND_DV(field, fieldd, ncv, mpg, ns, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_INDIRECT
  USE B2US_MAP_DIFFV
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER :: ncv, ns
  TYPE(MAPPING) :: mpg
  REAL(kind=r8) :: field(ncv, 0:ns-1)
  REAL(kind=r8) :: fieldd(nbdirsmax, ncv, 0:ns-1)
  INTEGER :: is, ic, ifc, icin
  INTRINSIC MIN
  INTEGER :: nd
  INTEGER :: nbdirs
  DO is=0,ns-1
    DO ic=mpg%nci+1,ncv
      ifc = mpg%cvfc(mpg%cvfcp(ic, 1))
      IF (mpg%fccv(ifc, 1) .GT. mpg%fccv(ifc, 2)) THEN
        icin = mpg%fccv(ifc, 2)
      ELSE
        icin = mpg%fccv(ifc, 1)
      END IF
      DO nd=1,nbdirs
        fieldd(nd, ic, is) = fieldd(nd, icin, is)
      END DO
      field(ic, is) = field(icin, is)
    END DO
  END DO
  RETURN
END SUBROUTINE EXTEND_DV

!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE EXTEND_NODIFF(field, ncv, mpg, ns)
  USE B2MOD_TYPES
  USE B2MOD_INDIRECT
  USE B2US_MAP_DIFFV
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER :: ncv, ns
  TYPE(MAPPING) :: mpg
  REAL(kind=r8) :: field(ncv, 0:ns-1)
  INTEGER :: is, ic, ifc, icin
  INTRINSIC MIN
  DO is=0,ns-1
    DO ic=mpg%nci+1,ncv
      ifc = mpg%cvfc(mpg%cvfcp(ic, 1))
      IF (mpg%fccv(ifc, 1) .GT. mpg%fccv(ifc, 2)) THEN
        icin = mpg%fccv(ifc, 2)
      ELSE
        icin = mpg%fccv(ifc, 1)
      END IF
      field(ic, is) = field(icin, is)
    END DO
  END DO
  RETURN
END SUBROUTINE EXTEND_NODIFF

