!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of trimg in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: trimg
!   with respect to varying inputs: cc
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE TRIMG_DV(aa, bb, cc, ccd, trimg, trimgd, nbdirs)
  USE B2MOD_TYPES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!     ------------------------------------------------------------------
  REAL(kind=r8) :: trimg, aa, bb, cc
  REAL(kind=r8), DIMENSION(nbdirsmax) :: trimgd, ccd
  INTRINSIC MIN, MAX
  REAL(kind=r8), DIMENSION(nbdirsmax) :: y1d
  INTEGER :: nd
  INTEGER :: nbdirs
  REAL(kind=r8) :: y1
  IF (bb .GT. cc) THEN
    DO nd=1,nbdirs
      y1d(nd) = ccd(nd)
    END DO
    y1 = cc
  ELSE
    y1 = bb
    DO nd=1,nbdirsmax
      y1d(nd) = 0.D0
    END DO
  END IF
  IF (aa .LT. y1) THEN
    DO nd=1,nbdirs
      trimgd(nd) = y1d(nd)
    END DO
    trimg = y1
  ELSE
    trimg = aa
    DO nd=1,nbdirsmax
      trimgd(nd) = 0.D0
    END DO
  END IF
  RETURN
END SUBROUTINE TRIMG_DV

