"""
Generates b2cdcn.F
"""

from __future__ import print_function

import xml.etree.ElementTree as etree
from xml.etree.ElementTree import tostring
import textwrap
from itertools import chain

def get_default(text):
    base = ' Defaults to '
    end = '.'
    if text:
        if '.true.' in text or '.false.' in text or 'NX' in text or 'NY' in \
            text or 'NS' in text:
            return base + text + end
        if text.isalpha() or text == ' ' or text.replace('.', '').isalpha() or\
           text.replace('_', '').isalpha():
            return base + "'" + text + "'" + end
        else:
            return base + text + end
    else:
        return ''


def stringify_children(node):
    parts = ([node.text] +
            list(chain(*([tostring(c).split()[0], c.tail] for c in node.getchildren()))) +
            [node.tail])
    # filter removes possible Nones in texts and tails
    return ''.join([i.decode() if type(i) == bytes else i for i in filter(None, parts)])

def dedent(description, prefix = '\n*    ', width=75):
    """ Removes first empty fort from description and any leading tabs
        from the next fort before the description and any following forts.
        First forts are wrapped to 70 characters.

    :param description(string): from the XML generated tooltips dictionary
    :return: formatted output for the tooltip
    """
    trim_start = 0  # Remove any leading newfort that affects dedent
    while trim_start < len(description) and description[trim_start] == '\n':
        trim_start += 1
    description = textwrap.dedent(description[trim_start:])
    lines = description.splitlines()
    output = ''
    for line in lines:
        line = line.lstrip()
        output += prefix[1:] + prefix.join(textwrap.wrap(line, width)) + '\n'
    return output[0:]  # remove last newline


def dedent_without_wraping(description):
    trim_start = 0  # Remove any leading newfort that affects dedent
    while trim_start < len(description) and description[trim_start] == '\n':
        trim_start += 1
    description = textwrap.dedent(description[trim_start:])
    return description

def add_to_fort(text):
    global fort
    split_text = text.splitlines()
    text = ''
    for i, line in enumerate(split_text):
        line = line.lstrip()
        if i==0:
            text += '\n*  ' + line[:2]
            text += '\n*     '.join(textwrap.wrap(line[2:], 74)) + '\n'
        else:
            text += '*     ' + '\n*     '.join(textwrap.wrap(line, 73)) + '\n'
    fort += text[:-1]

xml_name = "b2input.xml"
tree = etree.parse(xml_name)
root = tree.getroot()

specification = root.find('module[@name="b2.parameters"]/routine[@name="b2cdcn"]')
purpose = specification.findtext('purpose')

DELIMITER = """*---------------------------------------------------------------\
--------\n"""

fort = DELIMITER
fort += """* Generated by b2cdcn.py from b2input.xml. DO NOT EDIT THIS FILE!
*.specification

      subroutine b2cdcn ()
      implicit none

"""

fort += DELIMITER
fort += '*.documentation\n*\n'
fort += '*  1. purpose\n*\n'
fort += dedent(purpose, prefix='\n*     ', width=66)
fort += '*\n' + DELIMITER
fort += '*.text\n*\n'


b2_parameters = root.find('module[@name="b2.parameters"]')
categories = b2_parameters.findall('category')



# Sections
for category in categories:


    # Namelist name
    namelist = category.findtext('introduction/namelist')
    fort += '* NAMELIST /' + namelist + '/\n'

    # Section description
    fort += '*    Found in ' + category.attrib['name']
    if category.findtext('introduction/note'):
        fort += category.findtext('introduction/note')
    fort += '.\n'
    fort += dedent(category.findtext('introduction/description'),
                   prefix='\n*    ')[:-1]
    # Adding all parameters and switches

    for element in category:
        if element.tag == 'switch':
            text = ''
            text +=  element.findtext('name') + ' - '
            text +=  element.findtext('type') + '. '
            text +=  dedent_without_wraping(stringify_children(element.find('description')))[:-1]
            text += get_default(element.findtext('default'))
            add_to_fort(text)
        elif element.tag == 'switchgroup':
            N = len(element.findall('switch'))
            counter = 0
            for switch in element.findall('switch'):
                counter+=1
                text = ''
                text +=  switch.findtext('name') + ' - '
                text +=  switch.findtext('type') + '. '
                text +=  dedent_without_wraping(stringify_children(switch.find('description')))[:-1]
                default = get_default(switch.findtext('default'))
                if default:
                    text += get_default(switch.findtext('default'))
                if counter == N and element.findtext('description'):
                    text += dedent_without_wraping(stringify_children(element.find('description')))

                add_to_fort(text)


        # Adding a stand alone note.
        elif element.tag == 'note':
            fort += '*\n'
            text = dedent(element.text, prefix='\n* ')+'*\n'
            fort += text
            continue
        else:
            continue
    fort += '\n*\n'

fort += DELIMITER
fort += """*.end b2cdcn\n\n      end subroutine b2cdcn\n"""

with open('b2cdcn.F', 'w') as f:
    f.write(fort)