"""
Generates b2cdci.F
"""
from __future__ import print_function

import xml.etree.ElementTree as etree
import textwrap

def check_constant(string):
    if 'pzmm' in string or 'upgrade' in string or string == 'iter' or string=='+c' or string=='-c':
        return True
    for char in string:
        if not char.isdigit():
            if char in ['.', 'e', '-', '+']:
                continue
            else:
                return False
    return True


def fort_switch(name, default, category, note):
    # Some switches may have no default value or categories.
    category = 'None' if category is None else category
    pname = "'" + name + "'"
    if check_constant(default):
        pdefault = '\'' + default + '\''
    else:
        pdefault = default
    fort = "*    "
    fort += pname
    fort += (27-len(pname) if 27-len(pname) >= 0 else 1) * ' ' + pdefault
    fort += (55-len(fort) if 55-len(fort) >= 0 else 1) * ' ' + category
    if note:
        fort += (67 - len(fort)) * ' ' + note + '\n'
    else:
        fort += '\n'
    #fort = "*    {:<26} {:<22} {:<14}\n".format(pname, pdefault, category)
    return fort

xml_name = "b2input.xml"
tree = etree.parse(xml_name)
root = tree.getroot()

b2cdci_switches = {}

# Create a sorted list of switches
for category in root.find('module[@name="b2mn"]'):
    for switchgroup in category.findall('switchgroup'):
        switch_description = switchgroup.findtext('description')
        for switch in switchgroup.findall('switch'):
            switch_name = switch.findtext('name')
            switch_default = switch.findtext('default')
            switch_note = switch.findtext('note')
            b2cdci_switches[switch_name] = (switch_default, 
                                            switch_description, 
                                            switch_note,
                                            category.attrib['name'])

    for switch in category.findall('switch'):
        switch_name = switch.findtext('name')
        switch_default = switch.findtext('default')
        switch_description = switch.findtext('description')
        switch_note = switch.findtext('note')
        b2cdci_switches[switch_name] = (switch_default,
                                        switch_description,
                                        switch_note,
                                        category.attrib['name'])

# Create description of switches for list by category
switch_list = []
category_section = []
for category in root.find('module[@name="b2mn"]'):
    section = category.attrib['name']# Name of category

    section_switches = []
    for element in category:
        if element.tag == 'switch':
            section_switches.append(element.findtext('name'))
            switch_list.append(element.findtext('name'))
        elif element.tag == 'switchgroup':
            #print(element.tag, element.findtext('name'))
            for i in element.findall('switch'):
                if i.tag == 'switch':
                    section_switches.append(i.findtext('name'))
                    switch_list.append(i.findtext('name'))

    category_section.append((section, section_switches))

DELIMITER = """*---------------------------------------------------------------\
--------\n"""


def dedent(description):
    """ Removes first empty fort from description and any leading tabs
        from the next fort before the description and any following forts.
        First forts are wrapped to 70 characters.

    :param description(string): from the XML generated tooltips dictionary
    :return: formatted output for the tooltip
    """
    trim_start = 0  # Remove any leading newfort that affects dedent
    while trim_start < len(description) and description[trim_start] == '\n':
        trim_start += 1
    description = textwrap.dedent(description[trim_start:])
    lines = description.splitlines()
    output = ''
    for line in lines:
        output += '*    ' + '\n*    '.join(textwrap.wrap(line, 70)) + '\n'
    return output[0:]  # remove last newline


specification = root.find('module[@name="b2mn"]/routine[@name="b2cdci"]')

purpose = specification.findtext('purpose')
introduction = specification.findtext('introduction')


fort = DELIMITER
fort += """* Generated by b2cdci.py from solps-input.xml. DO NOT EDIT THIS FILE!
*.specification

      subroutine b2cdci ()
      implicit none

"""
fort += DELIMITER
fort += '*.documentation\n*\n'
fort += '*  1. purpose\n*\n'
fort += dedent(purpose)
fort += '*\n*\n' + DELIMITER
fort += '*.text\n*\n'
fort += '*  0. Overview and naming conventions.\n*\n'
fort += dedent(introduction)
fort += '*\n*\n'

fort += """*    Switch name:               Default value:         Category:
*  -----------------------------------------------------------------\n"""
switch_list.sort()
for switch_name in switch_list:
    default = b2cdci_switches[switch_name][0]
    note = b2cdci_switches[switch_name][2]
    category = b2cdci_switches[switch_name][3]
    fort += fort_switch(switch_name, default, category, note)

fort += '*  -----------------------------------------------------------------' 
fort += '\n*\n*\n*\n'
fort += '*  1. Purpose of individual parameters\n*\n'


counter = 1
for section in category_section[1:]: # TODO remove first category
    category = section[0]
    section_title = '*   ' + '1.' + str(counter) + '. ' + category + ' switches'
    counter+=1
    switches_list = section[1]

    fort += '*   ' + section_title + '\n'

    switch_group = []
    group_description = ''

    for el in switches_list:
        switch_name = el
        default = b2cdci_switches[switch_name][0]
        description = b2cdci_switches[switch_name][1]
        note = b2cdci_switches[switch_name][2]
        category = b2cdci_switches[switch_name][3]

        # Special cases
        if switch_name == 'b2ardr_no_smoothing':
            category = 'Numerics'
        elif switch_name == 'b2sifr_phm2':
            category = 'Unused'
        else:
            category = section[0]

        if description == group_description:
            switch_group.append((switch_name, default, note))

        # Special case
        elif description != group_description:
            if switch_group and switch_group[-1][0] == 'b2sifr_limthii':
                switch_group.append((switch_name, default, note))
                continue
            for switch in switch_group:
                # Special case
                if switch[0] == 'b2ardr_no_smoothing':
                    category = 'Numerics'
                else:
                    category = section[0]

                fort += fort_switch(switch[0], switch[1], category, switch[2])
            fort += dedent(group_description) + '*\n'
            switch_group = [(switch_name, default, note)]
            group_description = description

    # Last group processed
    for switch in switch_group:
        fort += fort_switch(switch[0], switch[1], category, switch[2])
    fort += dedent(group_description) + '*\n'
fort += """*-----------------------------------------------------------------------
*.end b2cdci

      end subroutine b2cdci

"""

with open('b2cdci.F', 'w') as f:
    f.write(fort)
