#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# B2.5 IDS documentation build configuration file, created by
# sphinx-quickstart on Wed Nov 22 10:39:08 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
#import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinxfortran.fortran_autodoc',
    'sphinxfortran.fortran_domain']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst', ".F90"

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'B2.5 IDS'
copyright = '2017, Dejan Penko'
author = 'Dejan Penko'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.5'
# The full version, including alpha/beta/rc tags.
release = '1.5'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'classic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
        "rightsidebar": "false",
        "relbarbgcolor": "black",
        #"collapsiblesidebar": "true",
        "stickysidebar": "true"
}

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = "images/favicon.ico"


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'B25IDSdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'B25IDS.tex', 'B2.5 IDS Documentation',
     'Dejan Penko', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'b25ids', 'B2.5 IDS Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'B25IDS', 'B2.5 IDS Documentation',
     author, 'B25IDS', 'One line description of project.',
     'Miscellaneous'),
]

#fortran_src = "../../ids/b2_ual_write_b2mod.F90"
#fortran_src = os.path.abspath("../../ids/")
fortran_src = [
    os.path.abspath("../../ids/b2_ual_write.F90"),
    os.path.abspath("../../ids/b2_ual_write_gsl.F90"),
    os.path.abspath("../../ids/b2_ual_write_b2mod.F90"),
    os.path.abspath("../../ids/b2mod_cellhelper.F90"),
    os.path.abspath("../../ids/b2mod_connectivity.F90"),
    os.path.abspath("../../ids/b2mod_grid_mapping.F90"),
    os.path.abspath("../../ids/b2mod_interp.F90"),
    os.path.abspath("../../ids/b2mod_ual.F90"),
    os.path.abspath("../../ids/b2mod_ual_io.F90"),
    os.path.abspath("../../ids/b2mod_ual_io_data.F90"),
    os.path.abspath("../../ids/b2mod_ual_io_grid.F90")
]

fortran_ext = ['f90', 'F90', 'F']
