!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
MODULE B2MOD_USER_NAMELIST_DIFF
  USE B2MOD_TYPES
  USE B2MOD_DIAG_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2MOD_AD_DIFF, ONLY : nncf, b2rr, b2voloncf, b2voloncfb, b2data, &
& b2datab, b2dataoncf, b2dataoncfb
  IMPLICIT NONE
!
!  Common dimensions
!
!  version : 01.12.98 21:42
!
!
!
! parameters that are common to Eirene and B2
!
!
! NOTE: DEF_NXD should not include the additional cells to handle the cuts
!*** Max. number of groups of Eirene surfaces for which the data can
!*** be transferred from B2 (DG specification "Surface special")
!
! new! [2002.04.22]
! new! [2002.06.14]
!
!
! parameters that are unique to B2
!
!
!
!
! parameters that are unique to Eirene
!
!
!
!
! parameters needed by uinp
!
!
!
  INTEGER :: npfrgrpd, nntrgrpd
  PARAMETER (npfrgrpd=6, nntrgrpd=16)
  INTEGER :: nhetrgtx
  PARAMETER (nhetrgtx=300)
  INTEGER :: lhetrgts(nhetrgtx), lpfrgrp(300), lntrgrp(300)
  INTEGER :: l_h_mol(3, 3)
! VARIABLES RELATED TO DEFINITION OF MIDPLANES AND SEPARATRIX
! - [oi]mp: list of CVs beloning to the [OI]MP, defined through the segment rz[oi]mp
!           it should be built as an ordered list from core to SOL. 
! - nromp: pre-defined maximum size for these lists
! - icsep[oi]mp: location of the separatrix position in the [oi]omp list
! - n[oi]mp: number of CVs in the [oi]mp list
! - rz[o1]mp: R-Z coordinates of a segment whose intersection with the
!             plasma grid defines the OMP and IMP. rzomp(1,1:2) holds R-coordiantes 
!             of first and second point of the segment, rzomp(2,1:2) holds Z-coordinates
  INTEGER, PARAMETER :: nromp=100*4
  INTEGER, SAVE :: omp(nromp), icsepomp, nomp, ifssep, imp(nromp), &
& icsepimp, nimp
  REAL(kind=r8) :: rzomp(2, 2), rzimp(2, 2)
  REAL(kind=r8) :: fusion_power, spmp_he_to_d, spmp_nom
  INTEGER :: lpfrb_i, lpfrb_o, lpfrt_i, lpfrt_o, j_he_at, j_h_at(3), &
& j_ne_at, lpfrs_pmp, npfrgrp, ipfrgrp(npfrgrpd), jpfrgrp(npfrgrpd), &
& nntrgrp, intrgrp(nntrgrpd), jntrgrp(nntrgrpd)
! VARIABLES RELATED TO COST FUNCTION DEFINITION
! - mxnCf: maximum number of cost functions allowed
! - ncf: actual number of cost functions
! - cftype: type of cost function, 0-9 possible options
! - cfdef: defines how the cost function domain is defined 1-4 possible options
! - cfstart/cfend: starting and ending element for the cost function
! - cf_reg: Listing for each cost function the corresponding domain CVs or FCs
! - cf_regP: Points for each cost function to the first index in the CF_REG list, and its number of items.
! - cfReg and cfRegP: same as above, but allocatable and used to pass CF data into mapping structure
! - cfweight: multiplier to the cost function
! - cfread: according to cftype, decide if reading experimental data from file for cost function
! - ncfdata: number of experimental data points read from file for each cost function
! - cfdata(nncf,3,300): stores the experimental data points for each cost function
!   column 1 stores the curvilinear spatial coordinate (e.g. along OMP or target)
!   column 2 stores the experimental data value
!   column 3 stores the uncertianty
! - nvmx: maximum number of variables that can be used for optimization
! - nsigmx: maximum number of sigma values used in the Bayesian MAP cost function
! - nsigma: actual number of sigmas read and used for Bayesian MAP
! - prior_type: type of prior for each design parameter optimized in the MAP estimation
! - prior_par: parameters related to the type of prior (e.g. standard deviation for gaussian prior)
! - prior_range: range of validity of the prior, outside this interval the MAP cost function returns NaN
! - scale_sigma: tells of the sigma in the MAP cost function is intended as relative (true) or absolute (false)
! - mapToOMP: according to cftype, decide if cost function data is to be re-mapped to the OMP 
! - read_sigma: tells to read or not the experimental data uncertainty
! - sigma: stores the values of the standard deviation in  the MAP cost function
! - inf_opt: parameter that defines an 'infinity' bound for optimization variables (e.g. prior range)
  INTEGER, PARAMETER :: mxncf=1000
  INTEGER :: cfstart(nncf), cfend(nncf), cftype(nncf)
  LOGICAL, SAVE :: cfread(nncf)=.false.
  INTEGER, SAVE :: cfdef(nncf)
  INTEGER, SAVE :: ncfdata(nncf), ncf, cf_reg(mxncf), cf_regp(nncf, 2)
  REAL(kind=r8), SAVE :: cfdata(nncf, 3, 300), cfweight(nncf)
  INTEGER :: nvmx, nsigmx
  PARAMETER (nvmx=50, nsigmx=10)
!sc type of prior
  INTEGER, SAVE :: prior_type(nvmx), nsigma
!parameters for prior
  REAL(kind=r8), SAVE :: prior_par(nvmx, 2), prior_range(nvmx, 2)
  LOGICAL, SAVE :: scale_sigma(nsigmx)=.true.
  LOGICAL, SAVE :: maptoomp(nncf)=.false.
  LOGICAL, SAVE :: read_sigma(nncf)=.false.
  REAL(kind=r8), SAVE :: sigma(nsigmx)=0.0_R8
  REAL(kind=r8), SAVE :: sigmab(nsigmx)=0.D0
  DOUBLE PRECISION, PARAMETER :: inf_opt=1.0e30
  CHARACTER(len=8) :: gpfrgrp(npfrgrpd), gntrgrp(nntrgrpd)
  CHARACTER(len=80) :: user_filename
  LOGICAL :: scale_he, print_isat
  LOGICAL, SAVE :: user_namelist_used=.true.
  LOGICAL, SAVE :: written=.false.
  LOGICAL, SAVE :: write_nml_user=.false.
  LOGICAL, SAVE :: user_initialised=.false.
  PRIVATE :: user
  NAMELIST /user/ lhetrgts, lpfrb_i, lpfrb_o, lpfrt_i, lpfrt_o, j_h_at, &
&     j_he_at, j_ne_at, l_h_mol, fusion_power, spmp_he_to_d, lpfrs_pmp, &
&     npfrgrp, lpfrgrp, ipfrgrp, jpfrgrp, gpfrgrp, nntrgrp, lntrgrp, &
&     intrgrp, jntrgrp, gntrgrp, spmp_nom, scale_he, print_isat, &
&     write_nml_user, filedata, user_filename, ncf, cfstart, cfend, &
&     cftype, rzomp, rzimp, cfdef, cfweight, prior_type, prior_par, &
&     prior_range, scale_sigma, nsigma, sigma, cf_reg, cf_regp, maptoomp&
&     , read_sigma

CONTAINS
!  Differentiation of alloc_b2mod_user as a context to call adjoint code (with options context noISIZE r8):
!   Plus diff mem management of: b2voloncf:in-out b2data:in-out
!                b2dataoncf:in-out m.cffcor:in-out geo.cvx:in geo.cvy:in
!                geo.vxx:in geo.vxy:in
!----------------------------------------------------------------------
!*** fusion_power : fusion power (including neutrons) [MW]
!*** Spmp_He_to_D : ratio of He to DT pumping speeds (typically, 0.8)
!*** lhetrgts  :  list of surface indices (EIRENE notation) which
!***              are used for calculation of helium enrichment
!*** lpfrb_[io]:  B2 x-cell indices corresponding to the bottom of the
!***              bypass between the inner and outer divertor (counted
!***              from the bottom, if non-positive)
!*** lpfrt_[io]:  B2 x-cell indices corresponding to the top of the
!***              bypass between the inner and outer divertor (counted
!***              from the x-point, if non-positive)
!*** j_h_at    :  Hydrogen isotope index in EIRENE atoms list
!*** j_he_at   :  Helium index in EIRENE atoms list
!*** j_ne_at   :  Neon index in EIRENE atoms list
!*** l_h_mol   :  Hydrogen isotope content in the molecules
!*** lpfrs_pmp :  Location of the pump.
!***              0 no pump at all, 1 - lower PFR, 2 - lower outer
!*** npfrgrpd  :  max. number of surface groups for PFR flows
!*** npfrgrp   :  actual number of surface groups for PFR flows
!*** lpfrgrp   :  list of surface segments for PFR flows
!*** [ij]pfrgrp:  first and last positions in this list for each group
!*** gpfrgrp   :  identifiers for the PFR surface groups
!*** nntrgrpd  :  max. number of surface groups for neutral data
!*** nntrgrp   :  actual number of surface groups for neutral data
!*** lntrgrp   :  list of surface segments for neutral data
!*** [ij]ntrgrp:  first and last positions in this list for each group
!*** gntrgrp   :  identifiers for the neutral data surface groups
!*** filedata  :  flag to turn on/off individual tracing files
!***              (see b2mod_diag for their definition)
! FIXME add description of Cf quantities
!----------------------------------------------------------------------
!
!
  SUBROUTINE ALLOC_B2MOD_USER_B(geo, geob, m, mb, ns, nlim, nmol, ntns)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ns, nlim, nmol, ntns
    TYPE(GEOMETRY), INTENT(IN) :: geo
    TYPE(GEOMETRY) :: geob
    TYPE(MAPPING), INTENT(INOUT) :: m
    TYPE(MAPPING_DIFF), INTENT(INOUT) :: mb
!
    CALL XERTST(1 .LE. ns, 'faulty argument ns')
    CALL XERTST(0 .LE. nlim, 'faulty argument nlim')
    CALL XERTST(0 .LE. nmol, 'faulty argument nmol')
    CALL XERTST(0 .LE. ntns, 'faulty argument ntns')
    IF (user_initialised) THEN
      RETURN
    ELSE
!
!*** PFR specification - for He enrichment and neutral pressure
!***  Standard set-up:
! no pumping
      lpfrs_pmp = 0
! no helium
      fusion_power = 0.0_R8
! same pumping speed for He and D
      spmp_he_to_d = 1.0_R8
      spmp_nom = 0.0_R8
      j_h_at = 0
      l_h_mol = 0
      j_he_at = 0
      j_ne_at = 0
      lpfrb_i = 0
      lpfrb_o = 0
      lpfrt_i = 0
      lpfrt_o = 0
      npfrgrp = 0
      ipfrgrp = 0
      jpfrgrp = 0
      nntrgrp = 0
      intrgrp = 0
      jntrgrp = 0
      lhetrgts(1:nhetrgtx) = 0
      lhetrgts(1:nsts) = -ltns(1:nsts)
      gpfrgrp = ' '
      gntrgrp = ' '
      scale_he = .false.
      print_isat = .false.
      user_filename = 'b2.user.parameters'
      ncf = 0
      cfstart = 0
      cfend = 0
      cfdef = 0
      cftype = 0
      cfdata = 0.0_R8
      ncfdata = 0
      read_sigma = .false.
      rzomp = 0.0_R8
      rzimp = 0.0_R8
      cfweight = 1.0_R8
      nsigma = 0
      scale_sigma = .true.
      prior_type = -1
      prior_par = -1.0_R8
! sc  Set prior range to (-inf,+inf)
      prior_range(:, 1) = -(inf_opt*10.0)
      prior_range(:, 2) = inf_opt*10.0
      cf_reg = 0
      cf_regp = 0
      maptoomp = .false.
      CALL READ_B2MOD_USER_NAMELIST_B(ns, ntns, geo, geob, m, mb)
      user_initialised = .true.
!
      RETURN
    END IF
  END SUBROUTINE ALLOC_B2MOD_USER_B

!----------------------------------------------------------------------
!*** fusion_power : fusion power (including neutrons) [MW]
!*** Spmp_He_to_D : ratio of He to DT pumping speeds (typically, 0.8)
!*** lhetrgts  :  list of surface indices (EIRENE notation) which
!***              are used for calculation of helium enrichment
!*** lpfrb_[io]:  B2 x-cell indices corresponding to the bottom of the
!***              bypass between the inner and outer divertor (counted
!***              from the bottom, if non-positive)
!*** lpfrt_[io]:  B2 x-cell indices corresponding to the top of the
!***              bypass between the inner and outer divertor (counted
!***              from the x-point, if non-positive)
!*** j_h_at    :  Hydrogen isotope index in EIRENE atoms list
!*** j_he_at   :  Helium index in EIRENE atoms list
!*** j_ne_at   :  Neon index in EIRENE atoms list
!*** l_h_mol   :  Hydrogen isotope content in the molecules
!*** lpfrs_pmp :  Location of the pump.
!***              0 no pump at all, 1 - lower PFR, 2 - lower outer
!*** npfrgrpd  :  max. number of surface groups for PFR flows
!*** npfrgrp   :  actual number of surface groups for PFR flows
!*** lpfrgrp   :  list of surface segments for PFR flows
!*** [ij]pfrgrp:  first and last positions in this list for each group
!*** gpfrgrp   :  identifiers for the PFR surface groups
!*** nntrgrpd  :  max. number of surface groups for neutral data
!*** nntrgrp   :  actual number of surface groups for neutral data
!*** lntrgrp   :  list of surface segments for neutral data
!*** [ij]ntrgrp:  first and last positions in this list for each group
!*** gntrgrp   :  identifiers for the neutral data surface groups
!*** filedata  :  flag to turn on/off individual tracing files
!***              (see b2mod_diag for their definition)
! FIXME add description of Cf quantities
!----------------------------------------------------------------------
!
!
  SUBROUTINE ALLOC_B2MOD_USER(geo, m, ns, nlim, nmol, ntns)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ns, nlim, nmol, ntns
    TYPE(GEOMETRY), INTENT(IN) :: geo
    TYPE(MAPPING), INTENT(INOUT) :: m
!
    CALL XERTST(1 .LE. ns, 'faulty argument ns')
    CALL XERTST(0 .LE. nlim, 'faulty argument nlim')
    CALL XERTST(0 .LE. nmol, 'faulty argument nmol')
    CALL XERTST(0 .LE. ntns, 'faulty argument ntns')
    IF (user_initialised) THEN
      RETURN
    ELSE
!
!*** PFR specification - for He enrichment and neutral pressure
!***  Standard set-up:
! no pumping
      lpfrs_pmp = 0
! no helium
      fusion_power = 0.0_R8
! same pumping speed for He and D
      spmp_he_to_d = 1.0_R8
      spmp_nom = 0.0_R8
      j_h_at = 0
      l_h_mol = 0
      j_he_at = 0
      j_ne_at = 0
      lpfrb_i = 0
      lpfrb_o = 0
      lpfrt_i = 0
      lpfrt_o = 0
      npfrgrp = 0
      ipfrgrp = 0
      jpfrgrp = 0
      nntrgrp = 0
      intrgrp = 0
      jntrgrp = 0
      lhetrgts(1:nhetrgtx) = 0
      lhetrgts(1:nsts) = -ltns(1:nsts)
      gpfrgrp = ' '
      gntrgrp = ' '
      scale_he = .false.
      print_isat = .false.
      user_filename = 'b2.user.parameters'
      ncf = 0
      cfstart = 0
      cfend = 0
      cfdef = 0
      cftype = 0
      cfdata = 0.0_R8
      ncfdata = 0
      read_sigma = .false.
      rzomp = 0.0_R8
      rzimp = 0.0_R8
      cfweight = 1.0_R8
      nsigma = 0
      scale_sigma = .true.
      prior_type = -1
      prior_par = -1.0_R8
! sc  Set prior range to (-inf,+inf)
      prior_range(:, 1) = -(inf_opt*10.0)
      prior_range(:, 2) = inf_opt*10.0
      cf_reg = 0
      cf_regp = 0
      maptoomp = .false.
      CALL READ_B2MOD_USER_NAMELIST(ns, ntns, geo, m)
      user_initialised = .true.
!
      RETURN
    END IF
  END SUBROUTINE ALLOC_B2MOD_USER

!  Differentiation of dealloc_b2mod_user as a context to call adjoint code (with options context noISIZE r8):
!   Plus diff mem management of: b2voloncf:out b2data:out b2dataoncf:out
!
  SUBROUTINE DEALLOC_B2MOD_USER_B()
    IMPLICIT NONE
    INTRINSIC ALLOCATED
    IF (ALLOCATED(b2rr)) THEN
      DEALLOCATE(b2rr)
    END IF
    IF (ALLOCATED(b2voloncf)) THEN
      IF (ALLOCATED(b2voloncfb)) THEN
        DEALLOCATE(b2voloncfb)
      END IF
      DEALLOCATE(b2voloncf)
    END IF
    IF (ALLOCATED(b2data)) THEN
      IF (ALLOCATED(b2datab)) THEN
        DEALLOCATE(b2datab)
      END IF
      DEALLOCATE(b2data)
    END IF
    IF (ALLOCATED(b2dataoncf)) THEN
      IF (ALLOCATED(b2dataoncfb)) THEN
        DEALLOCATE(b2dataoncfb)
      END IF
      DEALLOCATE(b2dataoncf)
    END IF
    user_initialised = .false.
    RETURN
  END SUBROUTINE DEALLOC_B2MOD_USER_B

!
  SUBROUTINE DEALLOC_B2MOD_USER()
    IMPLICIT NONE
    INTRINSIC ALLOCATED
    IF (ALLOCATED(b2rr)) THEN
      DEALLOCATE(b2rr)
    END IF
    IF (ALLOCATED(b2voloncf)) THEN
      DEALLOCATE(b2voloncf)
    END IF
    IF (ALLOCATED(b2data)) THEN
      DEALLOCATE(b2data)
    END IF
    IF (ALLOCATED(b2dataoncf)) THEN
      DEALLOCATE(b2dataoncf)
    END IF
    user_initialised = .false.
    RETURN
  END SUBROUTINE DEALLOC_B2MOD_USER

!  Differentiation of read_b2mod_user_namelist as a context to call adjoint code (with options context noISIZE r8):
!   Plus diff mem management of: b2voloncf:in-out b2data:in-out
!                b2dataoncf:in-out m.cffcor:in-out geo.cvx:in geo.cvy:in
!                geo.vxx:in geo.vxy:in
!
  SUBROUTINE READ_B2MOD_USER_NAMELIST_B(ns, ntns, geo, geob, m, mb)
    USE B2MOD_B2CMPA_DIFF
    USE B2MOD_SUBSYS
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ns, ntns
    TYPE(GEOMETRY), INTENT(IN) :: geo
    TYPE(GEOMETRY) :: geob
    TYPE(MAPPING), INTENT(INOUT) :: m
    TYPE(MAPPING_DIFF), INTENT(INOUT) :: mb
    INTEGER :: ic, noss, iss, indss, ncffc, incf, idb, icf, ic1, ic2, &
&   icff, icv, ifc, ifcc, ifc1, ifc2, ifs, ii, ifc11, ifc22, jj
!
    LOGICAL :: file_ok
    CHARACTER(len=260) :: filename, cffile
    CHARACTER(len=1) :: str
    INTEGER :: i, ndata
    INTEGER, ALLOCATABLE :: cfreg(:)
    LOGICAL :: done, ifail, found
    INTEGER, SAVE :: use_eirene, neutrals_namelist
    EXTERNAL IPGETI, FIND_FILE, XERTST
    INTRINSIC TRIM
    EXTERNAL XERRAB
    INTRINSIC MIN
    INTRINSIC MAX
    INTRINSIC ANY
    EXTERNAL ANY_B
    INTRINSIC ALLOCATED
    INTRINSIC MAXVAL
    EXTERNAL MAXVAL_B
    INTRINSIC SIZE
    LOGICAL :: ANY_B
!
    CALL SUBINI('readuser')
    CALL IPGETI('b2mndr_eirene', use_eirene)
    CALL IPGETI('b2stbr_neutrals_namelist', neutrals_namelist)
!
!  -- USER --
    filename = user_filename
    CALL FIND_FILE(filename, file_ok)
    IF (file_ok) THEN
      OPEN(99, file=filename) 
      WRITE(*, *) 'Reading namelist user from ', TRIM(filename)
      READ(99, user) 
      CLOSE(99) 
      WRITE(*, *) 'Read namelist user from ', TRIM(filename)
      user_namelist_used = .true.
    ELSE
      WRITE(*, *) 'No ', TRIM(filename)
      user_namelist_used = .false.
      filedata(ntrc_usr) = .false.
    END IF
!
    nomp = 0
!Need to add check for monotonicity in list
    omp = 0
! Define OMP list by finding CVs which are intersected by the rzomp segment
    CALL CV_INTERSECTIONS_NODIFF(m%ncv, geo, m, rzomp, omp, nomp, nromp&
&                          , 1, ifail)
    CALL XERTST(.NOT.ifail, 'Increase nromp in b2.user.parameters')
! Here we need to guarantee ordering of CVs. With classical grids the conversion
! is done such that CVs are ordered from left to right and bottom to top wrt
! the structured computational domain. With fully unstructured grids this is not guaranteed.
! IDEA: project the cell center onto the segment and order CVs based on distance wrt one of the segment's extremes
! SAME FOR IMP
    CALL XERTST(m%isclassicalgrid .EQ. 1, &
&         ' OMP list need to be revised for fully unstructured grids')
    DO ic=2,nomp
      IF (geo%cvx(omp(ic)) .LT. geo%cvx(omp(ic-1))) CALL XERRAB(&
&                                                  'OMP LIST NOT SORTED'&
&                                                        )
    END DO
!   ..Definition of separatrix position in OMP list (to be improved for DN)
! Separatrix is defined by checking when cvReg changes value inside the OMP list
    icsepomp = 0
    ic = 1
    found = .false.
    DO WHILE (ic .LE. nomp .AND. (.NOT.found))
      IF (m%cvreg(omp(ic)) .NE. m%cvreg(omp(ic+1))) THEN
        found = .true.
        icsepomp = ic + 1
      END IF
      ic = ic + 1
    END DO
!
    CALL XERTST(ncf .LE. nncf, 'increase nncf in b2mod_user_namelist')
    IF (ncf .GT. 0) THEN
      WRITE(*, *) ' Number of cost functions: ', ncf
      m%ncf = ncf
      m%mxncf = mxncf
      CALL ALLOC_MAPPING_CF_B(m, mb)
      m%cfregp = 0
      ALLOCATE(cfreg(mxncf))
      cfreg = 0
      OPEN(newunit=idb, file='debug_user.out') 
      incf = 0
      DO 100 icf=1,ncf
        IF (cftype(icf) .GT. 10) CALL XERRAB('cftype>10 not coded ')
        IF (cftype(1) .EQ. 0 .AND. ncf .EQ. 1) CALL XERRAB(&
&                  'cftype(1)=0 but no other cost functions are defined'&
&                                                   )
        IF (cftype(icf) .EQ. 0 .AND. icf .NE. 1) CALL XERRAB(&
&                                          'only cftype(1) should be =0'&
&                                                     )
        IF (cftype(icf) .EQ. 6 .AND. icf .NE. 1) CALL XERRAB(&
&                                          'only cftype(1) should be =6'&
&                                                     )
        IF ((cftype(icf) .EQ. 0 .OR. cftype(icf) .EQ. 6) .AND. ncf .LT. &
&           cfend(icf) - cfstart(icf) + 2) CALL XERRAB(&
&               'cost functions specified for sum with cftype 0/6 > nCf'&
&                                               )
        IF ((cftype(icf) .EQ. 0 .OR. cftype(icf) .EQ. 6) .AND. cfstart(&
&           icf) .LT. 2 .AND. cfend(icf) .LT. 2) CALL XERRAB(&
&                     'cost functions type 0/6 requires cfstart/cfend>1'&
&                                                     )
        IF ((cftype(icf) .GE. 1 .AND. cftype(icf) .LE. 3) .OR. (cftype(&
&           icf) .GE. 7 .AND. cftype(icf) .LE. 10)) cfread(icf) = .true.
        IF (cftype(icf) .EQ. 5) m%cfoncv(icf) = .false.
        IF (cftype(icf) .EQ. 5 .AND. cfdef(icf) .EQ. 3) CALL XERRAB(&
&                                'cftype 5 must be defined using faces!'&
&                                                            )
        IF (cfread(icf)) THEN
          WRITE(str, '(I1)') icf
          cffile = 'cf'//TRIM(str)//'.dat'
          CALL FIND_FILE(cffile, file_ok)
          IF (.NOT.file_ok) CALL XERRAB(&
&                                 'Cannot find cost function file '//&
&                                 TRIM(cffile))
          OPEN(unit=99, file=cffile, status='old', action='read') 
          WRITE(*, *) 'Reading cost function data from ', TRIM(cffile)
          ncfdata(icf) = 0
!csc File is of unknown length, so first count the number of lines
 5        READ(99, *, end=15) str
          ncfdata(icf) = ncfdata(icf) + 1
          GOTO 5
 15       CLOSE(99) 
          CALL XERTST(ncfdata(icf) .LE. 300, &
&               'Cost function data limited to DEF_NLIM!')
          OPEN(unit=99, file=cffile, status='old', action='read') 
          DO i=1,ncfdata(icf)
!csc The data in the file are (r-rsep), data, sigma. Stored in cfdata according to
!    first dimension (# of cost functions), second dimension ((r-rsep)-data-sigma), third
!    dimension (number of records/data points)
            IF (read_sigma(icf)) THEN
              READ(99, *) cfdata(icf, 1:3, i)
            ELSE
              READ(99, *) cfdata(icf, 1:2, i)
            END IF
          END DO
          CLOSE(99) 
        END IF
!no need to specify domain here
        IF (.NOT.(cftype(icf) .EQ. 0 .OR. cftype(icf) .EQ. 6)) THEN
          done = .false.
!
!
! FIXME need to add flag for reversing lists?
!
          SELECT CASE  (cfdef(icf)) 
          CASE (1) 
!
!defined on OMP (only internal CVs)
!
            CALL XERTST(m%cfoncv(icf), 'This cost function type '//&
&                 'cannot be evaluated on OMP')
            CALL XERTST(nomp .GT. 0, 'Asking for OMP cost function '//&
&                 'but no OMP cells, check rzomp')
            WRITE(*, *) ' defining cost function ', icf, ' on omp'
            DO icff=1,icf-1
              IF (cfdef(icff) .EQ. 1) THEN
                m%cfregp(icf, :) = m%cfregp(icff, :)
                done = .true.
              END IF
            END DO
            IF (done) THEN
              GOTO 100
            ELSE
              m%cfregp(icf, 1) = incf + 1
              ndata = 0
              DO icv=1,nomp
!only use internal CVs
                IF (omp(icv) .LE. m%nci) THEN
                  m%cfreg(incf+1+ndata) = omp(icv)
                  ndata = ndata + 1
                END IF
              END DO
              m%cfregp(icf, 2) = ndata
              incf = incf + ndata
            END IF
          CASE (2) 
!
!defined using fclabel
!
            CALL XERTST(cfstart(icf) .NE. 0 .AND. cfend(icf) .NE. 0, &
&                 'cfdef=2 requires cfstart/cfend>0')
! check if other CFs have same domain (must have same start/end, same type of definition (fcLabl)
! and also same type of domain (FcLabl can be used to identify either CVs or FCs)
            DO icff=1,icf-1
              IF (cfstart(icf) .EQ. cfstart(icff) .AND. cfend(icf) .EQ. &
&                 cfend(icff) .AND. cfdef(icff) .EQ. 2 .AND. (m%cfoncv(&
&                 icf) .AND. m%cfoncv(icff))) THEN
                m%cfregp(icf, :) = m%cfregp(icff, :)
                done = .true.
              END IF
            END DO
            IF (done) THEN
              GOTO 100
            ELSE
! this domain has not yet been done
              m%cfregp(icf, 1) = incf + 1
              ncffc = 0
              noss = cfend(icf) - cfstart(icf) + 1
              DO iss=1,noss
                indss = cfstart(icf) + iss - 1
                WRITE(*, *) ' Defining cost function ', icf
                WRITE(*, *) ' surface label ', indss
! find all faces belonging to surface structure INDSS
                CALL FIND_FACES_NODIFF(indss, incf, ncffc, m%mxncf, m%&
&                                cfreg, m%cffcor, m, idb)
              END DO
! iss	
              m%cfregp(icf, 2) = ncffc
! if cost function is on CV e.g. target for CV-based CF --> substitute FCs with linked CVs
              IF (m%cfoncv(icf)) THEN
                DO ifc=1,m%cfregp(icf, 2)
                  ifcc = m%cfreg(m%cfregp(icf, 1)+ifc-1)
                  IF (m%fccv(ifcc, 1) .GT. m%fccv(ifcc, 2)) THEN
                    ic1 = m%fccv(ifcc, 2)
                  ELSE
                    ic1 = m%fccv(ifcc, 1)
                  END IF
                  IF (m%fccv(ifcc, 1) .LT. m%fccv(ifcc, 2)) THEN
                    ic2 = m%fccv(ifcc, 2)
                  ELSE
                    ic2 = m%fccv(ifcc, 1)
                  END IF
                  IF (ic1 .LE. m%nci) THEN
                    m%cfreg(m%cfregp(icf, 1)+ifc-1) = ic1
                  ELSE IF (ic2 .LE. m%nci) THEN
                    m%cfreg(m%cfregp(icf, 1)+ifc-1) = ic2
                  ELSE
                    CALL XERRAB('cfdef=2 -- problem with boundary face')
                  END IF
                END DO
              END IF
            END IF
          CASE (3) 
!
!defined using cvlabel
!
            CALL XERTST(cfstart(icf) .NE. 0 .AND. cfend(icf) .NE. 0, &
&                 'cfdef=3 requires cfstart/cfend>0')
! check if other CFs have same domain !FIXME check if also cfdef is the same
            DO icff=1,icf-1
              IF (cfstart(icf) .EQ. cfstart(icff) .AND. cfend(icf) .EQ. &
&                 cfend(icff) .AND. cfdef(icff) .EQ. 3) THEN
                m%cfregp(icf, :) = m%cfregp(icff, :)
                done = .true.
              END IF
            END DO
            IF (done) THEN
              GOTO 100
            ELSE
! this domain has not yet been done
              m%cfregp(icf, 1) = incf + 1
              noss = cfend(icf) - cfstart(icf) + 1
              DO iss=1,noss
                indss = cfstart(icf) + iss - 1
                WRITE(*, *) ' Defining cost function ', icf
                WRITE(*, *) ' cell label ', indss
                DO icv=1,m%ncv
                  IF (m%cvlbl(icv) .EQ. indss) THEN
                    m%cfreg(incf+1) = icv
                    incf = incf + 1
                  END IF
                END DO
              END DO
! FIXME no attempt to sort or check if they belong together somehow
              m%cfregp(icf, 2) = incf + 1 - m%cfregp(icf, 1)
            END IF
          CASE (4) 
!
!defined using cf_reg (No attempt whatsoever to check if they are sorted)
!
            CALL XERTST(cf_regp(icf, 2) .GT. 0, 'cf_RegP not defined')
! csc can we check somehow if this has already been filled?
            m%cfregp(icf, 1) = incf + 1
            m%cfregp(icf, 2) = cf_regp(icf, 2)
            IF (ANY(cf_reg(cf_regp(icf, 1):cf_regp(icf, 1)+cf_regp(icf, &
&               2)-1) .LE. 0)) CALL XERRAB('cf_Reg<=0')
            m%cfreg(incf+1:incf+1+m%cfregp(icf, 2)-1) = cf_reg(cf_regp(&
&             icf, 1):cf_regp(icf, 1)+cf_regp(icf, 2)-1)
            incf = incf + cf_regp(icf, 2)
          CASE DEFAULT
!
!
            CALL XERRAB('cfDef undefined')
          END SELECT
!
          CALL XERTST(incf + 1 .LE. m%mxncf, &
&               'Increase size of mxnCf in b2mod_user_namelist')
        END IF
 100  CONTINUE
!icf
      CLOSE(idb) 
      IF (ALLOCATED(cfreg)) THEN
        DEALLOCATE(cfreg)
      END IF
    END IF
!
    IF (ANY(cftype .EQ. 6)) THEN
      CALL XERTST(nsigma .GT. 0 .AND. nsigma .LE. nsigmx, &
&           'b2mod_user_namelist: nsigma<=0 or nsigma>nsigmx')
! sc  prior_type refers to the prior type for the design variables:
!     0 - Uniform distribution.
!     1 - Uninformative, proper, Gaussian prior.
!     2 - Jeffrey's 1/sigma (only for sigma!!)
      CALL XERTST(ANY(prior_type(1:nsigma) .GE. 0) .AND. ANY(prior_type(&
&           1:nsigma) .LE. 2), &
&           'b2mod_user_namelist: prior_type<=0 or prior_type>=2')
! sc  prior_par refers to the prior parameters:
!     For prior_type = 1, prior_par(ii,1) = mu, prior_par(ii,2) = sigma
!     For prior_type = 2, not used?
      DO icf=1,nsigma
        IF (prior_type(icf) .EQ. 1) CALL XERTST(prior_par(icf, 2) .GT. &
&                                         0.0_R8, &
&                                 'b2mod_user_namelist: sigma prior <=0'&
&                                        )
        CALL XERTST(prior_range(icf, 1) .LT. prior_range(icf, 2), &
&             'b2mod_user_namelist: prior_range(.,1)>prior_range(.,2)')
      END DO
    END IF
! now allocate vector that will be used to interpolate solps onto data grid
    IF (ANY(cfread)) THEN
      ndata = MAXVAL(ncfdata(1:ncf), 1)
      ALLOCATE(b2voloncfb(ncf, ndata))
      b2voloncfb = 0.D0
      ALLOCATE(b2voloncf(ncf, ndata))
!stores interpolated B2.5 volumes onto CF radial points
      ALLOCATE(b2dataoncfb(ndata))
      b2dataoncfb = 0.D0
      ALLOCATE(b2dataoncf(ndata))
!variable to store SOLPS data interpolated onto CF radial points
!max number of CVs in a cost function
      ndata = MAXVAL(m%cfregp(1:ncf, 2))
      ALLOCATE(b2rr(ncf, ndata))
!store here radial distance coordiante of SOLPS data
      ALLOCATE(b2datab(ndata))
      b2datab = 0.D0
      ALLOCATE(b2data(ndata))
!temporary variable to store SOLPS data for interpolation
      b2rr = 0.0_R8
      b2voloncf = 0.0_R8
      b2data = 0.0
      b2dataoncf = 0.0
    END IF
!
!   ..Create list of IMP control volumes
! Same logic as OMP list, find CVs intersected by rzimp segment
    nimp = 0
    imp = 0
    CALL CV_INTERSECTIONS_NODIFF(m%ncv, geo, m, rzimp, imp, nimp, nromp&
&                          , 1, ifail)
    CALL XERTST(.NOT.ifail, 'Increase nromp in b2.user.parameters')
    DO ic=2,nimp
      IF (geo%cvx(imp(ic)) .LT. geo%cvx(imp(ic-1))) CALL XERRAB(&
&                                                  'IMP LIST NOT SORTED'&
&                                                        )
    END DO
! Find position of separatrix in IMP list (same as for OMP)
    icsepimp = 0
    ic = 1
    found = .false.
    DO WHILE (ic .LE. nimp .AND. (.NOT.found))
      IF (m%cvreg(imp(ic)) .NE. m%cvreg(imp(ic+1))) THEN
        found = .true.
        icsepimp = ic + 1
      END IF
      ic = ic + 1
    END DO
    IF (.NOT.found) THEN
      WRITE(*, *) 'Warning: did not find separatrix in IMP definition'
      WRITE(*, *) 'check specification of RZIMP in b2.user.parameters'
      WRITE(*, *) 'if IMP is needed.'
    END IF
!flux surface of separatrix
    ifssep = 1
    found = .false.
!cv of flux tube just inside sep
    ic1 = omp(icsepomp-1)
!cv of flux tube just outside sep
    ic2 = omp(icsepomp)
    ifc1 = m%cvfcp(ic1, 1)
    ifc2 = ifc1 + m%cvfcp(ic1, 2) - 1
    ifc11 = m%cvfcp(ic2, 1)
! find face belonging to both ic1 and ic2
    ifc22 = ifc11 + m%cvfcp(ic2, 2) - 1
    DO ii=ifc1,ifc2
      ifc = m%cvfc(ii)
      DO jj=ifc11,ifc22
        ifcc = m%cvfc(jj)
        IF (ifc .EQ. ifcc) EXIT
      END DO
    END DO
! find this face in fsFc --> ii
    DO ii=1,SIZE(m%fsfc, 1)
      IF (ifc .EQ. m%fsfc(ii)) EXIT
    END DO
! find ii in fsFcP(ifs,1):fsFcP(ifs,1)+fsFcP(ifs,2)
    DO ifs=1,SIZE(m%fsfcp, 1)
      ifc1 = m%fsfcp(ifs, 1)
      ifc2 = ifc1 + m%fsfcp(ifs, 2) - 1
      IF (ii .GE. ifc1 .AND. ii .LE. ifc2) GOTO 110
    END DO
    GOTO 120
 110 found = .true.
 120 IF (.NOT.found) CALL XERRAB('No flux surface found for separatrix!'&
&                         )
    ifssep = ifs
    IF (m%isclassicalgrid .EQ. 1) CALL XERTST(m%fsfcp(ifssep, 2) .GT. 0&
&                                       , 'No separatrix faces!')
    WRITE(*, *) 'SEPARATRIX FLUX SURFACE AT ifs=', ifssep
!
    CALL SUBEND()
    RETURN
  END SUBROUTINE READ_B2MOD_USER_NAMELIST_B

!
  SUBROUTINE READ_B2MOD_USER_NAMELIST(ns, ntns, geo, m)
    USE B2MOD_B2CMPA_DIFF
    USE B2MOD_SUBSYS
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ns, ntns
    TYPE(GEOMETRY), INTENT(IN) :: geo
    TYPE(MAPPING), INTENT(INOUT) :: m
    INTEGER :: ic, noss, iss, indss, ncffc, incf, idb, icf, ic1, ic2, &
&   icff, icv, ifc, ifcc, ifc1, ifc2, ifs, ii, ifc11, ifc22, jj
!
    LOGICAL :: file_ok
    CHARACTER(len=260) :: filename, cffile
    CHARACTER(len=1) :: str
    INTEGER :: i, ndata
    INTEGER, ALLOCATABLE :: cfreg(:)
    LOGICAL :: done, ifail, found
    INTEGER, SAVE :: use_eirene, neutrals_namelist
    EXTERNAL IPGETI, FIND_FILE, XERTST
    INTRINSIC TRIM
    EXTERNAL XERRAB
    INTRINSIC MIN
    INTRINSIC MAX
    INTRINSIC ANY
    INTRINSIC ALLOCATED
    INTRINSIC MAXVAL
    INTRINSIC SIZE
!
    CALL SUBINI('readuser')
    CALL IPGETI('b2mndr_eirene', use_eirene)
    CALL IPGETI('b2stbr_neutrals_namelist', neutrals_namelist)
!
!  -- USER --
    filename = user_filename
    CALL FIND_FILE(filename, file_ok)
    IF (file_ok) THEN
      OPEN(99, file=filename) 
      WRITE(*, *) 'Reading namelist user from ', TRIM(filename)
      READ(99, user) 
      CLOSE(99) 
      WRITE(*, *) 'Read namelist user from ', TRIM(filename)
      user_namelist_used = .true.
    ELSE
      WRITE(*, *) 'No ', TRIM(filename)
      user_namelist_used = .false.
      filedata(ntrc_usr) = .false.
    END IF
!
    nomp = 0
!Need to add check for monotonicity in list
    omp = 0
! Define OMP list by finding CVs which are intersected by the rzomp segment
    CALL CV_INTERSECTIONS_NODIFF(m%ncv, geo, m, rzomp, omp, nomp, nromp&
&                          , 1, ifail)
    CALL XERTST(.NOT.ifail, 'Increase nromp in b2.user.parameters')
! Here we need to guarantee ordering of CVs. With classical grids the conversion
! is done such that CVs are ordered from left to right and bottom to top wrt
! the structured computational domain. With fully unstructured grids this is not guaranteed.
! IDEA: project the cell center onto the segment and order CVs based on distance wrt one of the segment's extremes
! SAME FOR IMP
    CALL XERTST(m%isclassicalgrid .EQ. 1, &
&         ' OMP list need to be revised for fully unstructured grids')
    DO ic=2,nomp
      IF (geo%cvx(omp(ic)) .LT. geo%cvx(omp(ic-1))) CALL XERRAB(&
&                                                  'OMP LIST NOT SORTED'&
&                                                        )
    END DO
!   ..Definition of separatrix position in OMP list (to be improved for DN)
! Separatrix is defined by checking when cvReg changes value inside the OMP list
    icsepomp = 0
    ic = 1
    found = .false.
    DO WHILE (ic .LE. nomp .AND. (.NOT.found))
      IF (m%cvreg(omp(ic)) .NE. m%cvreg(omp(ic+1))) THEN
        found = .true.
        icsepomp = ic + 1
      END IF
      ic = ic + 1
    END DO
!
    CALL XERTST(ncf .LE. nncf, 'increase nncf in b2mod_user_namelist')
    IF (ncf .GT. 0) THEN
      WRITE(*, *) ' Number of cost functions: ', ncf
      m%ncf = ncf
      m%mxncf = mxncf
      CALL ALLOC_MAPPING_CF(m)
      m%cfregp = 0
      ALLOCATE(cfreg(mxncf))
      cfreg = 0
      OPEN(newunit=idb, file='debug_user.out') 
      incf = 0
      DO 100 icf=1,ncf
        IF (cftype(icf) .GT. 10) CALL XERRAB('cftype>10 not coded ')
        IF (cftype(1) .EQ. 0 .AND. ncf .EQ. 1) CALL XERRAB(&
&                  'cftype(1)=0 but no other cost functions are defined'&
&                                                   )
        IF (cftype(icf) .EQ. 0 .AND. icf .NE. 1) CALL XERRAB(&
&                                          'only cftype(1) should be =0'&
&                                                     )
        IF (cftype(icf) .EQ. 6 .AND. icf .NE. 1) CALL XERRAB(&
&                                          'only cftype(1) should be =6'&
&                                                     )
        IF ((cftype(icf) .EQ. 0 .OR. cftype(icf) .EQ. 6) .AND. ncf .LT. &
&           cfend(icf) - cfstart(icf) + 2) CALL XERRAB(&
&               'cost functions specified for sum with cftype 0/6 > nCf'&
&                                               )
        IF ((cftype(icf) .EQ. 0 .OR. cftype(icf) .EQ. 6) .AND. cfstart(&
&           icf) .LT. 2 .AND. cfend(icf) .LT. 2) CALL XERRAB(&
&                     'cost functions type 0/6 requires cfstart/cfend>1'&
&                                                     )
        IF ((cftype(icf) .GE. 1 .AND. cftype(icf) .LE. 3) .OR. (cftype(&
&           icf) .GE. 7 .AND. cftype(icf) .LE. 10)) cfread(icf) = .true.
        IF (cftype(icf) .EQ. 5) m%cfoncv(icf) = .false.
        IF (cftype(icf) .EQ. 5 .AND. cfdef(icf) .EQ. 3) CALL XERRAB(&
&                                'cftype 5 must be defined using faces!'&
&                                                            )
        IF (cfread(icf)) THEN
          WRITE(str, '(I1)') icf
          cffile = 'cf'//TRIM(str)//'.dat'
          CALL FIND_FILE(cffile, file_ok)
          IF (.NOT.file_ok) CALL XERRAB(&
&                                 'Cannot find cost function file '//&
&                                 TRIM(cffile))
          OPEN(unit=99, file=cffile, status='old', action='read') 
          WRITE(*, *) 'Reading cost function data from ', TRIM(cffile)
          ncfdata(icf) = 0
!csc File is of unknown length, so first count the number of lines
 5        READ(99, *, end=15) str
          ncfdata(icf) = ncfdata(icf) + 1
          GOTO 5
 15       CLOSE(99) 
          CALL XERTST(ncfdata(icf) .LE. 300, &
&               'Cost function data limited to DEF_NLIM!')
          OPEN(unit=99, file=cffile, status='old', action='read') 
          DO i=1,ncfdata(icf)
!csc The data in the file are (r-rsep), data, sigma. Stored in cfdata according to
!    first dimension (# of cost functions), second dimension ((r-rsep)-data-sigma), third
!    dimension (number of records/data points)
            IF (read_sigma(icf)) THEN
              READ(99, *) cfdata(icf, 1:3, i)
            ELSE
              READ(99, *) cfdata(icf, 1:2, i)
            END IF
          END DO
          CLOSE(99) 
        END IF
!no need to specify domain here
        IF (.NOT.(cftype(icf) .EQ. 0 .OR. cftype(icf) .EQ. 6)) THEN
          done = .false.
!
!
! FIXME need to add flag for reversing lists?
!
          SELECT CASE  (cfdef(icf)) 
          CASE (1) 
!
!defined on OMP (only internal CVs)
!
            CALL XERTST(m%cfoncv(icf), 'This cost function type '//&
&                 'cannot be evaluated on OMP')
            CALL XERTST(nomp .GT. 0, 'Asking for OMP cost function '//&
&                 'but no OMP cells, check rzomp')
            WRITE(*, *) ' defining cost function ', icf, ' on omp'
            DO icff=1,icf-1
              IF (cfdef(icff) .EQ. 1) THEN
                m%cfregp(icf, :) = m%cfregp(icff, :)
                done = .true.
              END IF
            END DO
            IF (done) THEN
              GOTO 100
            ELSE
              m%cfregp(icf, 1) = incf + 1
              ndata = 0
              DO icv=1,nomp
!only use internal CVs
                IF (omp(icv) .LE. m%nci) THEN
                  m%cfreg(incf+1+ndata) = omp(icv)
                  ndata = ndata + 1
                END IF
              END DO
              m%cfregp(icf, 2) = ndata
              incf = incf + ndata
            END IF
          CASE (2) 
!
!defined using fclabel
!
            CALL XERTST(cfstart(icf) .NE. 0 .AND. cfend(icf) .NE. 0, &
&                 'cfdef=2 requires cfstart/cfend>0')
! check if other CFs have same domain (must have same start/end, same type of definition (fcLabl)
! and also same type of domain (FcLabl can be used to identify either CVs or FCs)
            DO icff=1,icf-1
              IF (cfstart(icf) .EQ. cfstart(icff) .AND. cfend(icf) .EQ. &
&                 cfend(icff) .AND. cfdef(icff) .EQ. 2 .AND. (m%cfoncv(&
&                 icf) .AND. m%cfoncv(icff))) THEN
                m%cfregp(icf, :) = m%cfregp(icff, :)
                done = .true.
              END IF
            END DO
            IF (done) THEN
              GOTO 100
            ELSE
! this domain has not yet been done
              m%cfregp(icf, 1) = incf + 1
              ncffc = 0
              noss = cfend(icf) - cfstart(icf) + 1
              DO iss=1,noss
                indss = cfstart(icf) + iss - 1
                WRITE(*, *) ' Defining cost function ', icf
                WRITE(*, *) ' surface label ', indss
! find all faces belonging to surface structure INDSS
                CALL FIND_FACES_NODIFF(indss, incf, ncffc, m%mxncf, m%&
&                                cfreg, m%cffcor, m, idb)
              END DO
! iss	
              m%cfregp(icf, 2) = ncffc
! if cost function is on CV e.g. target for CV-based CF --> substitute FCs with linked CVs
              IF (m%cfoncv(icf)) THEN
                DO ifc=1,m%cfregp(icf, 2)
                  ifcc = m%cfreg(m%cfregp(icf, 1)+ifc-1)
                  IF (m%fccv(ifcc, 1) .GT. m%fccv(ifcc, 2)) THEN
                    ic1 = m%fccv(ifcc, 2)
                  ELSE
                    ic1 = m%fccv(ifcc, 1)
                  END IF
                  IF (m%fccv(ifcc, 1) .LT. m%fccv(ifcc, 2)) THEN
                    ic2 = m%fccv(ifcc, 2)
                  ELSE
                    ic2 = m%fccv(ifcc, 1)
                  END IF
                  IF (ic1 .LE. m%nci) THEN
                    m%cfreg(m%cfregp(icf, 1)+ifc-1) = ic1
                  ELSE IF (ic2 .LE. m%nci) THEN
                    m%cfreg(m%cfregp(icf, 1)+ifc-1) = ic2
                  ELSE
                    CALL XERRAB('cfdef=2 -- problem with boundary face')
                  END IF
                END DO
              END IF
            END IF
          CASE (3) 
!
!defined using cvlabel
!
            CALL XERTST(cfstart(icf) .NE. 0 .AND. cfend(icf) .NE. 0, &
&                 'cfdef=3 requires cfstart/cfend>0')
! check if other CFs have same domain !FIXME check if also cfdef is the same
            DO icff=1,icf-1
              IF (cfstart(icf) .EQ. cfstart(icff) .AND. cfend(icf) .EQ. &
&                 cfend(icff) .AND. cfdef(icff) .EQ. 3) THEN
                m%cfregp(icf, :) = m%cfregp(icff, :)
                done = .true.
              END IF
            END DO
            IF (done) THEN
              GOTO 100
            ELSE
! this domain has not yet been done
              m%cfregp(icf, 1) = incf + 1
              noss = cfend(icf) - cfstart(icf) + 1
              DO iss=1,noss
                indss = cfstart(icf) + iss - 1
                WRITE(*, *) ' Defining cost function ', icf
                WRITE(*, *) ' cell label ', indss
                DO icv=1,m%ncv
                  IF (m%cvlbl(icv) .EQ. indss) THEN
                    m%cfreg(incf+1) = icv
                    incf = incf + 1
                  END IF
                END DO
              END DO
! FIXME no attempt to sort or check if they belong together somehow
              m%cfregp(icf, 2) = incf + 1 - m%cfregp(icf, 1)
            END IF
          CASE (4) 
!
!defined using cf_reg (No attempt whatsoever to check if they are sorted)
!
            CALL XERTST(cf_regp(icf, 2) .GT. 0, 'cf_RegP not defined')
! csc can we check somehow if this has already been filled?
            m%cfregp(icf, 1) = incf + 1
            m%cfregp(icf, 2) = cf_regp(icf, 2)
            IF (ANY(cf_reg(cf_regp(icf, 1):cf_regp(icf, 1)+cf_regp(icf, &
&               2)-1) .LE. 0)) CALL XERRAB('cf_Reg<=0')
            m%cfreg(incf+1:incf+1+m%cfregp(icf, 2)-1) = cf_reg(cf_regp(&
&             icf, 1):cf_regp(icf, 1)+cf_regp(icf, 2)-1)
            incf = incf + cf_regp(icf, 2)
          CASE DEFAULT
!
!
            CALL XERRAB('cfDef undefined')
          END SELECT
!
          CALL XERTST(incf + 1 .LE. m%mxncf, &
&               'Increase size of mxnCf in b2mod_user_namelist')
        END IF
 100  CONTINUE
!icf
      CLOSE(idb) 
      IF (ALLOCATED(cfreg)) THEN
        DEALLOCATE(cfreg)
      END IF
    END IF
!
    IF (ANY(cftype .EQ. 6)) THEN
      CALL XERTST(nsigma .GT. 0 .AND. nsigma .LE. nsigmx, &
&           'b2mod_user_namelist: nsigma<=0 or nsigma>nsigmx')
! sc  prior_type refers to the prior type for the design variables:
!     0 - Uniform distribution.
!     1 - Uninformative, proper, Gaussian prior.
!     2 - Jeffrey's 1/sigma (only for sigma!!)
      CALL XERTST(ANY(prior_type(1:nsigma) .GE. 0) .AND. ANY(prior_type(&
&           1:nsigma) .LE. 2), &
&           'b2mod_user_namelist: prior_type<=0 or prior_type>=2')
! sc  prior_par refers to the prior parameters:
!     For prior_type = 1, prior_par(ii,1) = mu, prior_par(ii,2) = sigma
!     For prior_type = 2, not used?
      DO icf=1,nsigma
        IF (prior_type(icf) .EQ. 1) CALL XERTST(prior_par(icf, 2) .GT. &
&                                         0.0_R8, &
&                                 'b2mod_user_namelist: sigma prior <=0'&
&                                        )
        CALL XERTST(prior_range(icf, 1) .LT. prior_range(icf, 2), &
&             'b2mod_user_namelist: prior_range(.,1)>prior_range(.,2)')
      END DO
    END IF
! now allocate vector that will be used to interpolate solps onto data grid
    IF (ANY(cfread)) THEN
      ndata = MAXVAL(ncfdata(1:ncf), 1)
      ALLOCATE(b2voloncf(ncf, ndata))
!stores interpolated B2.5 volumes onto CF radial points
      ALLOCATE(b2dataoncf(ndata))
!variable to store SOLPS data interpolated onto CF radial points
!max number of CVs in a cost function
      ndata = MAXVAL(m%cfregp(1:ncf, 2))
      ALLOCATE(b2rr(ncf, ndata))
!store here radial distance coordiante of SOLPS data
      ALLOCATE(b2data(ndata))
!temporary variable to store SOLPS data for interpolation
      b2rr = 0.0_R8
      b2voloncf = 0.0_R8
      b2data = 0.0
      b2dataoncf = 0.0
    END IF
!
!   ..Create list of IMP control volumes
! Same logic as OMP list, find CVs intersected by rzimp segment
    nimp = 0
    imp = 0
    CALL CV_INTERSECTIONS_NODIFF(m%ncv, geo, m, rzimp, imp, nimp, nromp&
&                          , 1, ifail)
    CALL XERTST(.NOT.ifail, 'Increase nromp in b2.user.parameters')
    DO ic=2,nimp
      IF (geo%cvx(imp(ic)) .LT. geo%cvx(imp(ic-1))) CALL XERRAB(&
&                                                  'IMP LIST NOT SORTED'&
&                                                        )
    END DO
! Find position of separatrix in IMP list (same as for OMP)
    icsepimp = 0
    ic = 1
    found = .false.
    DO WHILE (ic .LE. nimp .AND. (.NOT.found))
      IF (m%cvreg(imp(ic)) .NE. m%cvreg(imp(ic+1))) THEN
        found = .true.
        icsepimp = ic + 1
      END IF
      ic = ic + 1
    END DO
    IF (.NOT.found) THEN
      WRITE(*, *) 'Warning: did not find separatrix in IMP definition'
      WRITE(*, *) 'check specification of RZIMP in b2.user.parameters'
      WRITE(*, *) 'if IMP is needed.'
    END IF
!flux surface of separatrix
    ifssep = 1
    found = .false.
!cv of flux tube just inside sep
    ic1 = omp(icsepomp-1)
!cv of flux tube just outside sep
    ic2 = omp(icsepomp)
    ifc1 = m%cvfcp(ic1, 1)
    ifc2 = ifc1 + m%cvfcp(ic1, 2) - 1
    ifc11 = m%cvfcp(ic2, 1)
! find face belonging to both ic1 and ic2
    ifc22 = ifc11 + m%cvfcp(ic2, 2) - 1
    DO 110 ii=ifc1,ifc2
      ifc = m%cvfc(ii)
      DO jj=ifc11,ifc22
        ifcc = m%cvfc(jj)
        IF (ifc .EQ. ifcc) GOTO 110
      END DO
 110 CONTINUE
! find this face in fsFc --> ii
    DO ii=1,SIZE(m%fsfc, 1)
      IF (ifc .EQ. m%fsfc(ii)) GOTO 120
    END DO
! find ii in fsFcP(ifs,1):fsFcP(ifs,1)+fsFcP(ifs,2)
 120 DO ifs=1,SIZE(m%fsfcp, 1)
      ifc1 = m%fsfcp(ifs, 1)
      ifc2 = ifc1 + m%fsfcp(ifs, 2) - 1
      IF (ii .GE. ifc1 .AND. ii .LE. ifc2) THEN
        found = .true.
        GOTO 130
      END IF
    END DO
 130 IF (.NOT.found) CALL XERRAB('No flux surface found for separatrix!'&
&                         )
    ifssep = ifs
    IF (m%isclassicalgrid .EQ. 1) CALL XERTST(m%fsfcp(ifssep, 2) .GT. 0&
&                                       , 'No separatrix faces!')
    WRITE(*, *) 'SEPARATRIX FLUX SURFACE AT ifs=', ifssep
!
    CALL SUBEND()
    RETURN
  END SUBROUTINE READ_B2MOD_USER_NAMELIST

!
  SUBROUTINE WRITE_B2MOD_USER_NAMELIST()
    IMPLICIT NONE
!
    IF (written) THEN
      RETURN
    ELSE
      IF (user_namelist_used .AND. write_nml_user) WRITE(*, user) 
      written = .true.
      RETURN
    END IF
  END SUBROUTINE WRITE_B2MOD_USER_NAMELIST

END MODULE B2MOD_USER_NAMELIST_DIFF

