!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
MODULE B2MOD_FIRST_FLIGHT_DIFF
  USE B2MOD_TYPES
  IMPLICIT NONE
!
!
  INTEGER, SAVE :: no_of_slices, size_of_table, no_of_start_points
  REAL(kind=r8), ALLOCATABLE, SAVE :: angle(:)
  INTEGER, ALLOCATABLE, SAVE :: cell(:, :), cellx(:), celly(:)
  INTEGER, ALLOCATABLE, SAVE :: table(:, :), index(:, :, :)
  INTEGER, SAVE :: ptr_table, ptr_index
  REAL(kind=r8), SAVE :: dl

CONTAINS
!
!
  SUBROUTINE ALLOC_B2MOD_FIRST_FLIGHT(in_no_of_slices, in_size_of_table&
&   , in_no_of_start_points, nx, ny, in_dl)
    USE B2MOD_CONSTANTS
    IMPLICIT NONE
    INTEGER :: in_no_of_slices, in_size_of_table, in_no_of_start_points&
&   , nx, ny
    REAL(kind=r8) :: t1, t2, in_dl
    INTEGER :: ia, ic, ix, iy
    INTRINSIC REAL
    INTRINSIC SIN
    INTRINSIC ASIN
    no_of_slices = in_no_of_slices
    size_of_table = in_size_of_table
    no_of_start_points = in_no_of_start_points
    ALLOCATE(angle(no_of_slices))
    t1 = -(pi/2.0_R8)
    DO ia=1,no_of_slices
      t2 = ASIN(REAL(ia)/REAL(no_of_slices)*2 + SIN(-(pi/2.0_R8)))
      angle(ia) = 0.5_R8*(t1+t2)
      t1 = t2
      WRITE(*, *) angle(ia)/pi*180
    END DO
    ALLOCATE(cell(-1:nx, -1:ny))
    ALLOCATE(cellx((nx+2)*(ny+2)))
    ALLOCATE(celly((nx+2)*(ny+2)))
    ic = 0
    DO ix=-1,nx
      DO iy=-1,ny
        ic = ic + 1
        cell(ix, iy) = ic
        cellx(ic) = ix
        celly(ic) = iy
      END DO
    END DO
    ALLOCATE(table(size_of_table, 0:1))
    ptr_table = 0
    ALLOCATE(index(no_of_start_points, no_of_slices, 0:1))
    ptr_index = 0
    dl = in_dl
  END SUBROUTINE ALLOC_B2MOD_FIRST_FLIGHT

!
  SUBROUTINE DEALLOC_B2MOD_FIRST_FLIGHT()
    IMPLICIT NONE
    INTRINSIC ALLOCATED
    IF (.NOT.ALLOCATED(angle)) THEN
      RETURN
    ELSE
      DEALLOCATE(angle)
      DEALLOCATE(cell)
      DEALLOCATE(cellx)
      DEALLOCATE(celly)
      DEALLOCATE(table)
      DEALLOCATE(index)
      RETURN
    END IF
  END SUBROUTINE DEALLOC_B2MOD_FIRST_FLIGHT

!
  SUBROUTINE SETUP_B2MOD_FIRST_FLIGHT(ix0, iy0, nx, ny, orientation, &
&   output)
    USE B2MOD_GEO_DIFF
    USE B2MOD_PLASMA_DIFF
    USE B2MOD_CONSTANTS
    USE B2MOD_SUBSYS
    IMPLICIT NONE
    INTEGER :: ix0, iy0, nx, ny, output
    INTEGER :: ix, iy, ia, curr, cnt, new
!
    REAL(kind=r8) :: t1, x, y, dx, dy
    LOGICAL :: inside
    CHARACTER(len=1) :: orientation
    EXTERNAL XERRAB
    INTRINSIC ATAN2
    INTRINSIC COS
    INTRINSIC SIN
!
    CALL SUBINI('setup_b2mod_first_flight')
    ptr_index = ptr_index + 1
    CALL XERTST(ptr_index .LE. no_of_start_points, &
&         'b2mod_first_flight: increase no_of_start_points')
    WRITE(6, '(a,2i4,1x,a1,1x,2i6)') 'setup_b2mod_first_flight: ', ix0, &
&   iy0, orientation, ptr_index, ptr_table
    DO ia=1,no_of_slices
      index(ptr_index, ia, 0) = 0
      index(ptr_index, ia, 1) = -1
      cnt = 0
      curr = -1
      new = -1
      ix = ix0
      iy = iy0
      IF (orientation .EQ. 'W') THEN
        t1 = ATAN2(cry(ix, iy, 2) - cry(ix, iy, 0), crx(ix, iy, 2) - crx&
&         (ix, iy, 0)) - pi/2e0_R8 + angle(ia)
        x = 0.5_R8*(crx(ix, iy, 2)+crx(ix, iy, 0))
        y = 0.5_R8*(cry(ix, iy, 2)+cry(ix, iy, 0))
      ELSE IF (orientation .EQ. 'E') THEN
        t1 = ATAN2(cry(ix, iy, 1) - cry(ix, iy, 3), crx(ix, iy, 1) - crx&
&         (ix, iy, 3)) - pi/2e0_R8 + angle(ia)
        x = 0.5_R8*(crx(ix, iy, 3)+crx(ix, iy, 1))
        y = 0.5_R8*(cry(ix, iy, 3)+cry(ix, iy, 1))
      ELSE IF (orientation .EQ. 'N') THEN
        t1 = ATAN2(cry(ix, iy, 3) - cry(ix, iy, 2), crx(ix, iy, 3) - crx&
&         (ix, iy, 2)) - pi/2e0_R8 + angle(ia)
        x = 0.5_R8*(crx(ix, iy, 3)+crx(ix, iy, 2))
        y = 0.5_R8*(cry(ix, iy, 3)+cry(ix, iy, 2))
      ELSE IF (orientation .EQ. 'S') THEN
        t1 = ATAN2(cry(ix, iy, 0) - cry(ix, iy, 1), crx(ix, iy, 0) - crx&
&         (ix, iy, 1)) - pi/2e0_R8 + angle(ia)
        x = 0.5_R8*(crx(ix, iy, 1)+crx(ix, iy, 0))
        y = 0.5_R8*(cry(ix, iy, 1)+cry(ix, iy, 0))
      ELSE
        WRITE(*, *) 'Unknown orientation ', orientation, ' at ', ix0, &
&       iy0
        CALL XERRAB('Unknown orientation')
      END IF
      inside = .true.
      IF (output .GE. 1) WRITE(88, *) x, y, ia, ix, iy
      dx = dl*COS(t1)
      dy = dl*SIN(t1)
      DO WHILE (inside)
        x = x + dx
        y = y + dy
        CALL CHORD_FIND(nx, ny, crx, cry, x, 0.0_R8, y, inside, ix, iy)
        IF (inside) THEN
          new = cell(ix, iy)
          IF (new .EQ. curr) THEN
            cnt = cnt + 1
          ELSE
            IF (curr .EQ. -1) THEN
              index(ptr_index, ia, 0) = ptr_table + 1
            ELSE
              ptr_table = ptr_table + 1
              CALL XERTST(ptr_table .LE. size_of_table, &
&                   'b2mod_first_flight: increase size_of_table')
              table(ptr_table, 0) = curr
              table(ptr_table, 1) = cnt
            END IF
            curr = new
            cnt = 1
          END IF
        ELSE IF (cnt .GT. 0) THEN
          ptr_table = ptr_table + 1
          table(ptr_table, 0) = curr
          table(ptr_table, 1) = cnt
          index(ptr_index, ia, 1) = ptr_table
        END IF
        IF (output .GE. 1) WRITE(88, *) x, y, inside, ix, iy, new, cnt, &
&                          curr, ptr_table
      END DO
      IF (output .GE. 1) WRITE(88, '()') 
    END DO
    CALL SUBEND()
    RETURN
  END SUBROUTINE SETUP_B2MOD_FIRST_FLIGHT

!
  SUBROUTINE PROCESS_B2MOD_FIRST_FLIGHT(indptr, ix0, iy0, nx, ny, ns, &
&   nscx, iscx, isneut, jsep, dtim, src, sri, work, wrk2, wrk3, pfrpuff&
&   , mainpuff, corepuff)
    USE B2MOD_GEO_DIFF
    USE B2MOD_MATH_DIFF
    USE B2MOD_PLASMA_DIFF
    USE B2MOD_RATES
    USE B2MOD_INDIRECT
    USE B2MOD_NUMERICS_NAMELIST_DIFF
    USE B2MOD_CONSTANTS
    USE B2MOD_B2CMPA_DIFF
    IMPLICIT NONE
    INTEGER :: indptr, ix0, iy0, nx, ny, ns, nscx, iscx(0:nscxmax-1), &
&   isneut, jsep
    INTEGER :: ix, iy, ia, ptr, ik, ision, k, ixend, iyend
    REAL(kind=r8) :: dtim, dist_start, dist_end, dist_deposit, vcx, vion&
&   , vnn, vexc, rcx, rion, rnn, src, sri, eion, sxb, flight_time, &
&   flown_time, thru_time, work(-1:nx, -1:ny, 0:1), wrk2(-1:nx, -1:ny), &
&   wrk3(-1:nx, -1:ny), pfrpuff, mainpuff, corepuff
    INTRINSIC ABS
    INTRINSIC LOG
    INTRINSIC SQRT
    INTRINSIC MIN
    REAL(kind=r8) :: abs0
    REAL(kind=r8) :: arg1
    REAL(kind=r8) :: result1
! ignore core
    IF (on_closed_surface(ix0, iy0)) THEN
      RETURN
    ELSE
      IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
      IF (src .GE. 0.) THEN
        abs0 = src
      ELSE
        abs0 = -src
      END IF
! jump over zero sources
      IF (abs0 .LT. cutlo) THEN
        RETURN
      ELSE
        dist_start = src/no_of_slices
        eion = sri/src
!WG_TODO!
        flight_time = dtim*dtco(isneut, region(ix0, iy0, 0))*time_factor&
&         (ix0+2+(iy0+1)*(nx+2))
! recover the old default value of 1.0 eV
        IF (eion .EQ. 0.0_R8) eion = 1.0_R8
        k = 0
        DO WHILE (iscx(k) .NE. isneut .AND. k .LT. nscx)
          k = k + 1
        END DO
        IF (k .GE. nscx) WRITE(*, *) 'CX species index not found!'
!xpb
!xpb  We follow the launched neutrals over their pre-computed trajectories
!xpb  and distribute the associated sources along the way.
!xpb  We must account for:
!xpb   a. CX processes with ions
!xpb   b. electron-impact ionisation
!xpb   c. electron-impact excitation (we use the S/XB factor to convert 
!xpb      electron heat loss rate into number of collision events)
!xpb   d. elastic collisions with neutrals
!xpb  We distribute the sources into
!xpb   work(:,:,0:1) => sna(:,:,0,is0:is0+1)
!xpb   wrk2(:,:) => shi(:,:,0)
!xpb   wrk3(:,:) => she(:,:,0)
!xpb  We must also take care that we do not allow the neutrals to travel longer
!xpb  that the timestep permits. We set the average energy of the launched
!xpb  neutrals to be eion=shi/sna.
        DO ia=1,no_of_slices
          dist_end = dist_start
          flown_time = 0.0_R8
          ixend = -2
          iyend = -2
          ptr = index(indptr, ia, 0)
          DO WHILE (flown_time .LT. flight_time .AND. ptr .LE. index(&
&                   indptr, ia, 1))
            ix = cellx(table(ptr, 0))
            iy = celly(table(ptr, 0))
            vcx = 0.0_R8
            vnn = 0.0_R8
            IF (k .LT. nscx) THEN
              DO ision=0,ns-1
                arg1 = rlcx(ix, iy, 0, ision, k) + rlcx(ix, iy, 1, ision&
&                 , k)*LOG(ti(ix, iy)/(am(isneut)*ev))
                rcx = EXPU(arg1)
                vcx = vcx + rcx*na(ix, iy, ision)
              END DO
            END IF
            arg1 = rlsa(ix, iy, 0, isneut) + rlsa(ix, iy, 1, isneut)*LOG&
&             (te(ix, iy)/ev)
            rion = EXPU(arg1)
            vion = rion*ne(ix, iy)
            arg1 = rlqa(ix, iy, 0, isneut) + rlqa(ix, iy, 1, isneut)*LOG&
&             (te(ix, iy)/ev)
            result1 = EXPU(arg1)
            sxb = result1/(rion*rpt(ix, iy, isneut+1))
            vexc = sxb*vion
            DO ik=0,nscx-1
              rnn = 2.0e-19_R8*SQRT(ti(ix, iy)/(mp*am(iscx(ik))))
              vnn = vnn + rnn*na(ix, iy, iscx(ik))
            END DO
            thru_time = dl/SQRT(eion/(am(isneut)*mp))*table(ptr, 1)
            IF (flown_time + thru_time .LT. flight_time) THEN
              dist_deposit = (vcx+vion+vexc+vnn)*dl/SQRT(eion/(am(isneut&
&               )*mp))*table(ptr, 1)
              IF (dist_end*dist_deposit .GT. dist_end) THEN
                dist_deposit = dist_end
              ELSE
                dist_deposit = dist_end*dist_deposit
              END IF
            ELSE
              thru_time = flight_time - flown_time
              dist_deposit = dist_end
            END IF
            flown_time = flown_time + thru_time
            work(ix, iy, 0) = work(ix, iy, 0) + dist_deposit*(vcx+vnn+&
&             vexc)/(vcx+vion+vexc+vnn)
            work(ix, iy, 1) = work(ix, iy, 1) + dist_deposit*vion/(vcx+&
&             vion+vexc+vnn)
            wrk2(ix, iy) = wrk2(ix, iy) + dist_deposit*eion
            wrk3(ix, iy) = wrk3(ix, iy) - dist_deposit*sxb*rpt(ix, iy, &
&             isneut+1)*ev*(vion+vexc)/(vcx+vion+vexc+vnn)
            dist_end = dist_end - dist_deposit
            IF (dist_end .LE. 0.0_R8) THEN
              ixend = ix
              iyend = iy
              GOTO 100
            ELSE
              ptr = ptr + 1
            END IF
          END DO
 100      IF (dist_end .GT. 0.0_R8 .AND. ixend .NE. -2 .AND. iyend .NE. &
&             -2) THEN
            IF (iyend .GT. jsep) THEN
              mainpuff = mainpuff + dist_end
            ELSE IF (on_closed_surface(ixend, iyend)) THEN
              corepuff = corepuff + dist_end
            ELSE IF (nnreg(0) .GE. 4) THEN
              pfrpuff = pfrpuff + dist_end
            END IF
          END IF
        END DO
        RETURN
      END IF
    END IF
  END SUBROUTINE PROCESS_B2MOD_FIRST_FLIGHT

!
  SUBROUTINE READ_B2MOD_FIRST_FLIGHT(nread)
    IMPLICIT NONE
    INTEGER :: nread
    CALL XERTST(1 .LE. nread, 'faulty argument nread')
    RETURN
  END SUBROUTINE READ_B2MOD_FIRST_FLIGHT

!
  SUBROUTINE WRITE_B2MOD_FIRST_FLIGHT(nwrite)
    IMPLICIT NONE
    INTEGER :: nwrite
    INTEGER :: is, ia, ptr
    DO is=1,ptr_index
      WRITE(nwrite, *) 'is = ', is
      DO ia=1,no_of_slices
        WRITE(nwrite, *) 'index: ', index(is, ia, 0), index(is, ia, 1)
        DO ptr=index(is, ia, 0),index(is, ia, 1)
          WRITE(nwrite, *) '        table: ', table(ptr, :), '  --  ', &
&         cellx(table(ptr, 0)), celly(table(ptr, 0))
        END DO
      END DO
    END DO
    RETURN
  END SUBROUTINE WRITE_B2MOD_FIRST_FLIGHT

END MODULE B2MOD_FIRST_FLIGHT_DIFF

