!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!!-----------------------------------------------------------------------------
!! DOCUMENTATION:
!>      @section b2uw_ualio_grid_desc Description
!!      Module providing routines to set the B2 grid geometry, including grid
!!      subsets (subgrids), to ITM CPO or IMAS IDS grid description data
!!      structure.
!!
!!      The main two routines are:
!!          - b2_IMAS_Fill_Grid_Desc (for IMAS edge_profiles, edge_sources
!!            and edge_transport IDSs)
!!          - b2ITMFillGridDescription (for ITM edge CPO)
!!
!!      @subsection b2uw_ualio_grid_syx     Exceptional syntax explanation
!!      @code
!!          ! IGNORE    !! syntax used to ignore this module in list
!!                      !! dependency when compiling the code
!!      @endcode
!!
!!-----------------------------------------------------------------------------
MODULE B2MOD_UAL_IO_GRID_DIFF
  USE B2MOD_TYPES, b2_r8 => r8, b2_r4 => r4
  USE B2MOD_CONSTANTS, b2_pi => pi
  USE HELPER
  USE LOGGING, ONLY : logmsg, logdebug
  USE B2MOD_CONNECTIVITY, removed_b2_r8 => r8
  USE CARRE_CONSTANTS
  USE B2MOD_CELLHELPER
  USE B2MOD_GRID_MAPPING
  USE B2MOD_INDIRECT
  USE B2MOD_INTERP
  USE B2MOD_B2CMFS
  USE B2MOD_PPOUT_DIFF
  USE B2MOD_GEO_DIFF
  USE B2MOD_USER_NAMELIST_DIFF
  IMPLICIT NONE
!! Constants for use with the ITM grid description
  LOGICAL, PARAMETER :: include_ghost_cells=.false.
!! Space indices
!< Space index
  INTEGER, PARAMETER :: space_poloidalplane=1
!< (polodal plane)
!< Space index
  INTEGER, PARAMETER :: space_toroidalangle=2
!< (toroidal angle)
!< Space count
  INTEGER, PARAMETER :: space_count=space_toroidalangle
!< set up:
!< SPACE_COUNT = SPACE_POLOIDALPLANE: do only the poloidal plane space;
!< SPACE_COUNT = SPACE_TOROIDALANGLE: will do the full 3d grid with two
!< spaces
!! Will have at maximum so many spaces
  INTEGER, PARAMETER :: space_count_max=2
!! Number of points in toroidal direction
!! (only 1 makes sense here, this is for playing around)
!< Number of points in toroidal
  INTEGER, PARAMETER :: nnodes_toroidal=1
!< direction (only 1 makes sense here, this is for playing around)
!< Flag controlling
  LOGICAL, PARAMETER :: toroidal_periodic=.false.
!< whether the toroidal space is set up periodic or not.
!< If periodic, the last node is connected to the first by an edge.
!< If not periodic, an additional node at 2 pi is added
!< B2.5 Inner and Outer midplane default locations
  INTEGER :: jxi, jxa
!! Object class tuples (ITM class definition)
!< Object class tuple (ITM class definition): Node
  INTEGER, DIMENSION(space_count_max), PARAMETER :: class_node=(/0, 0/)
!< Object class tuple (ITM class definition): Edge (R, Z)
  INTEGER, DIMENSION(space_count_max), PARAMETER :: class_rz_edge=(/1, 0&
&   /)
!< Object class tuple (ITM class definition): Edge (phi)
  INTEGER, DIMENSION(space_count_max), PARAMETER :: class_phi_edge=(/0, &
&   1/)
!< Object class tuple
  INTEGER, DIMENSION(space_count_max), PARAMETER :: &
& class_poloidalradial_edge=(/1, 1/)
!< (ITM class definition): Poloidal/radial edge (in observed existing
!< CPO cases this class refers to 2D cells)
!< Object class tuple
  INTEGER, DIMENSION(space_count_max), PARAMETER :: class_toroidal_edge=&
&   (/2, 0/)
!< (ITM class definition): Toroidal edge
  INTEGER, DIMENSION(space_count_max), PARAMETER :: class_cell=(/2, 1/)
!< Object class tuple (ITM class definition): Cell
!! Object class tuples
!! (one digit IDS classes, transformed from the above ITM classes )
!! Primary IDS classes are:
!!      Class 1 - nodes/vertices (0D objects)
!!      Class 2 - edges/faces (1D objects)
!!      Class 3 - 2D cells (2D objects)
!!      Class 4 - 3D volumes (3D objects)
!! Fortran90 does not allow initialization of constants using SUM. This is
!! permitted in newer Fortran 2003. Current workaround is to directly
!! specify the primary IDS class constants
! integer, parameter :: IDS_CLASS_NODE = sum(CLASS_NODE) + 1
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_node=1
!< (IMAS class definition): Node
! integer, parameter :: IDS_CLASS_EDGE
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_edge=2
!< (IMAS class definition): Edge
! integer, parameter :: IDS_CLASS_RZ_EDGE = sum(CLASS_RZ_EDGE) + 1
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_rz_edge=2
!< (IMAS class definition): Edge
! integer, parameter :: IDS_CLASS_PHI_EDGE = sum(CLASS_PHI_EDGE) + 1
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_phi_edge=2
!< (IMAS class definition): Edge
! integer, parameter :: IDS_CLASS_POLOIDALRADIAL_EDGE =   &
! &   sum(CLASS_POLOIDALRADIAL_EDGE)
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_poloidalradial_edge=2
!< (IMAS class definition): Edge
! integer, parameter :: IDS_CLASS_TOROIDAL_EDGE =         &
! &   sum(CLASS_TOROIDAL_EDGE)
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_toroidal_edge=2
!< (IMAS class definition): Edge
! integer, parameter :: IDS_CLASS_CELL = sum(IDS_CLASS_CELL)
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_cell=3
!< (IMAS class definition): Cell (2D)
!< Object class tuple
  INTEGER, PARAMETER :: ids_class_volume=4
!< (IMAS class definition): Volume (3D)
!! Field aligned vector component definitions
!> Default vector component
  INTEGER, PARAMETER :: vec_align_default=1
!> Default vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_default_id='DEFAULT'
!> Poloidal vector component
  INTEGER, PARAMETER :: vec_align_poloidal=1001
!> Poloidal vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_poloidal_id='Poloidal'
!> Radial vector component
  INTEGER, PARAMETER :: vec_align_radial=1002
!> Radial vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_radial_id='Radial'
!> Parallel vector component
  INTEGER, PARAMETER :: vec_align_parallel=1003
!> Parallel vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_parallel_id='Parallel'
!> Toroidal vector component
  INTEGER, PARAMETER :: vec_align_toroidal=1004
!> Toroidal vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_toroidal_id='Toroidal'
!> Diamagnetic vector component ID
  INTEGER, PARAMETER :: vec_align_diamagnetic=1005
!> Diamagnetic vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_diamagnetic_id=&
&   'Diamagnetic'
!> Major radius aligned vector component
  INTEGER, PARAMETER :: vec_align_r_major=1006
!> Major radius aligned vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_r_major_id='R'
!> Vertical vector component
  INTEGER, PARAMETER :: vec_align_z=1007
!> Vertical vector component ID
  CHARACTER(len=132), PARAMETER :: vec_align_z_id='Z'
!! Subgrid/Grid subset name constants
!< Total number of
  INTEGER, PARAMETER :: b2_generic_gsubset_count=6
!< generic grid subsets
!! Generic grid subsets (all cells, all edges)
!! Note: special grid subsets (given by region ids) do not have specific
!! constants (see also b2mod_connectivity.f90)
!! IMAS uses GGD grid subset identifier definitions defined in GSL
!! (in ids_grid_common)
!! IMAS GGD grid subset identifier definitions
  INTEGER, PARAMETER :: grid_subset_types=106
!> x-aligned edges defining part of active separatrix separating core and SOL
  INTEGER, PARAMETER :: grid_subset_active_separatrix=26
!> main_chamber_wall + outer_baffle(s) + inner_baffle(s)
  INTEGER, PARAMETER :: grid_subset_main_wall=27
!> outer_PFR_wall(s) + inner_PFR_wall(s)
  INTEGER, PARAMETER :: grid_subset_pfr_wall=28
!> y-aligned edges inside the separatrix connecting to the non-active x-point
  INTEGER, PARAMETER :: grid_subset_core_cut_inactive=29
!> y-aligned edges in the private flux region connecting to the non-active x-point
  INTEGER, PARAMETER :: grid_subset_pfr_cut_inactive=30
!> y-aligned edges in the outer SOL connecting to the non-active x-point
  INTEGER, PARAMETER :: grid_subset_outer_throat_inactive=31
!> y-aligned edges in the inner SOL connecting to the non-active x-point
  INTEGER, PARAMETER :: grid_subset_inner_throat_inactive=32
!> x-aligned edges defining the non-active separatrix
  INTEGER, PARAMETER :: grid_subset_second_separatrix=33
!> x-aligned edges defining the chamber wall of the outer non-active divertor region
  INTEGER, PARAMETER :: grid_subset_outer_baffle_inactive=34
!> x-aligned edges defining the chamber wall of the inner non-active divertor region
  INTEGER, PARAMETER :: grid_subset_inner_baffle_inactive=35
!> x-aligned edges defining the private flux region wall of the outer non-active
!> divertor region
  INTEGER, PARAMETER :: grid_subset_outer_pfr_wall_inactive=36
!> x-aligned edges defining the private flux region wall of the inner non-active
!> divertor region
  INTEGER, PARAMETER :: grid_subset_inner_pfr_wall_inactive=37
!> Cells between the two separatrices
  INTEGER, PARAMETER :: grid_subset_between_separatrices=38
!> Cells defining the outer inactive divertor region
  INTEGER, PARAMETER :: grid_subset_outer_divertor_inactive=39
!> Cells defining the inner inactive divertor region
  INTEGER, PARAMETER :: grid_subset_inner_divertor_inactive=40
!> y-aligned edges defining the outer inactive target
  INTEGER, PARAMETER :: grid_subset_outer_target_inactive=41
!> y-aligned edges defining the inner inactive target
  INTEGER, PARAMETER :: grid_subset_inner_target_inactive=42
!> Point on active separatrix at outer midplane
  INTEGER, PARAMETER :: grid_subset_outer_midplane_separatrix=101
!> Point on active separatrix at inner midplane
  INTEGER, PARAMETER :: grid_subset_inner_midplane_separatrix=102
!> Point on active separatrix at outer active target
  INTEGER, PARAMETER :: grid_subset_outer_strikepoint=103
!> Point on active separatrix at inner active target
  INTEGER, PARAMETER :: grid_subset_inner_strikepoint=104
!> Point on non-active separatrix at outer active target
  INTEGER, PARAMETER :: grid_subset_outer_strikepoint_inactive=105
!> Point on non-active separatrix at inner active target
  INTEGER, PARAMETER :: grid_subset_inner_strikepoint_inactive=106
!< Unspecified string
  CHARACTER(len=26), PARAMETER, PRIVATE :: uu=&
&   'UNSPECIFIED               '
  CHARACTER(len=26), DIMENSION(0:grid_subset_types), PARAMETER :: &
& gridsubsetname=(/'UNSPECIFIED               ', &
&   'NODES                     ', 'EDGES                     ', &
&   'X_ALIGNED_EDGES           ', 'Y_ALIGNED_EDGES           ', &
&   'CELLS                     ', 'X_POINTS                  ', &
&   'CORE_CUT                  ', 'PFR_CUT                   ', &
&   'OUTER_THROAT              ', 'INNER_THROAT              ', &
&   'OUTER_MIDPLANE            ', 'INNER_MIDPLANE            ', &
&   'OUTER_TARGET              ', 'INNER_TARGET              ', &
&   'CORE_BOUNDARY             ', 'SEPARATRIX                ', &
&   'MAIN_CHAMBER_WALL         ', 'OUTER_BAFFLE              ', &
&   'INNER_BAFFLE              ', 'OUTER_PFR_WALL            ', &
&   'INNER_PFR_WALL            ', 'CORE                      ', &
&   'SOL                       ', 'OUTER_DIVERTOR            ', &
&   'INNER_DIVERTOR            ', 'ACTIVE_SEPARATRIX         ', &
&   'MAIN_WALL                 ', 'PFR_WALL                  ', &
&   'CORE_CUT_INACTIVE         ', 'PFR_CUT_INACTIVE          ', &
&   'OUTER_THROAT_INACTIVE     ', 'INNER_THROAT_INACTIVE     ', &
&   'SECOND_SEPARATRIX         ', 'OUTER_BAFFLE_INACTIVE     ', &
&   'INNER_BAFFLE_INACTIVE     ', 'OUTER_PFR_WALL_INACTIVE   ', &
&   'INNER_PFR_WALL_INACTIVE   ', 'BETWEEN_SEPARATRICES      ', &
&   'OUTER_DIVERTOR_INACTIVE   ', 'INNER_DIVERTOR_INACTIVE   ', &
&   'OUTER_TARGET_INACTIVE     ', 'INNER_TARGET_INACTIVE     ', &
&   'VOLUMES                   ', 'FULL_WALL                 ', &
&   'OUTER_SF_LEG_ENTRANCE_1   ', 'OUTER_SF_LEG_ENTRANCE_2   ', &
&   'OUTER_SF_PFR_CONNECTION_1 ', 'OUTER_SF_PFR_CONNECTION_2 ', uu, uu, &
&   uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, &
&   uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, &
&   uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, uu, &
&   'MAGNETIC_AXIS             ', 'OUTER_MIDPLANE_SEPARATRIX ', &
&   'INNER_MIDPLANE_SEPARATRIX ', 'OUTER_STRIKEPOINT         ', &
&   'INNER_STRIKEPOINT         ', 'OUTER_STRIKEPOINT_INACTIVE', &
&   'INNER_STRIKEPOINT_INACTIVE'/)
!< Unspecified subset string
  CHARACTER(len=93), PARAMETER, PRIVATE :: us='Unspecified grid subset  &
&                                                                    '
  CHARACTER(len=93), DIMENSION(0:grid_subset_types), PARAMETER :: &
& gridsubsetdescription=(/'Unspecified grid subset                      &
&                                                ', 'All nodes (0D objec&
&ts)                                                                    &
&   ', 'All edges (1D objects)                                          &
&                             ', 'All x-aligned (poloidally) aligned edg&
&es                                                     ', 'All y-aligne&
&d (radially) aligned edges                                             &
&          ', 'All cells (2D objects)                                   &
&                                    ', 'X-points                       &
&                                                              ', 'y-ali&
&gned edges inside the separatrix connecting to the x-point             &
&                 ', 'y-aligned edges in the private flux region connect&
&ing to the x-point                         ', 'y-aligned edges in the o&
&uter SOL connecting to the x-point                                   '&
&   , 'y-aligned edges in the inner SOL connecting to the x-point       &
&                            ', 'y-aligned edges connecting to the node &
&closest to outer midplane on the separatrix           ', 'y-aligned edg&
&es connecting to the node closest to inner midplane on the separatrix  &
&         ', 'y-aligned edges defining the outer target                 &
&                                   ', 'y-aligned edges defining the inn&
&er target                                                    ', 'Innerm&
&ost x-aligned edges                                                    &
&                ', 'x-aligned edges defining the separatrix            &
&                                          ', 'x-aligned edges defining &
&main chamber wall outside of the divertor regions                   ', &
&'x-aligned edges defining the chamber wall of the outer divertor region&
&                       ', 'x-aligned edges defining the chamber wall of&
& the inner divertor region                       ', 'x-aligned edges de&
&fining the private flux region wall of the outer divertor region       &
&    ', 'x-aligned edges defining the private flux region wall of the in&
&ner divertor region           ', 'Cells inside the separatrix          &
&                                                        ', 'Cells defin&
&ing the main SOL outside of the divertor regions                       &
&           ', 'Cells defining the outer divertor region                &
&                                     ', 'Cells defining the inner diver&
&tor region                                                     ', 'x-al&
&igned edges defining part of active separatrix separating core and SOL &
&                  ', 'main_chamber_wall + outer_baffle(s) + inner_baffl&
&e(s)                                        ', 'outer_PFR_wall(s) + inn&
&er_PFR_wall(s)                                                        '&
&   , 'y-aligned edges inside the separatrix connecting to the non-activ&
&e x-point                   ', 'y-aligned edges in the private flux reg&
&ion connecting to the non-active x-point              ', 'y-aligned edg&
&es in the outer SOL connecting to the non-active x-point               &
&         ', 'y-aligned edges in the inner SOL connecting to the non-act&
&ive x-point                        ', 'x-aligned edges defining the non&
&-active separatrix                                           ', 'x-alig&
&ned edges defining the chamber wall of the outer non-active divertor re&
&gion            ', 'x-aligned edges defining the chamber wall of the in&
&ner non-active divertor region            ', 'x-aligned edges defining &
&the private flux region wall of the outer non-active divertor region', &
&'x-aligned edges defining the private flux region wall of the inner non&
&-active divertor region', 'Cells between the two separatrices          &
&                                                 ', 'Cells defining the&
& outer inactive divertor region                                        &
&    ', 'Cells defining the inner inactive divertor region              &
&                              ', 'y-aligned edges defining the outer in&
&active target                                           ', 'y-aligned e&
&dges defining the inner inactive target                                &
&           ', 'All volumes (3D objects)                                &
&                                     ', 'All edges defining walls, baff&
&les, and targets                                               ', 'y-al&
&igned edges defining the SOL entrance of the first snowflake outer leg &
&                  ', 'y-aligned edges defining the SOL entrance of the &
&third snowflake outer leg                   ', 'y-aligned edges definin&
&g the connection between the outer snowflake entrance and third leg   '&
&   , 'y-aligned edges defining the connection between the outer snowfla&
&ke first and second leg     ', us, us, us, us, us, us, us, us, us, us, &
&   us, us, us, us, us, us, us, us, us, us, us, us, us, us, us, us, us, &
&   us, us, us, us, us, us, us, us, us, us, us, us, us, us, us, us, us, &
&   us, us, us, us, us, us, us, 'Point on magnetic axis                 &
&                                                      ', 'Point on acti&
&ve separatrix at outer midplane                                        &
&         ', 'Point on active separatrix at inner midplane              &
&                                   ', 'Point on active separatrix at ou&
&ter active target                                            ', 'Point &
&on active separatrix at inner active target                            &
&                ', 'Point on non-active separatrix at outer active targ&
&et                                        ', 'Point on non-active separ&
&atrix at inner active target                                        '/)

CONTAINS
!> Collect the grid indices of all vertices on the radial grid line outward
!! starting at the vertex at position six,siy in computational space.
  FUNCTION COLLECTRADIALVERTEXINDEXLIST(gmap, cflag, six, siy, topix, &
&   topiy) RESULT (indexlist)
    IMPLICIT NONE
!< The grid mapping as computed by
    TYPE(B2GRIDMAP), INTENT(IN) :: gmap
!< b2CreateMap holding an intermediate grid description to be
!< transferred into a CPO or IDS
!< 2D index list
    INTEGER, DIMENSION(:, :), ALLOCATABLE :: indexlist
!< First vertex position
    INTEGER, INTENT(IN) :: six
!< Second vertex position
    INTEGER, INTENT(IN) :: siy
    INTEGER, INTENT(IN) :: cflag(-1:gmap%b2nx, -1:gmap%b2ny, &
&   carreout_ncellflags)
!! B2 connectivity array
!< Top
    INTEGER, INTENT(IN) :: topix(-1:gmap%b2nx, -1:gmap%b2ny)
!< neighbour poloidal (first coordinate) index array
!< Top
    INTEGER, INTENT(IN) :: topiy(-1:gmap%b2nx, -1:gmap%b2ny)
!< neighbour radial (second coordinate) index
!! Internal variables
!< x-aligned cell index
    INTEGER :: ix
!< y-aligned cell index
    INTEGER :: iy
    INTEGER :: nix
    INTEGER :: niy
    INTEGER :: nvx
    INTEGER :: ivx
!! Procedures
    EXTERNAL XERTST
!! First figure out how many points we have: start at six, siy,
!! go towards top until running out of physical domain
    nvx = 1
    ix = six
    iy = siy
    DO 
!! Take a step upwards
      nix = topix(ix, iy)
      niy = topiy(ix, iy)
!! Stepped outside grid?
      IF (IS_UNNEEDED_CELL(gmap%b2nx, gmap%b2ny, cflag, .true., nix, niy&
&         )) THEN
        ALLOCATE(indexlist(nvx, space_count))
        IF (space_count .EQ. space_toroidalangle) indexlist(:, &
&         space_toroidalangle) = 1
!! collect indices: repeat above loop with storing indices
        ix = six
        iy = siy
!! Store starting point index
        ivx = 1
        indexlist(ivx, space_poloidalplane) = gmap%mapvxi(ix, iy, &
&         vx_lowerleft)
        DO 
!! take a step
          nix = topix(ix, iy)
          niy = topiy(ix, iy)
!! Stepped outside grid?
          IF (IS_UNNEEDED_CELL(gmap%b2nx, gmap%b2ny, cflag, .true., nix&
&             , niy)) THEN
            CALL XERTST(ivx .EQ. nvx, &
&          'Assert error (vertex count) in collectRadialVertexIndexList'&
&                )
            GOTO 100
          ELSE
!! Store index for new point
            ivx = ivx + 1
            IF (gmap%mapvxi(nix, niy, vx_lowerleft) .NE. &
&               b2_grid_undefined) THEN
              indexlist(ivx, space_poloidalplane) = gmap%mapvxi(nix, niy&
&               , vx_lowerleft)
            ELSE IF (gmap%mapvxi(ix, iy, vx_upperleft) .NE. &
&               b2_grid_undefined .AND. ivx .EQ. nvx) THEN
              indexlist(ivx, space_poloidalplane) = gmap%mapvxi(ix, iy, &
&               vx_upperleft)
            ELSE
              STOP
            END IF
            ix = nix
            iy = niy
          END IF
        END DO
      ELSE
        nvx = nvx + 1
        ix = nix
        iy = niy
      END IF
    END DO
 100 CONTINUE
  END FUNCTION COLLECTRADIALVERTEXINDEXLIST

!> Collect the grid indices of all vertices on the radial grid line outward
!! starting at the vertex at position six,siy in computational space.
  SUBROUTINE COLLECTRADIALVERTEXINDEXLISTSUBROUTINE(gmap, cflag, six, &
&   siy, topix, topiy, indexlist)
    IMPLICIT NONE
!< The grid mapping as computed by
    TYPE(B2GRIDMAP), INTENT(IN) :: gmap
!< b2CreateMap holding an intermediate grid description to be
!< transferred into a CPO or IDS
!< 2D
    INTEGER, DIMENSION(:, :), ALLOCATABLE, INTENT(OUT) :: indexlist
!< index list
!< First vertex position
    INTEGER, INTENT(IN) :: six
!< Second vertex position
    INTEGER, INTENT(IN) :: siy
    INTEGER, INTENT(IN) :: cflag(-1:gmap%b2nx, -1:gmap%b2ny, &
&   carreout_ncellflags)
!! B2 connectivity array
!< Top
    INTEGER, INTENT(IN) :: topix(-1:gmap%b2nx, -1:gmap%b2ny)
!< neighbour poloidal (first coordinate) index array
!< Top
    INTEGER, INTENT(IN) :: topiy(-1:gmap%b2nx, -1:gmap%b2ny)
!< neighbour radial (second coordinate) index
!! Internal variables
!< x-aligned cell index
    INTEGER :: ix
!< y-aligned cell index
    INTEGER :: iy
    INTEGER :: nix
    INTEGER :: niy
    INTEGER :: nvx
    INTEGER :: ivx
!! Procedures
    EXTERNAL XERTST
!! First figure out how many points we have: start at six, siy,
!! go towards top until running out of physical domain
    nvx = 1
    ix = six
    iy = siy
    DO 
!! Take a step upwards
      nix = topix(ix, iy)
      niy = topiy(ix, iy)
!! Stepped outside grid ?
      IF (IS_UNNEEDED_CELL(gmap%b2nx, gmap%b2ny, cflag, .true., nix, niy&
&         )) THEN
        ALLOCATE(indexlist(nvx, space_count))
        IF (space_count .EQ. space_toroidalangle) indexlist(:, &
&         space_toroidalangle) = 1
!! collect indices: repeat above loop with storing indices
        ix = six
        iy = siy
!! Store starting point index
        ivx = 1
        indexlist(ivx, space_poloidalplane) = gmap%mapvxi(ix, iy, &
&         vx_lowerleft)
        DO 
!! take a step
          nix = topix(ix, iy)
          niy = topiy(ix, iy)
!! Stepped outside grid?
          IF (IS_UNNEEDED_CELL(gmap%b2nx, gmap%b2ny, cflag, .true., nix&
&             , niy)) THEN
            CALL XERTST(ivx .EQ. nvx, &
&'Assert error (vertex count) in collectRadialVertexIndexListSubroutine'&
&                )
            GOTO 100
          ELSE
!! Store index for new point
            ivx = ivx + 1
            IF (gmap%mapvxi(nix, niy, vx_lowerleft) .NE. &
&               b2_grid_undefined) THEN
              indexlist(ivx, space_poloidalplane) = gmap%mapvxi(nix, niy&
&               , vx_lowerleft)
            ELSE IF (gmap%mapvxi(ix, iy, vx_upperleft) .NE. &
&               b2_grid_undefined .AND. ivx .EQ. nvx) THEN
              indexlist(ivx, space_poloidalplane) = gmap%mapvxi(ix, iy, &
&               vx_upperleft)
            ELSE
              STOP
            END IF
            ix = nix
            iy = niy
          END IF
        END DO
      ELSE
        nvx = nvx + 1
        ix = nix
        iy = niy
      END IF
    END DO
 100 CONTINUE
  END SUBROUTINE COLLECTRADIALVERTEXINDEXLISTSUBROUTINE

!> Build an index list of all objects of a given region type
!! (b2mod_connectivity.REGIONTYPE_*) for a given region id.
!! @result The list of indices for all objects that constitute this grid
!! region. The array has two dimensions because it is given as a list of
!! object descriptors.
  FUNCTION COLLECTINDEXLISTFORREGION(gmap, region, iregiontype, iregion)&
& RESULT (indexlist)
    IMPLICIT NONE
    INTEGER, DIMENSION(:, :), ALLOCATABLE :: indexlist
    TYPE(B2GRIDMAP), INTENT(IN) :: gmap
    INTEGER, INTENT(IN) :: region(-1:gmap%b2nx, -1:gmap%b2ny, 0:2)
    INTEGER, INTENT(IN) :: iregiontype, iregion
!! internal
    INTEGER :: ix, iy, nind, iind, ind
!! procedures
    EXTERNAL XERTST
!! Figure out how many indices to expect. A simple count of the form
!! nInd = count( region(:,:,iRegionType) == iRegion )
!! will not do, because we have to account for removed objects (ghost cells/edges).
!! search the relevant objects and count them
    nind = 0
    DO ix=-1,gmap%b2nx
      DO iy=-1,gmap%b2ny
        IF (region(ix, iy, iregiontype) .EQ. iregion) THEN
!! Get index depending on what object type we are looking at
          SELECT CASE  (iregiontype) 
          CASE (regiontype_cell) 
            ind = gmap%mapcvi(ix, iy)
          CASE (regiontype_xedge) 
            ind = gmap%mapfci(ix, iy, left)
          CASE (regiontype_yedge) 
            ind = gmap%mapfci(ix, iy, bottom)
          END SELECT
!! Only count this index if not undefined
          IF (ind .NE. b2_grid_undefined) nind = nind + 1
        END IF
      END DO
    END DO
    ALLOCATE(indexlist(nind, space_count))
    indexlist = 1
!! search the relevant objects and store their index consecutively
    iind = 0
    DO ix=-1,gmap%b2nx
      DO iy=-1,gmap%b2ny
        IF (region(ix, iy, iregiontype) .EQ. iregion) THEN
!! Get index depending on what object type we are looking at
          SELECT CASE  (iregiontype) 
          CASE (regiontype_cell) 
            ind = gmap%mapcvi(ix, iy)
          CASE (regiontype_xedge) 
            ind = gmap%mapfci(ix, iy, left)
          CASE (regiontype_yedge) 
            ind = gmap%mapfci(ix, iy, bottom)
          END SELECT
          IF (ind .NE. b2_grid_undefined) THEN
            iind = iind + 1
            CALL XERTST(iind .LE. nind, &
&                 'Assert error 1 (index) in collectIndexListForRegion')
            indexlist(iind, space_poloidalplane) = ind
          END IF
        END IF
      END DO
    END DO
    CALL XERTST(iind .EQ. nind, &
&         'Assert error 2 (index) in collectIndexListForRegion')
  END FUNCTION COLLECTINDEXLISTFORREGION

!> Build an index list of all objects of a given region type
!! (b2mod_connectivity.REGIONTYPE_*) for a given region id.
!! @result The list of indices for all objects that constitute this grid
!! region. The array has two dimensions because it is given as a list of
!! object descriptors.
  SUBROUTINE COLLECTINDEXLISTFORREGIONSUBROUTINE(gmap, region, &
&   iregiontype, iregion, indexlist)
    IMPLICIT NONE
!< The grid mapping as computed by
    TYPE(B2GRIDMAP), INTENT(IN) :: gmap
!< b2CreateMap holding an intermediate grid description to be
!< transferred into a CPO or IDS
!< 2D
    INTEGER, DIMENSION(:, :), ALLOCATABLE, INTENT(OUT) :: indexlist
!< index list
    INTEGER, INTENT(IN) :: region(-1:gmap%b2nx, -1:gmap%b2ny, 0:2)
    INTEGER, INTENT(IN) :: iregiontype
    INTEGER, INTENT(IN) :: iregion
!! Internal variables
!< x-aligned cell index
    INTEGER :: ix
!< y-aligned cell index
    INTEGER :: iy
    INTEGER :: nind
    INTEGER :: iind
    INTEGER :: ind
!! Procedures
    EXTERNAL XERTST
!! Figure out how many indices to expect. A simple count of the form
!! nInd = count( region(:,:,iRegionType) == iRegion )
!! will not do, because we have to account for removed objects
!! (ghost cells/edges).
!! search the relevant objects and count them
    nind = 0
    DO ix=-1,gmap%b2nx
      DO iy=-1,gmap%b2ny
        IF (region(ix, iy, iregiontype) .EQ. iregion) THEN
!! Get index depending on what object type we are looking at
          SELECT CASE  (iregiontype) 
          CASE (regiontype_cell) 
            ind = gmap%mapcvi(ix, iy)
          CASE (regiontype_xedge) 
            ind = gmap%mapfci(ix, iy, left)
          CASE (regiontype_yedge) 
            ind = gmap%mapfci(ix, iy, bottom)
          END SELECT
!! Only count this index if not undefined
          IF (ind .NE. b2_grid_undefined) nind = nind + 1
        END IF
      END DO
    END DO
    ALLOCATE(indexlist(nind, space_count))
    indexlist = 1
!! search the relevant objects and store their index consecutively
    iind = 0
    DO ix=-1,gmap%b2nx
      DO iy=-1,gmap%b2ny
        IF (region(ix, iy, iregiontype) .EQ. iregion) THEN
!! Get index depending on what object type we are looking at
          SELECT CASE  (iregiontype) 
          CASE (regiontype_cell) 
            ind = gmap%mapcvi(ix, iy)
          CASE (regiontype_xedge) 
            ind = gmap%mapfci(ix, iy, left)
          CASE (regiontype_yedge) 
            ind = gmap%mapfci(ix, iy, bottom)
          END SELECT
          IF (ind .NE. b2_grid_undefined) THEN
            iind = iind + 1
            CALL XERTST(iind .LE. nind, &
&        'Assert error 1 (index) in collectIndexListForRegionSubroutine'&
&                )
            indexlist(iind, space_poloidalplane) = ind
          END IF
        END IF
      END DO
    END DO
    CALL XERTST(iind .EQ. nind, &
&        'Assert error 2 (index) in collectIndexListForRegionSubroutine'&
&        )
  END SUBROUTINE COLLECTINDEXLISTFORREGIONSUBROUTINE

END MODULE B2MOD_UAL_IO_GRID_DIFF
!!!Local Variables:
!!! mode: f90
!!! End:

