!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
MODULE B2MOD_USER_NAMELIST_DIFF
  USE B2MOD_TYPES
  USE B2MOD_DIAG_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2MOD_DIMENSIONS
  IMPLICIT NONE
!
  INTEGER :: npfrgrpd, nntrgrpd
  PARAMETER (npfrgrpd=6, nntrgrpd=16)
  INTEGER :: nhetrgtx
  PARAMETER (nhetrgtx=def_nlim)
  INTEGER :: lhetrgts(nhetrgtx), lpfrgrp(def_nlim), lntrgrp(def_nlim)
  INTEGER :: l_h_mol(def_nmol, 3)
! VARIABLES RELATED TO DEFINITION OF MIDPLANES AND SEPARATRIX
! - [oi]mp: list of CVs belonging to the [OI]MP, defined through the segment rz[oi]mp
!           it should be built as an ordered list from core to SOL. 
! - nromp: pre-defined maximum size for these lists
! - icsep[oi]mp: location of the separatrix position in the [oi]mp list
! - n[oi]mp: number of CVs in the [oi]mp list
! - rz[o1]mp: R-Z coordinates of a segment whose intersection with the
!             plasma grid defines the OMP and IMP. rzomp(1,1:2) holds R-coordinates 
!             of first and second point of the segment, rzomp(2,1:2) holds Z-coordinates
  INTEGER, PARAMETER :: nromp=def_nyd*4
  INTEGER, SAVE :: omp(nromp), icsepomp, nomp, ifssep, imp(nromp), &
& icsepimp, nimp
  REAL(kind=r8) :: rzomp(2, 2), rzimp(2, 2)
  REAL(kind=r8) :: fusion_power, spmp_he_to_d, spmp_nom
  INTEGER :: lpfrb_i, lpfrb_o, lpfrt_i, lpfrt_o, j_he_at, j_h_at(3), &
& j_ne_at, lpfrs_pmp, npfrgrp, ipfrgrp(npfrgrpd), jpfrgrp(npfrgrpd), &
& nntrgrp, intrgrp(nntrgrpd), jntrgrp(nntrgrpd)
  CHARACTER(len=8) :: gpfrgrp(npfrgrpd), gntrgrp(nntrgrpd)
  CHARACTER(len=80) :: user_filename
  LOGICAL :: scale_he, print_isat
  LOGICAL, SAVE :: user_namelist_used=.true.
  LOGICAL, SAVE :: written=.false.
  LOGICAL, SAVE :: write_nml_user=.false.
  LOGICAL, SAVE :: user_initialised=.false.
  PRIVATE :: user
  NAMELIST /user/ lhetrgts, lpfrb_i, lpfrb_o, lpfrt_i, lpfrt_o, j_h_at, &
&     j_he_at, j_ne_at, l_h_mol, fusion_power, spmp_he_to_d, lpfrs_pmp, &
&     npfrgrp, lpfrgrp, ipfrgrp, jpfrgrp, gpfrgrp, nntrgrp, lntrgrp, &
&     intrgrp, jntrgrp, gntrgrp, spmp_nom, scale_he, print_isat, &
&     write_nml_user, filedata, user_filename, rzomp, rzimp

CONTAINS
!----------------------------------------------------------------------
!*** fusion_power : fusion power (including neutrons) [MW]
!*** Spmp_He_to_D : ratio of He to DT pumping speeds (typically, 0.8)
!*** lhetrgts  :  list of surface indices (EIRENE notation) which
!***              are used for calculation of helium enrichment
!*** lpfrb_[io]:  B2 x-cell indices corresponding to the bottom of the
!***              bypass between the inner and outer divertor (counted
!***              from the bottom, if non-positive)
!*** lpfrt_[io]:  B2 x-cell indices corresponding to the top of the
!***              bypass between the inner and outer divertor (counted
!***              from the x-point, if non-positive)
!*** j_h_at    :  Hydrogen isotope index in EIRENE atoms list
!*** j_he_at   :  Helium index in EIRENE atoms list
!*** j_ne_at   :  Neon index in EIRENE atoms list
!*** l_h_mol   :  Hydrogen isotope content in the molecules
!*** lpfrs_pmp :  Location of the pump.
!***              0 no pump at all, 1 - lower PFR, 2 - lower outer
!*** npfrgrpd  :  max. number of surface groups for PFR flows
!*** npfrgrp   :  actual number of surface groups for PFR flows
!*** lpfrgrp   :  list of surface segments for PFR flows
!*** [ij]pfrgrp:  first and last positions in this list for each group
!*** gpfrgrp   :  identifiers for the PFR surface groups
!*** nntrgrpd  :  max. number of surface groups for neutral data
!*** nntrgrp   :  actual number of surface groups for neutral data
!*** lntrgrp   :  list of surface segments for neutral data
!*** [ij]ntrgrp:  first and last positions in this list for each group
!*** gntrgrp   :  identifiers for the neutral data surface groups
!*** filedata  :  flag to turn on/off individual tracing files
!***              (see b2mod_diag for their definition)
!----------------------------------------------------------------------
!
!
  SUBROUTINE ALLOC_B2MOD_USER(geo, m, ns, nlim, nmol, ntns)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ns, nlim, nmol, ntns
    TYPE(GEOMETRY), INTENT(IN) :: geo
    TYPE(MAPPING), INTENT(INOUT) :: m
!
    CALL XERTST(1 .LE. ns, 'faulty argument ns')
    CALL XERTST(0 .LE. nlim, 'faulty argument nlim')
    CALL XERTST(0 .LE. nmol, 'faulty argument nmol')
    CALL XERTST(0 .LE. ntns, 'faulty argument ntns')
    IF (user_initialised) THEN
      RETURN
    ELSE
!
!*** PFR specification - for He enrichment and neutral pressure
!***  Standard set-up:
! no pumping
      lpfrs_pmp = 0
! no helium
      fusion_power = 0.0_R8
! same pumping speed for He and D
      spmp_he_to_d = 1.0_R8
      spmp_nom = 0.0_R8
      j_h_at = 0
      l_h_mol = 0
      j_he_at = 0
      j_ne_at = 0
      lpfrb_i = 0
      lpfrb_o = 0
      lpfrt_i = 0
      lpfrt_o = 0
      npfrgrp = 0
      ipfrgrp = 0
      jpfrgrp = 0
      nntrgrp = 0
      intrgrp = 0
      jntrgrp = 0
      lhetrgts(1:nhetrgtx) = 0
      lhetrgts(1:nsts) = -ltns(1:nsts)
      gpfrgrp = ' '
      gntrgrp = ' '
      scale_he = .false.
      print_isat = .false.
      rzomp = 0.0_R8
      rzimp = 0.0_R8
      user_filename = 'b2.user.parameters'
      CALL READ_B2MOD_USER_NAMELIST(ns, ntns, geo, m)
      user_initialised = .true.
!
      RETURN
    END IF
  END SUBROUTINE ALLOC_B2MOD_USER

!
  SUBROUTINE DEALLOC_B2MOD_USER()
    IMPLICIT NONE
    user_initialised = .false.
    RETURN
  END SUBROUTINE DEALLOC_B2MOD_USER

!
  SUBROUTINE READ_B2MOD_USER_NAMELIST(ns, ntns, geo, m)
    USE B2MOD_B2CMPA_DIFF
    USE B2MOD_SUBSYS
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ns, ntns
    TYPE(GEOMETRY), INTENT(IN) :: geo
    TYPE(MAPPING), INTENT(INOUT) :: m
    INTEGER :: ic, ic1, ic2, ifc, ifcc, ifc1, ifc2, ifs, ii, ifc11, &
&   ifc22, jj
!
    LOGICAL :: file_ok
    CHARACTER(len=260) :: filename
    CHARACTER(len=1) :: str
    INTEGER :: i
    LOGICAL :: done, ifail, found
    INTEGER, SAVE :: use_eirene, neutrals_namelist
    EXTERNAL IPGETI, FIND_FILE, XERTST
    INTRINSIC TRIM
    EXTERNAL XERRAB
    INTRINSIC SIZE
!
    CALL SUBINI('readuser')
    CALL IPGETI('b2mndr_eirene', use_eirene)
    CALL IPGETI('b2stbr_neutrals_namelist', neutrals_namelist)
!
!  -- USER --
    filename = user_filename
    CALL FIND_FILE(filename, file_ok)
    IF (file_ok) THEN
      OPEN(99, file=filename) 
      WRITE(*, *) 'Reading namelist user from ', TRIM(filename)
      READ(99, user) 
      CLOSE(99) 
      WRITE(*, *) 'Read namelist user from ', TRIM(filename)
      user_namelist_used = .true.
    ELSE
      WRITE(*, *) 'No ', TRIM(filename)
      user_namelist_used = .false.
      filedata(ntrc_usr) = .false.
    END IF
!
    nomp = 0
!Need to add check for monotonicity in list
    omp = 0
! Define OMP list by finding CVs which are intersected by the rzomp segment
    CALL CV_INTERSECTIONS_NODIFF(m%ncv, geo, m, rzomp, omp, nomp, nromp&
&                          , 1, ifail)
    CALL XERTST(.NOT.ifail, 'Increase nromp in b2.user.parameters')
! Here we need to guarantee ordering of CVs. With classical grids the conversion
! is done such that CVs are ordered from left to right and bottom to top wrt
! the structured computational domain. With fully unstructured grids this is not guaranteed.
! IDEA: project the cell center onto the segment and order CVs based on distance wrt one of the segment's extremes
! SAME FOR IMP
    CALL XERTST(m%isclassicalgrid .EQ. 1, &
&         ' OMP list need to be revised for fully unstructured grids')
    DO ic=2,nomp
      IF (geo%cvx(omp(ic)) .LT. geo%cvx(omp(ic-1))) CALL XERRAB(&
&                                                  'OMP LIST NOT SORTED'&
&                                                        )
    END DO
!   ..Definition of separatrix position in OMP list (to be improved for DN)
! Separatrix is defined by checking when cvReg changes value inside the OMP list
    icsepomp = 0
    ic = 1
    found = .false.
    DO WHILE (ic .LE. nomp .AND. (.NOT.found))
      IF (m%cvreg(omp(ic)) .NE. m%cvreg(omp(ic+1))) THEN
        found = .true.
        icsepomp = ic + 1
      END IF
      ic = ic + 1
    END DO
!
!   ..Create list of IMP control volumes
! Same logic as OMP list, find CVs intersected by rzimp segment
    nimp = 0
    imp = 0
    CALL CV_INTERSECTIONS_NODIFF(m%ncv, geo, m, rzimp, imp, nimp, nromp&
&                          , 1, ifail)
    CALL XERTST(.NOT.ifail, 'Increase nromp in b2.user.parameters')
    DO ic=2,nimp
      IF (geo%cvx(imp(ic)) .LT. geo%cvx(imp(ic-1))) CALL XERRAB(&
&                                                  'IMP LIST NOT SORTED'&
&                                                        )
    END DO
! Find position of separatrix in IMP list (same as for OMP)
    icsepimp = 0
    ic = 1
    found = .false.
    DO WHILE (ic .LE. nimp .AND. (.NOT.found))
      IF (m%cvreg(imp(ic)) .NE. m%cvreg(imp(ic+1))) THEN
        found = .true.
        icsepimp = ic + 1
      END IF
      ic = ic + 1
    END DO
    IF (.NOT.found) THEN
      WRITE(*, *) 'Warning: did not find separatrix in IMP definition'
      WRITE(*, *) 'check specification of RZIMP in b2.user.parameters'
      WRITE(*, *) 'if IMP is needed.'
    END IF
!flux surface of separatrix
    ifssep = 1
    found = .false.
!cv of flux tube just inside sep
    ic1 = omp(icsepomp-1)
!cv of flux tube just outside sep
    ic2 = omp(icsepomp)
    ifc1 = m%cvfcp(ic1, 1)
    ifc2 = ifc1 + m%cvfcp(ic1, 2) - 1
    ifc11 = m%cvfcp(ic2, 1)
! find face belonging to both ic1 and ic2
    ifc22 = ifc11 + m%cvfcp(ic2, 2) - 1
    DO 100 ii=ifc1,ifc2
      ifc = m%cvfc(ii)
      DO jj=ifc11,ifc22
        ifcc = m%cvfc(jj)
        IF (ifc .EQ. ifcc) GOTO 100
      END DO
 100 CONTINUE
! find this face in fsFc --> ii
    DO ii=1,SIZE(m%fsfc, 1)
      IF (ifc .EQ. m%fsfc(ii)) GOTO 110
    END DO
! find ii in fsFcP(ifs,1):fsFcP(ifs,1)+fsFcP(ifs,2)
 110 DO ifs=1,SIZE(m%fsfcp, 1)
      ifc1 = m%fsfcp(ifs, 1)
      ifc2 = ifc1 + m%fsfcp(ifs, 2) - 1
      IF (ii .GE. ifc1 .AND. ii .LE. ifc2) THEN
        found = .true.
        GOTO 120
      END IF
    END DO
 120 IF (.NOT.found) CALL XERRAB('No flux surface found for separatrix!'&
&                         )
    ifssep = ifs
    IF (m%isclassicalgrid .EQ. 1) CALL XERTST(m%fsfcp(ifssep, 2) .GT. 0&
&                                       , 'No separatrix faces!')
    WRITE(*, *) 'SEPARATRIX FLUX SURFACE AT ifs=', ifssep
!
    CALL SUBEND()
    RETURN
  END SUBROUTINE READ_B2MOD_USER_NAMELIST

!
  SUBROUTINE WRITE_B2MOD_USER_NAMELIST()
    IMPLICIT NONE
!
    IF (written) THEN
      RETURN
    ELSE
      IF (user_namelist_used .AND. write_nml_user) WRITE(*, user) 
      written = .true.
      RETURN
    END IF
  END SUBROUTINE WRITE_B2MOD_USER_NAMELIST

END MODULE B2MOD_USER_NAMELIST_DIFF

