!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
MODULE B2MOD_MATH_DIFF
  USE B2MOD_TYPES
  IMPLICIT NONE
!
!
  REAL(kind=r8), SAVE :: cutll, cutlo
  REAL(kind=r8), SAVE :: cutlob
  REAL(kind=r4), SAVE :: small_r4_constant
  LOGICAL, SAVE :: b2mod_math_initialised=.false.

CONTAINS
!  Differentiation of addup in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: addup
!   with respect to varying inputs: t0 t1
!
!-----------------------------------------------------------------------
!.documentation-internal
!
!     Let (p0x,p0y) specify a vector p0, and (p1x,p1y) specify
!     a vector p1. Then norm(p0x,p0y) is the standard norm of p0,
!     and cosang(p0x,p0y,p1x,p1y) is cos(t), where t is the complementary
!     angle between p0 and p1.
!     t=pi/2 when p0 and p1 are parallel, t=0 or t=pi when p0 and p1
!     are orthogonal, and t=-pi/2 when p0 and p1 are anti-parallel.
!
!-----------------------------------------------------------------------
!
!
  SUBROUTINE ADDUP_B(t0, t0b, t1, t1b, addupb)
    IMPLICIT NONE
    REAL(kind=r8) :: addup, t0, t1
    REAL(kind=r8) :: addupb, t0b, t1b
    t0b = addupb
    t1b = addupb
  END SUBROUTINE ADDUP_B

!
!-----------------------------------------------------------------------
!.documentation-internal
!
!     Let (p0x,p0y) specify a vector p0, and (p1x,p1y) specify
!     a vector p1. Then norm(p0x,p0y) is the standard norm of p0,
!     and cosang(p0x,p0y,p1x,p1y) is cos(t), where t is the complementary
!     angle between p0 and p1.
!     t=pi/2 when p0 and p1 are parallel, t=0 or t=pi when p0 and p1
!     are orthogonal, and t=-pi/2 when p0 and p1 are anti-parallel.
!
!-----------------------------------------------------------------------
!
!
  FUNCTION ADDUP(t0, t1)
    IMPLICIT NONE
    REAL(kind=r8) :: addup, t0, t1
    addup = t0 + t1
    RETURN
  END FUNCTION ADDUP

!
  FUNCTION COSANG(p0x, p0y, p1x, p1y)
    IMPLICIT NONE
    REAL(kind=r8) :: cosang, p0x, p0y, p1x, p1y
    REAL(kind=r8) :: result1
    REAL(kind=r8) :: result2
    REAL(kind=r8) :: arg1
    result1 = NORM(p0x, p0y)
    result2 = NORM(p1x, p1y)
    arg1 = (p0x*p1y-p0y*p1x)/(result1*result2)
    cosang = TRIM1(arg1)
    RETURN
  END FUNCTION COSANG

!  Differentiation of expu in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: expu
!   with respect to varying inputs: t0
!
  SUBROUTINE EXPU_B(t0, t0b, expub)
    IMPLICIT NONE
    REAL(kind=r8) :: expu, t0
    REAL(kind=r8) :: expub, t0b
    INTRINSIC MAX
    INTRINSIC EXP
    INTRINSIC DIM
    REAL(kind=r8) :: max1
    REAL(kind=r8) :: max1b
    REAL(kind=r8) :: arg1
    REAL(kind=r8) :: arg1b
    REAL(kind=r8) :: res
    REAL(kind=r8) :: resb
    INTEGER :: branch
    EXTERNAL DIM_FWD
  real(kind=r8) :: dim_fwd
    EXTERNAL DIM_BWD
    IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
    IF (t0 .LT. cutll) THEN
      max1 = cutll
      CALL PUSHCONTROL1B(0)
    ELSE
      max1 = t0
      CALL PUSHCONTROL1B(1)
    END IF
    arg1 = EXP(max1)
    res = DIM_FWD(arg1, cutlo)
    resb = expub
    CALL DIM_BWD(arg1, arg1b, cutlo, cutlob, resb)
    max1b = EXP(max1)*arg1b
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      t0b = 0.D0
    ELSE
      t0b = max1b
    END IF
  END SUBROUTINE EXPU_B

!
  FUNCTION EXPU(t0)
    IMPLICIT NONE
    REAL(kind=r8) :: expu, t0
    INTRINSIC MAX
    INTRINSIC EXP
    INTRINSIC DIM
    REAL(kind=r8) :: max1
    REAL(kind=r8) :: arg1
    IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
    IF (t0 .LT. cutll) THEN
      max1 = cutll
    ELSE
      max1 = t0
    END IF
    arg1 = EXP(max1)
    expu = DIM(arg1, cutlo)
    RETURN
  END FUNCTION EXPU

!
  FUNCTION EXPU1(t0)
    IMPLICIT NONE
    REAL(kind=r8) :: expu1, t0
    INTRINSIC MAX
    INTRINSIC EXP
    REAL(kind=r8) :: max1
    IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
    IF (t0 .LT. cutll) THEN
      max1 = cutll
    ELSE
      max1 = t0
    END IF
    expu1 = EXP(max1)
    RETURN
  END FUNCTION EXPU1

!  Differentiation of expu2 in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: expu2
!   with respect to varying inputs: t0
!
  SUBROUTINE EXPU2_B(t0, t0b, expu2b)
    IMPLICIT NONE
    REAL(kind=r8) :: expu2, t0
    REAL(kind=r8) :: expu2b, t0b
    INTRINSIC MAX
    INTRINSIC MIN
    INTRINSIC EXP
    INTRINSIC DIM
    REAL(r8) :: y1
    REAL(r8) :: y1b
    REAL(r8) :: min1
    REAL(r8) :: min1b
    REAL(r8) :: arg1
    REAL(r8) :: arg1b
    REAL(kind=r8) :: res
    REAL(kind=r8) :: resb
    INTEGER :: branch
    EXTERNAL DIM_FWD
  real(kind=r8) :: dim_fwd
    EXTERNAL DIM_BWD
    IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
    IF (t0 .LT. cutll) THEN
      y1 = cutll
      CALL PUSHCONTROL1B(0)
    ELSE
      y1 = t0
      CALL PUSHCONTROL1B(1)
    END IF
    IF (20.0_R8 .GT. y1) THEN
      min1 = y1
      CALL PUSHCONTROL1B(0)
    ELSE
      min1 = 20.0_R8
      CALL PUSHCONTROL1B(1)
    END IF
    arg1 = EXP(min1)
    res = DIM_FWD(arg1, cutlo)
    resb = expu2b
    CALL DIM_BWD(arg1, arg1b, cutlo, cutlob, resb)
    min1b = EXP(min1)*arg1b
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      y1b = min1b
    ELSE
      y1b = 0.D0
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      t0b = 0.D0
    ELSE
      t0b = y1b
    END IF
  END SUBROUTINE EXPU2_B

!
  FUNCTION EXPU2(t0)
    IMPLICIT NONE
    REAL(kind=r8) :: expu2, t0
    INTRINSIC MAX
    INTRINSIC MIN
    INTRINSIC EXP
    INTRINSIC DIM
    REAL(r8) :: y1
    REAL(r8) :: min1
    REAL(r8) :: arg1
    IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
    IF (t0 .LT. cutll) THEN
      y1 = cutll
    ELSE
      y1 = t0
    END IF
    IF (20.0_R8 .GT. y1) THEN
      min1 = y1
    ELSE
      min1 = 20.0_R8
    END IF
    arg1 = EXP(min1)
    expu2 = DIM(arg1, cutlo)
    RETURN
  END FUNCTION EXPU2

!
  FUNCTION EXPU4(t0)
    IMPLICIT NONE
    REAL(kind=r8) :: expu4, t0
    INTRINSIC MAX
    INTRINSIC EXP
    REAL(kind=r8) :: max1
    IF (.NOT.b2mod_math_initialised) CALL B2MOD_MATH_INIT()
    IF (t0 .LT. cutll) THEN
      max1 = cutll
    ELSE
      max1 = t0
    END IF
    expu4 = EXP(max1) + small_r4_constant
    RETURN
  END FUNCTION EXPU4

!
  INTEGER FUNCTION IBASE(n, incx)
    IMPLICIT NONE
    INTEGER :: n, incx
    INTRINSIC MAX
    IF (0 .LT. (1-n)*incx) THEN
      ibase = (1-n)*incx
    ELSE
      ibase = 0
    END IF
    RETURN
  END FUNCTION IBASE

!
  INTEGER FUNCTION IBASE1(n1, inc1x)
    IMPLICIT NONE
    INTEGER :: n1, inc1x
    INTRINSIC MAX
    IF (1 .LT. 1 + (1-n1)*inc1x) THEN
      ibase1 = 1 + (1-n1)*inc1x
    ELSE
      ibase1 = 1
    END IF
    RETURN
  END FUNCTION IBASE1

!  Differentiation of med in reverse (adjoint) mode, forward sweep (with options context noISIZE r8):
!   gradient     of useful results: t0 t1 t2 med
!   with respect to varying inputs: t0 t1 t2
!
  FUNCTION MED_FWD(t0, t0b, t1, t1b, t2, t2b) RESULT (med)
    IMPLICIT NONE
    REAL(kind=r8) :: med, t0, t1, t2
    INTRINSIC MAX
    INTRINSIC MIN
    REAL(kind=r8) :: t2b
    REAL(kind=r8) :: t0b
    REAL(kind=r8) :: t1b
    REAL(kind=r8) :: x1
    REAL(kind=r8) :: z1
    REAL(kind=r8) :: y1
    IF (t0 .LT. t1) THEN
      x1 = t1
      CALL PUSHCONTROL1B(0)
    ELSE
      x1 = t0
      CALL PUSHCONTROL1B(1)
    END IF
    IF (t1 .LT. t2) THEN
      y1 = t2
      CALL PUSHCONTROL1B(0)
    ELSE
      y1 = t1
      CALL PUSHCONTROL1B(1)
    END IF
    IF (t2 .LT. t0) THEN
      z1 = t0
      CALL PUSHCONTROL1B(0)
    ELSE
      z1 = t2
      CALL PUSHCONTROL1B(1)
    END IF
    IF (x1 .GT. y1) THEN
      IF (y1 .GT. z1) THEN
        med = z1
        CALL PUSHCONTROL2B(0)
      ELSE
        med = y1
        CALL PUSHCONTROL2B(1)
      END IF
    ELSE IF (x1 .GT. z1) THEN
      med = z1
      CALL PUSHCONTROL2B(2)
    ELSE
      med = x1
      CALL PUSHCONTROL2B(3)
    END IF
  END FUNCTION MED_FWD

!  Differentiation of med in reverse (adjoint) mode, backward sweep (with options context noISIZE r8):
!   gradient     of useful results: t0 t1 t2 med
!   with respect to varying inputs: t0 t1 t2
!
  SUBROUTINE MED_BWD(t0, t0b, t1, t1b, t2, t2b, medb)
    IMPLICIT NONE
    REAL(kind=r8) :: med, t0, t1, t2
    REAL(kind=r8) :: medb, t0b, t1b, t2b
    INTRINSIC MAX
    INTRINSIC MIN
    REAL(kind=r8) :: x1b
    REAL(kind=r8) :: y1b
    REAL(kind=r8) :: z1b
    INTEGER :: branch
    REAL(kind=r8) :: x1
    REAL(kind=r8) :: z1
    REAL(kind=r8) :: y1
    CALL POPCONTROL2B(branch)
    IF (branch .LT. 2) THEN
      IF (branch .EQ. 0) THEN
        z1b = medb
        y1b = 0.D0
      ELSE
        y1b = medb
        z1b = 0.D0
      END IF
      x1b = 0.D0
    ELSE
      IF (branch .EQ. 2) THEN
        z1b = medb
        x1b = 0.D0
      ELSE
        x1b = medb
        z1b = 0.D0
      END IF
      y1b = 0.D0
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      t0b = t0b + z1b
    ELSE
      t2b = t2b + z1b
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      t2b = t2b + y1b
    ELSE
      t1b = t1b + y1b
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      t1b = t1b + x1b
    ELSE
      t0b = t0b + x1b
    END IF
  END SUBROUTINE MED_BWD

!
  FUNCTION MED(t0, t1, t2)
    IMPLICIT NONE
    REAL(kind=r8) :: med, t0, t1, t2
    INTRINSIC MAX
    INTRINSIC MIN
    REAL(kind=r8) :: x1
    REAL(kind=r8) :: z1
    REAL(kind=r8) :: y1
    IF (t0 .LT. t1) THEN
      x1 = t1
    ELSE
      x1 = t0
    END IF
    IF (t1 .LT. t2) THEN
      y1 = t2
    ELSE
      y1 = t1
    END IF
    IF (t2 .LT. t0) THEN
      z1 = t0
    ELSE
      z1 = t2
    END IF
    IF (x1 .GT. y1) THEN
      IF (y1 .GT. z1) THEN
        med = z1
      ELSE
        med = y1
      END IF
    ELSE IF (x1 .GT. z1) THEN
      med = z1
    ELSE
      med = x1
    END IF
    RETURN
  END FUNCTION MED

!
  FUNCTION NORM(p0x, p0y)
    IMPLICIT NONE
    REAL(kind=r8) :: norm, p0x, p0y
    INTRINSIC SQRT
    norm = SQRT(p0x**2 + p0y**2)
    RETURN
  END FUNCTION NORM

!
  FUNCTION SINANG(p0x, p0y, p1x, p1y)
    IMPLICIT NONE
    REAL(kind=r8) :: sinang, p0x, p0y, p1x, p1y
    REAL(kind=r8) :: result1
    REAL(kind=r8) :: result2
    REAL(kind=r8) :: arg1
    result1 = NORM(p0x, p0y)
    result2 = NORM(p1x, p1y)
    arg1 = (p0x*p1x+p0y*p1y)/(result1*result2)
    sinang = TRIM1(arg1)
    RETURN
  END FUNCTION SINANG

!
  FUNCTION TRIM1(p0x)
    IMPLICIT NONE
    REAL(kind=r8) :: trim1, p0x
    INTRINSIC MIN
    INTRINSIC MAX
    REAL(r8) :: y1
    IF (1.0_R8 .GT. p0x) THEN
      y1 = p0x
    ELSE
      y1 = 1.0_R8
    END IF
    IF (-1.0_R8 .LT. y1) THEN
      trim1 = y1
    ELSE
      trim1 = -1.0_R8
    END IF
    RETURN
  END FUNCTION TRIM1

!
  FUNCTION TRUNC(t0, edg)
    IMPLICIT NONE
    REAL(kind=r8) :: trunc, t0, edg
    INTRINSIC MIN
    INTRINSIC MAX
    REAL(kind=r8) :: y1
    IF (1 + edg .GT. t0) THEN
      y1 = t0
    ELSE
      y1 = 1 + edg
    END IF
    IF (-edg .LT. y1) THEN
      trunc = y1
    ELSE
      trunc = -edg
    END IF
    RETURN
  END FUNCTION TRUNC

!
  LOGICAL FUNCTION LTST(t0, t1)
    IMPLICIT NONE
    REAL(kind=r8) :: t0, t1
    INTRINSIC ABS
    REAL(kind=r8) :: abs0
    REAL(kind=r8) :: abs1
    REAL(kind=r8) :: abs2
    IF (t0 - t1 .GE. 0.) THEN
      abs0 = t0 - t1
    ELSE
      abs0 = -(t0-t1)
    END IF
    IF (t0 .GE. 0.) THEN
      abs1 = t0
    ELSE
      abs1 = -t0
    END IF
    IF (t1 .GE. 0.) THEN
      abs2 = t1
    ELSE
      abs2 = -t1
    END IF
    ltst = abs0 .LE. 1.0e-6_R8*(abs1+abs2)
    RETURN
  END FUNCTION LTST

!
!
  SUBROUTINE B2MOD_MATH_INIT()
    IMPLICIT NONE
    EXTERNAL MACHSFR
    REAL(kind=r8) :: MACHSFR
    INTRINSIC LOG
    INTRINSIC EXP
    INTRINSIC MAX
    INTRINSIC TINY
    REAL(kind=r8) :: result1
    REAL(kind=r8) :: x1
    REAL(kind=r8) :: y1
!   ..set cutll, cutlo
    result1 = MACHSFR()
    cutll = LOG(result1)
    x1 = MACHSFR()
    y1 = EXP(cutll)
    IF (x1 .LT. y1) THEN
      cutlo = y1
    ELSE
      cutlo = x1
    END IF
    small_r4_constant = TINY(small_r4_constant)
    b2mod_math_initialised = .true.
    RETURN
  END SUBROUTINE B2MOD_MATH_INIT

END MODULE B2MOD_MATH_DIFF

