!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!!-----------------------------------------------------------------------------
!! DOCUMENTATION:
!>      @section b2uw_ualio_desc Description
!!      Module providing main routines for setting processed B2.5 data for
!!      ITM CPO edge or IMAS edge_profiles, edge_sources and edge_transport IDSs.
!!
!!      @detail The data comprises of grid geometry, grid subsets and data
!!              fields of various quantities.
!!
!!      @subsection b2uw_ualio_syx     Exceptional syntax explanation
!!      @code
!!          ! IGNORE    !! syntax used to ignore this module in list
!!                      !! dependency when compiling the code
!!      @endcode
!!
!!-----------------------------------------------------------------------------
MODULE B2MOD_UAL_IO_DIFF
!! B2 modules
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFF
  USE B2MOD_B2CMRC_DIFF
  USE B2MOD_GEO_DIFF
  USE B2MOD_WORK
  USE B2MOD_DIAG_DIFF
  USE B2MOD_MWTI
  USE B2MOD_RATES
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2MOD_ELEMENTS_DIFF
  USE B2MOD_CONSTANTS
  USE B2MOD_SOURCES_DIFF
  USE B2MOD_FEEDBACK_DIFF
  USE B2MOD_TRANSPORT_DIFF
  USE B2MOD_ANOMALOUS_TRANSPORT_DIFF
  USE B2MOD_BOUNDARY_NAMELIST_DIFF
  USE B2MOD_NEUTRALS_NAMELIST_DIFF
  USE B2MOD_USER_NAMELIST_DIFF
  USE B2MOD_INDIRECT
  USE B2MOD_EXTERNAL_DIFF
  USE B2MOD_INTERP
  USE B2MOD_IPMAIN
  USE B2MOD_B2CMRC_DIFF
  USE B2MOD_B2CMFS
  USE B2MOD_B2CMPB_DIFF
  USE B2MOD_VERSION_DIFF
  USE B2MOD_SWITCHES_DIFF
  USE B2MOD_GRID_MAPPING
  USE B2MOD_B2PLOT_WALL_LOADING
  USE LOGGING
  IMPLICIT NONE
  PUBLIC :: b25_process_ids, b25_av_ids
!< Total number of time slices.
  INTEGER, PUBLIC :: num_time_slices
!< Total number of batch slices.
  INTEGER, PUBLIC :: num_batch_slices
  PRIVATE 
  REAL(kind=r8) :: b25_process_ids
  REAL(kind=r8) :: b25_av_ids
END MODULE B2MOD_UAL_IO_DIFF
!!!Local Variables:
!!! mode: f90
!!! End:

