!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
SUBROUTINE B2STBC_FB_POST_NODIFF(ncv, nfc, nvx, ns, ismain, switch, geo&
& , mpg, pl, dv, srw, main_call)
  USE B2MOD_TYPES
!      use b2mod_rates
!      use b2mod_indirect
  USE B2MOD_CONSTANTS
  USE B2MOD_FEEDBACK_DIFF
  USE B2MOD_B2CMPA_DIFF
!      use b2mod_b2cmpb
  USE B2MOD_BOUNDARY_NAMELIST_DIFF
  USE B2MOD_NEUTRALS_NAMELIST_DIFF
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!-----------------------------------------------------------------------
!.end b2stbc_fb_post
!
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns, ismain
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  LOGICAL :: main_call
!   ..output arguments (unspecified on entry)
  TYPE(B2SOURCEWORK), INTENT(INOUT) :: srw
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2STBC_FB provides linearised expressions for the sources of
!     density, parallel momentum, electron heat, atom heat, and charge,
!     due to feedback boundary conditions after the normal boundary
!     conditions have been applied.
!
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ncall
  SAVE ncall
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG_NODIFF, B2XVPS_NODIFF
  EXTERNAL XERRAB
  INTEGER :: arg1
!   ..initialisation
  DATA ncall /0/
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2stbc_fb')
!   ..set internal parameters on first call
  IF (ncall .EQ. 0) THEN
    CALL READ_B2MOD_FEEDBACK_CONTROL(99)
    CALL READ_B2MOD_FEEDBACK(99, '    ', feedback_namelist_used)
  END IF
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
  CALL XERTST(0 .LE. ismain .AND. ismain .LT. ns, &
&       'invalid main plasma species index ismain')
  CALL XERTST(.NOT.is_neutral(ismain), &
&       'invalid main plasma species ismain; must not be neutral')
!   ..extensive tests on first few calls
  IF (ncall .LT. 3) THEN
!    ..test sign of vol
    CALL B2XVSG_NODIFF(ncv, geo%cvvol, 1, 'vol', '.gt.')
    arg1 = nfc*2
    CALL B2XVSG_NODIFF(arg1, geo%fcvol, 1, 'vol', '.gt.')
!    ..test state
    CALL B2XVPS_NODIFF(ncv, nfc, ns, pl, dv)
  END IF
!
! process feedbacks in b2.feedback_control.parameters
  IF (vacuum_communication .GT. 0) CALL XERRAB(&
&                        'vacuum communication not yet converted in WG!'&
&                                       )
!
! ..return
  IF (ncall .EQ. 0 .OR. main_call) ncall = ncall + 1
  CALL SUBEND()
  IF (ncall .GT. 1 .OR. (.NOT.main_call)) THEN
    RETURN
  ELSE
    CALL B2STBC_FB_FINAL_NODIFF()
    RETURN
  END IF
END SUBROUTINE B2STBC_FB_POST_NODIFF

!
! ..finalise feedback
SUBROUTINE B2STBC_FB_FINAL_NODIFF()
  USE B2MOD_TYPES
  USE B2MOD_FEEDBACK_DIFF
  IMPLICIT NONE
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  result1 = MAXVAL(saved_na_feedback_actuator)
  result2 = MAX(saved_cbshe_core, saved_cbshi_core, saved_cbsna_core, &
&   saved_cbsch_core, saved_cbsna_pfr1, saved_cbsna_pfr2, &
&   saved_cbsna_sol, result1)
  feedback_namelist_used = feedback_namelist_used .OR. result2 .GT. &
&   0.0_R8
  IF (feedback_namelist_used) CALL WRITE_B2MOD_FEEDBACK(99, '    ')
  RETURN
END SUBROUTINE B2STBC_FB_FINAL_NODIFF

!
!-----------------------------------------------------------------------
!.specification
SUBROUTINE B2STBC_FB_PRE_NODIFF(ncv, nfc, nvx, ns, ismain, boris, switch&
& , geo, mpg, pl, dv, rt, srw, psnc, psnl, main_call, diagno)
  USE B2MOD_TYPES
  USE B2MOD_RATES
  USE B2MOD_INDIRECT
  USE B2MOD_CONSTANTS
  USE B2MOD_FEEDBACK_DIFF
  USE B2MOD_B2CMPA_DIFF
  USE B2MOD_B2CMPB_DIFF
  USE B2MOD_DIAG_DIFF
  USE B2MOD_TIME
  USE B2MOD_NEUTRALS_NAMELIST_DIFF
  USE B2MOD_BOUNDARY_NAMELIST_DIFF
  USE B2MOD_USER_NAMELIST_DIFF, ONLY : omp, icsepomp, ifssep
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2stbc_fb_pre
!
!  Common dimensions
!
!  version : 01.12.98 21:42
!
!
!
! parameters that are common to Eirene and B2
!
!
! NOTE: DEF_NXD should not include the additional cells to handle the cuts
!*** Max. number of groups of Eirene surfaces for which the data can
!*** be transferred from B2 (DG specification "Surface special")
!
! new! [2002.04.22]
! new! [2002.06.14]
!
!
! parameters that are unique to B2
!
!
!
!
! parameters that are unique to Eirene
!
!
!
!
! parameters needed by uinp
!
!
!
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns, ismain, diagno
  REAL(kind=r8) :: boris
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2PLASMA), INTENT(INOUT) :: pl
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2RATES), INTENT(IN) :: rt
  TYPE(B2PLASMASNAPSHOT), INTENT(INOUT) :: psnc, psnl
  LOGICAL :: main_call
!   ..output arguments (unspecified on entry)
  TYPE(B2SOURCEWORK), INTENT(INOUT) :: srw
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2STBC_FB_PRE provides a change to the plasma or boundary conditions
!
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ncall, icv, is, ispecies, is0, is_start, is_end, ix, iy, ib&
& , iss, ifc, ifc1, ifc2, ic1, ic2
  INTEGER, SAVE :: coreregno, coreregn2, solregno, pfrregno1, pfrregno2&
& , isfeedback
  REAL(kind=r8) :: na_feedback_current, na_feedback_rescale, &
& vol_feedback, dtim, na_feedback_prev(0:6-1), na_feedback_save(0:6-1), &
& dt_prev, sum_e, sum_s, total_flux
  REAL(kind=r8), ALLOCATABLE :: charge_frac(:)
  INTEGER, SAVE :: b2sral_style=2
  CHARACTER(len=72) :: message
  LOGICAL, SAVE :: consistent
  SAVE ncall, dtim, dt_prev, na_feedback_prev, na_feedback_save
!   ..procedures
  EXTERNAL XERTST, IPGETR, IPGETI
  EXTERNAL B2XVSG_NODIFF
  INTRINSIC MINVAL
  EXTERNAL XERRAB
  INTRINSIC LOG
  INTRINSIC TANH
  INTRINSIC EXP
  INTRINSIC TRIM
  INTRINSIC MIN
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  INTEGER :: arg1
  REAL(kind=r8) :: result10
!   ..initialisation
  DATA ncall /0/
  DATA dtim /1.0_R8/
  DATA na_feedback_save /6*0.0_R8/
  DATA na_feedback_prev /6*0.0_R8/
  DATA coreregno /1/
  DATA coreregn2 /4/
  DATA solregno /3/
  DATA pfrregno1 /0/
  DATA pfrregno2 /2/
  DATA isfeedback /0/
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2stbc_fb_pre')
! ncall.eq.0
!   ..set internal parameters on first call
  IF (ncall .EQ. 0) THEN
!       call get_jsep(nx,ny,jxi,jxa,jsep)
    CALL XERTST(icsepomp .GT. 0, &
&         'Invalid icsepomp value, check rzomp in b2.user.parameters')
    CALL READ_B2MOD_FEEDBACK_CONTROL(99)
    CALL READ_B2MOD_FEEDBACK(99, '    ', feedback_namelist_used)
    CALL IPGETR('b2mndr_dtim', dtim)
    CALL XERTST(dtim .GT. 0.0_R8, 'faulty parameter dtim')
    dt_prev = dtim
!   ..test for input consistency, i.e. are the cbs.. arrays used in the b.c settings
    CALL IPGETI('b2sral_style', b2sral_style)
    consistent = .true.
    DO ispecies=0,nspecies-1
      IF (na_feedback_ib(ispecies) .GT. 0) THEN
        is0 = eb2spcr(ispecies+1)
        is_start = eb2spcr(ispecies+1) + 1
        is_end = eb2spcr(ispecies+1) + nfluids(ispecies+1)
        result1 = MAXVAL(bccon(is_start:is_end, na_feedback_ib(ispecies)&
&         ))
        result2 = MINVAL(bccon(is_start:is_end, na_feedback_ib(ispecies)&
&         ))
        consistent = consistent .AND. (((((((na_feedback_target(ispecies&
&         ) .EQ. 0.0_R8 .OR. na_feedback_choice(ispecies) .EQ. 0) .OR. &
&         na_feedback_option(ispecies) .EQ. 0) .OR. na_feedback_actuator&
&         (ispecies) .EQ. 0) .OR. na_feedback_actuator(ispecies) .EQ. 2)&
&         .OR. (na_feedback_actuator(ispecies) .EQ. 1 .AND. bccon(is0, &
&         na_feedback_ib(ispecies)) .EQ. 11)) .OR. (na_feedback_actuator&
&         (ispecies) .EQ. 1 .AND. bccon(is0, na_feedback_ib(ispecies)) &
&         .EQ. 13)) .OR. (na_feedback_actuator(ispecies) .EQ. 3 .AND. &
&         result1 .EQ. 11 .AND. result2 .EQ. 11 .AND. na_feedback_choice&
&         (ispecies) .EQ. 6))
      END IF
    END DO
    consistent = ((consistent .OR. lbndusr) .OR. b2sral_style .EQ. 1) &
&     .OR. switch%b2stbc_boundary_namelist .LT. 1
    DO ispecies=0,nspecies-1
      IF (na_feedback_ib(ispecies) .LT. 0) consistent = consistent .AND.&
&         (.NOT.(na_feedback_actuator(ispecies) .EQ. 1 .OR. &
&         na_feedback_actuator(ispecies) .EQ. 3)) .AND. (.NOT.&
&         na_feedback_option(ispecies) .EQ. 4)
    END DO
    DO ispecies=0,nspecies-1
      IF (na_feedback_actuator(ispecies) .EQ. 2) THEN
        DO is=is_start,is_end
          DO ib=1,nbc
            consistent = consistent .AND. (((((((((bccon(is, ib) .EQ. 0 &
&             .OR. bccon(is, ib) .EQ. 2) .OR. bccon(is, ib) .EQ. 3) .OR.&
&             bccon(is, ib) .EQ. 4) .OR. bccon(is, ib) .EQ. 9) .OR. &
&             bccon(is, ib) .EQ. 10) .OR. bccon(is, ib) .EQ. 14) .OR. &
&             bccon(is, ib) .EQ. 15) .OR. (bccon(is, ib) .EQ. 5 .AND. &
&             conpar(is, ib, 1) .EQ. 0.0_R8)) .OR. (bccon(is, ib) .EQ. 8&
&             .AND. conpar(is, ib, 1) .EQ. 0.0_R8))
          END DO
        END DO
      END IF
    END DO
    CALL XERTST(consistent, &
&         'feedback scheme not consistent with B.C.''s!')
!  ..now read data for other feedback schemes given directly in b2mn.dat
    IF (nnreg(0) .LE. 2) THEN
      coreregno = 0
    ELSE
      coreregno = 1
    END IF
    CALL IPGETI('b2stbc_coreregno', coreregno)
    CALL IPGETI('b2stbc_coreregn2', coreregn2)
    CALL IPGETI('b2stbc_solregno', solregno)
    CALL IPGETI('b2stbc_pfrregno1', pfrregno1)
    CALL IPGETI('b2stbc_pfrregno2', pfrregno2)
    CALL IPGETI('b2stbc_isfeedback', isfeedback)
    CALL XERTST(0 .LE. isfeedback .AND. isfeedback .LT. ns, &
&         'faulty internal parameter isfeedback')
  END IF
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
  CALL XERTST(0 .LE. ismain .AND. ismain .LT. ns, &
&       'invalid main plasma species index ismain')
  CALL XERTST(.NOT.is_neutral(ismain), &
&       'invalid main plasma species ismain; must not be neutral')
!   ..extensive tests on first few calls
  IF (ncall .LT. 3) THEN
!    ..test sign of vol
    CALL B2XVSG_NODIFF(ncv, geo%cvvol, 1, 'vol', '.gt.')
    arg1 = nfc*2
    CALL B2XVSG_NODIFF(arg1, geo%fcvol, 1, 'vol', '.gt.')
!    ..test state
    CALL B2XVPS_NODIFF(ncv, nfc, ns, pl, dv)
  END IF
!
  result10 = MAXVAL(na_feedback_target(0:nspecies-1))
  result2 = MAXVAL(na_feedback_choice(0:nspecies-1))
  IF (result10 .GT. 0.0_R8 .OR. result2 .GT. 0) THEN
! we have a request for feedback control of na
! the idea here is to break the actions into 3 phases
! 1/ calculate something based on the present state of the plasma depending on a
!    species block based on "na_feedback_choice"
! 2/ compare this with the reference value and calculate a change
! 3/ apply this in some way to the species block based on "na_feedback_actuator"
!
    DO ispecies=0,nspecies-1
!
      IF (na_feedback_choice(ispecies) .GT. 0 .AND. na_feedback_option(&
&         ispecies) .GT. 0 .AND. na_feedback_actuator(ispecies) .GT. 0) &
&     THEN
!
        IF (main_call) na_feedback_prev(ispecies) = na_feedback_save(&
&           ispecies)
!
! phase 1:
        SELECT CASE  (na_feedback_choice(ispecies)) 
        CASE (0) 

        CASE (1) 
!
! no action
!
! local density of isonuclear sequence
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=1 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using ', &
&           'local_density for sequence ', ispecies + 1
          END IF
!
          na_feedback_current = 0.0_R8
          vol_feedback = 0.0_R8
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (b2espcr(is) .EQ. ispecies + 1) THEN
              IF (is_start .EQ. -1) is_start = is
              DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(ispecies)
                DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(ispecies&
&                   )
                  icv = mpg%imapcv(ix, iy)
                  na_feedback_current = na_feedback_current + pl%na(icv&
&                   , is)*geo%cvvol(icv)
                  IF (is .EQ. is_start) vol_feedback = vol_feedback + &
&                     geo%cvvol(icv)
                END DO
              END DO
              is_end = is
            END IF
          END DO
          na_feedback_current = na_feedback_current/vol_feedback
        CASE (2) 
!
! local electron density
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=1 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using ', &
&           'local_electron_density for sequence ', ispecies + 1
          END IF
!
          na_feedback_current = 0.0_R8
          vol_feedback = 0.0_R8
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (b2espcr(is) .EQ. ispecies + 1) THEN
              IF (is_start .EQ. -1) is_start = is
              is_end = is
            END IF
          END DO
          DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(ispecies)
            DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(ispecies)
              icv = mpg%imapcv(ix, iy)
              na_feedback_current = na_feedback_current + dv%ne(icv)*geo&
&               %cvvol(icv)
              vol_feedback = vol_feedback + geo%cvvol(icv)
            END DO
          END DO
          na_feedback_current = na_feedback_current/vol_feedback
        CASE (3) 
!
! nesepm electron density
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_choice: using ', &
&                           'nesepm_electron_density for sequence ', &
&                           ispecies + 1
!
          na_feedback_current = 0.5_R8*(dv%ne(omp(icsepomp-1))+dv%ne(omp&
&           (icsepomp)))
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (b2espcr(is) .EQ. ispecies + 1) THEN
              IF (is_start .EQ. -1) is_start = is
              is_end = is
            END IF
          END DO
        CASE (4) 
!
! total particle content for that isonuclear sequence
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=4 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using ', &
&           'total particle content for sequence ', ispecies + 1
          END IF
          na_feedback_current = 0.0_R8
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (b2espcr(is) .EQ. ispecies + 1) THEN
              IF (is_start .EQ. -1) is_start = is
              DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(ispecies)
                DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(ispecies&
&                   )
                  icv = mpg%imapcv(ix, iy)
                  IF (mpg%cvreg(icv) .NE. 0 .AND. icv .LE. mpg%nci) &
&                   na_feedback_current = na_feedback_current + pl%na(&
&                     icv, is)*geo%cvvol(icv)
                END DO
              END DO
              is_end = is
            END IF
          END DO
        CASE (5) 
!
! total ion content for that isonuclear sequence
! (not including neutrals)
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=5 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using ', &
&           'total ion content for sequence ', ispecies + 1
          END IF
          na_feedback_current = 0.0_R8
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (.NOT.is_neutral(is)) THEN
              IF (b2espcr(is) .EQ. ispecies + 1) THEN
                IF (is_start .EQ. -1) is_start = is
                DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(ispecies&
&                   )
                  DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(&
&                     ispecies)
                    icv = mpg%imapcv(ix, iy)
                    IF (mpg%cvreg(icv) .NE. 0 .AND. icv .LE. mpg%nci) &
&                     na_feedback_current = na_feedback_current + pl%na(&
&                       icv, is)*geo%cvvol(icv)
                  END DO
                END DO
                is_end = is
              END IF
            END IF
          END DO
        CASE (6) 
!
! neutral particle flux through the core boundary
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=6 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using ', &
&           'core boundary flux for sequence ', ispecies + 1
          END IF
          na_feedback_current = na_feedback_const(ispecies)
          WRITE(*, *) 'WARNING: na_feedback_choice = 6 needs to be'//&
&         ' adapted for hybrid methods!'
          CALL XERRAB('na_feedback_choice=6 not yet adapted for'//&
&               ' pure fluid cases')
          is_start = eb2spcr(ispecies+1)
          is_end = eb2spcr(ispecies+1) + nfluids(ispecies+1)
          ALLOCATE(charge_frac(1:is_end-is_start+1))
          charge_frac = 0.0_R8
          sum_s = 0.0_R8
          DO is=is_start,is_end
            iss = is - is_start + 1
            IF (.NOT.(is_neutral(is) .AND. switch%use_eirene .NE. 0)) &
&           THEN
              DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(ispecies)
                DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(ispecies&
&                   )
                  icv = mpg%imapcv(ix, iy)
                  IF (mpg%cvonclosedsurface(icv)) THEN
                    sum_s = sum_s + pl%na(icv, is)*geo%cvvol(icv)
                    charge_frac(iss) = charge_frac(iss) + pl%na(icv, is)&
&                     *geo%cvvol(icv)
                  END IF
                END DO
              END DO
            END IF
          END DO
          charge_frac = charge_frac/sum_s
        CASE (7) 
!
! relative average concentration of this species at the separatrix
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=7 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using ', &
&           'average separatrix concentration for sequence ', ispecies +&
&           1
          END IF
          na_feedback_current = 0.0_R8
          sum_e = 0.0_R8
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (b2espcr(is) .EQ. ispecies + 1) THEN
              IF (is_start .EQ. -1) is_start = is
              IF (.NOT.(is_neutral(is) .AND. switch%use_eirene .NE. 0)) &
&             THEN
                ifc1 = mpg%fsfcp(ifssep, 1)
                ifc2 = ifc1 + mpg%fsfcp(ifssep, 2) - 1
! csc Here the idea is to follow the separatrix along its flux surface, then use the two CVs
!     belonging to each face of the flux surface
                DO ifc=ifc1,ifc2
                  ic1 = mpg%fccv(mpg%fsfc(ifc), 1)
                  ic2 = mpg%fccv(mpg%fsfc(ifc), 2)
                  IF (mpg%cvonclosedsurface(ic1) .OR. mpg%&
&                     cvonclosedsurface(ic2)) THEN
                    na_feedback_current = na_feedback_current + (pl%na(&
&                     ic1, is)+pl%na(ic2, is))*geo%fcs(mpg%fsfc(ifc))
                    IF (is .EQ. is_start + 1) sum_e = sum_e + (dv%ne(ic1&
&                       )+dv%ne(ic2))*geo%fcs(mpg%fsfc(ifc))
                  END IF
                END DO
                is_end = is
              END IF
            END IF
          END DO
          na_feedback_current = na_feedback_current/sum_e
        CASE (8) 
!
! relative average concentration of this species on desired domain
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_choice=8 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_choice: using average '&
&           , 'concentration for sequence ', ispecies + 1
          END IF
          na_feedback_current = 0.0_R8
          sum_e = 0.0_R8
          is_start = -1
          is_end = -1
          DO is=0,ns-1
            IF (b2espcr(is) .EQ. ispecies + 1) THEN
              IF (is_start .EQ. -1) is_start = is
              IF (.NOT.(is_neutral(is) .AND. switch%use_eirene .NE. 0)) &
&             THEN
                DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(ispecies&
&                   )
                  DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(&
&                     ispecies)
                    icv = mpg%imapcv(ix, iy)
                    na_feedback_current = na_feedback_current + pl%na(&
&                     icv, is)*geo%cvvol(icv)
                    IF (is .EQ. is_start + 1) sum_e = sum_e + dv%ne(icv)&
&                       *geo%cvvol(icv)
                  END DO
                END DO
                is_end = is
              END IF
            END IF
          END DO
          na_feedback_current = na_feedback_current/sum_e
        CASE (9) 
!
! inner midplane electron density
          CALL XERRAB('na_feedback_choice=9 not yet coverted in WG')
        CASE DEFAULT
          WRITE(*, *) 'na feedback_choice not coded ', &
&         na_feedback_choice(ispecies)
        END SELECT
!
!
! phase 2:
!
        SELECT CASE  (na_feedback_option(ispecies)) 
        CASE (0) 

        CASE (1) 
!
! no action
!
! rescale slowed by na_feedback_alpha
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_option: using ', &
&                           'slowed_rescale for sequence ', ispecies + 1
!
          na_feedback_rescale = (1.0_R8+na_feedback_alpha(ispecies)*&
&           na_feedback_target(ispecies)/na_feedback_current)/(1.0_R8+&
&           na_feedback_alpha(ispecies))
        CASE (2) 
!
! pure rescale
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_option: using ', &
&                           'rescale for sequence ', ispecies + 1
!
          na_feedback_rescale = na_feedback_target(ispecies)/&
&           na_feedback_current
        CASE (3) 
!
! rescale slowed by tanh_log
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_option: using ', &
&                           'tanh_log_rescale for sequence ', ispecies +&
&                           1
!
! 2**(tanh(log(x)/b)*log(a)/log(2))
          na_feedback_rescale = 2.0_R8**(TANH(LOG(na_feedback_target(&
&           ispecies)/na_feedback_current)/na_feedback_beta(ispecies))*&
&           LOG(na_feedback_alpha(ispecies))/LOG(2.0_R8))
        CASE (4) 
!
! rescale done according to SOLPS4 formula:
! N = A + B*(time-T)
!
          IF (ncall .EQ. 0) THEN
            CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&                'na_feedback_option=4 not available for extended grids'&
&                )
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_option: using ', &
&           'SOLPS4 linear increase for sequence ', ispecies + 1
            IF (na_feedback_const(ispecies) .LT. 0.0_R8) THEN
              na_feedback_const(ispecies) = 0.0_R8
              is_start = -1
              is_end = -1
              DO is=0,ns-1
                IF (b2espcr(is) .EQ. ispecies + 1) THEN
                  IF (is_start .EQ. -1) is_start = is
                  DO iy=na_feedback_iy1(ispecies),na_feedback_iy2(&
&                     ispecies)
                    DO ix=na_feedback_ix1(ispecies),na_feedback_ix2(&
&                       ispecies)
                      icv = mpg%imapcv(ix, iy)
                      IF (mpg%cvreg(icv) .NE. 0 .AND. icv .LE. mpg%nci) &
&                       na_feedback_const(ispecies) = na_feedback_const(&
&                         ispecies) + pl%na(icv, is)*geo%cvvol(icv)
                    END DO
                  END DO
                  is_end = is
                END IF
              END DO
            END IF
            na_feedback_prev(ispecies) = na_feedback_current
          END IF
!
          na_feedback_target(ispecies) = na_feedback_const(ispecies) + &
&           na_feedback_beta(ispecies)*(tim-na_feedback_time(ispecies))
          na_feedback_rescale = na_feedback_alpha(ispecies)*((&
&           na_feedback_target(ispecies)-na_feedback_current)/dtim+(&
&           na_feedback_prev(ispecies)-na_feedback_current)/dt_prev)
          na_feedback_save(ispecies) = na_feedback_current
        CASE (5) 
!
! rescale done according to SOLPS4 formula:
! Nt = A*exp((time-T)*B)
!
          IF (ncall .EQ. 0) THEN
            WRITE(*, '(a,a,i3)') 'b2stbc_fb_pre_option: using ', &
&           'SOLPS4 exponential decay for sequence ', ispecies + 1
            IF (na_feedback_const(ispecies) .LT. 0.0_R8) THEN
              na_feedback_const(ispecies) = 0.0_R8
              is_start = -1
              is_end = -1
              DO is=0,ns-1
                IF (b2espcr(is) .EQ. ispecies + 1) THEN
                  IF (is_start .EQ. -1) is_start = is
                  DO icv=1,mpg%nci
                    IF (mpg%cvreg(icv) .NE. 0) na_feedback_const(&
&                     ispecies) = na_feedback_const(ispecies) + pl%na(&
&                       icv, is)*geo%cvvol(icv)
                  END DO
                  is_end = is
                END IF
              END DO
            END IF
            na_feedback_prev(ispecies) = na_feedback_current
          END IF
!
          na_feedback_target(ispecies) = na_feedback_const(ispecies)*EXP&
&           (na_feedback_beta(ispecies)*(tim-na_feedback_time(ispecies))&
&           )
          na_feedback_rescale = na_feedback_alpha(ispecies)*((&
&           na_feedback_target(ispecies)-na_feedback_current)/dtim+(&
&           na_feedback_prev(ispecies)-na_feedback_current)/dt_prev)
          na_feedback_save(ispecies) = na_feedback_current
        CASE (6) 
!
! rescale slowed by na_feedback_alpha (SOLPS4 style)
!
          na_feedback_rescale = na_feedback_alpha(ispecies)*&
&           na_feedback_current
        CASE DEFAULT
!
          WRITE(*, *) 'na feedback_option not coded ', &
&         na_feedback_option(ispecies)
        END SELECT
!
        WRITE(*, '(a,1x,1p,i3,6g15.6)') 'na_feedback_rescale ', ispecies&
&       + 1, na_feedback_current, na_feedback_target(ispecies), &
&       na_feedback_rescale, na_feedback_prev(ispecies), dtim, dt_prev
!
!
! phase 3:
!
        SELECT CASE  (na_feedback_actuator(ispecies)) 
        CASE (0) 

        CASE (1) 
!
! no action
!
! gas puff via boundary condition
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_actuator: using ', &
&                           'gas_puff for sequence ', ispecies + 1
!
          IF (feedback_namelist_used .AND. ncall .EQ. 0 .AND. &
&             saved_na_feedback_actuator(ispecies) .EQ. 0.0_R8) THEN
            WRITE(message, '(a,i3,a,i2,a)') &
&           'Initial gas puff strength.le.0, set by CONPAR(', is_start, &
&           ',', na_feedback_ib(ispecies), ',1) !'
            CALL XERTST(conpar(is_start, na_feedback_ib(ispecies), 1) &
&                 .GT. 0.0_R8, TRIM(message))
            saved_na_feedback_actuator(ispecies) = conpar(is_start, &
&             na_feedback_ib(ispecies), 1)
          END IF
!
          IF (na_feedback_option(ispecies) .LT. 4) THEN
            saved_na_feedback_actuator(ispecies) = &
&             saved_na_feedback_actuator(ispecies)*na_feedback_rescale
          ELSE
            saved_na_feedback_actuator(ispecies) = na_feedback_rescale
          END IF
          IF (na_feedback_puff_min(ispecies) .GE. 0.0_R8) THEN
            IF (na_feedback_puff_min(ispecies) .LT. &
&               saved_na_feedback_actuator(ispecies)) THEN
              saved_na_feedback_actuator(ispecies) = &
&               saved_na_feedback_actuator(ispecies)
            ELSE
              saved_na_feedback_actuator(ispecies) = &
&               na_feedback_puff_min(ispecies)
            END IF
          END IF
          IF (na_feedback_puff_max(ispecies) .GT. 0.0_R8) THEN
            IF (na_feedback_puff_max(ispecies) .GT. &
&               saved_na_feedback_actuator(ispecies)) THEN
              saved_na_feedback_actuator(ispecies) = &
&               saved_na_feedback_actuator(ispecies)
            ELSE
              saved_na_feedback_actuator(ispecies) = &
&               na_feedback_puff_max(ispecies)
            END IF
          END IF
!
          IF (na_feedback_overshoot(ispecies) .GT. 1.0_R8 .AND. &
&             na_feedback_current .GT. na_feedback_target(ispecies)*&
&             na_feedback_overshoot(ispecies)) THEN
            conpar(is_start, na_feedback_ib(ispecies), 1) = 0.0_R8
          ELSE
            conpar(is_start, na_feedback_ib(ispecies), 1) = &
&             saved_na_feedback_actuator(ispecies)
          END IF
        CASE (2) 
!
! rescale na
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_actuator: using ', &
&                           'rescale for sequence ', ispecies + 1
!
          DO is=is_start,is_end
            pl%na(:, is) = pl%na(:, is)*na_feedback_rescale
            dv%kinrgy(:, is) = dv%kinrgy(:, is)*na_feedback_rescale
            dv%ne = dv%ne + (na_feedback_rescale-1.0_R8)*pl%na(:, is)*rt&
&             %rza(:, is)
            dv%fna(:, 0:1, is) = dv%fna(:, 0:1, is)*na_feedback_rescale
            dv%fna_mdf(:, 0:1, is) = dv%fna_mdf(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fna_fcor(:, 0:1, is) = dv%fna_fcor(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fna_nodrift(:, 0:1, is) = dv%fna_nodrift(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fna_he(:, 0:1, is) = dv%fna_he(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fnapsch(:, 0:1, is) = dv%fnapsch(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fna_eir(:, 0:1, is) = dv%fna_eir(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fna_32(:, 0:1, is) = dv%fna_32(:, 0:1, is)*&
&             na_feedback_rescale
            dv%fna_52(:, 0:1, is) = dv%fna_52(:, 0:1, is)*&
&             na_feedback_rescale
          END DO
!   ..initialise previous state and fluxes
          psnl%na = pl%na
          psnc%na = pl%na
          psnl%ne = dv%ne
          psnc%ne = dv%ne
          psnl%fna = dv%fna
          psnc%fna = dv%fna
          psnl%kinrgy = dv%kinrgy
          psnc%kinrgy = dv%kinrgy
!   ..compute initial ni
          CALL B2XPNI_NODIFF(ncv, ns, pl%na, dv%ni)
          CALL B2XPNN_NODIFF(ncv, ns, pl%na, dv%nn)
!   ..compute ni0
          psnl%ni = dv%ni
          psnc%ni = dv%ni
        CASE (3) 
!
! core boundary flux condition
!
          IF (ncall .EQ. 0) WRITE(*, '(a,a,i3)') &
&                           'b2stbc_fb_pre_actuator: using ', &
&                           'core boundary flux condition for sequence '&
&                           , ispecies + 1
!
          is_start = eb2spcr(ispecies+1) + 1
          is_end = eb2spcr(ispecies+1) + nfluids(ispecies+1)
!
          IF (feedback_namelist_used .AND. ncall .EQ. 0 .AND. &
&             saved_na_feedback_actuator(ispecies) .EQ. 0.0_R8) &
&           saved_na_feedback_actuator(ispecies) = conpar(is_end, &
&             na_feedback_ib(ispecies), 1)
!
          saved_na_feedback_actuator(ispecies) = (1.0_R8-&
&           na_feedback_alpha(ispecies))*saved_na_feedback_actuator(&
&           ispecies) + na_feedback_rescale
!
          IF (na_feedback_puff_min(ispecies) .GE. 0.0_R8) THEN
            IF (na_feedback_puff_min(ispecies) .LT. &
&               saved_na_feedback_actuator(ispecies)) THEN
              saved_na_feedback_actuator(ispecies) = &
&               saved_na_feedback_actuator(ispecies)
            ELSE
              saved_na_feedback_actuator(ispecies) = &
&               na_feedback_puff_min(ispecies)
            END IF
          END IF
          IF (na_feedback_puff_max(ispecies) .GT. 0.0_R8) THEN
            IF (na_feedback_puff_max(ispecies) .GT. &
&               saved_na_feedback_actuator(ispecies)) THEN
              saved_na_feedback_actuator(ispecies) = &
&               saved_na_feedback_actuator(ispecies)
            ELSE
              saved_na_feedback_actuator(ispecies) = &
&               na_feedback_puff_max(ispecies)
            END IF
          END IF
!
          IF (na_feedback_overshoot(ispecies) .GT. 1.0_R8 .AND. &
&             na_feedback_current .GT. na_feedback_target(ispecies)*&
&             na_feedback_overshoot(ispecies)) THEN
            total_flux = 0.0_R8
          ELSE
            total_flux = saved_na_feedback_actuator(ispecies)
          END IF
!
          DO is=is_start,is_end
            iss = is - is_start + 1
            conpar(is, na_feedback_ib(ispecies), 1) = total_flux*&
&             charge_frac(iss)
          END DO
        CASE DEFAULT
!
          WRITE(*, *) 'na feedback_choice not coded ', &
&         na_feedback_choice(ispecies)
        END SELECT
!
        IF (na_feedback_actuator(ispecies) .EQ. 1 .OR. &
&           na_feedback_actuator(ispecies) .EQ. 3) WRITE(*, &
&                                                  '(a,1p,i3,g15.6)') &
&                                                'na_feedback_actuator '&
&                                                  , ispecies + 1, &
&                                             saved_na_feedback_actuator&
&                                                  (ispecies)
!
        IF (na_feedback_choice(ispecies) .EQ. 6) THEN
          DEALLOCATE(charge_frac)
        END IF
      END IF
    END DO
!
!
!
    feedback_namelist_used = (feedback_namelist_used .OR. &
&     na_feedback_actuator(ispecies) .EQ. 1) .OR. na_feedback_actuator(&
&     ispecies) .EQ. 3
    dt_prev = dtim
!
  END IF
! ..return
  IF (ncall .EQ. 0 .OR. main_call) ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2STBC_FB_PRE_NODIFF

