!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHI_NODIFF(ncv, nfc, mp, cflmi, switch, geo, mpg, ni, nirm&
& , ni_ext, ti, tn, chvimx)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: mp, cflmi, ni(ncv, 0:1), nirm(ncv), ni_ext(ncv, 0:1)&
& , ti(ncv), tn(ncv), chvimx(nfc)
!     ------------------------------------------------------------------
!     B2TLHI computes the all atom heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: icv, ifc
  REAL(kind=r8) :: t0, t1
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVFX_NODIFF
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlhi')
!   ..test mp, cflmi
  CALL XERTST(0.0_R8 .LT. mp, 'faulty argument mp')
  CALL XERTST(0.0_R8 .LE. cflmi, 'faulty argument cflmi')
!
!   ..compute flux limit velocity
  IF (switch%b2tqca_model .EQ. 1) THEN
! SOLPS5.0 treatments
    DO ifc=1,nfc
      IF (ti(mpg%fccv(ifc, 1)) .LT. ti(mpg%fccv(ifc, 2))) THEN
        t0 = ti(mpg%fccv(ifc, 2))
      ELSE
        t0 = ti(mpg%fccv(ifc, 1))
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        abs0 = geo%fcpbs(ifc)
      ELSE
        abs0 = -geo%fcpbs(ifc)
      END IF
!srv 11.01.13
      chvimx(ifc) = cflmi*abs0*SQRT(t0/mp)*(nirm(mpg%fccv(ifc, 1))+nirm(&
&       mpg%fccv(ifc, 2)))/(ni(mpg%fccv(ifc, 1), 0)+ni_ext(mpg%fccv(ifc&
&       , 1), 0)+ni(mpg%fccv(ifc, 2), 0)+ni_ext(mpg%fccv(ifc, 2), 0))
    END DO
  ELSE IF (switch%b2tqca_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      t0 = ti(mpg%fccv(ifc, 2))
      t1 = ti(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        abs1 = geo%fcqalf(ifc, 0)
      ELSE
        abs1 = -geo%fcqalf(ifc, 0)
      END IF
      IF (t0 .LT. t1) THEN
        max1 = t1
      ELSE
        max1 = t0
      END IF
!wdk 10.03.16 Divide by ni*ti at cell faces, so chvimx contains the same information
!           as case b2tqca_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhi), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      result1 = PIT(mpg%fccv(ifc, 2))
      result2 = PIT(mpg%fccv(ifc, 1))
      chvimx(ifc) = cflmi*geo%fcs(ifc)*abs1*(nirm(mpg%fccv(ifc, 2))*&
&       result1*SQRT(t0/mp)*t0+nirm(mpg%fccv(ifc, 1))*result2*SQRT(t1/mp&
&       )*t1)/((ni(mpg%fccv(ifc, 1), 0)+ni_ext(mpg%fccv(ifc, 1), 0)+ni(&
&       mpg%fccv(ifc, 2), 0)+ni_ext(mpg%fccv(ifc, 2), 0))*max1)
    END DO
  END IF
  CALL SUBEND()
  RETURN

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHI_NODIFF

!  Differentiation of b2tlhi in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: ti ni chvimx
!   with respect to varying inputs: ti ni nirm chvimx
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHI_B(ncv, nfc, mp, cflmi, switch, geo, mpg, ni, nib, nirm&
& , nirmb, ni_ext, ti, tib, tn, chvimx, chvimxb)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: mp, cflmi, ni(ncv, 0:1), nirm(ncv), ni_ext(ncv, 0:1)&
& , ti(ncv), tn(ncv), chvimx(nfc)
  REAL(kind=r8) :: nib(ncv, 0:1), nirmb(ncv), tib(ncv), chvimxb(nfc)
!     ------------------------------------------------------------------
!     B2TLHI computes the all atom heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: icv, ifc
  REAL(kind=r8) :: t0, t1
  REAL(kind=r8) :: t0b, t1b
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVFX_NODIFF
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: max1b
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(kind=r8) :: temp
  REAL(kind=r8) :: tempb
  REAL(kind=r8) :: temp0
  REAL(kind=r8) :: temp1
  REAL(kind=r8) :: tempb0
  REAL(kind=r8) :: tempb1
  REAL(kind=r8) :: temp2
  REAL(kind=r8) :: tempb2
  REAL(kind=r8) :: temp3
  REAL(kind=r8) :: temp4
  REAL(kind=r8) :: tempb3
  INTEGER :: branch
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
!   ..test mp, cflmi
!
!   ..compute flux limit velocity
  IF (switch%b2tqca_model .EQ. 1) THEN
! SOLPS5.0 treatments
    DO ifc=1,nfc
      IF (ti(mpg%fccv(ifc, 1)) .LT. ti(mpg%fccv(ifc, 2))) THEN
        CALL PUSHREAL8ARRAY(t0, r8/8)
        t0 = ti(mpg%fccv(ifc, 2))
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8ARRAY(t0, r8/8)
        t0 = ti(mpg%fccv(ifc, 1))
        CALL PUSHCONTROL1B(1)
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        CALL PUSHREAL8ARRAY(abs0, r8/8)
        abs0 = geo%fcpbs(ifc)
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8ARRAY(abs0, r8/8)
        abs0 = -geo%fcpbs(ifc)
        CALL PUSHCONTROL1B(1)
      END IF
    END DO
    nirmb = 0.D0
    DO ifc=nfc,1,-1
      temp = ni_ext(mpg%fccv(ifc, 1), 0) + ni_ext(mpg%fccv(ifc, 2), 0) +&
&       ni(mpg%fccv(ifc, 1), 0) + ni(mpg%fccv(ifc, 2), 0)
      temp0 = nirm(mpg%fccv(ifc, 1)) + nirm(mpg%fccv(ifc, 2))
      temp1 = SQRT(t0/mp)
      tempb = cflmi*abs0*chvimxb(ifc)/temp
      chvimxb(ifc) = 0.D0
      IF (t0/mp .EQ. 0.D0) THEN
        t0b = 0.D0
      ELSE
        t0b = temp0*tempb/(mp*2.0*temp1)
      END IF
      nirmb(mpg%fccv(ifc, 1)) = nirmb(mpg%fccv(ifc, 1)) + temp1*tempb
      nirmb(mpg%fccv(ifc, 2)) = nirmb(mpg%fccv(ifc, 2)) + temp1*tempb
      tempb0 = -(temp1*temp0*tempb/temp)
      nib(mpg%fccv(ifc, 1), 0) = nib(mpg%fccv(ifc, 1), 0) + tempb0
      nib(mpg%fccv(ifc, 2), 0) = nib(mpg%fccv(ifc, 2), 0) + tempb0
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(abs0, r8/8)
      ELSE
        CALL POPREAL8ARRAY(abs0, r8/8)
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(t0, r8/8)
        tib(mpg%fccv(ifc, 2)) = tib(mpg%fccv(ifc, 2)) + t0b
      ELSE
        CALL POPREAL8ARRAY(t0, r8/8)
        tib(mpg%fccv(ifc, 1)) = tib(mpg%fccv(ifc, 1)) + t0b
      END IF
    END DO
  ELSE IF (switch%b2tqca_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      t0 = ti(mpg%fccv(ifc, 2))
      t1 = ti(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        CALL PUSHREAL8ARRAY(abs1, r8/8)
        abs1 = geo%fcqalf(ifc, 0)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHREAL8ARRAY(abs1, r8/8)
        abs1 = -geo%fcqalf(ifc, 0)
        CALL PUSHCONTROL1B(0)
      END IF
      IF (t0 .LT. t1) THEN
        CALL PUSHREAL8ARRAY(max1, r8/8)
        max1 = t1
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8ARRAY(max1, r8/8)
        max1 = t0
        CALL PUSHCONTROL1B(1)
      END IF
!wdk 10.03.16 Divide by ni*ti at cell faces, so chvimx contains the same information
!           as case b2tqca_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhi), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      CALL PUSHREAL8ARRAY(result1, r8/8)
      result1 = PIT(mpg%fccv(ifc, 2))
      CALL PUSHREAL8ARRAY(result2, r8/8)
      result2 = PIT(mpg%fccv(ifc, 1))
    END DO
    nirmb = 0.D0
    DO ifc=nfc,1,-1
      t0 = ti(mpg%fccv(ifc, 2))
      t1 = ti(mpg%fccv(ifc, 1))
      temp1 = ni_ext(mpg%fccv(ifc, 1), 0) + ni_ext(mpg%fccv(ifc, 2), 0) &
&       + ni(mpg%fccv(ifc, 1), 0) + ni(mpg%fccv(ifc, 2), 0)
      temp = SQRT(t0/mp)
      temp2 = nirm(mpg%fccv(ifc, 2))
      temp3 = SQRT(t1/mp)
      temp4 = nirm(mpg%fccv(ifc, 1))
      tempb1 = geo%fcs(ifc)*cflmi*abs1*chvimxb(ifc)/(temp1*max1)
      chvimxb(ifc) = 0.D0
      tempb = result1*tempb1
      tempb2 = result2*tempb1
      tempb3 = -((result1*(temp2*t0*temp)+result2*(temp4*t1*temp3))*&
&       tempb1/(temp1*max1))
      nib(mpg%fccv(ifc, 1), 0) = nib(mpg%fccv(ifc, 1), 0) + max1*tempb3
      nib(mpg%fccv(ifc, 2), 0) = nib(mpg%fccv(ifc, 2), 0) + max1*tempb3
      max1b = temp1*tempb3
      nirmb(mpg%fccv(ifc, 1)) = nirmb(mpg%fccv(ifc, 1)) + t1*temp3*&
&       tempb2
      IF (t1/mp .EQ. 0.D0) THEN
        t1b = temp4*temp3*tempb2
      ELSE
        t1b = (temp4*temp3+temp4*t1/(mp*2.0*temp3))*tempb2
      END IF
      nirmb(mpg%fccv(ifc, 2)) = nirmb(mpg%fccv(ifc, 2)) + t0*temp*tempb
      IF (t0/mp .EQ. 0.D0) THEN
        t0b = temp2*temp*tempb
      ELSE
        t0b = (temp2*temp+temp2*t0/(mp*2.0*temp))*tempb
      END IF
      CALL POPREAL8ARRAY(result2, r8/8)
      CALL POPREAL8ARRAY(result1, r8/8)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(max1, r8/8)
        t1b = t1b + max1b
      ELSE
        CALL POPREAL8ARRAY(max1, r8/8)
        t0b = t0b + max1b
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(abs1, r8/8)
      ELSE
        CALL POPREAL8ARRAY(abs1, r8/8)
      END IF
      tib(mpg%fccv(ifc, 1)) = tib(mpg%fccv(ifc, 1)) + t1b
      tib(mpg%fccv(ifc, 2)) = tib(mpg%fccv(ifc, 2)) + t0b
    END DO
  ELSE
    nirmb = 0.D0
  END IF

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHI_B

