!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHE_NODIFF(ncv, nfc, me, cflme, switch, geo, mpg, ne, te, &
& chvemx)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : ncall_b2tlhe
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: me, cflme, ne(ncv), te(ncv), chvemx(nfc)
!     ------------------------------------------------------------------
!     B2TLHE computes the electron heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: icv, ifc
  REAL(kind=r8) :: t0, t1
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVSG_NODIFF
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
!
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlhe')
!   ..test nCv, nFc
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
!   ..test me, cflme
  CALL XERTST(0.0_R8 .LT. me, 'faulty argument me')
  CALL XERTST(0.0_R8 .LE. cflme, 'faulty argument cflme')
!   ..extensive tests on first few calls
  IF (ncall_b2tlhe .LT. 3) THEN
!    ..test sign of ne, te
    CALL B2XVSG_NODIFF(ncv, ne, 1, 'ne', '.gt.')
    CALL B2XVSG_NODIFF(ncv, te, 1, 'te', '.gt.')
  END IF
!
!   ..compute flux limit velocity
  IF (switch%b2tqce_model .EQ. 1 .OR. switch%b2tqce_model .EQ. 3) THEN
! SOLPS5.0 treatments
!wdk perhaps the if-test should be based on a 'mode' switch, instead of b2tqce_model,
!    because now both options are interchangeable
    DO ifc=1,nfc
      IF (te(mpg%fccv(ifc, 1)) .LT. te(mpg%fccv(ifc, 2))) THEN
        t0 = te(mpg%fccv(ifc, 2))
      ELSE
        t0 = te(mpg%fccv(ifc, 1))
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        abs0 = geo%fcpbs(ifc)
      ELSE
        abs0 = -geo%fcpbs(ifc)
      END IF
!srv 11.01.13
      chvemx(ifc) = cflme*SQRT(t0/me)*abs0
    END DO
  ELSE IF (switch%b2tqce_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      t0 = te(mpg%fccv(ifc, 2))
      t1 = te(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        abs1 = geo%fcqalf(ifc, 0)
      ELSE
        abs1 = -geo%fcqalf(ifc, 0)
      END IF
      IF (t0 .LT. t1) THEN
        max1 = t1
      ELSE
        max1 = t0
      END IF
!wdk 10.03.16 Divide by ne*te at cell faces, so chvemx contains the same information
!           as case b2tqce_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhe), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      result1 = PIT(mpg%fccv(ifc, 2))
      result2 = PIT(mpg%fccv(ifc, 1))
      chvemx(ifc) = cflme*geo%fcs(ifc)*abs1*(ne(mpg%fccv(ifc, 2))*&
&       result1*SQRT(t0/me)*t0+ne(mpg%fccv(ifc, 1))*result2*SQRT(t1/me)*&
&       t1)/((ne(mpg%fccv(ifc, 1))+ne(mpg%fccv(ifc, 2)))*max1)
    END DO
  END IF
  ncall_b2tlhe = ncall_b2tlhe + 1
  CALL SUBEND()
  RETURN

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHE_NODIFF

!  Differentiation of b2tlhe in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: ne chvemx te
!   with respect to varying inputs: ne chvemx te
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHE_B(ncv, nfc, me, cflme, switch, geo, mpg, ne, neb, te, &
& teb, chvemx, chvemxb)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : ncall_b2tlhe
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: me, cflme, ne(ncv), te(ncv), chvemx(nfc)
  REAL(kind=r8) :: neb(ncv), teb(ncv), chvemxb(nfc)
!     ------------------------------------------------------------------
!     B2TLHE computes the electron heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: icv, ifc
  REAL(kind=r8) :: t0, t1
  REAL(kind=r8) :: t0b, t1b
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVSG_NODIFF
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: max1b
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
!
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
!   ..test nCv, nFc
!   ..test me, cflme
!   ..extensive tests on first few calls
  REAL(kind=r8) :: temp
  REAL(kind=r8) :: tempb
  REAL(kind=r8) :: tempb0
  REAL(kind=r8) :: temp0
  REAL(kind=r8) :: temp1
  REAL(kind=r8) :: tempb1
  REAL(kind=r8) :: temp2
  REAL(kind=r8) :: temp3
  REAL(kind=r8) :: tempb2
  INTEGER :: branch
!
!   ..compute flux limit velocity
  IF (switch%b2tqce_model .EQ. 1 .OR. switch%b2tqce_model .EQ. 3) THEN
! SOLPS5.0 treatments
!wdk perhaps the if-test should be based on a 'mode' switch, instead of b2tqce_model,
!    because now both options are interchangeable
    DO ifc=1,nfc
      IF (te(mpg%fccv(ifc, 1)) .LT. te(mpg%fccv(ifc, 2))) THEN
        CALL PUSHREAL8ARRAY(t0, r8/8)
        t0 = te(mpg%fccv(ifc, 2))
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8ARRAY(t0, r8/8)
        t0 = te(mpg%fccv(ifc, 1))
        CALL PUSHCONTROL1B(1)
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        CALL PUSHREAL8ARRAY(abs0, r8/8)
        abs0 = geo%fcpbs(ifc)
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8ARRAY(abs0, r8/8)
        abs0 = -geo%fcpbs(ifc)
        CALL PUSHCONTROL1B(1)
      END IF
    END DO
    DO ifc=nfc,1,-1
      IF (t0/me .EQ. 0.D0) THEN
        t0b = 0.D0
      ELSE
        t0b = cflme*abs0*chvemxb(ifc)/(me*2.0*SQRT(t0/me))
      END IF
      chvemxb(ifc) = 0.D0
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(abs0, r8/8)
      ELSE
        CALL POPREAL8ARRAY(abs0, r8/8)
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(t0, r8/8)
        teb(mpg%fccv(ifc, 2)) = teb(mpg%fccv(ifc, 2)) + t0b
      ELSE
        CALL POPREAL8ARRAY(t0, r8/8)
        teb(mpg%fccv(ifc, 1)) = teb(mpg%fccv(ifc, 1)) + t0b
      END IF
    END DO
  ELSE IF (switch%b2tqce_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      t0 = te(mpg%fccv(ifc, 2))
      t1 = te(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        CALL PUSHREAL8ARRAY(abs1, r8/8)
        abs1 = geo%fcqalf(ifc, 0)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHREAL8ARRAY(abs1, r8/8)
        abs1 = -geo%fcqalf(ifc, 0)
        CALL PUSHCONTROL1B(0)
      END IF
      IF (t0 .LT. t1) THEN
        CALL PUSHREAL8ARRAY(max1, r8/8)
        max1 = t1
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8ARRAY(max1, r8/8)
        max1 = t0
        CALL PUSHCONTROL1B(1)
      END IF
!wdk 10.03.16 Divide by ne*te at cell faces, so chvemx contains the same information
!           as case b2tqce_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhe), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      CALL PUSHREAL8ARRAY(result1, r8/8)
      result1 = PIT(mpg%fccv(ifc, 2))
      CALL PUSHREAL8ARRAY(result2, r8/8)
      result2 = PIT(mpg%fccv(ifc, 1))
    END DO
    DO ifc=nfc,1,-1
      t0 = te(mpg%fccv(ifc, 2))
      t1 = te(mpg%fccv(ifc, 1))
      temp = ne(mpg%fccv(ifc, 1)) + ne(mpg%fccv(ifc, 2))
      temp0 = SQRT(t0/me)
      temp1 = ne(mpg%fccv(ifc, 2))
      temp2 = SQRT(t1/me)
      temp3 = ne(mpg%fccv(ifc, 1))
      tempb = geo%fcs(ifc)*cflme*abs1*chvemxb(ifc)/(temp*max1)
      chvemxb(ifc) = 0.D0
      tempb0 = result1*tempb
      tempb1 = result2*tempb
      tempb2 = -((result1*(temp1*t0*temp0)+result2*(temp3*t1*temp2))*&
&       tempb/(temp*max1))
      neb(mpg%fccv(ifc, 1)) = neb(mpg%fccv(ifc, 1)) + max1*tempb2
      neb(mpg%fccv(ifc, 2)) = neb(mpg%fccv(ifc, 2)) + max1*tempb2
      max1b = temp*tempb2
      neb(mpg%fccv(ifc, 1)) = neb(mpg%fccv(ifc, 1)) + t1*temp2*tempb1
      IF (t1/me .EQ. 0.D0) THEN
        t1b = temp3*temp2*tempb1
      ELSE
        t1b = (temp3*temp2+temp3*t1/(me*2.0*temp2))*tempb1
      END IF
      neb(mpg%fccv(ifc, 2)) = neb(mpg%fccv(ifc, 2)) + t0*temp0*tempb0
      IF (t0/me .EQ. 0.D0) THEN
        t0b = temp1*temp0*tempb0
      ELSE
        t0b = (temp1*temp0+temp1*t0/(me*2.0*temp0))*tempb0
      END IF
      CALL POPREAL8ARRAY(result2, r8/8)
      CALL POPREAL8ARRAY(result1, r8/8)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(max1, r8/8)
        t1b = t1b + max1b
      ELSE
        CALL POPREAL8ARRAY(max1, r8/8)
        t0b = t0b + max1b
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(abs1, r8/8)
      ELSE
        CALL POPREAL8ARRAY(abs1, r8/8)
      END IF
      teb(mpg%fccv(ifc, 1)) = teb(mpg%fccv(ifc, 1)) + t1b
      teb(mpg%fccv(ifc, 2)) = teb(mpg%fccv(ifc, 2)) + t0b
    END DO
  END IF

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHE_B

