!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2usr_cost_function in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: j
!   with respect to varying inputs: sigma *par_opt_phys mean *(st.pl.na)
!                *(st.pl.te) *(st.pl.ti) *(st.dv.fna) *(st.dv.fne)
!                *(st.dv.fhe) *(st.dv.fhi) *(st.dv.kinrgy) *(st.dv.ne)
!                *(st.rt.rpt)
!   Plus diff mem management of: b2voloncf:in b2data:in b2dataoncf:in
!                par_opt_phys:in mpg.cffcor:in mpg.intcellr:in
!                geo.cvx:in geo.cvy:in geo.cvvol:in geo.fcs:in
!                geo.fchc:in geo.fcht:in geo.fcqgam:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in st_ext.am:in st_ext.na:in
!                st_ext.ta:in st.pl.na:in st.pl.te:in st.pl.ti:in
!                st.dv.fna:in st.dv.fne:in st.dv.fhe:in st.dv.fhi:in
!                st.dv.kinrgy:in st.dv.ne:in st.rt.rpt:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2USR_COST_FUNCTION_B(ncv, nfc, nvx, ns, geo, geob, mpg, mpgb&
& , st, stb, st_ext, st_extb, boris, j, jb)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_USER_NAMELIST_DIFF, ONLY : omp, nomp, icsepomp
  USE B2MOD_B2CMPA_DIFF, ONLY : am
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2US_GEO_DIFF
  USE B2MOD_PAR_OPT_DIFF
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : vold, cfnorm, nncf, b2rr, b2voloncf, &
& b2voloncfb, b2data, b2datab, b2dataoncf, b2dataoncfb
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFF) :: mpgb
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY) :: geob
  TYPE(B2STATE), INTENT(IN) :: st
  TYPE(B2STATE_DIFF) :: stb
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  TYPE(B2STATEEXT_DIFF) :: st_extb
  REAL(kind=r8) :: boris, j(nncf)
  REAL(kind=r8) :: jb(nncf)
  INTEGER :: ncv, nfc, nvx, ns
  INTEGER :: icf, ic1, ic2, icv, n1, n2, ifc, is, iicf
  LOGICAL, SAVE :: first_call=.true.
  LOGICAL :: inrange
  REAL(kind=r8) :: qq, prior, lll, lll_cum
  REAL(kind=r8) :: qqb, priorb, lllb, lll_cumb
  REAL(kind=r8) :: gradr(ncv), funv(nvx), pz(ncv), rz(ncv), cs(ncv)
  REAL(kind=r8) :: gradrb(ncv), funvb(nvx), pzb(ncv), rzb(ncv), csb(ncv)
  INTEGER :: isigma, imean
  EXTERNAL CALC_DIST_NODIFF
  INTRINSIC SUM
  INTRINSIC MIN
  INTRINSIC SQRT
  EXTERNAL XERRAB
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: max1b
  INTEGER :: arg1
  INTEGER :: branch
  REAL(kind=r8) :: tempb
  REAL(kind=r8), DIMENSION(ncv) :: tempb0
  REAL(kind=r8) :: tmp
  REAL(kind=r8) :: tmpb
  INTEGER :: ad_to
  INTEGER :: ad_to0
  INTEGER :: ad_to1
  INTEGER :: ad_from
  INTEGER :: ad_to2
  INTEGER :: ad_from0
  INTEGER :: ad_to3
  INTEGER :: ad_to4
  INTEGER :: ad_to5
  INTEGER :: ad_to6
  INTEGER :: ad_to7
  INTEGER :: ad_to8
  INTEGER :: ad_to9
!
!
  IF (first_call .AND. ncf .GT. 0) THEN
    cfnorm = 0.0_R8
    vold = 0.0_R8
    DO icf=1,ncf
      IF (cfread(icf)) THEN
! WARNING! For now we assume that the data read from the cost function is only radially dependent
        WRITE(*, *) 'WARNING, b2usr_cost_function assumes data '//&
&       'read for CF is only radially dependent'
        ic1 = mpg%cfregp(icf, 1)
        ic2 = ic1 + mpg%cfregp(icf, 2) - 1
        CALL PUSHINTEGER4(n1)
        n1 = mpg%cfregp(icf, 2)
        n2 = ncfdata(icf)
!csc icsep-1 because non-internal cells have been excluded!
        arg1 = icsepomp - 1
        CALL CALC_DIST_NODIFF(mpg, geo, mpg%cfreg(ic1:ic2), n1, arg1, &
&                       b2rr(icf, 1:n1))
        b2data(1:n1) = geo%cvvol(mpg%cfreg(ic1:ic2))
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2voloncf(icf, 1:n2))
        vold(icf) = SUM(b2voloncf(icf, 1:n2))
        DO icv=1,n2
          cfnorm(icf) = cfnorm(icf) + b2voloncf(icf, icv)*cfdata(icf, 2&
&           , icv)
        END DO
        IF (maptoomp(icf)) THEN
! FIXME to be considerably improved!
!for now assume radial data rigidly moved at the OMP (like in ST code)
! simply use as b2rr the OMP radial coordinates.
! check on, and then use, only internal Cvs in OMP list
          arg1 = icsepomp - 1
          CALL CALC_DIST_NODIFF(mpg, geo, omp(2:nomp-1), n1, arg1, b2rr(&
&                         icf, 1:n1))
          CALL PUSHCONTROL2B(2)
        ELSE
          CALL PUSHCONTROL2B(1)
        END IF
      ELSE
        CALL PUSHCONTROL2B(0)
      END IF
    END DO
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
!
  j = 0.0_R8
  IF (ncf .GT. 0) THEN
    DO icf=1,ncf
      CALL PUSHINTEGER4(ic1)
      ic1 = mpg%cfregp(icf, 1)
      ic2 = ic1 + mpg%cfregp(icf, 2) - 1
      CALL PUSHINTEGER4(n1)
      n1 = mpg%cfregp(icf, 2)
      n2 = ncfdata(icf)
      SELECT CASE  (cftype(icf)) 
      CASE (0) 
        CALL PUSHCONTROL4B(12)
      CASE (1) 
!sum of other cost function. It is skipped at this stage because it MUST be J(1) for optimization
!electron density on desired CVs
        b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        CALL PUSHINTEGER4(icv)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(11)
      CASE (2) 
!electron temperature on desired CVs
        b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        CALL PUSHINTEGER4(icv)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(10)
      CASE (3) 
!ion temperature on desired CVs
        b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        CALL PUSHINTEGER4(icv)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(9)
      CASE (4) 
        ad_from = ic1
        CALL PUSHINTEGER4(icv)
!max electron temperature on desired CVs
        DO icv=ad_from,ic2
          IF (j(icf) .LT. st%pl%te(mpg%cfreg(icv))) THEN
            j(icf) = st%pl%te(mpg%cfreg(icv))
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
            j(icf) = j(icf)
          END IF
        END DO
        CALL PUSHINTEGER4(icv - 1)
        CALL PUSHINTEGER4(ad_from)
        j(icf) = j(icf)/ev
        CALL PUSHCONTROL4B(8)
      CASE (5) 
        ad_from0 = ic1
!max heat flux density on desired FCs
        DO ifc=ad_from0,ic2
          IF (mpg%fccv(mpg%cfreg(ifc), 1) .GT. mpg%fccv(mpg%cfreg(ifc), &
&             2)) THEN
            CALL PUSHINTEGER4(icv)
            icv = mpg%fccv(mpg%cfreg(ifc), 2)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHINTEGER4(icv)
            icv = mpg%fccv(mpg%cfreg(ifc), 1)
            CALL PUSHCONTROL1B(1)
          END IF
          IF (icv .GT. mpg%nci) THEN
            IF (mpg%fccv(mpg%cfreg(ifc), 1) .LT. mpg%fccv(mpg%cfreg(ifc)&
&               , 2)) THEN
              CALL PUSHCONTROL1B(1)
              icv = mpg%fccv(mpg%cfreg(ifc), 2)
            ELSE
              CALL PUSHCONTROL1B(1)
              icv = mpg%fccv(mpg%cfreg(ifc), 1)
            END IF
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
          qq = st%dv%fhe(mpg%cfreg(ifc), 0) + st%dv%fhi(mpg%cfreg(ifc), &
&           0) + (1-boris)*st%dv%fne(mpg%cfreg(ifc), 0)*st%pl%te(icv)
          DO is=0,ns-1
            qq = qq + st%dv%fna(mpg%cfreg(ifc), 0, is)*(st%rt%rpt(icv, &
&             is)*ev+(1-boris)*(st%dv%kinrgy(icv, is)+st%pl%ti(icv)))
          END DO
          qq = qq*mpg%cffcor(ifc)/geo%fcs(mpg%cfreg(ifc))
          IF (j(icf) .LT. qq) THEN
            max1 = qq
            CALL PUSHCONTROL1B(0)
          ELSE
            max1 = j(icf)
            CALL PUSHCONTROL1B(1)
          END IF
          j(icf) = max1*cfweight(icf)
        END DO
        CALL PUSHINTEGER4(ifc - 1)
        CALL PUSHINTEGER4(ad_from0)
        CALL PUSHCONTROL4B(7)
      CASE (6) 
!loglikelihood + log prior for Bayesian MAP estimate
        CALL CALC_LOG_PRIOR_NODIFF(prior, inrange)
        WRITE(*, *) 'MAP log prior value:', prior
        lll_cum = 0.0_R8
        isigma = 1
        imean = 1
        DO iicf=cfstart(1),cfend(1)
          n1 = mpg%cfregp(iicf, 2)
          n2 = ncfdata(iicf)
          CALL PUSHINTEGER4(ic1)
          ic1 = mpg%cfregp(iicf, 1)
          ic2 = ic1 + n1 - 1
          SELECT CASE  (cftype(iicf)) 
          CASE (1) 
!electron density
            b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
            CALL PUSHCONTROL3B(0)
          CASE (2) 
!electron temperature
            b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
            CALL PUSHCONTROL3B(1)
          CASE (3) 
!ion temperature
            b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
            CALL PUSHCONTROL3B(2)
          CASE (7) 
!electron density radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%dv%ne, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
            CALL PUSHCONTROL3B(3)
          CASE (8) 
!electron temperature radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%te, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
            CALL PUSHCONTROL3B(4)
          CASE (9) 
!ion temperature radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%ti, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
            CALL PUSHCONTROL3B(5)
          CASE (10) 
!ion saturation current (kA/m**2)
            CALL PUSHREAL8ARRAY(rz, r8*ncv/8)
            CALL B2XPRZ_NODIFF(ncv, ns, mp, am, st%pl%na, rz, st_ext)
            CALL PUSHREAL8ARRAY(pz, r8*ncv/8)
            CALL B2XPPZ_NODIFF(ncv, ns, st%dv%ne, st%pl%na, st%pl%te, st&
&                        %pl%ti, pz, st_ext)
            CALL PUSHREAL8ARRAY(cs, r8*ncv/8)
            cs = SQRT(pz/rz)
            CALL PUSHINTEGER4(icv)
            DO icv=1,n1
              b2data(icv) = st%dv%ne(mpg%cfreg(ic1+icv-1))*cs(mpg%cfreg(&
&               ic1+icv-1))*ev/1.0e3_R8
            END DO
            CALL PUSHINTEGER4(icv - 1)
            CALL PUSHCONTROL3B(6)
          CASE DEFAULT
            CALL PUSHCONTROL3B(7)
            WRITE(*, *) cftype(iicf)
          END SELECT
          IF (ALLOCATED(b2dataoncf)) THEN
            CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
          CALL INTERP1D(n1, n2, b2rr(iicf, 1:n1), cfdata(iicf, 1, 1:n2)&
&                 , b2data(1:n1), b2dataoncf(1:n2))
          CALL CALC_LOGLIKELIHOOD_NODIFF(n2, b2dataoncf(1:n2), cfdata(&
&                                  iicf, 2, 1:n2), cfdata(iicf, 3, 1:n2)&
&                                  , lll, isigma, imean)
          lll_cum = lll_cum + lll
          CALL PUSHINTEGER4(isigma)
          isigma = isigma + 1
          CALL PUSHINTEGER4(imean)
          imean = imean + 1
        END DO
        IF (inrange) THEN
          j(icf) = -((prior+lll_cum)*cfweight(icf))
          CALL PUSHCONTROL4B(6)
        ELSE
          j(icf) = inf_opt
          CALL PUSHCONTROL4B(5)
        END IF
      CASE (7) 
!electron density radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%dv%ne, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        CALL PUSHINTEGER4(icv)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(4)
      CASE (8) 
!electron temperature radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%te, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        CALL PUSHINTEGER4(icv)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(3)
      CASE (9) 
!ion temperature radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%ti, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        CALL PUSHINTEGER4(icv)
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(2)
      CASE (10) 
!ion saturation current (kA/m**2)
        CALL PUSHREAL8ARRAY(rz, r8*ncv/8)
        CALL B2XPRZ_NODIFF(ncv, ns, mp, am, st%pl%na, rz, st_ext)
        CALL PUSHREAL8ARRAY(pz, r8*ncv/8)
        CALL B2XPPZ_NODIFF(ncv, ns, st%dv%ne, st%pl%na, st%pl%te, st%pl%&
&                    ti, pz, st_ext)
! Calculate saturation current as ne*cs*eV
        CALL PUSHREAL8ARRAY(cs, r8*ncv/8)
        cs = SQRT(pz/rz)
        CALL PUSHINTEGER4(icv)
        DO icv=1,n1
          b2data(icv) = st%dv%ne(mpg%cfreg(ic1+icv-1))*cs(mpg%cfreg(ic1+&
&           icv-1))*ev/1.0e3_R8
        END DO
        CALL PUSHINTEGER4(icv - 1)
        IF (ALLOCATED(b2dataoncf)) THEN
          CALL PUSHREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        CALL PUSHINTEGER4(icv - 1)
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
        CALL PUSHCONTROL4B(1)
      CASE DEFAULT
        CALL PUSHCONTROL4B(0)
        WRITE(*, *) cftype(icf)
      END SELECT
    END DO
! now sum of cost functions for cftype=0
    IF (cftype(1) .EQ. 0) THEN
      DO icf=cfend(1),cfstart(1),-1
        tmpb = jb(1)
        jb(1) = tmpb
        jb(icf) = jb(icf) + tmpb
      END DO
    END IF
    IF (ALLOCATED(b2datab)) b2datab = 0.D0
    IF (ALLOCATED(b2dataoncfb)) b2dataoncfb = 0.D0
    sigmab = 0.D0
    IF (ALLOCATED(par_opt_physb)) par_opt_physb = 0.D0
    meanb = 0.D0
    stb%pl%na = 0.D0
    stb%pl%te = 0.D0
    stb%pl%ti = 0.D0
    stb%dv%fna = 0.D0
    stb%dv%fne = 0.D0
    stb%dv%fhe = 0.D0
    stb%dv%fhi = 0.D0
    stb%dv%kinrgy = 0.D0
    stb%dv%ne = 0.D0
    stb%rt%rpt = 0.D0
    funvb = 0.D0
    DO icf=ncf,1,-1
      CALL POPCONTROL4B(branch)
      IF (branch .LT. 6) THEN
        IF (branch .LT. 3) THEN
          IF (branch .NE. 0) THEN
            IF (branch .EQ. 1) THEN
              jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&               2.0_R8)
              n2 = ncfdata(icf)
              CALL POPINTEGER4(ad_to9)
              DO icv=ad_to9,1,-1
                b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)&
&                 -cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
              END DO
              n1 = mpg%cfregp(icf, 2)
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8&
&                                             *n2/8)
              CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:&
&                       n2), b2data(1:n1), b2datab(1:n1), b2dataoncf(1:&
&                       n2), b2dataoncfb(1:n2))
              csb = 0.D0
              CALL POPINTEGER4(ad_to8)
              DO icv=ad_to8,1,-1
                stb%dv%ne(mpg%cfreg(ic1+icv-1)) = stb%dv%ne(mpg%cfreg(&
&                 ic1+icv-1)) + cs(mpg%cfreg(ic1+icv-1))*ev*b2datab(icv)&
&                 /1.0e3_R8
                csb(mpg%cfreg(ic1+icv-1)) = csb(mpg%cfreg(ic1+icv-1)) + &
&                 st%dv%ne(mpg%cfreg(ic1+icv-1))*ev*b2datab(icv)/&
&                 1.0e3_R8
                b2datab(icv) = 0.D0
              END DO
              CALL POPINTEGER4(icv)
              rzb = 0.D0
              pzb = 0.D0
              CALL POPREAL8ARRAY(cs, r8*ncv/8)
              WHERE (pz/rz .EQ. 0.D0) 
                tempb0 = 0.D0
              ELSEWHERE
                tempb0 = csb/(rz*2.0*SQRT(pz/rz))
              END WHERE
              pzb = tempb0
              rzb = -(pz*tempb0/rz)
              CALL POPREAL8ARRAY(pz, r8*ncv/8)
              CALL B2XPPZ_B(ncv, ns, st%dv%ne, stb%dv%ne, st%pl%na, stb%&
&                     pl%na, st%pl%te, stb%pl%te, st%pl%ti, stb%pl%ti, &
&                     pz, pzb, st_ext)
              CALL POPREAL8ARRAY(rz, r8*ncv/8)
              CALL B2XPRZ_B(ncv, ns, mp, am, st%pl%na, stb%pl%na, rz, &
&                     rzb, st_ext)
            ELSE
              jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&               2.0_R8)
              n2 = ncfdata(icf)
              CALL POPINTEGER4(ad_to7)
              DO icv=ad_to7,1,-1
                b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)&
&                 -cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
              END DO
              CALL POPINTEGER4(icv)
              n1 = mpg%cfregp(icf, 2)
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8&
&                                             *n2/8)
              CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:&
&                       n2), b2data(1:n1), b2datab(1:n1), b2dataoncf(1:&
&                       n2), b2dataoncfb(1:n2))
              ic1 = mpg%cfregp(icf, 1)
              ic2 = ic1 + mpg%cfregp(icf, 2) - 1
              gradrb = 0.D0
              gradrb(mpg%cfreg(ic1:ic2)) = gradrb(mpg%cfreg(ic1:ic2)) + &
&               b2datab(1:n1)/ev
              b2datab(1:n1) = 0.D0
              CALL GRADC_R_B(ncv, nfc, nvx, 0, geo, geob, mpg, mpgb, st%&
&                      pl%ti, stb%pl%ti, funv, funvb, gradr, gradrb)
            END IF
          END IF
          GOTO 100
        ELSE IF (branch .EQ. 3) THEN
          jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&           2.0_R8)
          n2 = ncfdata(icf)
          CALL POPINTEGER4(ad_to6)
          DO icv=ad_to6,1,-1
            b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)-&
&             cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
          END DO
          CALL POPINTEGER4(icv)
          n1 = mpg%cfregp(icf, 2)
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8*n2/&
&                                         8)
          CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2)&
&                   , b2data(1:n1), b2datab(1:n1), b2dataoncf(1:n2), &
&                   b2dataoncfb(1:n2))
          ic1 = mpg%cfregp(icf, 1)
          ic2 = ic1 + mpg%cfregp(icf, 2) - 1
          gradrb = 0.D0
          gradrb(mpg%cfreg(ic1:ic2)) = gradrb(mpg%cfreg(ic1:ic2)) + &
&           b2datab(1:n1)/ev
          b2datab(1:n1) = 0.D0
          CALL GRADC_R_B(ncv, nfc, nvx, 0, geo, geob, mpg, mpgb, st%pl%&
&                  te, stb%pl%te, funv, funvb, gradr, gradrb)
          GOTO 100
        ELSE IF (branch .EQ. 4) THEN
          jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&           2.0_R8)
          n2 = ncfdata(icf)
          CALL POPINTEGER4(ad_to5)
          DO icv=ad_to5,1,-1
            b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)-&
&             cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
          END DO
          CALL POPINTEGER4(icv)
          n1 = mpg%cfregp(icf, 2)
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8*n2/&
&                                         8)
          CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2)&
&                   , b2data(1:n1), b2datab(1:n1), b2dataoncf(1:n2), &
&                   b2dataoncfb(1:n2))
          ic1 = mpg%cfregp(icf, 1)
          ic2 = ic1 + mpg%cfregp(icf, 2) - 1
          gradrb = 0.D0
          gradrb(mpg%cfreg(ic1:ic2)) = gradrb(mpg%cfreg(ic1:ic2)) + &
&           b2datab(1:n1)/1.0e19_R8
          b2datab(1:n1) = 0.D0
          CALL GRADC_R_B(ncv, nfc, nvx, 0, geo, geob, mpg, mpgb, st%dv%&
&                  ne, stb%dv%ne, funv, funvb, gradr, gradrb)
          GOTO 100
        ELSE
          jb(icf) = 0.D0
          lll_cumb = 0.D0
          priorb = 0.D0
        END IF
      ELSE IF (branch .LT. 9) THEN
        IF (branch .EQ. 6) THEN
          priorb = -(cfweight(icf)*jb(icf))
          lll_cumb = -(cfweight(icf)*jb(icf))
          jb(icf) = 0.D0
        ELSE
          IF (branch .EQ. 7) THEN
            CALL POPINTEGER4(ad_from0)
            CALL POPINTEGER4(ad_to3)
            DO ifc=ad_to3,ad_from0,-1
              max1b = cfweight(icf)*jb(icf)
              jb(icf) = 0.D0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                qqb = max1b
              ELSE
                jb(icf) = jb(icf) + max1b
                qqb = 0.D0
              END IF
              qqb = mpg%cffcor(ifc)*qqb/geo%fcs(mpg%cfreg(ifc))
              DO is=ns-1,0,-1
                stb%dv%fna(mpg%cfreg(ifc), 0, is) = stb%dv%fna(mpg%cfreg&
&                 (ifc), 0, is) + (ev*st%rt%rpt(icv, is)+(1-boris)*(st%&
&                 dv%kinrgy(icv, is)+st%pl%ti(icv)))*qqb
                tempb = st%dv%fna(mpg%cfreg(ifc), 0, is)*qqb
                stb%rt%rpt(icv, is) = stb%rt%rpt(icv, is) + ev*tempb
                stb%dv%kinrgy(icv, is) = stb%dv%kinrgy(icv, is) + (1-&
&                 boris)*tempb
                stb%pl%ti(icv) = stb%pl%ti(icv) + (1-boris)*tempb
              END DO
              stb%dv%fhe(mpg%cfreg(ifc), 0) = stb%dv%fhe(mpg%cfreg(ifc)&
&               , 0) + qqb
              stb%dv%fhi(mpg%cfreg(ifc), 0) = stb%dv%fhi(mpg%cfreg(ifc)&
&               , 0) + qqb
              stb%dv%fne(mpg%cfreg(ifc), 0) = stb%dv%fne(mpg%cfreg(ifc)&
&               , 0) + st%pl%te(icv)*(1-boris)*qqb
              stb%pl%te(icv) = stb%pl%te(icv) + st%dv%fne(mpg%cfreg(ifc)&
&               , 0)*(1-boris)*qqb
              CALL POPCONTROL1B(branch)
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPINTEGER4(icv)
              ELSE
                CALL POPINTEGER4(icv)
              END IF
            END DO
          ELSE
            jb(icf) = jb(icf)/ev
            CALL POPINTEGER4(ad_from)
            CALL POPINTEGER4(ad_to2)
            DO icv=ad_to2,ad_from,-1
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                stb%pl%te(mpg%cfreg(icv)) = stb%pl%te(mpg%cfreg(icv)) + &
&                 jb(icf)
                jb(icf) = 0.D0
              END IF
            END DO
            CALL POPINTEGER4(icv)
          END IF
          GOTO 100
        END IF
      ELSE
        IF (branch .LT. 11) THEN
          IF (branch .EQ. 9) THEN
            jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&             2.0_R8)
            n2 = ncfdata(icf)
            CALL POPINTEGER4(ad_to1)
            DO icv=ad_to1,1,-1
              b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)-&
&               cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
            END DO
            CALL POPINTEGER4(icv)
            n1 = mpg%cfregp(icf, 2)
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8*&
&                                           n2/8)
            CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2&
&                     ), b2data(1:n1), b2datab(1:n1), b2dataoncf(1:n2), &
&                     b2dataoncfb(1:n2))
            ic1 = mpg%cfregp(icf, 1)
            ic2 = ic1 + mpg%cfregp(icf, 2) - 1
            stb%pl%ti(mpg%cfreg(ic1:ic2)) = stb%pl%ti(mpg%cfreg(ic1:ic2)&
&             ) + b2datab(1:n1)/ev
            b2datab(1:n1) = 0.D0
          ELSE
            jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&             2.0_R8)
            n2 = ncfdata(icf)
            CALL POPINTEGER4(ad_to0)
            DO icv=ad_to0,1,-1
              b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)-&
&               cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
            END DO
            CALL POPINTEGER4(icv)
            n1 = mpg%cfregp(icf, 2)
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8*&
&                                           n2/8)
            CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2&
&                     ), b2data(1:n1), b2datab(1:n1), b2dataoncf(1:n2), &
&                     b2dataoncfb(1:n2))
            ic1 = mpg%cfregp(icf, 1)
            ic2 = ic1 + mpg%cfregp(icf, 2) - 1
            stb%pl%te(mpg%cfreg(ic1:ic2)) = stb%pl%te(mpg%cfreg(ic1:ic2)&
&             ) + b2datab(1:n1)/ev
            b2datab(1:n1) = 0.D0
          END IF
        ELSE IF (branch .EQ. 11) THEN
          jb(icf) = cfweight(icf)*vold(icf)*jb(icf)/(cfnorm(icf)**2*&
&           2.0_R8)
          n2 = ncfdata(icf)
          CALL POPINTEGER4(ad_to)
          DO icv=ad_to,1,-1
            b2dataoncfb(icv) = b2dataoncfb(icv) + 2*(b2dataoncf(icv)-&
&             cfdata(icf, 2, icv))*b2voloncf(icf, icv)*jb(icf)
          END DO
          CALL POPINTEGER4(icv)
          n1 = mpg%cfregp(icf, 2)
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8*n2/&
&                                         8)
          CALL INTERP1D_B(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2)&
&                   , b2data(1:n1), b2datab(1:n1), b2dataoncf(1:n2), &
&                   b2dataoncfb(1:n2))
          ic1 = mpg%cfregp(icf, 1)
          ic2 = ic1 + mpg%cfregp(icf, 2) - 1
          stb%dv%ne(mpg%cfreg(ic1:ic2)) = stb%dv%ne(mpg%cfreg(ic1:ic2)) &
&           + b2datab(1:n1)/1.0e19_R8
          b2datab(1:n1) = 0.D0
        END IF
        GOTO 100
      END IF
      DO iicf=cfend(1),cfstart(1),-1
        CALL POPINTEGER4(imean)
        CALL POPINTEGER4(isigma)
        lllb = lll_cumb
        n2 = ncfdata(iicf)
        CALL CALC_LOGLIKELIHOOD_B(n2, b2dataoncf(1:n2), b2dataoncfb(1:n2&
&                           ), cfdata(iicf, 2, 1:n2), cfdata(iicf, 3, 1:&
&                           n2), lll, lllb, isigma, imean)
        n1 = mpg%cfregp(iicf, 2)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 1) CALL POPREAL8ARRAY(b2dataoncf(1:n2), r8*n2/8)
        CALL INTERP1D_B(n1, n2, b2rr(iicf, 1:n1), cfdata(iicf, 1, 1:n2)&
&                 , b2data(1:n1), b2datab(1:n1), b2dataoncf(1:n2), &
&                 b2dataoncfb(1:n2))
        CALL POPCONTROL3B(branch)
        IF (branch .LT. 4) THEN
          IF (branch .LT. 2) THEN
            IF (branch .EQ. 0) THEN
              ic1 = mpg%cfregp(iicf, 1)
              ic2 = ic1 + n1 - 1
              stb%dv%ne(mpg%cfreg(ic1:ic2)) = stb%dv%ne(mpg%cfreg(ic1:&
&               ic2)) + b2datab(1:n1)/1.0e19_R8
              b2datab(1:n1) = 0.D0
            ELSE
              ic1 = mpg%cfregp(iicf, 1)
              ic2 = ic1 + n1 - 1
              stb%pl%te(mpg%cfreg(ic1:ic2)) = stb%pl%te(mpg%cfreg(ic1:&
&               ic2)) + b2datab(1:n1)/ev
              b2datab(1:n1) = 0.D0
            END IF
          ELSE IF (branch .EQ. 2) THEN
            ic1 = mpg%cfregp(iicf, 1)
            ic2 = ic1 + n1 - 1
            stb%pl%ti(mpg%cfreg(ic1:ic2)) = stb%pl%ti(mpg%cfreg(ic1:ic2)&
&             ) + b2datab(1:n1)/ev
            b2datab(1:n1) = 0.D0
          ELSE
            ic1 = mpg%cfregp(iicf, 1)
            ic2 = ic1 + n1 - 1
            gradrb = 0.D0
            gradrb(mpg%cfreg(ic1:ic2)) = gradrb(mpg%cfreg(ic1:ic2)) + &
&             b2datab(1:n1)/1.0e19_R8
            b2datab(1:n1) = 0.D0
            CALL GRADC_R_B(ncv, nfc, nvx, 0, geo, geob, mpg, mpgb, st%dv&
&                    %ne, stb%dv%ne, funv, funvb, gradr, gradrb)
          END IF
        ELSE IF (branch .LT. 6) THEN
          IF (branch .EQ. 4) THEN
            ic1 = mpg%cfregp(iicf, 1)
            ic2 = ic1 + n1 - 1
            gradrb = 0.D0
            gradrb(mpg%cfreg(ic1:ic2)) = gradrb(mpg%cfreg(ic1:ic2)) + &
&             b2datab(1:n1)/ev
            b2datab(1:n1) = 0.D0
            CALL GRADC_R_B(ncv, nfc, nvx, 0, geo, geob, mpg, mpgb, st%pl&
&                    %te, stb%pl%te, funv, funvb, gradr, gradrb)
          ELSE
            ic1 = mpg%cfregp(iicf, 1)
            ic2 = ic1 + n1 - 1
            gradrb = 0.D0
            gradrb(mpg%cfreg(ic1:ic2)) = gradrb(mpg%cfreg(ic1:ic2)) + &
&             b2datab(1:n1)/ev
            b2datab(1:n1) = 0.D0
            CALL GRADC_R_B(ncv, nfc, nvx, 0, geo, geob, mpg, mpgb, st%pl&
&                    %ti, stb%pl%ti, funv, funvb, gradr, gradrb)
          END IF
        ELSE IF (branch .EQ. 6) THEN
          csb = 0.D0
          CALL POPINTEGER4(ad_to4)
          DO icv=ad_to4,1,-1
            stb%dv%ne(mpg%cfreg(ic1+icv-1)) = stb%dv%ne(mpg%cfreg(ic1+&
&             icv-1)) + cs(mpg%cfreg(ic1+icv-1))*ev*b2datab(icv)/&
&             1.0e3_R8
            csb(mpg%cfreg(ic1+icv-1)) = csb(mpg%cfreg(ic1+icv-1)) + st%&
&             dv%ne(mpg%cfreg(ic1+icv-1))*ev*b2datab(icv)/1.0e3_R8
            b2datab(icv) = 0.D0
          END DO
          CALL POPINTEGER4(icv)
          rzb = 0.D0
          pzb = 0.D0
          CALL POPREAL8ARRAY(cs, r8*ncv/8)
          WHERE (pz/rz .EQ. 0.D0) 
            tempb0 = 0.D0
          ELSEWHERE
            tempb0 = csb/(rz*2.0*SQRT(pz/rz))
          END WHERE
          pzb = tempb0
          rzb = -(pz*tempb0/rz)
          CALL POPREAL8ARRAY(pz, r8*ncv/8)
          CALL B2XPPZ_B(ncv, ns, st%dv%ne, stb%dv%ne, st%pl%na, stb%pl%&
&                 na, st%pl%te, stb%pl%te, st%pl%ti, stb%pl%ti, pz, pzb&
&                 , st_ext)
          CALL POPREAL8ARRAY(rz, r8*ncv/8)
          CALL B2XPRZ_B(ncv, ns, mp, am, st%pl%na, stb%pl%na, rz, rzb, &
&                 st_ext)
        END IF
        CALL POPINTEGER4(ic1)
      END DO
      CALL CALC_LOG_PRIOR_B(prior, priorb, inrange)
 100  CALL POPINTEGER4(n1)
      CALL POPINTEGER4(ic1)
    END DO
  ELSE
    sigmab = 0.D0
    IF (ALLOCATED(par_opt_physb)) par_opt_physb = 0.D0
    meanb = 0.D0
    stb%pl%na = 0.D0
    stb%pl%te = 0.D0
    stb%pl%ti = 0.D0
    stb%dv%fna = 0.D0
    stb%dv%fne = 0.D0
    stb%dv%fhe = 0.D0
    stb%dv%fhi = 0.D0
    stb%dv%kinrgy = 0.D0
    stb%dv%ne = 0.D0
    stb%rt%rpt = 0.D0
  END IF
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DO icf=ncf,1,-1
      CALL POPCONTROL2B(branch)
      IF (branch .NE. 0) THEN
        IF (branch .NE. 1) n1 = mpg%cfregp(icf, 2)
        n2 = ncfdata(icf)
        ic1 = mpg%cfregp(icf, 1)
        ic2 = ic1 + mpg%cfregp(icf, 2) - 1
        CALL POPINTEGER4(n1)
      END IF
    END DO
  END IF
END SUBROUTINE B2USR_COST_FUNCTION_B
!

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2USR_COST_FUNCTION_NODIFF(ncv, nfc, nvx, ns, geo, mpg, st, &
& st_ext, boris, j)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_USER_NAMELIST_DIFF, ONLY : omp, nomp, icsepomp
  USE B2MOD_B2CMPA_DIFF, ONLY : am
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2US_GEO_DIFF
  USE B2MOD_PAR_OPT_DIFF
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : vold, cfnorm, nncf, b2rr, b2voloncf, b2data,&
& b2dataoncf
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(B2STATE), INTENT(IN) :: st
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  REAL(kind=r8) :: boris, j(nncf)
  INTEGER :: ncv, nfc, nvx, ns
  INTEGER :: icf, ic1, ic2, icv, n1, n2, ifc, is, iicf
  LOGICAL, SAVE :: first_call=.true.
  LOGICAL :: inrange
  REAL(kind=r8) :: qq, prior, lll, lll_cum
  REAL(kind=r8) :: gradr(ncv), funv(nvx), pz(ncv), rz(ncv), cs(ncv)
  INTEGER :: isigma, imean
  EXTERNAL CALC_DIST_NODIFF
  INTRINSIC SUM
  INTRINSIC MIN
  INTRINSIC SQRT
  EXTERNAL XERRAB
  REAL(kind=r8) :: max1
  INTEGER :: arg1
!
  CALL SUBINI('b2usr_cost_function')
!
  IF (first_call .AND. ncf .GT. 0) THEN
    CALL XERTST(ncf .EQ. mpg%ncf, 'ncf=/mpg%nCf')
    CALL XERTST(mpg%isclassicalgrid .EQ. 1, ' Cost function CVs and '//&
&         'FCs ordering  and interpolation in case of unstructured grid'&
&         //' needs to be revised')
    cfnorm = 0.0_R8
    vold = 0.0_R8
    DO icf=1,ncf
      IF (cfread(icf)) THEN
! WARNING! For now we assume that the data read from the cost function is only radially dependent
        WRITE(*, *) 'WARNING, b2usr_cost_function assumes data '//&
&       'read for CF is only radially dependent'
        ic1 = mpg%cfregp(icf, 1)
        ic2 = ic1 + mpg%cfregp(icf, 2) - 1
        n1 = mpg%cfregp(icf, 2)
        n2 = ncfdata(icf)
!csc icsep-1 because non-internal cells have been excluded!
        arg1 = icsepomp - 1
        CALL CALC_DIST_NODIFF(mpg, geo, mpg%cfreg(ic1:ic2), n1, arg1, &
&                       b2rr(icf, 1:n1))
        b2data(1:n1) = geo%cvvol(mpg%cfreg(ic1:ic2))
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2voloncf(icf, 1:n2))
        vold(icf) = SUM(b2voloncf(icf, 1:n2))
        DO icv=1,n2
          cfnorm(icf) = cfnorm(icf) + b2voloncf(icf, icv)*cfdata(icf, 2&
&           , icv)
        END DO
        IF (maptoomp(icf)) THEN
! FIXME to be considerably improved!
!for now assume radial data rigidly moved at the OMP (like in ST code)
! simply use as b2rr the OMP radial coordinates.
          CALL XERTST(mpg%isclassicalgrid .EQ. 1, &
&               'Mapping to OMP need revision for extended grids')
! check on, and then use, only internal Cvs in OMP list
          CALL XERTST(n1 .EQ. nomp - 2, &
&               'number of Cv in CF does not equal Cvs in OMP')
          arg1 = icsepomp - 1
          CALL CALC_DIST_NODIFF(mpg, geo, omp(2:nomp-1), n1, arg1, b2rr(&
&                         icf, 1:n1))
        END IF
      END IF
    END DO
    first_call = .false.
  END IF
!
  j = 0.0_R8
  IF (ncf .GT. 0) THEN
    DO icf=1,ncf
      ic1 = mpg%cfregp(icf, 1)
      ic2 = ic1 + mpg%cfregp(icf, 2) - 1
      n1 = mpg%cfregp(icf, 2)
      n2 = ncfdata(icf)
      SELECT CASE  (cftype(icf)) 
      CASE (0) 

      CASE (1) 
!sum of other cost function. It is skipped at this stage because it MUST be J(1) for optimization
!electron density on desired CVs
        b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (2) 
!electron temperature on desired CVs
        b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (3) 
!ion temperature on desired CVs
        b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (4) 
!max electron temperature on desired CVs
        DO icv=ic1,ic2
          IF (j(icf) .LT. st%pl%te(mpg%cfreg(icv))) THEN
            j(icf) = st%pl%te(mpg%cfreg(icv))
          ELSE
            j(icf) = j(icf)
          END IF
        END DO
        j(icf) = j(icf)/ev
      CASE (5) 
!max heat flux density on desired FCs
        DO ifc=ic1,ic2
          qq = 0.0
          IF (mpg%fccv(mpg%cfreg(ifc), 1) .GT. mpg%fccv(mpg%cfreg(ifc), &
&             2)) THEN
            icv = mpg%fccv(mpg%cfreg(ifc), 2)
          ELSE
            icv = mpg%fccv(mpg%cfreg(ifc), 1)
          END IF
          IF (icv .GT. mpg%nci) THEN
            IF (mpg%fccv(mpg%cfreg(ifc), 1) .LT. mpg%fccv(mpg%cfreg(ifc)&
&               , 2)) THEN
              icv = mpg%fccv(mpg%cfreg(ifc), 2)
            ELSE
              icv = mpg%fccv(mpg%cfreg(ifc), 1)
            END IF
          END IF
          qq = st%dv%fhe(mpg%cfreg(ifc), 0) + st%dv%fhi(mpg%cfreg(ifc), &
&           0) + (1-boris)*st%dv%fne(mpg%cfreg(ifc), 0)*st%pl%te(icv)
          DO is=0,ns-1
            qq = qq + st%dv%fna(mpg%cfreg(ifc), 0, is)*(st%rt%rpt(icv, &
&             is)*ev+(1-boris)*(st%dv%kinrgy(icv, is)+st%pl%ti(icv)))
          END DO
          qq = qq*mpg%cffcor(ifc)/geo%fcs(mpg%cfreg(ifc))
          IF (j(icf) .LT. qq) THEN
            max1 = qq
          ELSE
            max1 = j(icf)
          END IF
          j(icf) = max1*cfweight(icf)
        END DO
      CASE (6) 
!loglikelihood + log prior for Bayesian MAP estimate
        CALL CALC_LOG_PRIOR_NODIFF(prior, inrange)
        WRITE(*, *) 'MAP log prior value:', prior
        lll_cum = 0.0_R8
        isigma = 1
        imean = 1
        DO iicf=cfstart(1),cfend(1)
          n1 = mpg%cfregp(iicf, 2)
          n2 = ncfdata(iicf)
          ic1 = mpg%cfregp(iicf, 1)
          ic2 = ic1 + n1 - 1
          SELECT CASE  (cftype(iicf)) 
          CASE (1) 
!electron density
            b2data(1:n1) = st%dv%ne(mpg%cfreg(ic1:ic2))/1.0e19_R8
          CASE (2) 
!electron temperature
            b2data(1:n1) = st%pl%te(mpg%cfreg(ic1:ic2))/ev
          CASE (3) 
!ion temperature
            b2data(1:n1) = st%pl%ti(mpg%cfreg(ic1:ic2))/ev
          CASE (7) 
!electron density radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%dv%ne, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
          CASE (8) 
!electron temperature radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%te, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
          CASE (9) 
!ion temperature radial gradient
            CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%ti, &
&                         funv, gradr)
            b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
          CASE (10) 
!ion saturation current (kA/m**2)
            CALL B2XPRZ_NODIFF(ncv, ns, mp, am, st%pl%na, rz, st_ext)
            CALL B2XPPZ_NODIFF(ncv, ns, st%dv%ne, st%pl%na, st%pl%te, st&
&                        %pl%ti, pz, st_ext)
            cs = SQRT(pz/rz)
            DO icv=1,n1
              b2data(icv) = st%dv%ne(mpg%cfreg(ic1+icv-1))*cs(mpg%cfreg(&
&               ic1+icv-1))*ev/1.0e3_R8
            END DO
          CASE DEFAULT
            WRITE(*, *) cftype(iicf)
            CALL XERRAB('cftype for sum out of bounds for cftype=6')
          END SELECT
          CALL INTERP1D(n1, n2, b2rr(iicf, 1:n1), cfdata(iicf, 1, 1:n2)&
&                 , b2data(1:n1), b2dataoncf(1:n2))
          CALL CALC_LOGLIKELIHOOD_NODIFF(n2, b2dataoncf(1:n2), cfdata(&
&                                  iicf, 2, 1:n2), cfdata(iicf, 3, 1:n2)&
&                                  , lll, isigma, imean)
          lll_cum = lll_cum + lll
          isigma = isigma + 1
          imean = imean + 1
        END DO
        IF (inrange) THEN
          j(icf) = -((prior+lll_cum)*cfweight(icf))
        ELSE
          j(icf) = inf_opt
        END IF
      CASE (7) 
!electron density radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%dv%ne, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/1.0e19_R8
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (8) 
!electron temperature radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%te, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (9) 
!ion temperature radial gradient
        CALL GRADC_R_NODIFF(ncv, nfc, nvx, 0, geo, mpg, st%pl%ti, funv, &
&                     gradr)
        b2data(1:n1) = gradr(mpg%cfreg(ic1:ic2))/ev
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE (10) 
!ion saturation current (kA/m**2)
        CALL B2XPRZ_NODIFF(ncv, ns, mp, am, st%pl%na, rz, st_ext)
        CALL B2XPPZ_NODIFF(ncv, ns, st%dv%ne, st%pl%na, st%pl%te, st%pl%&
&                    ti, pz, st_ext)
! Calculate saturation current as ne*cs*eV
        cs = SQRT(pz/rz)
        DO icv=1,n1
          b2data(icv) = st%dv%ne(mpg%cfreg(ic1+icv-1))*cs(mpg%cfreg(ic1+&
&           icv-1))*ev/1.0e3_R8
        END DO
        CALL INTERP1D(n1, n2, b2rr(icf, 1:n1), cfdata(icf, 1, 1:n2), &
&               b2data(1:n1), b2dataoncf(1:n2))
        DO icv=1,n2
          j(icf) = j(icf) + b2voloncf(icf, icv)*(b2dataoncf(icv)-cfdata(&
&           icf, 2, icv))**2
        END DO
        j(icf) = j(icf)*cfweight(icf)*vold(icf)/cfnorm(icf)**2/2.0_R8
      CASE DEFAULT
        WRITE(*, *) cftype(icf)
        CALL XERRAB('cftype out of bounds')
      END SELECT
    END DO
! now sum of cost functions for cftype=0
    IF (cftype(1) .EQ. 0) THEN
      DO icf=cfstart(1),cfend(1)
        j(1) = j(1) + j(icf)
      END DO
    END IF
  END IF
  CALL SUBEND()
  RETURN
END SUBROUTINE B2USR_COST_FUNCTION_NODIFF
!

